the-events-calendar/the-events-calendar

src/Tribe/Main.php
The `Tribe::redirect_past_upcoming_view_urls()` method incorrectly calls `trim()` on the result of `wp_parse_url()`, which is an array or `false`.
=> Fix warning in redirect_past_upcoming_view_urls()

src/Tribe/Main.php
This allows iCal exports to generate some location info and aids the end-user into more easily recognising where exactly they should be when they're close to the event location. It also makes sure that there is at least some location info in the iCal export, to prevent confusion both for the WordPress webmaster (why isn't the location showing up?) as to the end-user (what is the name of the place I need to be).
My username on WordPress.org is sylviavanos.
_Ref:_ [C#110464](http://central.tri.be/issues/110464)
=> Add venue name to full address string

src/Tribe/Integrations/WPML/Linked_Posts.php
I double checked this change works by looking at the queries with "Query Monitor"
- Before this change I could see the "order by" which we are trying to remove.
- And after this change I could see the same query without the "order by" as intended.
=> Fix: to drop the order from the query we need to unset orderby, not order.

src/Tribe/Main.php
_Ref:_ [C#111198](https://central.tri.be/issues/111198)
=> #111198 - fix 'tec.bar' is not a bound alias error

src/Tribe/Assets.php
🎫 https://central.tri.be/issues/40267
Make sure that the frontend assets are loaded when using the `[tribe_events]` shortcode
=> Fix: Load frontend assets when using shortcode

src/Tribe/Main.php
Reverts moderntribe/the-events-calendar#1880
After testing I found we do not return an array as we use the functions to return only the component we want.
_Ref:_ [C#110463](https://central.tri.be/issues/110463)
We pass the component we want to:
https://developer.wordpress.org/reference/functions/wp_parse_url/
Which then uses this function to return only that:
https://developer.wordpress.org/reference/functions/_get_component_from_parsed_url_array/
I plan to change the add_filter back to the correct add_action in another PR
=> Revert "Fix warning in redirect_past_upcoming_view_urls()"

src/Tribe/REST/V1/Endpoints/Single_Event.php
https://central.tri.be/issues/109627
Previous ticket work was not testable because the categories/tags was not shown in the REST API endpoint schema. Now it's added and can be tested via the MT REST API Tester.
=> Add categories/tags to REST API endpoint properties

src/Tribe/Query.php, src/Tribe/REST/V1/Documentation/Event_Definition_Provider.php, src/Tribe/REST/V1/Endpoints/Archive_Event.php, src/Tribe/REST/V1/Post_Repository.php, tests/restv1/RequestChecksumCest.php
Ticket: https://central.tri.be/issues/111525
This PR leverages the work done in moderntribe/tribe-common#747 to return checksums in Event REST API responses:
for single events the checksum is the checksum of the event itself
for archive two checksums are returned page_checksum for the checksum of the current page, and request_checksum for the checksum relative to the whole request; the two could have the same values if no pagination is involved
I've added some logic in the Tribe__Events__Query class and the last_found_ids method.
=> add tests and code to return single and archive checksums

readme.txt, src/Tribe/Aggregator/Processes/Queue_Control.php, src/Tribe/Aggregator/Processes/Service_Provider.php, src/Tribe/Aggregator/Record/Queue_Processor.php, src/Tribe/Aggregator/Record/Queue_Realtime.php, src/Tribe/Aggregator/Record/Void_Queue.php, tests/wpunit/Tribe/Events/Aggregator/Record/Queue_ProcessorTest.php, tests/wpunit/Tribe/Events/Aggregator/Record/Queue_RealtimeTest.php
Ticket:  https://central.tri.be/issues/111856
Builds on: https://github.com/moderntribe/tribe-common/pull/751
This PR adds the following (w/ tests):
* make it so that queues "orphaned" of a Records will be graciously handled and removed
* refine some Queue_Processor and Queue_Realtime code
* add a listener, on Event Aggregator > Import pages to allow users to clear all import queues appending the `clear_queues=1` query variable to the URL
=> Add more checks and fallbacks to handle queues

readme.txt, src/Tribe/Aggregator/Record/Eventbrite.php
**Ticket:** [**⌗107821**](http://central.tri.be/issues/107821)
Scott has a very good brain and used it to make this regex. This regex now lets folks import Eventbrite events from more domains than just `eventbrite.com`. Thanks Scott!
=> ⌗107821 Use Scott's Regex to Support More Eventbrite Domains

src/admin-views/aggregator/origins/eventbrite.php
**Ticket:** [**⌗107821**](http://central.tri.be/issues/107821)
**Code Review Note:** No readme entry needed for this.
Basically just improving the dropdown text here:
* First, removing the .com TLD from the label is good because as part of ⌗107821 we're ensuring support for basically any TLD Eventbrite itself supports. Also, the placeholder text in the input underneath it demonstrates the `eventbrite.com/` event URL.
* Next, fixing the typo of `url` being lowercase.
=> ⌗107821 Spotfix: Improve Label in EB Import Dropdown

readme.txt, src/Tribe/Aggregator/Processes/Queue_Control.php, src/Tribe/Aggregator/Processes/Service_Provider.php, src/Tribe/Aggregator/Record/Queue.php, src/Tribe/Aggregator/Record/Queue_Processor.php, src/Tribe/Aggregator/Record/Queue_Realtime.php, src/Tribe/Aggregator/Settings.php, src/admin-views/aggregator/settings.php
Tickets:
* https://central.tri.be/issues/113418
* https://central.tri.be/issues/113475
Screencast: http://p.tri.be/qTnJfj
Switching queue system while importing: http://p.tri.be/8mdhK0
This PR:
* exposes, via UI, a way for users to select which import process to use (asynchronous or cron-based)
* adds a link, and supports, stopping and removing async queues, be them in a working or stuck status
* supports (handles) the case where the system is switched mid-import; cron->async will finish "speeding up" (see second screencast); async -> cron will stop the async process
=> Expose and support UI to select import process system

readme.txt, src/Tribe/Query.php
_Ref:_ [C#111518](https://central.tri.be/issues/111518)
=> #111518 - fix tribe_get_events to accept 0 as an argument

src/Tribe/List_Widget.php, src/admin-views/widget-admin-list.php
This standardizes the saving process as well as fixing a notice error that could occur.  The readme entry is already merged. 
_Ref:_ [C#105176](https://central.tri.be/issues/105176)
_Ref:_ [C#113141](https://central.tri.be/issues/113141)
Relates to:
https://github.com/moderntribe/events-pro/pull/1008
=> #105176 & #113141 - fix list widget saving of jsonld and standard saving

readme.txt, src/Tribe/Aggregator.php, src/Tribe/Aggregator/Cron.php, src/Tribe/Aggregator/Record/Unsupported.php, src/Tribe/Aggregator/Records.php, tests/wpunit/Tribe/Events/Aggregator/CronTest.php, tests/wpunit/Tribe/Events/Aggregator/Record/UnsupportedTest.php
Ticket: https://central.tri.be/issues/114831
This PR:
1. removes FB notices
2. adds the `Unsupported` type record to allow code to keep using a record object and avoid fatals
3. adds an auto-clean method to the `Unsupported` record class to delete the record post on `shutdown`.
=> Remove Facebook records and notices

readme.txt, src/Tribe/Aggregator/Record/CSV.php
Ticket: https://central.tri.be/issues/114199
Screencast: http://p.tri.be/MZsePs
This PR adds support, in CSV import, for empty column headers.
What would happen with empty column headers is that those would be collapsed into one thus hiding the column entirely and messing up the column indexes; this would result in broken imports and hidden results.
=> Handle the case where CSV file column headers are empty

src/Tribe/Repositories/Event.php, tests/wpunit/Tribe/Events/ORM/Events/FetchByCostTest.php
Ticket: https://central.tri.be/issues/115580
Based on common PR: https://github.com/moderntribe/tribe-common/pull/798
This PR adds support for cost based filtering for events.  
This implementation is ET/ET+ agnostic and is solely based on the event custom fields.  
ET/ET+ support is handled in the Event Tickets PR and code with a repository decorator.
=> Add cost meta filters.

src/Tribe/Query.php, src/Tribe/Repositories/Event.php
Ticket: https://central.tri.be/issues/114076
Based on: https://github.com/moderntribe/tribe-common/pull/813 
This PR adds the `get_date_filters` and `has_date_filters` method to the Event repository to know if any kind of date-related filtering, e.g. `starts_after` or `runs_between` is being applied or not to the query.
The PR also make sure the render and display context are passed to the ORM in the `tribe_get_events` function.
=> Add methods to know if date filters are being applied to the ORM query.

src/modules/blocks/style.pcss
🎫 https://central.tri.be/issues/118223
WP 5.0 is introducing some CSS that was not working fine with our styles for Gutenberg. It was creating a gap between our blocks.
=> Gutenberg > All blocks > adjust padding

src/Tribe/Editor.php
add a new filter `tribe_blocks_editor_update_classic_content_params` so plugins can set the default params during the migration of blocks
Ticket: https://central.tri.be/issues/114554
=> Add filter so blocks can set the params during migration

src/Tribe/Editor/Template.php
🎫 https://central.tri.be/issues/118287
While working on other stuff realized that the notice was showing for future events as well.
=> Fix > Past event notice not showing

src/Tribe/Editor/Meta.php
🎫 https://central.tri.be/issues/114301
This one came up with "All Day Events". But we might also have others. The data for that was being saved as "yes" and "no". We're treating them as booleans, and they were always casting as true if there were some content in it. 
Adding a method to pay attention to how we return the data via the REST API for these cases.
=> Provide backwards compatibility for saved data

readme.txt, src/Tribe/Template/Month.php
**Ticket:** [**⌗116124**](http://central.tri.be/issues/116124)
**Related PR:** https://github.com/moderntribe/tribe-common/pull/831
This is part of an initial pass at improving the cache invalidation on `tribe_last_save_post`.
=> ⌗116124 New Hook to Help with Listening for Retrieval of Cached Month View Events

src/modules/blocks/event-datetime/style.pcss
🎫 https://central.tri.be/issues/118697
Seems that some core styles are taking over our editor styles and it looks like this: https://cloudup.com/c9LeOAMY5wd
=> Fix datetime block padding

readme.txt, src/Tribe/Aggregator/Record/CSV.php
Ref. https://central.tri.be/issues/117236
CSV files with whitespace at the beginning of the rows won't remove headers and skip columns on Preview
=> Previewing and Importing CSV files with whitespace

src/Tribe/Editor/Template/Overwrite.php
As 'tribe_events_before_view'  is an action being exected with
`do_action`
=> Update `add_filter` into `add_action`

readme.txt, src/functions/template-tags/general.php
Favor actions to be fired instead of direct dependency of Events
Calendar PRO
Ticket: https://central.tri.be/issues/119263
=> Remove direct dependency of `Tribe__Events__Pro__Main`

src/views/single-event/recurring-description.php
🎫 https://central.tri.be/issues/119354
Using the meta directly and not modifying the method that was originally used on the template, because the method is widely used on other places and changing that can cause new problems.
=> Fix > Block editor > recurrence marker not displaying properly

src/Tribe/Editor/Provider.php
Use the new action `tribe_editor_register_blocks` instead of
`tribe_events_editor_register_blocks` to register the blocks
Ticket: https://central.tri.be/issues/119362
=> Register blocks using `common` action

readme.txt, src/Tribe/Main.php, src/Tribe/Organizer.php, src/Tribe/Venue.php
**Ticket:** [**⌗119451**](http://central.tri.be/issues/119451)
Read more about the new labels themselves here → https://make.wordpress.org/core/2018/12/05/new-post-type-labels-in-5-0/
=> ⌗119451 Use New Post Type Labels Introduced in WP 5.0

codeception.dist.yml, composer.json
Based on the documentation of `wp-browser` we need to remove the dependency for `Codeception\Command\DbSnapshot` if we go to version `wp-browser@2.2.0` 
---
If we stick to version `2.1.6` we could keep using `DbSnapshot` and that could be a faster solution.
=> Make sure we have the correct version of wp-browser

readme.txt, src/Tribe/Editor/Template/Overwrite.php
This is re-applying `wpautop` in places we don't want it - rather than re-removing it, let's set up a check.
Discovered while debugging https://central.tri.be/issues/120562
=> Don't apply wpautop if it hasn't been applied already.

readme.txt, src/admin-views/admin-welcome-message.php
**Ticket:** [**⌗117795**](http://central.tri.be/issues/117795)
Note that this time there is no remote-JS code used for the email submission form, which will keep us in line with WordPress.org plugin guidelines.
=> ⌗117795 Restoring TEC Welcome Page Refresh Code

readme.txt, src/Tribe/Editor/Meta.php
🎫 https://central.tri.be/issues/120399
Include UTC dates meta for the events created on the block editor. This will prevent the api results from being broken and a lot of issues with the queries.
Props to @lucatume - his work 🥇
=> Include UTC dates meta for the events created on the block editor

src/views/blocks/event-tags.php
🎫 https://central.tri.be/issues/119393
Nico suggested to remove the textdomain as it's a WP taxonomy.
=> Use "Tags" without textdomain as its a WP taxonomy.

src/modules/blocks/event-datetime/style.pcss
🎫 https://central.tri.be/issues/119413
Fix WP block tools overlap with the date time block when using twentynineteen.
=> Fix WP block tools overlap

src/Tribe/Main.php
_Ref:_ [C#121275](https://central.tri.be/issues/121275)
Load two more classes manually to prevent fatal error on deactivation
=> #121275 - load more classes to prevent fatal on deactivation

src/Tribe/Main.php
_Ref:_ [C#121486](https://central.tri.be/issues/121486)
This disables Pre PDC Version of CE if TEC shuts down due to an older version of ET.
=> #121486 - if et is older version disable older ce to prevent fatal

src/Tribe/Repositories/Event.php, src/Tribe/Template/List.php
Ticket: https://central.tri.be/issues/122082
Based on PR: https://github.com/moderntribe/tribe-common/pull/948 
This PR fixes two more issues I've found on the List view dealing with the display of featured events and adds the `start_date` filter to the... filters the ORM will consider date filters.
No idea why I forgot in the first place.
=> Fix List view issues.

src/Tribe/Template/Month.php, src/functions/template-tags/general.php
Ticket: https://central.tri.be/issues/123472
This PR:
* fixes the issue that would cause inconsistent filtering of events in the Month view when filtering by category
* updates the `tribe_get_events` doc block to specify `WP_Query` as a possible return type.
=> Fix inconsistent display of events in Month view when filtering by category

src/Tribe/Admin/Notice/Timezones.php
_Ref:_ [C#123221](http://central.tri.be/issues/123221)
---
=> When global is not UTC and event is, still display notice

src/Tribe/Editor/Compatibility.php
Gutenberg block editor has already been launched, so there is no need for 'early access' any more.
=> Adjusted tooltip text for block editor setting

src/Tribe/Aggregator/Page.php
🎫 https://central.tri.be/issues/107413
With the changes from https://github.com/moderntribe/tribe-common/pull/783 - the method was always returning true, because it's always invoking the function with the `$ID`, which contains `tribe_`.
=> EA > Update `is_screen` method to avoid having "New Import" as page title

src/Tribe/Query.php, src/Tribe/Template/List.php, src/Tribe/Template/Month.php
Tickets:
* https://central.tri.be/issues/123945
* https://central.tri.be/issues/123950
This PR fixes two issues caused by the ORM switch in `tribe_get_events`:
1. the Month view was fetching events in starting and ending on the same day, the correct way to fetch those events is to fetch those that **overlap** the day.
2. the List view was not looking around for the context anymore triggering a PHP notice and defaulting to fetch, pretty much, all events.
3. to support 1 the `tribe_get_events` function contains now an "unpack" conditional logic, to "unpack" some filters before calling them on the ORM; currently this will only unpack the `date_overlaps` argument but we can add more along the way
=> Fix Month and List view ORM issues.

src/Tribe/Main.php, src/Tribe/Template/List.php, src/Tribe/Template/Month.php
Tickets:
* https://central.tri.be/issues/123950
* https://central.tri.be/issues/123945
* https://central.tri.be/issues/123472
This PR:
* fixes an issue in the List view where the past events AJAX pagination would not paginate beyond the first page.
* fixes an issue where the Month view would not display events (correctly or at all) depending on the timezone settings (Display, Site and Event)
* fixes an issue (not related in ORM but present in `master` too) where the event category would not be used and set in the Map view
=> Fix ORM and Views AJAX pagination issues.

src/Tribe/Query.php, src/Tribe/Template/Month.php
Ticket: https://central.tri.be/issues/125196
In implementing the ORM we've modified the behaviour of event queries to use the UTC dates in place
of the local ones. Before we would incorrectly display an 8AM Tokyo event (UTC+9) as happening
before a 9AM New York event (UTC-4). This fix makes sure the change is applied across all event
queries to ensure consistency between specialized queries using UTC dates and the main query that
would use, until now, non UTC dates.
=> Fix(Main Events Query): Ensure UTC-based filtering of dates is applied to all query components.

src/Tribe/Template/Month.php
🎫 https://central.tri.be/issues/125259
From what I talked with Luca, in ORM, if:
- the featured arg is true, then it brings only featured events.
- the featured arg is false, then it brings not featured events.
- not defined, brings all.
Adding the if statement to make this work with the filter bar. Maybe in the future we can revisit to see if we can hook to `tribe_events_month_daily_events_query_args` directly. I'm using both `featured` and `tribe_featuredevent` to get both cases working.
=> Make the filterbar featured event filter work with ORM

src/Tribe/Query.php, src/Tribe/Repositories/Event.php, src/Tribe/Template/Day.php, src/Tribe/Template/List.php, src/Tribe/Template/Month.php, tests/wpunit/Tribe/Events/ORM/Events/FetchByDateTest.php
Tickets: 
* https://central.tri.be/issues/125196
* https://central.tri.be/issues/123950
* https://central.tri.be/issues/125383
This PR updates the Event ORM to make it so that, upon construction, the Timezone settings will be taken into account.
The settings are the ones the user can set in `Events > Settings > Time Zone Settings` section.
This changes the ORM behavior to improve back-compatibility with existing views and honor the setting.
By default the ORM would use the UTC date/times to sort events, this would align with the "Use site-wide timezone setting everywhere" but it would ignore the "Use manual time zones for each event" setting before this fix.
What the settings mean is not immediate; here's an example:
* given the site timezone is Europe/Paris
* given a Asia/Tokyo timezone …
=> Modify the Event ORM to be Timezone Settings aware.

src/Tribe/Query.php
Some integrations rely on an `eventDisplay` query property to be set to work. Moving the
implementation of `tribe_get_events` to an ORM-based functionality we've removed that property
setting: this fix makes sure such property is set, if possible.
re https://central.tri.be/issues/125511
=> fix(tribe_get_events function): Set an `eventDisplay` query property if possible.

src/functions/template-tags/date.php
The `tribe_event_ends_on` function will assert whether an event ends on a date or not. The check is
timezone, and timezone settings, aware. As an example a 4/10 2pm to 7pm, Los Angeles timezone, event
does not end on 4/11 if using the Los Angeles timezone, it will end on 4/11 (at 4am) if using the
Paris timezone. What timezone will be used for the comparison depends on the site timezone and the
site timezone settings.
re https://central.tri.be/issues/125587
=> feat(template-tags/date.php): Added the `tribe_event_ends_on` function.

src/Tribe/Integrations/Freemius.php
🎫 https://central.tri.be/issues/125612
Freemius notices cannot be dismissed (at least in our implementation). This code will remove the activation complete notice.
=> Freemius > Maybe remove activation complete notice

src/Tribe/Template/Day.php, src/Tribe/Template/List.php, src/Tribe/Template_Factory.php, tests/wpunit/Tribe/Events/ORM/Events/FetchByDateTest.php
Tickets:
* https://central.tri.be/issues/123950
* https://central.tri.be/issues/125383
This PR fixes AJAX response pagination issues in the List view and Day view.
The first was caused by the List view relying on an hash generation, to detect whether query parameters were changed or not, that would generate the hash using incomplete information (see https://github.com/moderntribe/tribe-common/pull/980).
The second was caused by the Day view, in the `ajax_response` method, not defining the required order criteria.
=> Fix List and Day view pagination issues.

src/Tribe/List_Widget.php
_Ref:_ [C#125787](http://central.tri.be/issues/125787)
---
On this particular change here we are basically adding the `post_status` default, should we have this on the `tribe_get_events` level? for backwards compatible, it current is using `any` which causes problems.
=> Respect the correct post Status for List Widget

readme.txt, src/Tribe/Query.php, src/Tribe/Service_Providers/ORM.php, src/functions/template-tags/loop.php
These fixes makes sure AJAX pagination keeps working correctly when using the "Use manual timezones
for each event" Timezone Setting. In the List view the issues were caused on a the "now" date not
being "recycled" when generating the hash, in the other views the issue was caused by duplicate
event date meta queries caused by the way the next and previous links queries work by "recycling"
the global query arguments.
re https://central.tri.be/issues/123950
screencast: https://github.com/moderntribe/the-events-calendar/pull/2461
=> fix(AJAX Pagination): Fix a number of issues with AJAX pagination in local timezone.

src/Tribe/Cost_Utils.php
🎫 https://central.tri.be/issues/120193
Unrelated to the ticket, but discovered while doing QA.
=> Be sure we have the `$event_id` for the new filter

src/Tribe/API.php, src/Tribe/Organizer.php, src/Tribe/Venue.php
If the value of `FeaturedImage` on the request is present but is set to
null or empty value it means we want to remove the image or update the
resource with an empty image, as right now the check was in place to
review if the request has a valid image to update the image value.
Updates: 
- Applies the same logic for the featured image of an Event.
Ticket: https://central.tri.be/issues/120913
=> Remove featured image if the value is empty

readme.txt, src/Tribe/Main.php
Ticket: https://central.tri.be/issues/127173
This fix makes sure that, even when the plugin is not loaded due to a missing requirement or incompatibility, its source paths are registered, appending them, in the Autoloader.  
This makes it so that the paths registered by the plugin owning Common will be searced **first** using the "safe" version of the classes; if the classes are not found in the version of Common owned by the plugin loading it then the additional plugin paths will be searched avoiding fatals caused by some plugin functionalities relying on some classes that do not exist at all in the loaded (and probably older) version of Common.
=> fix(Main): fix autoloader related issue

src/Tribe/Views/V2/Assets.php
Now that we are only registering `tribe-common-style` we should add it as a dependency here.
Related: https://github.com/moderntribe/tribe-common/pull/1012
=> Add `tribe-common-style` as dependency of the new views styles

dev/docker/ci-compose.yml, src/Tribe/Rewrite.php, tests/views_integration/Tribe/Events/Views/V2/ThemeCompatibilityTest.php
In release/B19.07.1 we've removed the caching, on a per-request base with a simple array, done in
the `get_bases` method. Getting the bases is a costly operation (there are 3 filters applying on it)
that should be done as little as possible. Furthermore the caching was removed as consequence of an
eager call to the `setup` method in the `Tribe__Rewrite::instance` method that is removed in the
linked PR (https://github.com/moderntribe/tribe-common/pull/1043), thus this caching can be
reinstated.
=> fix(Tribe__Events__Rewrite.php): readd request cache in `get_bases`.

dev/docker/ci-compose.yml, readme.txt, src/Tribe/Rewrite.php, src/admin-views/admin-update-message.php, src/admin-views/admin-welcome-message.php, tests/views_integration/Tribe/Events/Views/V2/ThemeCompatibilityTest.php
Updates the newsletter signup forms (which are embedded in the welcome and update screens) so that they submit to the Support API platform. Functionality is essentially as it used to be, but the data will no longer be sent directly to createsend.com.
:warning: Important! This change depends on [Support API PR 28](https://github.com/moderntribe/support-api.tri.be/pull/28), which introduces the endpoint we need for this to work. That change must be approved and be deployed before this work ships.
:ticket: [♯129034](https://central.tri.be/issues/129034)
=> Newsletter signup changes

readme.txt, src/Tribe/Main.php, tests/views_ui/_bootstrap.php
This moves the tribe-common registration back to `__construct()` so that it happens _before_ `plugins_loaded` priority `0` as per the Plugin Dependency spec.
See: https://central.tri.be/issues/129478
Related: https://github.com/moderntribe/event-tickets/pull/1285
=> Ensure common version is declared early to make decisions on loading

readme.txt, src/Tribe/REST/V1/Post_Repository.php, src/Tribe/Repositories/Event.php, tests/_function-mocker-bootstrap.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_BodyTest.php, tests/wpunit/Tribe/Events/REST/V1/Post_RepositoryTest.php
Ticket: 
* https://central.tri.be/issues/98061
* https://central.tri.be/issues/129780
An event cost string might be generated, or stored, in a different locale from the one set for the current request. This would lead to wrong parsing of cost values due to decimal and separator misalignments. This fix leverages the work done in https://github.com/moderntribe/tribe-common/pull/1068 to try and read the original decimal and current separators and use them to convert to the english decimal point format.
Furthermore this PR fixes an issue with event repository I've found while working on it.
=> Fix event cost values parsing.

src/Tribe/Views/V2/Service_Provider.php, src/Tribe/Views/V2/Template/Page.php, src/Tribe/Views/V2/Template_Bootstrap.php, src/Tribe/Views/V2/V1_Compat.php
Our single event pages were broken due to View V2 deactivation of the V1 actions without correctly pulling the old single views to be included.
=> Views V2: Single Event template loading behavior fixed

readme.txt, src/Tribe/REST/V1/Post_Repository.php
The behavior in the REST endpoint resulted in undesirable data.
This reverts #1837
See: https://central.tri.be/issues/100159
=> Rolling back timezone fix from 100159

composer.json
Change the `mikey179/vfsStream` package to all lowercase to squash warnings about composer 2.0.
See also: https://github.com/moderntribe/events-pro/pull/1168
=> fix(composer): Change case of package name.

src/Tribe/Linked_Posts/Base.php
Ticket: https://central.tri.be/issues/132567#note-7
Remove the use of `abstract static get_fetch_callback` from the code.
With older, strict, PHP versions it will raise a warning.
=> Fix (Linked_Posts/Base.php) remove abstract static

tests/_bootstrap.php
The `spatie/phpunit-snapshot-assertions` will automatically regenerate snapshots on `--update-snaspshots` flag.
Since Codeception has strict check on che CLI arguments that flag will be dropped.
This fix bridges the gap.
=> tests(_bootstrap.php) regen snapshots on Codeception --debug flag

src/functions/template-tags/event.php, tests/wpunit/functions/template-tags/eventTest.php
Ticket: n/a
Based on https://github.com/moderntribe/tribe-common/pull/1128 and https://github.com/moderntribe/tribe-testing-facilities/pull/9
This PR leverages the `Tribe\Utils\Lazy_Events` trait to make sure the decorated post produced by the `tribe_get_event` function will be cached on `shutdown` and only if one of the "lazy" properties was accessed.
=> fix(tribe_get_event) use Lazy_Events

composer.lock, tests/views_integration/Tribe/Events/Views/V2/Rest_EndpointTest.php, tests/wpunit/Tribe/Events/iCalTest.php
Due to upstream changes in our test dependency chain the `assertStringContainsString` method was removed.
And it was never meant to be used in instance methods to begin with.
=> test(iCalTest.php) use correct assertion

src/Tribe/Models/Post_Types/Event.php
Ticket: n/a
Based on: https://github.com/moderntribe/tribe-common/pull/1149
This PR removes the trailing `_` from the Event model cache slug to follow the update in the `common` PR.
=> fix(Models/Post_Types/Event.php) cache slug

src/Tribe/Views/V2/Views/By_Day_View.php, src/Tribe/Views/V2/Views/Month_View.php
Ticket: https://central.tri.be/issues/133906 
This PR updates the `Month_View` class, and its ancerstor the `By_Day_View.php` class, to reduce the duplicated code Month and Week View (PRO) share.
The main change is the pull-up of the URL building method that does not change the Month View functionality in the slightest.
Screencap: https://drive.google.com/open?id=12-mUiE5KMFof2d8MpmSEA3i6AZfHbq-M&authuser=luca@tri.be&usp=drive_fs
=> Refactor some methods out of Month View.

tests/features/views/list-view/view-layout.feature
I wrote scenarios for what number should show in the visual Date Marker on V2 List View for multi-day events (since we can only show 1 number in the Date Marker, this is trickier on multi-day events). These are for List View but we'll use the same pattern for Photo and Map Views.
=> Scenario date marker

src/Tribe/Views/V2/View.php, src/Tribe/Views/V2/Views/By_Day_View.php, src/Tribe/Views/V2/Views/Month_View.php, tests/views_integration/Tribe/Events/Views/V2/TestCaseTest.php
Tickets:
* https://central.tri.be/issues/134428
* https://central.tri.be/issues/134427
Based on: https://github.com/moderntribe/tribe-common/pull/1157
This PR updates the Week and Month View parent class, the `By_Day_View` one, to correctly filter and re-use filtered repository arguments.
=> VR - Fix repository arg handling

src/Tribe/Views/V2/View.php, src/Tribe/Views/V2/Views/List_View.php
Ticket: https://central.tri.be/issues/134294
This PR fixes a small issue I found with List View and ensures repository arguments are set when creating the template vars.
=> VR - Filterbar integration support

src/Tribe/Views/V2/View.php
Ticket: https://central.tri.be/issues/134293 
To support Filterbar we need not only to read the URL arguments, but to add them too.
The filter opens the door to that.
=> VR - Allow filtering a View URL arguments

src/Tribe/Organizer.php, src/Tribe/Venue.php
Ticket: n/a
This PR fixes an issue found out while running tests by:
1. removing queries we do not need when fetching Event linked posts (Organizers and Venues) to rely, instead, on the already set meta values
2. by fixing `1` this makes the snapshot tests, that rely on cache alteration, to work correctly again.
=> fix(src) avoid query when fetching linked posts

readme.txt, src/Tribe/Query.php, src/Tribe/Views/V2/Hooks.php
Reverts moderntribe/the-events-calendar#2782
---
We need to find a better method of turning this off since this one breaks a lot of other integrations with Single view.
https://central.tri.be/issues/136498
=> Revert "fix(Views V2) correctly suppress v1 query filters"

src/Tribe/Views/V2/Hooks.php
_Ref:_ [C#136590](http://central.tri.be/issues/136590) [C#136621](http://central.tri.be/issues/136621)
---
Two bugs were reported around the queries we around events when we have V2 active, this particular PR resolves these problems by limiting the scope of where those filters happen.
📹 http://i.bordoni.me/7731d40475c0
=> Modifies the when to load the Query Abstractions

readme.txt, src/Tribe/Aggregator/Tabs/Abstract.php
When converting dates, handle the possibility that dates may be in tough-to-strtotime formats like DD/MM/YYYY. The fix is to pass them through our format conversion method in `Tribe__Date_Utils`.
🎥 http://p.tri.be/hvgKba
🎫 https://central.tri.be/issues/117691
=> Handle non-YYYY-MM-DD date formats for the datepicker on EA submission

src/Tribe/Views/V2/Template_Bootstrap.php, tests/views_integration/Tribe/Events/Views/V2/TemplateBootstrapTest.php
Ticket: https://central.tri.be/issues/136633 
[Screencap](https://drive.google.com/open?id=12kCKKNcsGzZy_NeSNh8R73l48_lsM8g3&authuser=luca@tri.be&usp=drive_fs)
This PR updates the Template_Bootstrap code to make sure Views are loaded only:
* if the query is the main one
* if the query is an event query (which included Venues, Organizers are Event Category too)
=> fix(Views V2) finer control over template bootstrap

src/Tribe/Views/V2/Assets.php, src/Tribe/Views/V2/Template_Bootstrap.php
_Ref:_ [C#136503](http://central.tri.be/issues/136503)
---
Super simple change that was causing regressions, due to how agressive the V1 disabling was happening.
📹 http://i.bordoni.me/2cc7af256998
=> Dont disable V1 on single event views

src/Tribe/Models/Post_Types/Event.php
🎫 https://central.tri.be/issues/136606
🎥 https://www.loom.com/share/0a569261f28e44cfa84a19855cfe477d
Use date diff instead of operating with `ymd`. When using ymd, the substraction between months gives a high number, so it defaults to 7 (using `min`).
=> VR > Month > Multi-day starting last month ending this month in same week.

src/Tribe/Service_Providers/Context.php
Ticket: https://central.tri.be/issues/138137 
This PR fixes an issue emerged in Day View that would, or reload of PHP initial state, set the Day View date to today's date, no matter the date set in the URL.
Since the Day View date, when permalinks are active, is set as part of the URL (e.g. `/events/2019-12-13/`) the Context attempt to read the requested date from a request var (from `GET` or `REQUEST`) would fail and fall back on the default value of today.
By the time the check is made by the context, though, WordPress has already parsed the URL into internally stored query args that, via the `Tribe__Context::WP_PARSED` location, can be accessed.
To avoid perturbation of previously working Views I've added the location last and re-ran the tests on PRO too: all passing.
=> fix(Context) add WP parsed query vars to event_date

src/Tribe/Views/V2/Template/Excerpt.php
Ticket: https://central.tri.be/issues/138249  
This PR is a slight variation on the fix @bordoni had originally implemented to avoid infinite loops on excerpt.
This PR re-introduces the fix and takes into account the additional scenario of object-cache presence.
[Screencap](https://drive.google.com/open?id=1-R3zdQKmdE_Z2Sz7vv5VZwl6t_a-Cc4l&authuser=luca@tri.be&usp=drive_fs)
To test the fix I'v put together a really incomplete, yet fitting for this specific issue testing, pluging [in this gist](https://gist.github.com/e44c5fe6b81d60651f8fbec3d49fecc0).
=> fix(Views V2) avoid inf. loop on object cache

src/Tribe/Models/Post_Types/Event.php
🎫 https://central.tri.be/issues/137838
🎥 https://www.loom.com/share/d7ec4db91fa94fefab235df99b9c4f1b
Switching `ymd` calcs for `date_diff` as the first one is not precise for end of month subtractions.
=> VR > Multiday duration fixes.

src/Tribe/Views/V2/Views/List_View.php, src/Tribe/Views/V2/Views/Traits/List_Behavior.php, tests/views_integration/Tribe/Events/Views/V2/Views/Traits/List_BehaviorTest.php
Ticket: n/a
Following check-in dev discussion, I'm moving the `List_Behavior` trait into a dedicated `Traits` directory in Views v2 code.
=> refactor(Views v2) move List_Behavior in Traits

src/Tribe/Views/V2/Repository/Event_Period.php, src/Tribe/Views/V2/Repository/Events_Result_Set.php
Ticket: https://central.tri.be/issues/138249
This fixes an issue where, depending on the object cache implementation,
the return object might be serialized or not.
In some object cache implementations, this would lead to an attempt to
call `unserialize` on a not serialized object.
=> fix(Repository/Event_Period.php) maybe_unserialize

src/Tribe/Views/V2/View.php, src/Tribe/Views/V2/Views/List_View.php
Filterbar hooks into `tribe_events_views_v2_url_query_args` filter to attach its query arguments to URLs. Our prev_url() and next_url() fire that filter, however, Map and Photo view's `get_past_url()` was not doing so. This changeset adds the filter so filterbar can work its magic on any of the URLs.
:movie_camera: http://p.tri.be/s6Gs7h
Related:
* https://github.com/moderntribe/events-pro/pull/1414
* https://github.com/moderntribe/events-filterbar/pull/217
see/138621
see/138632
=> Filter get_past_url() and get_upcoming_url() calls

src/Tribe/Collections/Lazy_Post_Collection.php, src/Tribe/Models/Post_Types/Event.php
Ticket: https://central.tri.be/issues/138249
[Screencap](https://drive.google.com/open?id=1-oMtf5y_vLdzWruQWX2iXZLzC75qtmGC&authuser=luca@tri.be&usp=drive_fs)
Based on: https://github.com/moderntribe/tribe-common/pull/1241
This PR adds, and uses, the `Lazy_Post_Collection` class to
correctly handle serialization and unserialization of decorated post
objects.
Calls to `serialize` on `WP_Post` objects decorated by methods like
`tribe_get_event` or `tribe_get_venue_object` will not throw any error
and will produce a serialized version of the post object w/ all the
added properties added to it.
During unserialization, though, the additional, decorating, properties
will not be recognized by the `unserialize` function and the object
instance will fail to build, returning `false` as result of …
=> fix(Collections) add and use Lazy_Post_Collection

src/admin-views/tribe-options-general.php, src/resources/js/views/datepicker.js
This changeset ensures that liverefresh remains possible as a setting in V2 regardless of the events search bar visibility setting.
The tiny UX tweak is as follows: when live refresh is _disabled_, the datepicker will remain _open_ until manually closed OR until the "Find Events" button is clicked.
:movie_camera: http://p.tri.be/ETczR7
see/138573
=> Support disabling live refresh within v2 AND tiny UX improvement

tests/_support/Factories/Event.php
Ticket: n/a
This PR updates the Event Factory to build the dates using the Dates and Timezone uitlities.
This should decouple the factory from the underlying system timezone setting and avoid some "wrong time of the day" failures.
=> test(_support) update Event Factory to use Dates and Timezone utils

src/Tribe/Views/V2/Hooks.php, tests/_support/Factories/Event.php
When redirecting from one view to another, we plop a `tribe_redirected` query argument onto the new URL. This changeset detects that and ensures that we can properly redirect.
:movie_camera: http://p.tri.be/ysdOT8
see/138864
=> Cease preventing redirects when we are TRYING to redirect

src/Tribe/Views/V2/Hooks.php, src/Tribe/Views/V2/Template/Event.php, src/functions/template-tags/general.php
Porting over the value blanking from v1. I've additionally done the following:
* Added a class property to avoid attempting to unhook filters that are not set.
* Added a password checker in the `tribe_events_event_schedule_details()` function as that function is called earlier than `the_post` in our V2 views.
:movie_camera: http://p.tri.be/aF58my
see/138862
=> Updating our pw-protected event handling to blank out values

src/Tribe/Template_Factory.php, src/Tribe/Views/V2/Hooks.php, src/Tribe/Views/V2/Template/Event.php, src/Tribe/Views/V2/Template_Bootstrap.php, src/functions/template-tags/event.php
Tickets: [TEC-2989], [TEC-3033]
This PR:
* fixes some password-protected fields issues I found on V1
* ports over V1 behavior, where possible, on V2
Screencaps:
1. [How it works on v1](https://drive.google.com/open?id=10ViBRIYfMnWzkAQ8YdX6rb9dumcaNwKY&authuser=luca@tri.be&usp=drive_fs); to provide a frame of reference about how it currently works
2. [How it works on v2](https://drive.google.com/open?id=10XwurNb5WbiUinoXLTUx1h4fwoF37o36&authuser=luca@tri.be&usp=drive_fs); the same in v2; there's an exception where the event day still shows (in pretty much all views) due to how v1 and v2 are different in terms of layout and UI building.
3. [How it works on V2 w/ object-caching enabled](https://drive.google.com/open?id=10ZAXQpMJQxQ5jsvBZqV-qzY33I6uXsGE&authuser=luca@tri.be&usp=drive_fs); …
=> TEC-2989 TEC-3033 - VR - Fix pwd protected post fields

src/Tribe/Views/V2/Views/By_Day_View.php
When array slicing from 0 to -1, we were getting strange results. If -1 is the events per day setting, we should be displaying _all_ events.
We also took the opportunity to change a variable name that was poorly named.
:movie_camera: http://p.tri.be/3WynOW
:ticket: [TEC-3151]
[TEC-3151]: https://moderntribe.atlassian.net/browse/TEC-3151
=> If events per day is set to -1, don't attempt to array slice

src/Tribe/Models/Post_Types/Event.php, src/Tribe/Views/V2/View.php, src/Tribe/Views/V2/Views/Traits/List_Behavior.php
This PR actually tackles three things.
1. On the views where the posts_per_page is -1, we shouldn't pop off an event
1. When navigating forward and backward in list views, the datepicker's date range was jumping around based on the start date of the first event in the list. That shouldn't always happen. Now, if we are on a page > 0 while navigating _forward_ in time (not a past pagination), we will defer to the top bar's date rather than the first event.
1. Update the multiday calculation logic to work with all day events and not be a slave to timezones.
:movie_camera: http://p.tri.be/1W9h5D
:ticket: [TEC-3154]
[TEC-3154]: https://moderntribe.atlassian.net/browse/TEC-3154
=> Ensure that pagination-less views show all events

src/Tribe/Views/V2/View.php
Adding the filtering of query args will allow filters to be properly injected and removed.
:movie_camera: http://p.tri.be/oF2nQk
:ticket: [FBAR-64]
[FBAR-64]: https://moderntribe.atlassian.net/browse/FBAR-64
=> Filter the today_url like we filter prev/next

phpcs.xml, src/Tribe/Views/V2/View.php, tests/views_integration/Tribe/Events/Views/V2/ViewTest.php
The structure of the next/prev URLs in View were such that tests around the filterability of the query arguments would fail. The slight restructure moves the query arguments to an array that gets filtered rather than adding/removing from the url over and over.
Related: https://github.com/moderntribe/events-filterbar/pull/228
:movie_camera: http://p.tri.be/cXR0UB
:ticket: [FBAR-64] (sorta related)
[FBAR-64]: https://moderntribe.atlassian.net/browse/FBAR-64
=> Adjust the structure of next/prev URLs so they can be properly tested

src/Tribe/Views/V2/Views/Month_View.php
Ticket: n/a
This PR fixes an issue where the Month View would not correctly display events overlapping the start of the week.
[Screencap](https://drive.google.com/open?id=10qAp97sSGc6Fg9YJ2ncprSGrtXcJx-Ng&authuser=luca@tri.be&usp=drive_fs)
=> fix(Month_View.php) is_start_of_week var

src/Tribe/Views/V2/Views/By_Day_View.php
Ticket: n/a
This is a small refactoring of the `By_Day_View.php` code that filters the events to detect if those are happening on a given day or not.  
Applying the same logic used in other parts of the code, this is an "overlaps" check: the event overlaps the date if event start lte day end and event end gte day start.
=> refactor(By_Day_View.php) use overlap logic for day filtering

phpcs.xml, src/Tribe/Views/V2/View.php, src/Tribe/Views/V2/Views/Month_View.php, src/Tribe/Views/V2/Views/Traits/HTML_Cache.php, tests/views_integration/Tribe/Events/Views/V2/Views/Traits/HTML_CacheTest.php
Ticket: https://moderntribe.atlassian.net/projects/TEC/issues/TEC-3149
[Screencap](https://drive.google.com/open?id=10yValZTXe7gwIxhTDOICXRbyIhUIorix&authuser=luca@tri.be&usp=drive_fs)
This PR updates the cache system for V2, V1 will be handled in another PR when this is merged, to correctly handle private and password-protected events.
I've slightly modified the logic that @borkweb proposed to this:
1. if there are no password-protected events then cache the HTML in two versions: one for users that can read private posts, one for users that cannot read private posts
2. if there are password-protectec events, then do not cache.
Point 2 is due to the fact that password-protected events have to be checked one-by-one to see if the user (logged in or not) can see all their details.
I've not …
=> fix(Month/Week View) cache w/ private/protected posts

src/Tribe/Organizer.php, src/Tribe/Venue.php
Ticket: https://moderntribe.atlassian.net/browse/TEC-3165
[Screencap](https://drive.google.com/open?id=10tqy3dht8raSJCio_m2PBtF8LL4Wcwld&authuser=luca@tri.be&usp=drive_fs)
This PR fixes an issue generated by the way block editor saves the linked post data for Venue and Organizer: the fix is to `array_filter` the Venue and Organizer IDs during in the lazy collection call-backs to drop the `0` value added by block editor.
=> fix(src) filter out empty value from Org/Venue fetch callback

src/Tribe/Main.php, src/Tribe/Rewrite.php
🎟 [TEC-3211]
---
When dealing with non-network admin updates we need to have a delayed trigger of the flush of rewrite rules required for a plugin activation.
To avoid including a new class to activation methods we flag a transient and on `wp_loaded` which is early enough to properly find the paths and prevent 404s.
[TEC-3211]: https://moderntribe.atlassian.net/browse/TEC-3211
=> Modify when and how we do our activation process flush of permalinks.

src/functions/template-tags/venue.php
`tribe_get_region( $postId )` is called by `$tec->fullAddressString()` in `/src/Tribe/iCal.php`.
Currently all events with empty `_VenueProvince` will be populated with the `_VenueProvince` of the first event in iCal list view. This patch passes the `$venue_id` to `tribe_get_province()` so the correct (empty) value is returned.
=> Fix incorrect _VenueProvince in iCal list view

readme.txt, src/Tribe/Integrations/Manager.php, src/Tribe/Integrations/WP_Rocket.php, src/Tribe/Main.php, src/Tribe/Views/V2/View.php, src/Tribe/Views/V2/Views/Traits/Breakpoint_Behavior.php, src/resources/js/views/breakpoints.js, src/views/v2/components/breakpoints.php, src/views/v2/day.php, src/views/v2/list.php, src/views/v2/month.php
🎟 [TEC-3221]
---
When dealing with inline script concatenation the usage of `<script>` tags could lead to bugs with some of the major plugins for caching.
The changes suggested here will modify the code to no longer rely on the inline script tag to being inside of the container.
[TEC-3221]: https://moderntribe.atlassian.net/browse/TEC-3221
=> Cache inline scripts working with breakpoints

readme.txt, src/Tribe/Assets.php, src/Tribe/Main.php, src/admin-views/aggregator/page.php, src/admin-views/events-meta-box.php, src/deprecated/Tribe__Events__Asset__Dynamic.php
This prevents datepicker formats on the event edit page, JSON vars, aggregator datepicker, etc from defaulting the datepickerFormat index to a blank string. Our default is `1`.
Related: https://github.com/moderntribe/tribe-common/pull/1280
🎥
* Event Edit: http://p.tri.be/NHqoXF
* Aggregator: http://p.tri.be/VkkDoC
* Calendar View: http://p.tri.be/ewgdS7
🎫 [TEC-3229]
[TEC-3229]: https://moderntribe.atlassian.net/browse/TEC-3229
=> This leverages new Date_Utils method for fetching datepickerFormat index

composer.json
Following merge of the [PR](https://github.com/lucatume/wp-snapshot-assertions/pull/2) we can resume using `dev-master` branch.
=> build(composer.json) track dev-master on testing-facilities

.gitignore, readme.txt, src/Tribe/Main.php, src/Tribe/Views/V2/View.php, tests/_support/Modules/Options.php
[TEC-3072]
We changed the live update to a radio - this ensures all the checks against the option are correct now (it was originally a boolean/checkbox).
📷 http://p.tri.be/ClOYUS (submit button shows on "manual")
📸 http://p.tri.be/bnke7V (no button and "live reload" on "automatic")
Related: https://github.com/moderntribe/events-filterbar/pull/236
[TEC-3072]: https://moderntribe.atlassian.net/browse/TEC-3072
=> Update the conditional checks for the new live update radios.

readme.txt, src/Tribe/Aggregator/API/Origins.php
Removal of the "beta" label as has been a while that the label is there,
as requested.
Ticket: [TEC-3289]
Ticket: [EA-140]
[TEC-3289]: https://moderntribe.atlassian.net/browse/TEC-3289
[EA-140]: https://moderntribe.atlassian.net/browse/EA-140
=> Update label for EA other URL import

readme.txt, src/Tribe/Aggregator/Record/Abstract.php
If an event does not set the value for "post_status" fallback to the settings value from EA, based on the origin.
Tickets: 
- [TEC-3255]
- [EA-152]
[TEC-3255]: https://moderntribe.atlassian.net/browse/TEC-3255
[EA-152]: https://moderntribe.atlassian.net/browse/EA-152
=> TEC-3255, EA-152: Respect EA value for "post_status" when not set

src/Tribe/Views/V2/Template/Page.php
_Ref:_ [TEC-3253](https://moderntribe.atlassian.net/browse/TEC-3253)
Readme is in the previous PR, this fixes a regression when using the Default Page Template.
https://github.com/moderntribe/the-events-calendar/pull/3083
=> TEC-3253 - fix regression when using the default page template

src/Tribe/Importer/File_Reader.php
Remove the need to declare a variable
=> Convert into an inline return and remove non used variable

readme.txt, src/Tribe/Views/V2/Hooks.php
A simple fix reported by the GravityView team when trying to do Gravity Forms Imports it would fail due to our redirect catching their request.
They have already tested that fix on their side, it works, I already tested this piece with the Embeds and Mobile redirects that this piece of code interacts with.
Not a lot to Screencast here, I this should be tested on our normal full pass.
=> Preventing redirects from updated Views V2 to be too broad

readme.txt, src/Tribe/Views/V2/Template/Page.php
[Internal Slack conversation detailing the bug report](https://tribe.slack.com/archives/C0258NG6N/p1585246131036200).
This was preventing anything other than page from actually being a template selected, which broke the behavior expected on that setting.
=> Dont prevent non-page make it an exact check for event template settings

composer.json, src/Tribe/Views/V2/Views/Traits/HTML_Cache.php
Just allows for turning it off in wp-config instead of having to use the filter.
=> Add constant to turn off views HTML caching.

readme.txt, src/modules/editor/utils/geo-data.js
Issue: https://moderntribe.atlassian.net/browse/TEC-3361
[Screencap](https://drive.google.com/open?id=14rY0aECsSy37iUuXpJdvXvLdYUPexKUU&authuser=luca@tri.be&usp=drive_fs)
This PR fixes the issue where, only in the context of the Event Block Editor, creating a Venue would default the Venue country to US.
=> fix(editor/geo-data.js) default country code to empty string

src/Tribe/Google/Maps_API_Key.php
While going through translations I discovered that we have the string 'Read more' in several different ways in the code:
- Read more (twice, which I took as the correct one)
- Read More
- Read more.
- Read More.
In this PR, and another one in tribe common I have unified these to all say 'Read more'. If there is a period after the string, that has been moved out, so it does not show up in the translation.
Jira: https://moderntribe.atlassian.net/browse/BTRIA-307
=> Updated 'Read more' string

src/Tribe/Query.php
Issue: https://moderntribe.atlassian.net/browse/ECP-391
No screencapture available as this issue seems to come into play only when the parent event of a series is manually removed from the database, not using our UI.
=> fix(Query.php) add parent event to query only if available

src/views/v2/latest-past.php
Prevents two containers and loaders from being rendered (see image below):
=> update latest past view template

src/Tribe/Views/V2/View.php
_Ref:_ [TEC-3385](https://moderntribe.atlassian.net/browse/TEC-3385)
With Pro active you can select the view for Mobile. One of those options is `Default`
This update supports if Default is selected.
=> TEC-3385 - fix Latest Past Events if mobile view is set to default

readme.txt, src/Tribe/Views/V2/Template/Page.php
🎟 [TEC-3434]
---
I wasn't able to reproduce the problem, but it seems related to the `date = 0` that we use to mock the page and how navigation will use that post date to figure out next and previous.
[TEC-3434]: https://moderntribe.atlassian.net/browse/TEC-3434
=> TwentyTwenty Navigation was throwing warings due to 0 on date fields

src/Tribe/Views/V2/Hooks.php
This PR fixes our code to make sure we're only using the screen object if it's, actually, a `WP_Screen` instance.
See:  https://tribe.slack.com/archives/CEUHNUF3R/p1587628382029600?thread_ts=1587622497.017900&cid=CEUHNUF3R
=> fix(Views v2) use of get_current_screen

readme.txt, src/Tribe/Editor/Template.php, src/views/blocks/event-datetime.php, tests/wpunit/Tribe/Events/Editor/TemplateTest.php
And code that checks for site data if event data is missing.
The attr() function was being passed an extra param, so it was returning incorrect default values.
The timezone info is saved to the block as attributes - so it's not saved to meta and it's not saved if the block isn't changed. This means that if we get a default value back, we have to check for it in Event->Settings->General.
[TEC-2964]
[TEC-2964]: https://moderntribe.atlassian.net/browse/TEC-2964
=> Code that fixes the incorrect data being passed.

readme.txt, src/Tribe/Templates.php
🎟 [TEC-3104]
---
No changes in behavior just add compatibility for version PHP 7.0 and above. 
Originally added here: https://github.com/moderntribe/the-events-calendar/pull/2750
[TEC-3104]: https://moderntribe.atlassian.net/browse/TEC-3104
=> Remove incompatible usage of func_get_args for PHP 7.0 

src/Tribe/Views/V2/functions/classes.php, src/views/v2/month/calendar-body/day/multiday-events/multiday-event.php, tests/wpunit/functions/classes/Month_Multiday_ClassesTest.php
In #3169 we've introduced a namespaced function that would still be called as if in the global namespace,
the `tribe_events_month_multiday_classes` one.
This PR shortens the function name to stick w/ namespaced functions convention.
=> Shorten multiday function name.

src/Tribe/Cost_Utils.php
While working on other code I found out the `Cost_Utils` class would incorrectly handle, in the `get_event_costs` method, new posts that will have a meta value set to `''`.
This PR makes sure we cast and filter the array before treating it as such.
=> Fix Cost_Utils to correctly handle empty costs

readme.txt, src/Tribe/Repositories/Event.php, tests/wpunit/Tribe/Events/ORM/Events/CreateTest.php
Related to https://github.com/moderntribe/tribe-common/pull/1377 
This PR leverages the work done in common.
=> Ensure Organizer ID meta is unpacked on write by ORM

readme.txt, src/Tribe/Linked_Posts.php, src/resources/js/events-admin.js
Typically when you are not logged in as the owner of a venue or organizer, you may get an empty edit link for a linked post type. This is more pronounced when you are logged out using the Community Events submission form when anonymous submissions are enabled.
This PR addresses this by introducing a new data attribute to know which options are an existing linked post and which are brand new. Only existing linked posts will get the data attribute as when typing to create a new one will have that attribute not set ensuring it's treated as intended (as a new linked post to create with the fields).
[TEC-3481]
All screenshots below are from the event submission form while logged out (with anonymous submissions enabled).
[TEC-3481]: https://moderntribe.atlassian.net/browse/TEC-3481
=> Add existing-post to linked post option data and use that to determine if 'new fields' should be shown

readme.txt, src/Tribe/Main.php, src/Tribe/Service_Providers/First_Boot.php, tests/views_wpunit/Tribe/Events/Views/V2/Template_BootstrapTest.php
Issue: https://moderntribe.atlassian.net/browse/TEC-3453 
[Screencap](https://drive.google.com/open?id=18BwF0dUQD5fcQXz9ulNCF4eloZkTIJ7z&authuser=luca%40tri.be&usp=drive_fs)
This PR:
1. Adds a `First_Boot` provider.
2. In that provider set the event template (Events > Settings > Display) to the Events one by default.
While the solution might seem a bit overkill for the issue at hand (set the template to a default value),
it scaffolds an extensible solution to consistently and efficiently handle "fresh installs".
Currently the code contains many places where we make checks like "if this has never been set, then set it
to this value" that could really fit into this provider.
As we model the "fresh install" experience more and more, this provider will grow into a less overkill solution
and …
=> Add a provider dedicated to first boot

src/Tribe/Linked_Posts.php
Issue: n/a
Removes  the `<b></b>` around the Create template of linked posts
to avoid visualization issues due to escaped HTML.
=> Remove HTML markup from Create linked post

src/Tribe/Integrations/WPML/Filters.php
This change, together with another change in WPML that will be released in 4.3.16, fixes archive slug translations.
=> Load bases for archive slug translation

.travis.yml, composer.lock, src/Tribe/Main.php, src/Tribe/Repositories/Event.php, src/Tribe/Views/V2/Views/By_Day_View.php, tests/integration/Navigation_Test.php, tests/wpunit/Tribe/Events/ORM/Events/FetchByDateTest.php, tests/wpunit/Tribe/Events/ORM/Events/FetchByDurationTest.php
This PR fixes an issue brought to light by [Stephen PR](https://github.com/moderntribe/the-events-calendar/pull/3227) (which is in no way responsible for the problem!)
that would cause "strange" failures when fetching events by date, either UTC or the
local-to-the-event-timezone one.
The issue is that, in the SQL we use in the `Tribe__Events__Repositories__Event::order_by_date`
method we build this SQL:
```sql
SELECT  DISTINCT test_posts.ID, MIN( orderby_event_date_utc_meta.meta_value ) AS event_date_utc ...
[...]
GROUP BY test_posts.ID ORDER BY event_date_utc DESC, test_posts.post_date
```
The issue with this code is that `MIN( orderby_event_date_utc_meta.meta_value ) AS event_date_utc`
will not make the `event_date_utc` a date-relevant field to sort events by.
So: why did this work …
=> Fix Event ORM SQL to order events by date

src/resources/js/views/manager.js
Issues:
* https://moderntribe.atlassian.net/browse/ECP-376
* https://moderntribe.atlassian.net/browse/ECP-374 
This PR supports the work done to make Views V2 work correctly
in the context of shortcodes and theme builders.
Why is this required?
When a shortcode is added in the context of a theme builder, then
it will be rendered as a post body and rendered second.
That rendering is **not** in our control, it's in the control of the
theme builder.
In that process the `data-js` attribute contents, that we use in Views
v2 to hydrate a number of functionalities, will be escaped.
The code in `manager.js` will, then, try to `JSON.parse` it and fail.
Normally:
post -> shortcode -> print HTML
In theme builder:
post -> render shortcode -> escape -> print HTML
The fix is simply one where we …
=> Normalize Views v2 data attribute before usage

src/functions/template-tags/general.php, src/functions/template-tags/organizer.php, src/functions/template-tags/venue.php
Remove the esc_html, add comments to the docblocks that we do not escape and all output should be escaped.
Not part of this ticket, but following CR [comments and new direction forward](https://github.com/moderntribe/events-virtual/pull/161#discussion_r462097152) from it.
[VE-136]
[VE-136]: https://moderntribe.atlassian.net/browse/VE-136
=> Tweak( template tags): Don't escape.

.travis.yml
This PR disables the `restv1` suite, covering the REST API v1 implementation from the acceptance level, as it became inconsistent in its failures over the last period.
The PR is **NOT** a permanent disable of the suite, I'm just taking it down for maintenance with the intent of cleaning up the build outputs of intermittent failures, unblocking devs and working on the issue(s) of the suite with more time.
=> Disable restv1 suite

readme.txt, src/Tribe/I18n.php
This PR is just a repackage of the [original PR from the WPML team](https://github.com/moderntribe/the-events-calendar/pull/3272) to add the changelog entry and test it out locally.
Credit for the fix goes to WPML team!
Issue: https://moderntribe.atlassian.net/browse/TEC-3578
[Screencast (no audio)](https://drive.google.com/open?id=1CRRHxMq5N69jBgN2y1xmWrHas4ZMmK60&authuser=luca%40tri.be&usp=drive_fs)
In the screencast I'm **not** testing the plugin with WPML activated as the WPML Team, that provided [the original PR I am only repackaging](https://github.com/moderntribe/the-events-calendar/pull/3272), has already tested that. In the screencast I am making sure the localization functions keep working correctly when the fix is applied (they do), including permalink localization and …
=> Add doc entry for TEC PR 3272

src/Tribe/I18n.php
https://wpml.org/de/forums/topic/adminbar-auf-deutsch-zeigt-funktionen-teilweise-auf-franzoesisch
https://wpml.org/forums/topic/admin-bar-isnt-displayed-in-default-language
https://wpml.org/forums/topic/adming-language-showing-in-wrong-language
https://wpml.org/forums/topic/automatically-showing-the-events-page-in-portugues-instead-of-default-english
https://wpml.org/forums/topic/chinese-strings-in-front-end-admin-bar-and-english-home-page
https://wpml.org/forums/topic/modern-tribe-events-calendar-events-page-displaying-french-text-on-english-page
https://wpml.org/forums/topic/string-translations-are-mixedup
https://wpml.org/forums/topic/wpml-chat-support-ticket-by-daniellem-2-1597319479
=> With WPML some strings are loaded in the wrong language.

src/Tribe/Views/V2/View.php, tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_base_template_if_view_has_no_template__1.php
Issue: https://moderntribe.atlassian.net/browse/TEC-3579
[Screencast](https://drive.google.com/open?id=1CUDUUP10O2N1n9-bm47NTcdpuaE-FXZX&authuser=luca%40tri.be&usp=drive_fs)
This PR fixes the issue that was caused by the following combination:
1. the user is not logged in
2. WooCommerce will filter the `nonce_user_logged_out` filter to set the user id to a hash used for cart tracking
3. the user id is part of the salts used to generated the nonces, including the views nonce, during the PHP initial state render
4. WooCommerc will not filter the `nonce_user_logged_out` filter during AJAx requests
5. during the AJAX requests fired by the Views to fetch the new HTML the nonce provided (salted with the hash user id) will not match the one generated without applying hashes (point 4: WC is not …
=> Generate the REST nonce suspending WC filters

src/resources/js/views/accordion.js
This PR modifies the auto-binding function of the accordion script to avoid issues when not using it in the Views Front-end context.
=> Allow the accordion script to run out of FE context

src/Tribe/I18n.php, src/Tribe/Integrations/WPML/Filters.php, src/Tribe/Integrations/WPML/WPML.php, src/Tribe/Rewrite.php
Issue: https://moderntribe.atlassian.net/browse/TEC-3578
This PR fixes some smaller issues I found while inspecting the issue that would make the translation
of the site slugs incorrect when using the WPML integration.
[Screencast (no audio)](https://drive.google.com/open?id=1D3Z08GM1ucS69CtZAsL70kd6P-Q4RTtP&authuser=luca%40tri.be&usp=drive_fs)
=> Fix some WPML integration issues and add default value for translation flags.

readme.txt, src/Tribe/Views/V2/Views/Latest_Past_View.php
This PR updates the Latest Past Events view to allow overriding its safelist
at run-time and allow templates to show hide with filter control.
[Screencast showing FBAR support that would not show before](https://drive.google.com/open?id=1D4PpfwChYp9JNe89tPNjwhNx8sTTKQDw&authuser=luca%40tri.be&usp=drive_fs)
=> Allow filtering the template display

readme.txt, src/Tribe/Views/V2/Views/List_View.php
Issue: https://moderntribe.atlassian.net/browse/ECP-467 
[Screencast](https://drive.google.com/open?id=1Fi6u79JEMep5HskfRIVZmQI7uoAAWNzD&authuser=luca%40tri.be&usp=drive_fs)
[Screeenshot of PRO tests passing](https://drive.google.com/open?id=1FWKM3vg9ETuWLyXevCuZzycf13syLmPV&authuser=luca%40tri.be&usp=drive_fs)
This PR fixes an issue where List View would not display events in ASCending order when the PRO setting "Recurring Event Instances" > "Show only the first instance of each recurring event" is activated.
The issue originated from the fact that List View would assume the default repository order direction would be set to ASC (correct in most cases), but would not enforce it.
The order would, but, be DESC when that setting is activated (due to how that setting works) and List View …
=> Ensure List View displays in ASC order

src/Tribe/Views/V2/View.php
Issue: n/a
[Screencast](https://drive.google.com/open?id=1FxWxbIlNkuWSxyK2VKKeq7enXGMQrWeT&authuser=luca%40tri.be&usp=drive_fs)
This PR fixes an issue where caused by the fact that trying to sort/prune `WP_Post` objects using the `array_unique` function would try and cast them to `string`; the function should be used using the `SORT_REGULAR` flag to avoid this kind of issues.
=> Do not cast types when sorting

src/Tribe/Importer/Column_Mapper.php
The variable it was never used other than for directly accesing inside
of the filter call, in this case having a variable sitting around for no
use does not provide any additional value.
=> Removal of non required variable

readme.txt, src/Tribe/Views/V2/View.php
While we corrected the prev/next links in [ECP-492] ( see https://github.com/moderntribe/the-events-calendar/pull/3304 ). The issue still remains for the "today" button.
This implements a similar fix for the today button.
I looked for additional instances of this url handling on my local and didn't find any. If anyone knows of another it would make sense to add it to this PR.
[ECP-492]: https://moderntribe.atlassian.net/browse/ECP-492
📷 Broken: http://p.tri.be/uHG5NM
📸  Fixed: http://p.tri.be/rCfKW3
[ECP-528]
[ECP-528]: https://moderntribe.atlassian.net/browse/ECP-528
=> ECP-528 Correct the today link on shortcodes with category(s).

readme.txt, src/Tribe/Models/Post_Types/Event.php, src/Tribe/Models/Post_Types/Organizer.php, src/Tribe/Models/Post_Types/Venue.php, src/Tribe/Organizer.php, src/functions/template-tags/organizer.php, tests/wpunit/functions/template-tags/eventTest.php, tests/wpunit/functions/template-tags/organizerTest.php
Issue: n/a
This PR adds the `tribe_get_organizer_object` function and, 
with it, all the attached structure to return a list of
Organizer post objects on `tribe_get_event()->organizers`.
The previous return value of the method, a collection of
Organizer names, is moved to the `tribe_get_event()->organizer_names`
method.
Artifacts: see tests.
=> Add the `tribe_get_organizer_object` function.

readme.txt, src/Tribe/Views/V2/Views/List_View.php
With this small change (which is present on a couple of other views), we make the List View extendable when creating new views—which should make new views more DRY.
:movie_camera: http://p.tri.be/LsTnFg
:ticket: [TEC-3648]
[TEC-3648]: https://moderntribe.atlassian.net/browse/TEC-3648
=> Use $this->slug when generating prev/next URLs for List View | TEC-3648

readme.txt, src/functions/template-tags/general.php, tests/wpunit/functions/template-tags/generalTest.php
Issue: n/a
This PR fixes an issue I ran into while working on other code that would cause
the `tribe_is_past_event` template tag to incorrectly report past events due
to an incorrect handling of the `UTC+0` timezone string.
Since that is the WordPress default on installations that are defining, via
filters too, an incorrect timezone string, this mis-handling could result in
consistent PHP Warnings on some sites, or, as is the case, on new installations.
The fix consists in building the timezone object using our more robust Timezone
handling class.
=> Fix and timezone handling issue

readme.txt, src/Tribe/Aggregator/Record/Eventbrite.php
JIRA Ticket: [TEC-3569](https://moderntribe.atlassian.net/browse/TEC-3569)
- Map all statuses to at least 'Draft', 'Private' or 'Published', ensuring no "orphaned" events due to invalid status
=> Fix/TEC-3569 - Fix Eventbrite 'do_not_override' status and additional statuses

src/resources/postcss/components/skeleton/_events-bar.pcss
**Ticket:** N/A
Spotfix a small issue with the accent not showing up when displaying mobile search
**Artifact:**
Before
After
=> move mobile search down to display search button accent

src/Tribe/Customizer/Single_Event.php
**Description:** Updates the Customizer UI's Single Event tab to include headings and other copy changes
**Ticket:** https://moderntribe.atlassian.net/browse/TEC-3654
=> Feature / TEC-3654 improved ui single event tab

src/Tribe/Customizer/Global_Elements.php
**Description:** Fixes the order of Links and Accent Color controls, according to the mockup and AC
**Ticket:** https://moderntribe.atlassian.net/browse/TEC-3653?focusedCommentId=91740
=> Fix / TEC-3653 inverted controls

src/Tribe/Views/V2/Widgets/Widget_List.php
**Ticket:** [TEC-3612]
This PR fixes the name for the events list widget in the admin.
**Artifact:**
[TEC-3612]: https://moderntribe.atlassian.net/browse/TEC-3612
=> update name of the list widget in the admin

src/Tribe/Views/V2/Hooks.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php, tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
Issue: https://moderntribe.atlassian.net/browse/TEC-3686 
Based on: https://github.com/moderntribe/tribe-common/pull/1509
This PR filters the action the Customizer will use to try and print inline styles to use the `wp_print_footer_scripts` one and print inline styles in the footer.
- feat(Views/V2) filter customizer inline styles print action
- build(common) track latest
=> Filter Customizer inline print styles action

.travis.yml
This PR updates the `.travis.yml` file to correctly roll back composer to version 1, if reuired.
=> Correctly rollback composer version

src/resources/postcss/components/full/_top-bar.pcss, src/resources/postcss/components/skeleton/_top-bar.pcss
**Description:** Fixes a misalignment introduced by the latest changes to svg icons. Also includes a fix for the background color of the disabled nav icon on Genesis as bonus. You're welcome (well, I guess it was my fault). See the issues in the screenshots attached.
**Ticket:** https://moderntribe.atlassian.net/browse/TEC-3651
=> Fix / TEC-3651 nav icons alignment

src/Tribe/Views/V2/Url.php, tests/views_integration/Tribe/Events/Views/V2/UrlTest.php
Ticket: https://moderntribe.atlassian.net/browse/FBAR-208
[Screencast](https://drive.google.com/open?id=1J5gu4sSo36p_39MoMjAtelOY9XOweENy&authuser=luca%40tri.be&usp=drive_fs)
This PR fixes the issue in FBAR, and elsewhere, where going from `/events` (hence using default view) would not correctly load, in Views v2 AJAX requests, page 2 of the default view (e.g. `/events/list/page/2`) and would require a second click to work.
=> Fix handling of URL query args diff

readme.txt, src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
**Description:** Updates the fast-forward link on the month view so that the plural version of the content type label is used, rather than always showing the hardcoded "events". That comes from the Relabeler extension, if defined ("classes" in the screenshot).
**Ticket:** https://moderntribe.atlassian.net/browse/TEC-3452
=> Fix / TEC-3452 fast forward link copy

src/Tribe/Views/V2/Assets.php, src/Tribe/Views/V2/Widgets/Widget_Abstract.php
**Ticket:** [ECP-690]
This fixes an issue with the countdown widget JS not loading properly, but loading after the manager. This enqueues the manager as the last JS asset to allow all the other JS files to work properly.
**Artifact:**
=> properly enqueue manager script as last script to be enqueued

src/resources/js/views/manager.js, tests/wpunit/Tribe/Events/Importer/File_Importer_Events_ReimportBehaviourTest.php, tests/wpunit/Tribe/Events/Importer/File_Importer_Organizers_FeaturedImageTest.php, tests/wpunit/Tribe/Events/Importer/File_Importer_Venues_FeaturedImageTest.php
The `prev_url` was using `window.location.href`, which _only_ works for the main event page. Updating the `prev_url` to use the `containerData` will always contain the appropriate value whether you are on the main event page or shortcodes.
=> Fetch prev_url from containerData

src/Tribe/Views/V2/Assets.php, src/resources/postcss/views/full/_single-event.pcss, src/resources/postcss/views/skeleton/_single-event.pcss
**Description:** This disabled the enqueueing of v1 styles to provide a clean slate for styling the whole Event Single view
**Ticket:** https://theeventscalendar.atlassian.net/browse/TEC-3755
**Screenshots:** see https://github.com/the-events-calendar/the-events-calendar/pull/3429 and others
=> Feature / TEC-3755 disable v1 styles

src/Tribe/Customizer/Single_Event.php, src/resources/postcss/views/full/_single-event.pcss, src/resources/postcss/views/skeleton/_single-event.pcss
**Description:** Updates the Event Single details block styles for V2. It also removes the Customizer background color override for the block.
**Note:** Related on https://github.com/the-events-calendar/the-events-calendar/pull/3442 for some layout updates
**Tickets:**
- https://theeventscalendar.atlassian.net/browse/TEC-3758
- https://theeventscalendar.atlassian.net/browse/TEC-3761
- https://theeventscalendar.atlassian.net/browse/TEC-3767
**Screencast:**
https://d.pr/i/7gmLNe
=> Feature / TEC-3758 event details

src/resources/postcss/views/full/_single-event.pcss, src/resources/postcss/views/skeleton/_single-event.pcss
**Description:** Adds styles to update the way Related Events block displays
**Note:** This also modifies the whole single event layout to re-order blocks according to the designs. It also separates part of the `.recurringinfo` styles to display things a bit differently between the top header and the related events metadata.
**Ticket:** https://theeventscalendar.atlassian.net/browse/ECP-673
=> Feature / event single related events updates

src/Tribe/Views/V2/Assets.php
**Description:** Fixes the logic behind disabling v1 styles on the single event view. In order to have them enabled, the view should:
- be a single event view
- have either the Block Editor enabled OR have the Classic editor enabled but the new styles overrides disabled (via the constant `TRIBE_EVENTS_SINGLE_VIEW_V2_DISABLED`)
=> Fix / event single v1 styles disabling logic

readme.txt, src/Tribe/Views/V2/Assets.php, src/Tribe/Views/V2/Widgets/Widget_Abstract.php, src/resources/js/views/datepicker.js, src/resources/js/views/manager.js
#3426 introduced a problem related to the Manager not being enqueued in the correct time. Depending on the order of how your Widgets/Shortcodes are rendered in the screen it breaks the manager, to resolve that problem we stop messing with the actual enqueuing and defer the execution on a browser level.
Depends on https://github.com/the-events-calendar/tribe-common/pull/1549
Video: https://i.bordoni.me/yAu6kmN6
=> Manager JS using `defer`

src/modules/blocks/event-datetime/content/template.js
**Description:** Removes the price field inside the datetime block for events migrated from the Classic editor to the Blocks editor.
**Ticket:** https://theeventscalendar.atlassian.net/browse/TEC-3458
=> Remove field

readme.txt, src/modules/blocks/classic-event-details/container.js, src/modules/blocks/classic-event-details/event-details-organizers/event-details-organizer/template.js, src/modules/blocks/classic-event-details/event-details-organizers/template.js, src/modules/blocks/classic-event-details/template.js, src/modules/blocks/event-datetime/content/template.js, src/modules/blocks/event-datetime/controls/template.js, src/modules/blocks/event-links/template.js, src/modules/blocks/event-organizer/container.js, src/modules/blocks/event-organizer/form/template.js, src/modules/blocks/event-organizer/template.js, src/modules/blocks/event-price/template.js, src/modules/blocks/event-venue/template.js, src/modules/blocks/event-website/template.js, src/modules/data/blocks/organizers/subscribers.js, src/modules/elements/search-posts/template.js, src/modules/elements/venue-form/element.js
**Description:** Fixes some deprecation warnings when using the block editor with the dev tools console open. It depends on https://github.com/the-events-calendar/tribe-common/pull/1554
**Note:** Some might still appear as they need a fix in the WordPress core:
- `Found 2 elements with non-unique id #_wpnonce` [development/production]
- React rename lifecycle methods (due to an old version of Redux used by core) [development]
- `Legacy context API has been detected within a strict-mode tree.` [development]
**Ticket:** https://theeventscalendar.atlassian.net/browse/TEC-3418
=> Fix / TEC-3418 - deprecated warnings

src/Tribe/Views/V2/Hooks.php, src/functions/template-tags/link.php, src/functions/template-tags/organizer.php, src/functions/template-tags/venue.php, src/resources/postcss/views/skeleton/_single-event.pcss, src/views/modules/meta/details.php, src/views/modules/meta/organizer.php, src/views/modules/meta/venue.php
**Description:** Update the details block so that the website field displays as a named link by default. Customers are then allowed to disable that behaviour and return to "Website: [link]" via a filter removal.
**Note:** To disable use (venue example):
`remove_filter( 'tribe_get_venue_website_link_label', [ tribe( 'events.views.v2.hooks' ), 'filter_single_event_details_venue_website_label' ] );`
`remove_filter( 'tribe_events_get_venue_website_title', '__return_empty_string' );`
**Ticket:** https://theeventscalendar.atlassian.net/browse/TEC-3758
=> Feature / single event reskin website label

src/views/modules/meta/venue.php
**Description:** Fixes the website label when the filters are removed with the following:
```
remove_filter( 'tribe_get_venue_website_link_label', [ tribe( 'events.views.v2.hooks' ), 'filter_single_event_details_venue_website_label' ] );
remove_filter( 'tribe_events_get_venue_website_title', '__return_empty_string' );
```
**Ticket:** https://theeventscalendar.atlassian.net/browse/TEC-3758
=> Fix / website label disabled

readme.txt, src/Tribe/Admin/Notice/Legacy_Views_Deprecation.php, src/Tribe/Main.php
🎫 [TEC-3809]
---
Added a recurring notice every 2 weeks around the Legacy views usage.
Depends on https://github.com/the-events-calendar/tribe-common/pull/1563
📹 https://i.bordoni.me/12uoW9Q8
---
Note that the developer and user version of the notice are the same until we update the copy later on in the sprint.
[TEC-3809]: https://theeventscalendar.atlassian.net/browse/TEC-3809
=> Add recurring notice about legacy views.

src/resources/postcss/views/skeleton/_single-event.pcss
**Description:** Fixes an issue where the "This event has passed." notice wasn't left aligned in Twenty Twenty and Twenty Twenty One themes.
**Ticket:** https://theeventscalendar.atlassian.net/browse/TEC-3693
=> Fix / event single themes compatibility

src/Tribe/Repositories/Organizer.php, src/Tribe/Repositories/Venue.php
@bordoni we discussed this.
When the filters were added, we'd intended to add one more each but they were never developed. They should be removed before release.
=> Remove filters that haven't been developed yet.

src/Tribe/Views/V2/Widgets/Assets.php
Widget styles should require common styles.
Bad: https://d.pr/i/DiS1WZ
Good: https://d.pr/i/7OccCg
=> Require common styles for widget styles.

tests/_support/Factories/Event.php
Out of the box build the local start and end date, instead if a local time is provided it should be constructed using the provided timezone so the local time is adjusted accordingly if a timezone change occurs around the initial local times.
The current behavior creates an event with the wrong dates information when creating an event using the following signature.
```php
factory()->event->create( [
'timezone' => 'America/Los_Angeles',
'when'     => '2020-01-01 08:00:00',
] );
```
The current behavior it creates and event with the start date as: `+2020-01-01T00:00:00.000000-0800` (UTC) date instead of the expected date `-2020-01-01T08:00:00.000000-0800` this date instead is used as the `UTC` date of the event.
=> Build the time with the specified timezone

readme.txt, src/Tribe/Views/V2/Assets.php
**Ticket:** [TEC-3848]
This PR ensures the v2 event single full styles are only enqueued when the setting is set to full styles, not skeleton.
**Artifact:**
[TEC-3848]: https://theeventscalendar.atlassian.net/browse/TEC-3848
=> Only enqueue full styles for event single v2 when display setting is full styles

src/Tribe/Views/V2/Hooks.php, src/functions/template-tags/link.php, src/views/blocks/classic-event-details.php, src/views/blocks/parts/details.php, src/views/modules/meta/details.php
The issue: 
The event website link label is not being filtered correctly.
Reason:
The filters rely on a valid post ID - and we don't always pass one.
Correction:
1. Find our uses of tribe_get_event_website_link() and include the post ID - it's a param and since it's available in every case we should pass it.
2. Add functionality to _get_ the post ID if it's not passed (for backwards compatibility and customizations)
https://d.pr/i/YJlL0I
[ECP-761]
Related: https://github.com/the-events-calendar/events-pro/pull/1734
[ECP-761]: https://theeventscalendar.atlassian.net/browse/ECP-761
=> Correct implementation of tribe_get_event_website_link()

src/Tribe/I18n.php
Issue: https://theeventscalendar.atlassian.net/browse/TEC-3810
This further PR on the work done in the first PR for the issue
integrates the snippet of code [shared by the WPML
team](https://wpml.org/errata/the-events-calendar-issues-with-string-translation/
) to fix more issues found during the first QA pass.
[Screencap](https://www.dropbox.com/s/o5gn2pqkar08lmm/TEC-3810-pass-2-self-qa.mov?dl=0)
=> Integrate WPML team language handling snippet

readme.txt, src/views/v2/day/time-separator.php
Issue: https://theeventscalendar.atlassian.net/browse/TEC-3877
This fixes an issue where the Day View time separator HTML would use the
event start time, without consideration of the Event Timezone and of the
site timezone settings (Events > Settings > "Timezone Settings" >
"Timezone Mode".
The fix consists in using the already available
`$event->dates->display_date` object that will be set, depending on the
site timezone mode settings, to the correct date and timezone to use
when the event details require, as the name implies, displaying.
[Screencap](https://www.dropbox.com/s/h99d1bd3ajyc9cq/TEC-3867-self-qa-2.mov?dl=0)
=> Fix Day View time separator time

readme.txt, src/Tribe/Views/V2/iCalendar/Request.php, tests/views_integration/Tribe/Events/Views/V2/iCalendar/RequestTest.php
Issue: https://theeventscalendar.atlassian.net/browse/TEC-3886
Fix the single event export by taking into account the request for the
single event.
Before we would build the View directly on the `view` context location
return value, when looking at single events, that return value would be
`single-event` that, not resolving to any View, would default to the
current default View (usually List).
This fix specially handles the iCalendar export request coming from
single event to return that single event ID only.
[Screencap](https://www.dropbox.com/s/dktmrh3con0bl1z/TEC-3886-self-qa.mov?dl=0)
=> Fix single event iCalendar export

readme.txt, src/resources/js/views/manager.js
Make sure hash changes on the URL are just to move the viewport to
the correct section of the page but on the same URL, for that
scenario we don't need to request a new request as the URL
didn't change.
Artifact: https://d.pr/v/5GeZUb
Ticket: TEC-3890
=> TEC-3890: Prevent to trigger `xhr` requests for hash changes.

readme.txt, src/Tribe/Main.php, tests/wpunit/functions/template-tags/GoogleCalendarTest.php
For the google calendar link use the timezone value according to the
settings specified on the settings of the calendar to make sure
behavior is consistent with the rest of the page.
Ticket: TEC-3143
Artifact: https://d.pr/v/VaYWQc
=> TEC-3143: Use the timezone accordingly with the settings on export link

.github/workflows/tests-php.yml
This is an optimization in workflow shenanigans so that we don't run the automated tests when we don't have to.
THREE CHEERS FOR INNOVATION DAY!
=> Only run Codeception tests when changing files that require it

src/views/v2/list.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
Make sure the list view on mobile displays the not found message when no
events are present on mobile layout.
Ticket: TEC-3812
This is done on top of https://github.com/the-events-calendar/the-events-calendar/pull/3514 to make sure this is not a regressive issue.
=> Make sure not found messages are render on mobile

src/Tribe/Views/V2/Customizer.php, src/resources/postcss/views/full/month/_calendar-event.pcss
Switch default color to use the primary + opacity
Ensure the Customizer also incorporates the opacity.
[TEC-3709]
[TEC-3709]: https://theeventscalendar.atlassian.net/browse/TEC-3709
=> Fix opacity on date colors.

readme.txt, src/resources/postcss/tribe-events-full.pcss
🎫  [TEC-3937]
The styles that we're applying for the 2019 overrides are taking over the `entry` of any other thing that's used in that page. In our case (Event Tickets) it's adding a margin top on every item of the tickets block. I assume for WooCommerce or any other thing that uses the post classes it'll happen the same.
On hold until is ticketed and assigned for a given sprint.
https://www.loom.com/share/e9dc59b71ef94f2382edb3af72cbdbb1
[TEC-3937]: https://theeventscalendar.atlassian.net/browse/TEC-3937
=> [TEC-3937] Fix for single view and Event Tickets compatibility when using `twentynineteen`.

readme.txt, src/Tribe/Editor/Meta.php
Similar to the Event API call that is done on event additions/updates in the classic editor, we need to give the opportunity for ET/ET+ and other sources to influence the cost fields.
🎥 https://d.pr/v/tMH4z7
🎫 [TEC-3141]
[TEC-3141]: https://theeventscalendar.atlassian.net/browse/TEC-3141
=> Trigger update to _EventCost when updating events via the Block Editor | TEC-3141

readme.txt, src/Tribe/Views/V2/Utils/View.php
Since the URL param is not namespaced, we cannot assume we will get back _our_ info.
This caused a plugin conflict and fatal here as Analytify also uses the `view_data` param - and it's a simple string.
Possibly a larger question here as to how/why the function is being called in the first place on an admin page that isn't ours?
[TEC-3946]
[TEC-3946]: https://theeventscalendar.atlassian.net/browse/TEC-3946
=> Cast tribe_get_request_var to array.

readme.txt, src/Tribe/Editor.php, src/Tribe/Editor/Provider.php, tests/views_integration/Tribe/Events/Views/V2/Partials/__snapshots__/Google_Map_LinkTest__test_render__1.php
Only load the blocks editor if explicitly enabled from the events
settings.
[TEC-3964]
[TEC-3964]: https://theeventscalendar.atlassian.net/browse/TEC-3964
=> Make sure classic editor loads by default on events

readme.txt, src/Tribe/Main.php, src/Tribe/Query.php, src/Tribe/Views/V2/Template_Bootstrap.php
Add an additional check in get_view_html() to ensure that we still show the single event when the context is wrong.
Need to explore further _why_ the context is wrong :/
[TEC-3975]
[TEC-3975]: https://theeventscalendar.atlassian.net/browse/TEC-3975
=> Add check for incorrect context

src/Tribe/Admin/Event_Meta_Box.php
In addition to setting the start and end dates, we also need to set the UTC start and end dates.
Error spotted when testing [ECP-901]
:movie_camera: https://d.pr/v/D89PuQ
[ECP-901]: https://theeventscalendar.atlassian.net/browse/ECP-901
=> Ensure we are setting the dates using the full DBDATETIMEFORMAT | ECP-901

readme.txt, src/views/blocks/event-datetime.php, src/views/blocks/parts/details.php, src/views/modules/meta/details.php
This PR ensures that the correct timezone label is displayed when we have the `use site-wide timezone everywhere` setting enabled.
It resolves the same issue as on this [other one](https://github.com/the-events-calendar/the-events-calendar/pull/3629) but focuses on the classic editor. 
It also cleans up the ternary operator used on the block editor. 
Ticket : https://theeventscalendar.atlassian.net/browse/TEC-3791
Artifact :
=> [TEC-3791] Ensure the correct timezone label is being displayed on the Classic editor when site-wide timezone is set.

src/Tribe/Editor/Blocks/Event_Datetime.php
This PR reverts the `src/Tribe/Editor/Blocks/Event_Datetime.php` file to its previous state before we merged this [PR](https://github.com/the-events-calendar/the-events-calendar/pull/3629). 
Reference : https://github.com/the-events-calendar/the-events-calendar/pull/3629#discussion_r703550154
Ticket : https://theeventscalendar.atlassian.net/browse/TEC-3791
=> Revert [src/Tribe/Editor/Blocks/Event_Datetime.php] to previous state

src/modules/blocks/event-organizer/details/style.pcss
This PR matches the fonts for the event venue and event organizer titles in the block editor. Below I'll attach some before and after screenshots. 
Ticket : https://theeventscalendar.atlassian.net/browse/TEC-4071
Artifacts: 
Before: 
After:
=> [TEC-4071] Match the font titles for venue and organizer blocks. 

readme.txt, src/Tribe/Views/V2/Rest_Endpoint.php
When the view endpoint is used to fetch new partials `application/json`
header is used when deliver the view to the clients.
Instead `text/html` is used to deliver the views with the charset from
the site.
Screencast: https://d.pr/v/zyib6Z
:ticket: [TEC-4087]
[TEC-4087]: https://theeventscalendar.atlassian.net/browse/TEC-4087
=> Set the correct content-type header for views | TEC-4087

src/resources/postcss/tribe-events-single-blocks.pcss
This PR updates that ensure the font customizer settings i.e. font size and font family settings are applied to the block editor single events page. 
Ticket : https://theeventscalendar.atlassian.net/browse/TEC-4071 
Artifact : https://www.loom.com/share/dbe39362001a43f59f4f52712d5f0843
We don't need a change log since this is a patch addressing some QA feedback from an earlier ticket.
=> [TEC-4071] Ensure customizer font control settings are applied to single events page.

src/Tribe/Aggregator/Service.php, src/admin-views/aggregator/origins/limit.php
Also, I "cleaned up" the template code.
While I am a HUGE fan of ternaries, it was hard to read and figure out what exactly was going on.
So shoot me :wink:
Desired result with test file: https://d.pr/i/iCztZI
[EA-423]
[EA-423]: https://theeventscalendar.atlassian.net/browse/EA-423
=> Ensure the _request_ respects the default limit too.

src/modules/elements/google-map/element.js
This PR is a patch of this [earlier one](https://github.com/the-events-calendar/the-events-calendar/pull/3657) and it addresses the map preview not being displayed correctly when the embed settings are toggled.
A change log was already provided added to the earlier PR.
Ticket : https://theeventscalendar.atlassian.net/browse/TEC-3042
Artifact : https://www.loom.com/share/26c42cde62194a6d841053af1c91721b
=> display map preview on embed toggle

src/Tribe/Event_Status/Compatibility/Events_Control_Extension/Service_Provider.php
- Adds back the coding to remove the extension metabox.
=> TEC-4108 - add back to removal of the extension on metabox

src/resources/js/customizer-views-v2-live-preview.js
I left off the link color control - this adds it to the live preview.
[TEC-4055]
[TEC-4055]: https://theeventscalendar.atlassian.net/browse/TEC-4055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add function for the missing link color to the live preview.

src/Tribe/Views/V2/Customizer/Configuration.php
The js targets get re-created on view change. This ensures we have at least one that will exist after a view change.
This might down the line require some fine tuning. We may be able to remove the other selectors, but for now I'd prefer to keep them.
=> Add body to selector so customizations carry through view refreshes.

src/Tribe/Views/V2/Customizer/Configuration.php, src/Tribe/Views/V2/Customizer/Hooks.php
Stop relying on targets that are only present at the whim of themes and filters 😉 
[TEC-4055]
Instead of relying on classes added by themes, or core (and removable via a filter) let's add our own.
[TEC-4055]: https://theeventscalendar.atlassian.net/browse/TEC-4055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Target a body class only added when in the Customizer preview.

readme.txt, src/Tribe/Editor/Objects/Event.php, src/modules/data/blocks/datetime/reducer.js
This PR ensures the date selected when creating a new event from the Event Manager is applied to the block editor.
Ticket : https://theeventscalendar.atlassian.net/browse/ECP-954
Artifact : https://www.loom.com/share/59f795e3736c4f7ba12319ee73bdd685
Updated Artifact : https://www.loom.com/share/b2c7e4f13be74c42b3ab56a71c3f179b
=> Apply date passed from Event Manager to event start date. [ECP-954]

readme.txt, src/Tribe/REST/V1/Main.php
This PR adds a valid rel value to the link tag for TEC REST API support in order to improve HTML 5 and WCAG 2.1 compliance.
Ticket : https://theeventscalendar.atlassian.net/browse/TEC-4129
Artifacts : 
Before Fix;
After Fix;
=> Wrong rel value causing HTML 5 and WCAG 2.1 compliance error [TEC-4129]

readme.txt, src/Tribe/Event_Status/Template_Modifications.php
...to avoid issues with duplicated titles in the admin list table.
In the list table, the title is acquired via  [_draft_or_post_title() ](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-posts-list-table.php#L1089) which does not carry the post ID.
Since the ID is not passed, it defaults to 0 and I think our caching is running afoul of this somewhere along the path. (or the key fields need to be corrected?)
📷 Bad: https://d.pr/i/KmobuT
📸 Good: https://d.pr/i/thGNlK
[TEC-4156]
[TEC-4156]: https://theeventscalendar.atlassian.net/browse/TEC-4156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Force get_post_classes() to bypass the cache in tribe_get_events()

src/Tribe/Editor/Blocks/Event_Links.php, src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php, src/Tribe/Views/V2/iCalendar/Links/Link_Interface.php, src/Tribe/Views/V2/iCalendar/iCalendar_Handler.php, src/Tribe/iCal.php, src/modules/blocks/event-links/index.js, src/modules/blocks/event-links/template.js, src/resources/postcss/components/skeleton/_ical-link.pcss, src/views/blocks/event-links.php
1. Style bug with vertical FBAR
2. Event-Single share block now uses correct url for gCal.
3. Changed text and link for iCal in share block - no download, subscribe.
[TEC-4131]
1
📷 (bad): https://d.pr/i/PQpfWw
📸 (good): https://d.pr/i/gMzXbY
2
📸 (good): https://d.pr/i/tLorIs
3
📸 (good): https://d.pr/i/KvpUEg
[TEC-4131]: https://theeventscalendar.atlassian.net/browse/TEC-4131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Subscribe to Calendar - URL, text, and placement fixes

readme.txt, src/functions/template-tags/date.php
This is a handy change from @huubl (original PR: #3668) to prevent improper values of the second argument of the `date()` function.
:ticket: [TEC-4161]
📷 
☝️ This artifact is just to show that the end date of a multi-day event continues to render as expected!
[TEC-4161]: https://theeventscalendar.atlassian.net/browse/TEC-4161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Enforce the second argument of date to be an int for custom date function | TEC-4161

readme.txt, src/Tribe/Views/V2/Template/Title.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_w_category__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_w_category_and_featured__1.php
NOT the on-page title, the "meta" title.
Needed because everywhere we call this function we're been passing false - which turns it off.
Note this also removes the default "false" where we call the function.
[TEC-4110]
:camera: https://d.pr/i/qJMlUN
[TEC-4110]: https://theeventscalendar.atlassian.net/browse/TEC-4110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adds a filter to allow folks to "turn on (or off)" the taxonomy breadcrumbs for the page title.

src/Tribe/Editor.php, src/modules/icons/events-list.svg, src/modules/widgets/style.pcss
Addresses some styling recommendations made by Rachel as part of the DQA for the `Events Featured Venue` and `Events Countdown blocks`. 
Please note that the change log was added to the bucket in this earlier [PR](https://github.com/the-events-calendar/events-pro/pull/1863).
Ticket: https://theeventscalendar.atlassian.net/browse/ECP-1022
Artifact : https://www.loom.com/share/d6cf451067c349f4a2717bf068e230d7
=> Shortcode based blocks DQA Feedback. [ECP-1022]

readme.txt, src/modules/widgets/style.pcss
Remove CSS attributes targeting `aria-labels` to prevent inconsistent styling for different languages.
Ticket : https://theeventscalendar.atlassian.net/browse/TEC-4227
Artifact : https://www.loom.com/share/03ddc5e6514b4bd6857db3289b5c9fff
=> Remove CSS attributes targeting `aria-labels` [TEC-4227]

.github/workflows/tests-php.yml, readme.txt, src/Tribe/Repositories/Event.php
This fixes an issue where the failover orderby logic within the Event Repository was failing to successfully apply when `$this->query_args['orderby']` was null and we were attempting to set the value to `[ $order_by => $order ]`. Setting to explicit `orderby` and `order` values consistently functions.
This fix is already in place on Loxi production.
:ticket: [TEC-4232]
:movie_camera: https://d.pr/v/SYKtFR
[TEC-4232]: https://theeventscalendar.atlassian.net/browse/TEC-4232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Resolve sorting problem in Event repository

src/Events/Custom_Tables/V1/Provider.php, src/Events/Legacy/Views/V1/Provider.php, src/Tribe/Main.php, src/functions/views/provider.php
The core bits of this PR are:
* Forcing views, widgets, and single to be v2 versions.
* This adds some cached notification of v1 files existing within themes.
That's pretty much it, other than removing a superfluous check on v2 being enabled in the Custom_Tables provider.
=> Add a Legacy Views provider and force v2 to be active

readme.txt, src/modules/widgets/events-list/index.js, src/modules/widgets/events-list/template.js
Remove the `wp.editor.InnerBlocks` gutenberg component in favor of `wp.blockEditor.InnerBlocks` which was deprecated since version 5.3. 
Ticket : [[TEC-4178]](https://theeventscalendar.atlassian.net/browse/TEC-4178)
[TEC-4178]: https://theeventscalendar.atlassian.net/browse/TEC-4178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Artifact : 
https://www.loom.com/share/c380d889c527450eb005dab87ccd822b
=> Remove deprecated `wp.editor.InnerBlocks` component in favor of `wp.blockEditor.InnerBlocks` [TEC-4178]

readme.txt, src/modules/blocks/event-venue/venue-details.js, src/resources/postcss/base/skeleton/_view.pcss
Resolving problems with GeneratePress and Astra by adding a CSS width to the view container.
🎫 [TEC-4257](https://theeventscalendar.atlassian.net/browse/TEC-4257)
| Before | After |
| - | - |
| <img width="1296" alt="Screen Shot 2022-02-07 at 9 39 19 AM" src="https://user-images.githubusercontent.com/236579/152809062-15e338cf-3dd8-4b77-86a5-0c58ddcbe433.png"> | <img width="1234" alt="Screen Shot 2022-02-07 at 9 36 12 AM" src="https://user-images.githubusercontent.com/236579/152809237-07ebae74-797d-4775-ba0c-6c59558564db.png"> |
| Before | After |
| - | - |
| ![image](https://user-images.githubusercontent.com/236579/152809345-6e2cd5ae-c09a-4ee6-a2a8-507c5af70fe9.png) | ![image](https://user-images.githubusercontent.com/236579/152809468-7f654f79-68c0-4fee-b720-4b3853a55b55.png) |
=> Include a declarative Width to the views container

src/views/blocks/event-links.php
Prevent some potential fatals and reinforce the bail-out conditions.
Note: The fatals _appear_ to be connected to VE, so we should examine where VE hooks into the links and alters things (we shouldn't be getting `null`) but this will act as a buffer to prevent a fatal if something does go wrong.
[TEC-4258]
[TEC-4258]: https://theeventscalendar.atlassian.net/browse/TEC-4258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add some sanity checks around our use of subscribe_links in the block template.

src/Tribe/Main.php
When we (I) placed the bailout for the metaboxes, I inadvertently included the Event Options mb. This corrects that:
Bad: https://d.pr/i/za1jir
Good: https://d.pr/i/mgLtz0
[TEC-4258]
[TEC-4258]: https://theeventscalendar.atlassian.net/browse/TEC-4258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make sure the Event Options metabox gets loaded in the block editor.

readme.txt, src/Tribe/Admin/Filter_Bar/Provider.php, src/Tribe/Main.php, the-events-calendar.php
This corrects the check in the provider so it works,
and moves the singleton creation to _before_ the action we can use to hook into it.
This bug is a great argument for testing admin views...
No FBAR: https://d.pr/i/0frA5z
With FBAR: https://d.pr/i/g0ptNz
[TEC-4284]
[TEC-4284]: https://theeventscalendar.atlassian.net/browse/TEC-4284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Correct the FBAR check.

tests/views_integration/Tribe/Events/Views/V2/iCalendar/RequestTest.php
This is a spotfix to adjust tests to ensure that the date of the text excution is taken into account when generating the expected values to test against when looking at the current month.
Related: https://github.com/the-events-calendar/the-events-calendar/pull/3794
=> Updating the tests to match the new ical subscribe logic for month view

readme.txt, src/admin-views/venue-meta-box.php, tests/integration/Venue_Creation_Test.php
A duplicated name attribute appears to be the underlying problem.
https://d.pr/i/0SzZSi
[TEC-4309]
[TEC-4309]: https://theeventscalendar.atlassian.net/browse/TEC-4309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure the venue saves for non-US venues.

src/Tribe/Views/V2/Views/Month_View.php
… but uses actual dates.
This was causing today "2022-03-11" to be compared to "now".
[TEC-4223]
[TEC-4223]: https://theeventscalendar.atlassian.net/browse/TEC-4223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Correct the calculation on the month ics dates so that it doesn't rely on "now"

readme.txt, src/Tribe/Views/V2/View.php
[TEC-4322]
If fed a string like "hello" and it equates to a larger number than the others, `max()` will return the string, not the integer representation of it. `"hello" - 1` will fail (and fatal)
[TEC-4322]: https://theeventscalendar.atlassian.net/browse/TEC-4322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure that max returns an int since we're doing math with it.

readme.txt, src/admin-views/create-venue-fields.php, src/admin-views/venue-meta-box.php
[TEC-4349]
When working on CE, we found that when adding new venue's the website URL was not validating. The file CE was using was found in TEC. 
This PR changes the input type from `text` to `url`. Therefore adding a small amount of validation so that invalid URL's are not submitted.
**Submitting an invalid URL from Edit Venue**
[TEC-4349]: https://theeventscalendar.atlassian.net/browse/TEC-4349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TEC-4349] Update Venue Website input type to url

readme.txt, src/Tribe/Importer/File_Reader.php
n PHP 8.0.15 they added this patch: [Fixed bug #75917 ](https://bugs.php.net/bug.php?id=75917)(SplFileObject::seek broken with CSV flags).
That appears to be the source of the issue. 
Before that patch this coding would return the last line of a csv file:
$this->file->seek( $this->file->getSize() );
$this->lines = $this->file->key();
It is similar to an example of getting the last line for [PHP: Hypertext Preprocessor](http://php.net/) 
https://www.php.net/manual/en/splfileobject.seek.php#121666
In PHP 8.0.18 this patch was added: [Fixed bug #8121](https://github.com/php/php-src/pull/8138) (SplFileObject - seek and key with csv file inconsistent).
_Ref:_ [TEC-4312](https://theeventscalendar.atlassian.net/browse/TEC-4312)
=> CSV Import Fix on PHP 8.0

src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
Tweak to make sure that the archive works the way expected.
$this->repository_args is more reliable than the context in situations where we use the date navigation.
[ECP-957]
[ECP-957]: https://theeventscalendar.atlassian.net/browse/ECP-957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure it works with archive views.

src/admin-views/create-venue-fields.php, src/functions/template-tags/organizer.php, src/functions/template-tags/venue.php
`tribe_get_venue_website_link` returns a formatted HTML anchor
we need a URL - we get that from `tribe_get_venue_link` with the second param set to false.
I also indexed the params for `tribe_get_organizer_website_link` and `tribe_get_venue_website_link` while testing and since we're supposed to always used indexed params, I left that in place.
=> Fix the venue link/url in the event venue form

readme.txt, src/admin-views/create-venue-fields.php, src/admin-views/venue-meta-box.php
This (reverted) change caused cascading issues with saving events in the admin.
[TEC-4349]
[TEC-4349]: https://theeventscalendar.atlassian.net/browse/TEC-4349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Don't use 'url' - yet.

readme.txt, src/Tribe/Views/V2/Hooks.php
This was intentionally removed as part  of the single event redesign. Yet its removal was not in any of the design files I could find.
📸 https://d.pr/i/wVL5Ma
[TEC_4334]
=> Put back the event website label for Classic editor.

readme.txt, src/Tribe/Aggregator/Settings.php
Fixes so the default category so it is selected for an import.
Artifact:
Video Review: https://cloudup.com/c7-m_qCB5Kl
Ticket
_Ref:_ [EA-426](https://theeventscalendar.atlassian.net/browse/EA-426)
=> EA-426 - fix the default ea category

readme.txt, src/resources/postcss/components/skeleton/_ical-link.pcss
Add a height to the subscribe to calendar export SVG icon on the single events page when using the `Skeleton Styles` to prevent it from taking over a huge portion of the page.
https://theeventscalendar.atlassian.net/browse/TEC-4399
Before Fix
After Fix
=> Tame the rogue SVG icon on the single events page. [TEC-4399]

readme.txt, src/admin-views/tribe-options-general.php
We're no longer updating the `updates page` and thus we're removing the link to it from the Event settings to prevent customers from navigating there.
https://theeventscalendar.atlassian.net/browse/TEC-4373
https://www.loom.com/share/81d84e3265024700aad87f5dda7ad91f
=> Remove link to updates page from Event settings. [TEC-4373]

src/Tribe/Front_Page_View.php, src/Tribe/Views/V2/Views/List_View.php
Instead of some suspicious logic in the `get_upcoming_url` function, let's add a sanity check to the `display` check in `next_url`
Ref: https://github.com/the-events-calendar/the-events-calendar/pull/3873
=> Use better logic on choosing the URL function.

readme.txt, src/resources/js/views/manager.js
Ensure the `Next` button when using the `Event View` Elementor widget navigates to the next page on the first click.
https://theeventscalendar.atlassian.net/browse/FBAR-263
https://www.loom.com/share/2fe681f49d4b420aa1afe94624d11439
=> Fix `Next` nav link for Event View Elementor widget [FBAR-263]

readme.txt, src/Tribe/Views/V2/Views/List_View.php
Ensure the `Next` arrow in `List` and `Summary` views navigates to the correct page when the `Main Events Page` is set as the homepage.
Related to : https://github.com/the-events-calendar/events-pro/pull/1960
https://theeventscalendar.atlassian.net/browse/TEC-4247
https://www.loom.com/share/0448a7f864424f99adb391586dcf626b
=> Fix `Next` arrow url when the Main Events Page is set to Homepage. [TEC-4247]

readme.txt, src/Tribe/Aggregator.php, src/Tribe/Aggregator/Cron.php, src/Tribe/Aggregator/Page.php, src/Tribe/Aggregator/Record/Queue_Processor.php, src/Tribe/Aggregator/Record/Queue_Realtime.php, src/resources/js/aggregator-fields.js, src/resources/postcss/aggregator-page.pcss
[TEC-4070]
This is a stopgap to get the import running on all admin pages. We should shift to using action scheduler, but that has to wait for RBE/V1-removal.
1. Ensure that import continues when we're in the admin: https://d.pr/i/TxrEif
- The intent is to hide the notice on non-aggregator pages, but w/o it the import stalls.
2. Use the built-in classes for notices, since we're copying their styling (colors, etc) 
[TEC-4070]: https://theeventscalendar.atlassian.net/browse/TEC-4070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Stopgap fix for aggregator csv imports

readme.txt, src/Tribe/Admin/Notice/Full_Site_Editor.php, src/Tribe/Admin/Settings.php, src/Tribe/Aggregator/Settings.php, src/Tribe/Views/V2/Customizer/Notice.php
Tickets Menu changed the admin URLs from `'tribe_events_page_tribe-common'` to `'tribe_events_page_tec-events-settings'`
This is just clean-up for places those URLs were hardcoded that were missed in that release.
ALso fixes some issues with network admin URLs - same cause.
Next iteration: create functions for all this.
[TEC-4405]
[ECP-1175](https://theeventscalendar.atlassian.net/browse/ECP-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Requires: https://github.com/the-events-calendar/tribe-common/pull/1770
[TEC-4405]: https://theeventscalendar.atlassian.net/browse/TEC-4405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Iterative changes - fix hardcoded urls.

CONTRIBUTING.md
**Issue**
When onboarding, burned a decent amount of time not knowing that composer v1 was required to get through the build when I already has v2 installed on my computer.
**Resolution**
Just a minor change to the CONTRIBUTING.md doc noting that v1 is required as a prerequisite.
=> Note required Composer version in Contributing doc

readme.txt, src/views/v2/month/calendar-body/day.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Calendar_BodyTest__test_static_render__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
Add a CSS class i.e. `tribe-events-othermonth` to past and future month dates in the month view to allow easy targeting similar to what we had in v1. 
https://theeventscalendar.atlassian.net/browse/TEC-4034
=> V2 Styling > Month view: add CSS selector tribe-events-othermonth. [TEC-4034]

readme.txt, src/Tribe/Views/V2/Template_Bootstrap.php, src/resources/postcss/tribe-events-full.pcss
Add a theme based CSS class to the HTML body tag when the `Default Page Template` setting is enabled under Events > Settings > Display. e.g. the CSS class would be `page-template-twenty-twenty-one` if the active theme is Twenty Twenty One.
https://theeventscalendar.atlassian.net/browse/TEC-4391
=> Theme based CSS class [TEC-4391]

src/Tribe/Admin/Notice/Update.php, src/admin-views/updates/6.0.0.php, src/resources/js/tec-update-6.0.0-notice.js, src/resources/postcss/admin-update-page.pcss, src/resources/postcss/events-admin.pcss
[ECP-1192]
The work in this PR addresses some content changes in the updates page and related notice. 
[ECP-1192]: https://theeventscalendar.atlassian.net/browse/ECP-1192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update page content tweaks

readme.txt, src/Tribe/Views/V2/Hooks.php
The Day and Week View shortcodes will get two dates like so:
https://dev.tec/events/week/2022-08-01/?shortcode=a8a52185&hide_subsequent_recurrences=1&tribe-bar-date=2022-08-08
and utilize the first one rather than the second.
This adds a filter so that if both tribe-bar-date and eventDate are present, the former overrides the latter.
Also addresses ECP-1195 where backslashes were not getting unescaped properly and breaking the date formats.
[ECP-1136]
[ECP-1195]
[ECP-1136]: https://theeventscalendar.atlassian.net/browse/ECP-1136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ECP-1195]: https://theeventscalendar.atlassian.net/browse/ECP-1195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a filter to ensure we use the correct date.

src/admin-views/updates/6.0.0.php
When Event Ticktes is active, then ET own `tribe_resource_url` function
will kick in and will use, where an `$origin` is not provided, ET
resources directory as a source for the assets.
Making the `$origin` explicit will force the function to look to
the TEC resources directory for those assets.
=> Fix CT1 update page asset paths

src/Tribe/Front_Page_View.php
RBE issue 399.
This is a fix for notice errors displaying on the home page when the main events page is set as the static page for home.
The page object was not being fetched properly. Now it loads the TEC post type.
=> Adding post type to query filter.

src/admin-views/aggregator/origins/csv.php, src/admin-views/aggregator/origins/limit.php
Add some helpful knowledgebase article links to the CSV import screen.
This is a tweak to the work merged in this [PR](https://github.com/the-events-calendar/the-events-calendar/pull/3947).
https://theeventscalendar.atlassian.net/browse/TEC-4353
=> Ensure the kb help links only appear on the CSV screen. [TEC-4353]

src/Tribe/Editor/Compatibility.php
Using the cache object rather than `static::` values allows automated tests to expire the cache.
The artifacts for this PR are the automated tests.
=> Cache the block editor toggle via cache object

src/Tribe/Views/V2/View.php, src/resources/js/views/manager.js
Ticket: [ECP-1308](https://theeventscalendar.atlassian.net/browse/ECP-1308).
Required by [ECP PR](https://github.com/the-events-calendar/events-pro/pull/2037).
This PR updates the Views v2 manager code to make it dispatch native JS events when the container HTML is replaced using jQuery.
The jQuery `element.replaceWith` method will not only replace the element HTML, but **it will remove all bound event listeners**.
Dispatching a native event before and after the container HTML is replaced will allow listeners to gracefully unbind and re-bind events before and after the container is replaced.
Artifacts: [ECP PR Screencast](https://share.cleanshot.com/dJSrQL)
=> Notify before/after Views container replacement

src/Events/Custom_Tables/V1/WP_Query/Modifiers/Events_Not_In_Series_Modifier.php
[BTRIA-1332]
[BTRIA-1332]: https://theeventscalendar.atlassian.net/browse/BTRIA-1332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Do not apply Events_Not_In_Scope modifier when ECP not active.

src/Events/Custom_Tables/V1/admin-views/migration/upgrade-box.php
Screencast: [link](https://share.cleanshot.com/0EB0sD)
This PR fixes the string used to assert that ECP is not outdate to compare it to the last possible dev version (`6.0.0-dev`) and not the last Beta version (`6.0.0-beta-4-dev`).
=> Fix ECP comparison string.

src/Events/Custom_Tables/V1/Migration/Process_Worker.php
Do not assume ECP is active in warning handler.
Ticket: [BTRIA-1341](https://theeventscalendar.atlassian.net/browse/BTRIA-1341)
Screencasts:
* [TEC only](https://share.cleanshot.com/11Txqb)
* [ECP and TEC](https://share.cleanshot.com/iHljTF)
The migration code has an error handler that will deal with `E_WARNINGS`
coming from plugins that are not TEC or ECP differently. That code has a
bug where the existence of the `EVENTS_CALENDAR_PRO_FILE` constant is
assumed.
This PR fixes that.
Plugin used to trigger the `E_WARNING`:
```php
<?php
/**
* Plugin Name: TEC - Test CT1 migration warning
*/
function tec_test_trigger_error() {
include 'some-file-that-will-not-exist.php';
}
add_action( 'tec_events_custom_tables_v1_before_migration_applied', 'tec_test_trigger_error' );
```
=> Fix CT1 migration undefined ECP const issue

readme.txt, src/Events/Custom_Tables/V1/Migration/Process_Worker.php, tests/ct1_migration/TEC/Events/Custom_Tables/V1/Migration/Process_WorkerTest.php
Ticket: [ECP-1318](https://theeventscalendar.atlassian.net/browse/ECP-1318)
Artifacts: tests and [screencast](https://share.cleanshot.com/Ebqn5Q)
Update the error handler logic we set during the migration process to
not throw due to notices (`E_NOTICE` and `E_USER_NOTICE`) and warnings
(`E_WARNING` and `E_USER_WARANING`) generated by non-TEC plugins.
The previous, stricter, code would stop the Event migration when notices
and warnings are raised during Event migration. Other plugins and themes
not as strict would routinely emit those and would, thus, prevent the
migration from happening.
The PR does not alter how notices and warnings coming from TEC plugins
are handled: they will raise an exception. This is a decision based on
the fact the TEC team cannot control others' code, but can …
=> CT1 Migration - do not throw on others' notices and warnings

readme.txt, src/Tribe/Integrations/Divi/Service_Provider.php, tests/integration/Tribe/Events/Integrations/DiviTest.php
Ticket: [BTRIA-1397](https://theeventscalendar.atlassian.net/browse/BTRIA-1397)
Artifacts: tests
When trying to determine the post ID of an post that is not an Event,
the current code would call the `wp_reset_postdata` function.
This would reset the postdata to the post ID of the queries post, page
or whatever, invalidating any custom query that might run in the context
of the same page.
=> Divi integration - don't reset postdata

readme.txt, src/functions/template-tags/venue.php, tests/wpunit/functions/template-tags/venueTest.php
The development team from Divi caught that `tribe_get_full_address()` was not returning the correct values. The problem was due to when I removed the internal method `Main::fullAddress()`, I didn't update the reference to Event/Venue IDs correctly.
🎫 [TEC-4505](https://theeventscalendar.atlassian.net/browse/TEC-4505)
---
📷
=> Correct the mix up around venue and event id for tribe_get_full_address

src/Tribe/Views/V2/Hooks.php
It works now, but it's the wrong function.
[TEC-4458]
[TEC-4458]: https://theeventscalendar.atlassian.net/browse/TEC-4458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> correct add_action to add_filter

readme.txt, src/admin-views/create-venue-fields.php, src/admin-views/venue-meta-box.php
This reverts a change that was made on this initial [PR](https://github.com/the-events-calendar/the-events-calendar/pull/3952)
We need to set the field type as `text` in order to prevent the error shown below when editing an Event using the classic editor. 
The error occurs because the venue website field is hidden to the user on the add/edit event page of the classic editor at the point of submission.
This won't affect validation as this is done in the Venue metabox [here](https://github.com/the-events-calendar/the-events-calendar/blob/949007824de6e399123d9a2d7bc8c60446fb84a5/src/admin-views/venue-meta-box.php#L194).
https://theeventscalendar.atlassian.net/browse/TEC-4349
=> Revert Venue Website Field Type to text. [TEC-4349]

readme.txt, src/Tribe/Collections/Lazy_Post_Collection.php, src/Tribe/Models/Post_Types/Event.php, src/Tribe/Updater.php, src/functions/template-tags/event.php, src/functions/template-tags/organizer.php, src/functions/template-tags/venue.php, tests/event_status/Tribe/Events/Event_Status/Updater_Test.php, tests/wpunit/functions/template-tags/eventTest.php
Ticket: [TEC-4379](https://theeventscalendar.atlassian.net/browse/TEC-4379)
Based on [Common PR](https://github.com/the-events-calendar/tribe-common/pull/1821) 
Artifacts: tests and [screencast](https://share.cleanshot.com/2ktUfb) 
This commit updates the code used to build and return decorated post
models for Events, Venues and Organizers when dealing with object
caching.
The update follows the one done in common in the branch by the same name
to avoid serialization and unserialization issues.
=> Update post type model code

readme.txt, src/Events/Custom_Tables/V1/WP_Query/Custom_Tables_Query.php, src/Events/Custom_Tables/V1/WP_Query/Modifiers/Events_Only_Modifier.php, tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/Custom_Tables_QueryTest.php, tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_not_run_found_rows_query_twice_per_single_query__1.php
Ticket: [ECP-1360](https://theeventscalendar.atlassian.net/browse/ECP-1360) 
Artifacts:
* The code under change is already covered by numerous tests.
* [Screencast](https://share.cleanshot.com/scKAmx)
This fixes an issue where, in the context of PHP 8.0, a fatal would be thrown on Event archives when using CT1 and the HyperDB plugin.
The cause of the issue is a `SELECT FOUND_ROWS()` query running twice; when running a query for Events:
1. During `WP_Query::get_posts` the `posts_pre_query` filter is applied
2. The `Custom_Tables_Query` hooked on that filter ...
3. ... runs its own `get_post` to fetch the results
4. ... runs its own `set_found_posts` (that will run `SELECT FOUND_ROWS()`)
5. ... and returns the post results from the filter pre-filling
6. ... the original `WP_Query` object …
=> Fix HyperDB compatibility issue

readme.txt, src/Events/Custom_Tables/V1/WP_Query/Custom_Tables_Query.php
We do our own caching of occurrence results, so we don't need WordPress core to do it.
=> Prevent the caching of occurrence queries

readme.txt, src/Events/Custom_Tables/V1/WP_Query/Custom_Tables_Query.php, src/functions/template-tags/venue.php, tests/wpunit/functions/template-tags/venueTest.php
[ECP-1411](https://theeventscalendar.atlassian.net/browse/ECP-1411)
Skips filters that require a WP_Post object when there is none to be found for a venue.
Artifact:
Screenshot of display when fix is in place.
=> Fix for ECP-1411

readme.txt, src/admin-views/tribe-options-display.php, src/admin-views/tribe-options-general.php
Also remove the redundant "Read More" link from the maps infobox.
[TEC-4573]
[TEC-4573]: https://theeventscalendar.atlassian.net/browse/TEC-4573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add target blank and rel noopener to our external (evnt.is) links.

readme.txt, src/Tribe/Aggregator/Service.php
Ticket: [EA-461](https://theeventscalendar.atlassian.net/browse/EA-461) 
The current EA Service hosting will not support special characters and
this will make it so that .ics file uploads will be rejected.
=> Generate safer multipart boundaries

src/Tribe/Query.php, tests/_support/_generated/WpunitTesterActions.php, tests/wpunit/Tribe/Events/QueryTest.php, tests/wpunit/Tribe/Events/__snapshots__/QueryTest__should_not_add_date_based_orderby_clauses_when_not_required with data set none__1.php, tests/wpunit/Tribe/Events/__snapshots__/QueryTest__should_not_add_date_based_orderby_clauses_when_not_required with data set rand__1.php
Ticket: [TEC-4588](https://theeventscalendar.atlassian.net/browse/TEC-4588)
This updates the removed, then restored, then refactored, then removed,
then refactored and restored `Tribe__Events__Query::parse_query` method
to reference the current parsed query to set its properties, and not the
context.
The context instance, provided by the `tribe_context()` function, will
model the whole request context and setting any query properties using
the whole request context would create a number of issues with secondary
queries.
=> Fix query property setting during parse

readme.txt, src/Tribe/Query.php, src/deprecated/Traits/Tribe__Events__Query_Deprecated.php
Ticket: [TEC-4540](https://theeventscalendar.atlassian.net/browse/TEC-4540) 
Artifacts: tests.
This re-introduces the `Tribe__Events__Query::pre_get_posts` method back
in the `Tribe__Events__Query` class by means of the
`Tribe__Events__Query_Deprecated` trait.
The method is used by some third-party plugins to deal with TEC
compatibility and its removal caused issues.
=> Add removed method back

readme.txt, src/Events/Custom_Tables/V1/Models/Builder.php, src/Events/Custom_Tables/V1/Models/Model.php, src/Events/Custom_Tables/V1/Schema_Builder/Abstract_Custom_Field.php, src/Events/Custom_Tables/V1/Schema_Builder/Abstract_Custom_Table.php, src/Events/Custom_Tables/V1/Tables/Occurrences.php, src/Tribe/API.php, tests/ct1_integration/TEC/Events/Custom_Tables/V1/Updates/ControllerTest.php, tests/ct1_integration/TEC/Events/Custom_Tables/V1/Updates/Post_Save_EventsTest.php, tests/ct1_migration/TEC/Events/Custom_Tables/V1/Schema_BuilderTest.php
[TEC-4578](https://theeventscalendar.atlassian.net/browse/TEC-4578)
This PR fixes two separate issues that caused 404's. The core issue is that CT1 table data is not being created, the reasons are completely unrelated.
1) We were creating UTC start/end dates different than legacy in our validators. This would fail to insert any data due to this inconsistency. Now using a consistent approach with how we handle offsets in Legacy and CT1 interpretation. Now DST will be respected when the offset is converted to the localized timezone.
2) There appears to have been some database "corruption" in some clients installations. Basically the foreign key association made in our occurrence table would point to a "missing" table, failing all insertions. Not sure how this happens, but we are removing …
=> Changing UTC offsets to convert to localized timezone.

src/Events/Custom_Tables/V1/WP_Query/Provider.php, src/Events/Custom_Tables/V1/WP_Query/Repository/Custom_Tables_Query_Filters.php
This is some cleanup related to: https://github.com/the-events-calendar/events-pro/pull/2134
Had some "series" logic that was fleshed out in Pro, it was removed from TEC repo.
Tests cover changes. See artifacts in [PRO PR](https://github.com/the-events-calendar/events-pro/pull/2134).
=> Moved pro logic to pro - removing here.

readme.txt, src/Events/Custom_Tables/V1/Models/Event.php, src/Events/Custom_Tables/V1/Models/Model.php
When on PHP 8.1 if you run the migration you can trigger a notice that stops the migration:
"[TECEventsCustom_TablesV1ModelsEvent implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)]"
This PR fixes that issue and retains backwards compatibility with PHP.
_Ref:_ [ECP-1319](https://theeventscalendar.atlassian.net/browse/ECP-1319)
Artifacts: None
=> ECP-1319 - prevent serialize notice during migration in PHP 8.1

readme.txt, src/resources/js/views/manager.js
Ticket: [FBAR-273](https://theeventscalendar.atlassian.net/browse/FBAR-273)
This PR ensures that the previous events url is passed correctly to the `Previous Events` navigation button in the `Event View` widget on initial page load. 
This fixes the issue where users weren't able to navigate to previous events without first navigating to the next events. 
Artifact 👇🏽
https://www.loom.com/share/e6a87441906d49ffad97e23fd9157556
=> Ensure the `Prev` button when using the `Event View` Elementor widget works as expected. [FBAR-273]

readme.txt, src/Tribe/Service_Providers/Context.php, src/Tribe/Views/V2/iCalendar/Request.php
[TEC-4469]
Per conversation with @bordoni I have changed to altering the Context object to recognize a single iCal URL as `single-event`
[TEC-4469]: https://theeventscalendar.atlassian.net/browse/TEC-4469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure that when we hit a single-event iCal URL we get a the correct single event.

src/Events/Custom_Tables/V1/Models/Model.php, src/Events/Custom_Tables/V1/WP_Query/Monitors/Query_Monitor.php, src/Events/Custom_Tables/V1/WP_Query/Provider.php, src/Tribe/Rewrite.php
Ticket: [ECP-1319](https://theeventscalendar.atlassian.net/browse/ECP-1319)
[Screencast](https://share.cleanshot.com/jSiAGj)
This updates the original fix code to take care of a fatal on PHP 7.4 and remove more deprecated notices.
Note: when the class is updated to use the `__serialize` and `__unserialize` methods, then those will be used in place of the previously implemented `serialize` and `unserialize` ones; this means existing tests are already covering the changes.
=> Fix more PHP 8.1 deprecation issues and PHP 7.4 fatal

src/Tribe/Front_Page_View.php
Ticket: [BTRIA-1545](https://theeventscalendar.atlassian.net/browse/BTRIA-1545)
[Screencast not using object cache](https://share.cleanshot.com/WNd6LC)
[Screencast using object cache](https://share.cleanshot.com/5HHDFF) 
This fixes an issue where setting the site to use the Main Events Page as front page would cause fatals on PHP 8.0+ and above when navigating to some settings pages.
On lower PHP version it would cause a notice, but it would still be the same issue.
The fix hooks on the actions and filters that run before the page is used by WordPress to hydrate the posts cache and provide a real post objec to WordPress when it gets the page using `get_post( $page_id )`.
=> fix(Front_Page_View) set main page to custom link

readme.txt, src/Events/Integrations/Plugins/WordPress_SEO/Events_Schema.php, src/functions/template-tags/general.php, tests/wpunit/functions/template-tags/generalTest.php
From user report:
```
[14-Dec-2022 15:59:47 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_main_query() on null in /home/website/public_html/wp-content/plugins/the-events-calendar/src/functions/template-tags/general.php:1896
Stack trace:
#0 /home/website/public_html/wp-content/plugins/the-events-calendar/src/Tribe/Query.php(130): tribe_is_events_front_page()
#1 /home/website/public_html/wp-includes/class-wp-hook.php(308): Tribe__Events__Query::parse_query(Object(WP_Query))
#2 /home/website/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#3 /home/website/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#4 /home/website/public_html/wp-includes/class-wp-query.php(1127): do_action_ref_array('parse_query', Array)
#5 …
```
=> Avoid fatal error when calling is_main_query on null

readme.txt, src/Tribe/iCal.php
If a requested category has been unregistered, `wp_get_object_terms()` will throw an error. Check for the error as well as for empty().
Readme entry already in place: https://github.com/the-events-calendar/the-events-calendar/blob/fix/TEC-4619-event-category--cal-error/readme.txt#L242
[TEC-4619]
[TEC-4619]: https://theeventscalendar.atlassian.net/browse/TEC-4619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure we don't try to use a WP_ERROR as an event category.

readme.txt, src/Tribe/Aggregator/Cron.php, tests/wpunit/Tribe/Events/Aggregator/CronTest.php
Ticket: [EA-446](https://theeventscalendar.atlassian.net/browse/EA-446)
Artifacts:
* tests
* [screencast](https://share.cleanshot.com/PlBbQryw)
This adds an opt-in way of deleting older records that, on cron, will
delete a significantly larger portion of them using direct database
queries.
The trade-off is the WordPress `wp_delete_post` function will not be
used and its filters and actions will not be triggered.
Users can opt-in into the alternate deletion system by either filtering
the `tec_event_aggregator_direct_record_deletion` filter or by setting
the `TEC_EVENT_AGGREGATOR_RECORDS_PURGE_DIRECT_DELETION` constant in the
site `wp-config.php` file.
[EA-446]: https://theeventscalendar.atlassian.net/browse/EA-446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
=> feat(Event_Aggregator) allow direct deletion of older records

readme.txt, src/Tribe/Integrations/WPML/Meta.php, src/Tribe/Integrations/WPML/WPML.php
Ticket: [TEC-4651](https://theeventscalendar.atlassian.net/browse/TEC-4651)
[Screencast](https://share.cleanshot.com/M7HPPNWv)
This updates the WPML integration code to make sure the Duplicate
function provided by WPML, not the one provided by ECP, works correctly
when duplicating an Event to another language.
The issue is that the duplicate function is not going through the usual
flow, but using AJAX. This would make it so that no default tracked meta
key is found (date-related ones) and custom tables data is not updated.
The fix consists in filtering the list of tracked meta keys to include
the `_icl_lang_duplicate_of` one used by WPML to indicate a duplicate
operation.
[BTRIA-1577]: https://theeventscalendar.atlassian.net/browse/BTRIA-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
=> fix(WPML) ensure duplicates update the custom tables

readme.txt, src/functions/template-tags/google-map.php
Ticket : [TEC-4634](https://theeventscalendar.atlassian.net/browse/TEC-4634)
Ensures the zoom level set under `Events → Settings → Display → Google Maps default zoom level` is applied to the single events page.
**Artifact 🎥**
https://www.loom.com/share/b402036022464ca1b10c3ebfe4a9689f
[TEC-4634]: https://theeventscalendar.atlassian.net/browse/TEC-4634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix zoom level setting. [TEC-4634]

readme.txt, src/Tribe/Views/V2/Hooks.php, tests/views_wpunit/Tribe/Events/Views/V2/HooksTest.php
Ticket: [TEC-4511](https://theeventscalendar.atlassian.net/browse/TEC-4511)
This PR is the companion to the [ECP one](https://github.com/the-events-calendar/events-pro/pull/2182) to allow detecting a redirected request only by means of the `tribe_redirected` query var.
The support for the `tribe_redirected` query variable cannot be removed due to its use in the Event Tickets PayPal gateway, but adding a filter allows the request lifecycle to mark the current request as a redirected one without requiring its use.
[TEC-4511]: https://theeventscalendar.atlassian.net/browse/TEC-4511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow filtering the redirection nature of a request

tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/Modifiers/Events_Only_ModifierTest.php
This PR just adds coverage, in the `ct1_integration` suite, for the filtering of `get_posts` call in CT1 context.
The issue tracked by [the ticket](https://theeventscalendar.atlassian.net/browse/TEC-4621) is dealt with in an [ECP PR](https://github.com/the-events-calendar/events-pro/pull/2194).
=> Add test coverage for CT1 get_posts filtering

readme.txt, src/Tribe/Aggregator/Page.php
Ticket : [TEC-4698](https://theeventscalendar.atlassian.net/browse/TEC-4698)
I'm adding the `datatables-css` stylesheet as a dependancy for `tribe-ea-styles` in order to fix the borked pagination stying on the Aggregator import preview data table.
For context, the stylesheet was previously registered [here](https://github.com/the-events-calendar/tribe-common/blob/cca67a481cff1f12942cfc1cc64d7e83cbbf8e59/src/Tribe/Main.php#L231) but was never enqueued.
Note that I've not updated the artifacts from the [previous pr](https://github.com/the-events-calendar/tribe-common/pull/1881) as they're still valid. I've however retested with the new updates to confirm the fix works as intended.
**Artifacts 📸**
Here we can see the pagination UI is borked prior to enqueuing the styles.
Here the UI is …
=> Fix the pagination styling on the Aggregator import preview data table.

readme.txt, src/functions/template-tags/general.php
Ticket : [TEC-4709](https://theeventscalendar.atlassian.net/browse/TEC-4709)
Avoid fatal error when the `tribe_events_event_classes` method is called on events that aren't assigned to any category.
https://www.loom.com/share/0370c51962724267af1e81f556563830
[TEC-4709]: https://theeventscalendar.atlassian.net/browse/TEC-4709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `tribe_events_event_classes` fatal error.

readme.txt, src/admin-views/create-venue-fields.php
This PR fixes an issue where the default venue information wasn't populating when using Community Events.
Screenshot within Admin
Screenshot from within Community Events
Showing the custom list of countries works as well
=> [CE-178] Fix allow venue defaults to work with Community Events 

readme.txt, src/Tribe/Integrations/WPML/Meta.php, tests/integration/Tribe/Events/Integrations/WPML/MetaTest.php, tests/integration/Tribe/Events/Integrations/WPMLTest.php
[ECP-1429](https://theeventscalendar.atlassian.net/browse/ECP-1429)
Artifact: [screencast](https://share.cleanshot.com/cmNgCGc0)
Required by [ECP PR](https://github.com/the-events-calendar/events-pro/pull/2212)
The `Tribe__Events__Integrations__WPML__Meta::translate_post_id` mehtod will filter the `get_post_metadata` calls to translate the post IDs that might be found in the meta (i.e. the `_EventOrganizerID` and the `_EventVenueID` ones).
Currently, the filtering will be applied in the `get_metadata_raw` and `metadata_exists` functions and, in both instances, it's for a bail check: one where returning a non-null value would short-circuit the function logic and return the value.  If not found, the value returned should be the original one, `null` in the case of the bail checks, to let the …
=> Fix WPML Integration meta manipulation

readme.txt, src/functions/template-tags/general.php
🎫 [TEC-4725]
---
Resolves the fatal, super simple change.
[TEC-4725]: https://theeventscalendar.atlassian.net/browse/TEC-4725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevent fatal on tribe_get_event_cat_slugs with bad type for array_filter

readme.txt, src/Events/Custom_Tables/V1/Activation.php
This resolves an issue where `implode()` was being called with the wrong argument order.
=> Resolve PHP 8+ issue with transposed implode call

src/Events/Custom_Tables/V1/Integrations/ACF/Controller.php, src/Events/Custom_Tables/V1/Integrations/ACF/Query_Modifier.php, src/Events/Custom_Tables/V1/Integrations/Provider.php, tests/ct1_integration/TEC/Events/Custom_Tables/V1/Integrations/ACF/ControllerTest.php
[TEC-4621](https://theeventscalendar.atlassian.net/browse/TEC-4621) 
Fix the query side of the ACF integration code to handle both initial PHP state queries for Events, and AJAX-based queries.
> Multiple post-type queries are not supported.
Artifacts:
* tests
* [screencast](https://share.cleanshot.com/HZ5pJZG2) 
[TEC-4621]: https://theeventscalendar.atlassian.net/browse/TEC-4621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix ACF integration

readme.txt, src/Tribe/Integrations/WPML/Meta.php, tests/integration/Tribe/Events/Integrations/WPML/MetaTest.php
Fix another issue in the WPML integration where multiple Organizers could not be assigned to an Event.
Changelog already added in previous PR.
[ECP-1442](https://theeventscalendar.atlassian.net/browse/ECP-1442) 
[ECP-1455](https://theeventscalendar.atlassian.net/browse/ECP-1455)
* [screencast](https://share.cleanshot.com/gBrMVTt1)
* tests (updated)
[Related ECP PR](https://github.com/the-events-calendar/events-pro/pull/2216)
[ECP-1442]: https://theeventscalendar.atlassian.net/browse/ECP-1442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ECP-1455]: https://theeventscalendar.atlassian.net/browse/ECP-1455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(Integrations/WPML) correctly handle linked post cached value

src/Tribe/Google/Maps_API_Key.php
There was a missing space in the description text under the Google Maps API key field when using a custom key.
=> Fix missing space under Custom Google Maps API key in Events Settings > Integrations tab

readme.txt, src/Tribe/Main.php, tests/wpunit/Tribe__Events__MainTest.php
[TEC-4689](https://theeventscalendar.atlassian.net/browse/TEC-4689)
Fix a smaller, pre-existing, issue found during QA pass to make sure the link to the Events page from the Permalinks page is built correctly.
The issue is highlighted by the WPML integration, but is based upon making the code that builds that link more robust.
Artifacts:
[Screencast](https://share.cleanshot.com/3vNpSN5j) 
[TEC-4689]: https://theeventscalendar.atlassian.net/browse/TEC-4689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WPML Integration - fix events link from Permalinks page

readme.txt, src/Tribe/Assets.php, src/Tribe/Editor.php
Ticket : [TEC-4762](https://theeventscalendar.atlassian.net/browse/TEC-4762)
Pass a NOOP callback function to Google Maps scripts to prevent JS warnings. These updates get rid of the warning in the following pages.
- Single events page ( Classic Editor )
- Create/edit events page ( Block Editor )
See related [pr](https://github.com/the-events-calendar/events-pro/pull/2242) in ECP.
**Screenshot 📸**
[TEC-4762]: https://theeventscalendar.atlassian.net/browse/TEC-4762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Google Maps callback function.

readme.txt, src/Tribe/Integrations/WPML/Views/V2/Filters.php, tests/integration/Tribe/Events/Integrations/WPMLTest.php
[TEC-4770](https://theeventscalendar.atlassian.net/browse/TEC-4770)
A fatal was happening because we use a Lazy_String object for the permalink property. Adding stringifying for the wpml filter.
Artifacts:
Fatal and tests.
```
Warning: Illegal offset type in isset or empty in /var/www/html/wp-content/plugins/sitepress-multilingual-cms/classes/url-handling/converter/class-wpml-url-cached-converter.php on line 46 Call Stack: 0.2026 381104 
1. {main}() /var/www/html/index.php:0 0.2026 381384 
2. require('/var/www/html/wp-blog-header.php') /var/www/html/index.php:17 0.3813 12812312 
3. require_once('/var/www/html/wp-includes/template-loader.php') /var/www/html/wp-blog-header.php:19 0.3946 13798528
4. include('/var/www/html/wp-content/plugins/the-events-calendar/src/views/v2/default-template.ph …
```
=> Fix and test for the WPML permalink filter.

readme.txt, src/Events/Integrations/Plugins/Elementor/Provider.php, src/Events/Integrations/Provider.php
Ticket : [TEC-4685](https://theeventscalendar.atlassian.net/browse/TEC-4685)
This update ensures Events are displayed correctly on Elementor's `Posts` widget.
I'm setting `tribe_suppress_query_filters` to true in order to prevent custom filters from modifying the query. In the context of the widget, we want the standard WordPress query behaviour to be applied.
https://drive.google.com/file/d/1kN6AxJ9BMPwaRGTLrEnuusvep8zoI2ul/view?usp=share_link
[TEC-4685]: https://theeventscalendar.atlassian.net/browse/TEC-4685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Elementor Posts widget [TEC-4685]

src/resources/postcss/base/full/_view.pcss
[TEC-4677](https://theeventscalendar.atlassian.net/browse/TEC-4677)
QA fix for a more friendly base alignment (centered as intended?).
[TEC-4677]: https://theeventscalendar.atlassian.net/browse/TEC-4677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> More friendly default alignment

readme.txt, src/resources/js/views/manager.js
Ticket : [TEC-4615](https://theeventscalendar.atlassian.net/browse/TEC-4615)
This update prevents pagination on the `month` and `week` views to address issue of missing events when a user switches views from a paginated list-style view. 
https://drive.google.com/file/d/1AZQvmdVxH2kTUuJofuRskHI0UXQ9OMrG/view?usp=share_link
[TEC-4615]: https://theeventscalendar.atlassian.net/browse/TEC-4615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevent pagination in `month` and `week` views.

readme.txt, src/modules/blocks/event-venue/template.js
[TEC-4741](https://theeventscalendar.atlassian.net/browse/TEC-4741)
In block editor while editing Event Venues, excessive geocode requests were being triggered. This adds a more definitive set of conditions and state changes are validated before fetching coords. No longer fetching during `render()`.
**Artifacts**:
Excessive requests to the Geocoding endpoint when a Google Maps API key is set, while in block editor. 
[TEC-4741]: https://theeventscalendar.atlassian.net/browse/TEC-4741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updates to watch state and props for geocode call.

readme.txt, src/Tribe/Main.php, tests/wpunit/Tribe__Events__MainTest.php
[TEC-4780](https://theeventscalendar.atlassian.net/browse/TEC-4780)
Fix fatal error caused by our assumption the `metaboxhidden_nav-menus` is always an array when on the Nav page.
Artifact:
```PHP Fatal error: Uncaught TypeError: array_search(): Argument #2 ($haystack) must be of type array, string given in /nas/content/live/website/wp-content/plugins/the-events-calendar/src/Tribe/Main.php:3535```
[TEC-4780]: https://theeventscalendar.atlassian.net/browse/TEC-4780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Gracefully handle invalid values for nav handler.

.github/workflows/tests-php.yml, readme.txt, src/Events/Custom_Tables/V1/WP_Query/Custom_Tables_Query.php, src/Events/Custom_Tables/V1/WP_Query/Repository/Custom_Tables_Query_Filters.php, tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/Repository/Custom_Tables_Query_FiltersTest.php
Ticket: n/a
Emerged in the context of the work for Flexible Tickets.
Artifacts: tests
This PR fixes an issue where, in ECP + CT1 context, using the Repository (`tribe_events`) to filter Events by series could raise a SQL error due to the `JOIN` clause on the Occurrences table being added twice to the filtered query `JOIN` clauses.
=> fix(CT1) avoid JOINing on Occurrences twice

readme.txt, src/Tribe/Views/V2/Views/By_Day_View.php, src/resources/js/views/manager.js, tests/views_integration/Tribe/Events/Views/V2/Views/By_Day_ViewTest.php
Ticket : [TEC-4615](https://theeventscalendar.atlassian.net/browse/TEC-4615)
Reverts the changes made on [this pr](https://github.com/the-events-calendar/the-events-calendar/pull/4240) because they've introduced some negative side-effects to the date picker.
Handling the issue from the PHP side of things.
[TEC-4615]: https://theeventscalendar.atlassian.net/browse/TEC-4615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevent pagination in month and week views.

readme.txt, src/Tribe/Models/Post_Types/Event.php, tests/wpunit/functions/template-tags/eventTest.php
[TEC-4690](https://theeventscalendar.atlassian.net/browse/TEC-4690)
This fixes a situation where cache would trigger a log call, that would serialize the `excerpt` property, and reset the global `post` mid-loop on the admin list.
Artifacts:
See tests and:
[TEC-4690]: https://theeventscalendar.atlassian.net/browse/TEC-4690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix excerpt serializer that would change current post.

src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php, src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php
- Fixing the preview, so that the calendar links settings respond to user selection. We'll adjust the information that's sent to the ajax call on ET.
- Remove the check to include the styles as they'll always be needed for venue.
- Change email settings from `toggle` to `checkbox_bool` as David requested.
=> Tickets Emails > DQA and calendar links

readme.txt, src/Events/Custom_Tables/V1/Activation.php, src/Events/Custom_Tables/V1/Health_Check.php, src/Events/Custom_Tables/V1/Schema_Builder/Abstract_Custom_Field.php, src/Events/Custom_Tables/V1/Schema_Builder/Abstract_Custom_Table.php, src/Events/Custom_Tables/V1/Tables/Events.php, src/Events/Custom_Tables/V1/Tables/Occurrences.php, src/Tribe/Main.php, tests/_support/Traits/CT1/CT1_Fixtures.php, tests/ct1_migration/TEC/Events/Custom_Tables/V1/Activation_StateTest.php
[TEC-4797](https://theeventscalendar.atlassian.net/browse/TEC-4797)
Removing our eager schema updates. This was causing a number of `ALTER` statements being run redundantly. No longer utilizes cache/transient for the last run check as it is not dependable.
Artifacts:
```
ALTER TABLE wp_tec_occurrences CHANGE COLUMNstart_date start_date VARCHAR(19) NOT NULL
```
See tests.
[TEC-4797]: https://theeventscalendar.atlassian.net/browse/TEC-4797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix for eager alter statements w/ tests.

src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php
[ET-1741]
[ET-1741]: https://theeventscalendar.atlassian.net/browse/ET-1741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Depends on: https://github.com/the-events-calendar/event-tickets/pull/2638
**Using Ticket Emails settings:**
**Without using Ticket Emails settings:**
=> [ET-1741] Hide TEC filtered RSVP email settings when RSVP is using Ticket settings.

readme.txt, src/Events/Custom_Tables/V1/WP_Query/Custom_Tables_Query.php, tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/Custom_Tables_QueryTest.php
[ECP-1495](https://theeventscalendar.atlassian.net/browse/ECP-1495)
Fixes database error, caused by the CT1 query parser when attempting rewrite the order by statement. Added logic to reflect on meta query arrays, and not just key/value pairs.
Artifact:
```WordPress database error Unknown column 'wp_tec_occurrences.meta_value' in 'order clause' for query 
SELECT   (wp_tec_occurrences.occurrence_id + 10000000) as occurrence_id
FROM wp_posts  LEFT JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) INNER JOIN wp_tec_occurrences ON wp_posts.ID = wp_tec_occurrences.post_id
WHERE 1=1  AND ( 
wp_term_relationships.term_taxonomy_id IN (4)
) AND ( 
wp_tec_occurrences.end_date >= '2023-03-23 00:00:00'
) AND wp_posts.post_type = 'tribe_events' AND ((wp_posts.post_status = …
```
=> Fix for meta_value orderby in CT1 context.

src/Tribe/Views/V2/Template/Title.php, tests/views_integration/Tribe/Events/Views/V2/Template/TitleTest.php
Fix for QA fail.
Past events need to flip order.
=> Reverse order for past events.

src/views/integrations/event-tickets/emails/template-parts/body/event/venue/address.php
n/a
City was appearing above state/province and zip code. They should be on one line, separated by a comma.
What it used to look like:
What it should look like, after this PR:
=> Tickets Emails: Fix City Being on Separate Line in Venue Address

src/Events/Telemetry/Provider.php, src/Events/Telemetry/Telemetry.php
Except for post editors and the Help page - as it does not trigger `in_admin_footer`.
[TEC-4704]
Related: https://github.com/the-events-calendar/tribe-common/pull/1928
[TEC-4704]: https://theeventscalendar.atlassian.net/browse/TEC-4704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Move modal logic to plugin. Ensure it show show up on all TEC admin pages.

src/Events/Integrations/Plugins/Event_Tickets/Emails/Hooks.php
- TE-27C1
- TE-9699
The event date should appear above the post title. By putting it in the right place, this also fixes the spacing issue (TE-9699) around the title.
Before:
After:
=> TE-27C1 Tickets Emails: Place Event Date Before Post Title

src/resources/postcss/views/skeleton/_single-event.pcss
Ticket : [TEC-4811](https://theeventscalendar.atlassian.net/browse/TEC-4811)
Harden some of our CSS to prevent unintended overrides by Elementor global styles i.e. this prevents Elementor gradient settings from being applied to ET buttons.
**Screenshot 📸**
[TEC-4811]: https://theeventscalendar.atlassian.net/browse/TEC-4811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Elementor vs TEC/ET styling conflicts.

readme.txt, src/modules/widgets/index.js
Reverts the updates made on this [pr](https://github.com/the-events-calendar/the-events-calendar/pull/4281).
The `core/legacy-widget` block needs to be registered for the block widgets to work.
- In earlier versions of WP i.e. between 5.8 and 6.0, the block is not registered by default in core. This was when widget blocks was in the _experimental_ phase.
- The error on this [ticket](https://theeventscalendar.atlassian.net/browse/TEC-4764) i.e. `Block "core/legacy-widget" is already registered` is showing up in later versions where the block is registered by default.
=> Prevent regression caused by registration of `core/legacy-widget` block.

readme.txt, src/Tribe/Admin/Settings.php
WP.org:
https://wordpress.org/support/topic/breaking-other-plugins-keep-getting-error-warnings-about-events-calendar/#post-16927655
=> Remove typed return for Admin Footer

.github/workflows/lint.yml, readme.txt, src/Tribe/Views/V2/Assets.php, src/modules/blocks/event-venue/style.pcss, src/modules/blocks/event-venue/template.js, src/modules/elements/google-map/element.js, src/modules/elements/google-map/style.pcss, src/resources/postcss/events-admin.pcss, src/resources/postcss/tribe-admin-single-blocks.pcss, src/resources/postcss/tribe-events-single-blocks.pcss, src/styles/event-venue/frontend.pcss, src/views/blocks/event-venue.php, src/views/blocks/parts/map.php, src/views/v2/day/event/venue.php, src/views/v2/list/event/venue.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/VenueTest__test_render_with_event_with_venue__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/VenueTest__test_render_with_event_with_venue__1.php
This updates block styling for venues so that they have a card-like appearance and cease to be full width, which looks odd on wide spaces.
🎥 
* [single event](https://www.loom.com/share/612f072c754b4f5ebe5657d6f931469b?sid=e2b72d15-d3c0-442a-9c70-26248ee62d98)
* [multi-venue +x](https://www.loom.com/share/9d9776a710ed49f2baedf60266d300f9?sid=4c7ea5d4-68e8-46d1-b2e2-ae36956ae161)
🎫 [ECP-1540]
Related:
* https://github.com/the-events-calendar/tribe-common/pull/1963
* https://github.com/the-events-calendar/events-pro/pull/2290
=> Adjust styling for venue blocks and set better map defaults

src/Tribe/Main.php, tests/wpunit/Tribe/Events/Linked_Posts/Publish_AssociatedTest.php
This reworks the `publishAssociatedTypes()` method to support arrays of organizers and venues and also updates the logic to accommodate changing any post status except `private` to publish.
🎥 https://www.loom.com/share/16e9aa58d0514d29b4ae4e4866cb560a
=> Publish venues and organizers on save of an event when it is published

src/Tribe/Linked_Posts/Chooser_Meta_Box.php
I accidentally hid the checkboxes behind a check for multiple venues (which is only enabled with Pro active), which was a silly thing to do. Rolling that back.
Here they are in all of their glory with Pro deactivated:
=> Show the checkboxes for ShowMap and ShowMapLink

src/Tribe/Editor/Meta.php, src/modules/blocks/event-venue/container.js, src/modules/blocks/event-venue/data/meta-sync.js, src/modules/data/blocks/venue/subscribers.js, src/modules/elements/search-or-create/template.js, src/modules/elements/venue-form/element.js
This set of fixes resolves a couple of things:
1. Venues created in the block editor will now default to having ShowMap and ShowMapLink set to true
2. Venues created in the block editor will now properly pass State, Province, and stateProvince to the backend
3. When you have multiple empty Organizer or Venue blocks and you start typing in one, text does not appear in all of them, just in the block you are typing in
🎥 https://www.loom.com/share/c98ddc6e6a5141e191029a398bde62d6?sid=fd545b83-099e-43a3-b7dd-bb79d2cddc59
=> Set venue defaults from block editor and pass state/stateProvince

src/modules/blocks/event-venue/data/meta-sync.js
This is a simple swap to using the proper editor function: `editEntityRecord()` rather than `editPost()`
:movie_camera: https://www.loom.com/share/d2a9e6b6e9e1444cb92b80e27dc3ad96
=> Prevent adding venues from breaking the event

src/views/modules/meta/organizer.php, src/views/modules/meta/venue.php
Ticket : [TEC-4812](https://theeventscalendar.atlassian.net/browse/TEC-4812)
Display an empty `<dt>` tag before `<dd>` even when the website title isn't available to ensure we always output valid html.
**Screenshot 📸**
[TEC-4812]: https://theeventscalendar.atlassian.net/browse/TEC-4812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure we output valid html.

src/Tribe/Linked_Posts.php, src/admin-views/create-venue-fields.php, src/resources/js/events-admin.js
This resolves 3 primary things:
1. **Fixed:** When a new venue was added to the event and save/publish/update was hit, the pre-existing venues were being duplicated on the event post.
1. **Fixed:** When a new venue was created from the event post editor, the state was not saving appropriately.
1. **Fixed:** When a new venue select box was added to the page and then the trash icon was clicked, the add venue button would not re-appear
:movie_camera: https://www.loom.com/share/2cd8a6079f6d4a3a922206d724fe9bd2?sid=92951c45-124f-403d-9b2e-ba3ef613f94d
=> Resolve venue duplication, state saving, and button handling issues

src/views/blocks/featured-image.php, src/views/blocks/parts/subscribe-list.php, src/views/blocks/parts/subscribe-single.php, tests/views_integration/Tribe/Events/Views/Blocks/Event_LinksTest.php, tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_no_custom_classes__1.php, tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_with_multiple_custom_classes__1.php, tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_with_single_custom_class__1.php
Ticket : [TEC-4724](https://theeventscalendar.atlassian.net/browse/TEC-4724)
Output custom CSS classes added to the `Event Links` and `Featured Image` blocks to the block output in the frontend.
This is a QA kickback so no need for a change log entry. 
**Screenshots 📸**
Custom classes added to Event Links block.
Custom classes added to Featured Image block.
[TEC-4724]: https://theeventscalendar.atlassian.net/browse/TEC-4724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Block Editor - Support for custom CSS classes.

src/Tribe/API.php
This prevents weird cases where the form fields are not passed when checkboxes are unchecked, thus, failing to update the desired state.  Instead, we say:
* If the field is missing when coming from the post editor, consider it false
* If the field is present when coming from the post editor, use the value
:movie_camera: https://www.loom.com/share/782199045be94f6bb9d0f13e1ed9f749
=> Ensure that the EventShowMap(Link) values are always set

src/Tribe/Embedded_Maps.php
This resolves an issue where height/width values were getting passed to the template as int values rather than units.
=> If height or width is numeric, tack on `px` for map dimensions

readme.txt, src/Events/Integrations/Plugins/Event_Tickets/Emails/Emails.php, tests/wpunit/TEC/Events/Integrations/Plugins/Event_Tickets/Emails/EmailTest.php
[ET-1843] Organizer email & Organizer Website were switched when using Tickets email. I refactored the `include_placeholders` method into 3 separate methods to allow us to test the variable replacement better.
[ET-1843]: https://theeventscalendar.atlassian.net/browse/ET-1843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ET-1843] Event Tickets email feature  Organizer email and website switched

readme.txt, src/Tribe/iCal.php
[ET-1778]
It was reported that spaces were being encoded as '%20' and we found that we were using `urlrawencode()` to encode the entire name. The iCalendar documentation states that the only disallowed characters are CTLs, DQUOTE, ";", "," and ":". This fix allows more characters to be used in Organizer names. It also converts double quotes to single quotes.
[ET-1778]: https://theeventscalendar.atlassian.net/browse/ET-1778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ET-1778] Change Organizer Name Sanitization to Encode Less Characters

readme.txt, src/Tribe/Views/V2/Hooks.php, src/Tribe/Views/V2/Rest_Endpoint.php, tests/views_integration/Tribe/Events/Views/V2/Rest_EndpointTest.php, tests/views_integration/Tribe/Events/Views/V2/iCalendar/RequestTest.php
[ECP-1581](https://theeventscalendar.atlassian.net/browse/ECP-1581)
In some situations the user capabilities were failing because the user session was not found. This would result in Event Manager pagination screens to lose the various event actions, and user authenticated logic.
The cause was the `_wpnonce` is used to auth the user.
Artifacts:
[ECP-1581]: https://theeventscalendar.atlassian.net/browse/ECP-1581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> We need wpnonce to validate user and show user caps.

src/Tribe/Editor/Compatibility.php
Ticket : [TEC-4790](https://stellarwp.atlassian.net/browse/TEC-4790)
As a result of the following [strategy decision](https://stellarwp.atlassian.net/browse/TEC-4790?focusedCommentId=115827), we won't enforce the block editor on FSE themes.
The ACs in the ticket have been updated to reflect this change.
[TEC-4790]: https://stellarwp.atlassian.net/browse/TEC-4790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Don't activate block editor on FSE theme switch.

src/Events/Custom_Tables/V1/WP_Query/Custom_Tables_Meta_Query.php, src/Tribe/Repositories/Event.php
Use `{$var}` instead.
[BTRIA-2088]
[BTRIA-2088]: https://stellarwp.atlassian.net/browse/BTRIA-2088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixes the deprecation of `${var}` in PHP 8.2.

src/Events/Custom_Tables/V1/Models/Builder.php
[BTRIA-2088](https://stellarwp.atlassian.net/browse/BTRIA-2088)
```
Deprecated: Creation of dynamic property TEC\Events\Custom_Tables\V1\Models\Builder::$query is deprecated in /var/www/html/wp-content/plugins/the-events-calendar/src/Events/Custom_Tables/V1/Models/Builder.php on line 820
```
[BTRIA-2088]: https://stellarwp.atlassian.net/browse/BTRIA-2088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Removing query prop

readme.txt, src/Tribe/Views/V2/View.php, src/modules/widgets/index.js, src/resources/js/event-editor.js
[TEC-4764](https://stellarwp.atlassian.net/browse/TEC-4764)
Resolves an issue with certain versions of Wordpress already having the legacy widget block registered causing us to trigger the console error `Block "core/legacy-widget" is already registered.` would occur. Now we check if registered first.
Artifact:
[TEC-4764]: https://stellarwp.atlassian.net/browse/TEC-4764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix legacy widget console error.

readme.txt, src/Tribe/REST/V1/Post_Repository.php, tests/wpunit/Tribe/Events/REST/V1/Endpoints/Single_EventTest.php
[TEC-4954](https://stellarwp.atlassian.net/browse/TEC-4954)
Fix a warning on our single event REST endpoint, when retrieving a venue attached to an event after the venue was deleted.
```Undefined variable: data at src/Tribe/REST/V1/Post_Repository.php:326```
[TEC-4954]: https://stellarwp.atlassian.net/browse/TEC-4954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix undefined var error, and added test coverage.

readme.txt, src/admin-views/admin-welcome-message.php
[TEC-4953](https://stellarwp.atlassian.net/browse/TEC-4953)
1. Replace the Virtual Event CTA in the admin welcome page with a CTA to the TEC Facebook community group.
2. Update existing cards to open external URLs in a new tab.
[TEC-4953]: https://stellarwp.atlassian.net/browse/TEC-4953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Facebook community group CTA in welcome page.

src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/address.php
This removes the whitespace that was in the "Get Directions" link for the venue address.
Before:
After:
=> ETWP DQA Fix: Remove whitespace from directions link

src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Passes/Pdf.php, src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/date.php, src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue.php, src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/address.php, src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/phone.php, src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/title.php, src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/website.php, src/views/integrations/event-tickets-wallet-plus/pdf/pass/tec-events-styles.php
- Using absolute image path for the venue icons to avoid TCPDF failures. `tribe_resource_url` returns the URL and that can fail in different scenarios.
- Updating template vars and docs linking to the ETWP templating article (where the docs live).
=> Use absolute image path for PDF images to avoid TCPDF failures.

readme.txt, src/Tribe/Views/V2/iCalendar/iCalendar_Handler.php
to the response headers for all `ical` and `outlook-ical` download "pages".
Reducing the amount of crawling and indexing of said pages.
[TEC-4966]
[TEC-4966]: https://stellarwp.atlassian.net/browse/TEC-4966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> This adds a noindex X-Robots-Tag 

readme.txt, src/Tribe/Views/V2/Hooks.php
Don't add one on:
- the site home page
- pages where tribe_context is not available
- any non-event views/pages
- if the filter is used
[TEC-4976]
[TEC-4976]: https://stellarwp.atlassian.net/browse/TEC-4976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a no index to alltheviews!

readme.txt, src/Tribe/Views/V2/Hooks.php, tests/wpunit/Tribe/Events/Views/V2/RobotsTest.php
This allows for very targeted alterations of the robots meta tag for whether it appears and what its contents are.
Default state: robots meta tag is present with `noindex, nofollow` for grid-based views (Month and Week)
🎫 [TEC-4976]
🎥 https://www.loom.com/share/1d121c97cb354887aeee4f7c99644b50?sid=f9861749-76d0-430d-b3e5-9c87927046fa
[TEC-4976]: https://stellarwp.atlassian.net/browse/TEC-4976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Alter robots noindex, nofollow to be more flexible | TEC-4976

readme.txt, src/Events/SEO/Controller.php
This allows single pages for Venues, Organizers, and Event Categories to have meta tags injected.
=> Enable meta tag on Venues, Organizers, and Event Category pages

src/Events/SEO/Controller.php, tests/views_integration/Tribe/Events/Views/V2/Views/Traits/With_NoindexTest.php
During the 6.2.6 release, I was too aggressive with removing some unnecessary code in the test for noindex and actually removed some asserts. This brings them back and adapts them to what they should be with the new filters.
=> This brings back some asserts that I removed accidentally

src/views/integrations/event-tickets-wallet-plus/pdf/pass/body/event/venue/website.php
Remove space at the end of the link so that we avoid having unnecessary blank space underlined (by default in PDFs)
=> [ETWP] Remove blank space at the end of the venue url.

.github/workflows/phpcs.yml
This re-enables PHPCS with comments on our PRs using https://github.com/reviewdog/reviewdog
If you want to see this in action with my test PR, you do so here: https://github.com/the-events-calendar/the-events-calendar/pull/4439
_Note: This is pull requested into `master` because this is merely a workflow addition._
=> Update phpcs workflow to use stellarwp/github-actions (reviewdog)

readme.txt, src/functions/template-tags/venue.php, tests/wpunit/functions/template-tags/venueTest.php
[ECP-1597](https://stellarwp.atlassian.net/browse/ECP-1597)
Update the `tribe_get_venues` function to work with recurring events that have provisional IDs by applying the `tec_events_custom_tables_v1_normalize_occurrence_id` filter.
https://drive.google.com/file/d/1PZHi0z9BzQx6mF4cU1NvxUn-B1vkEbbZ/view?usp=sharing
[ECP-1597]: https://stellarwp.atlassian.net/browse/ECP-1597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Tweak `tribe_get_venues` to work with provisional IDs.

readme.txt, src/Tribe/Views/V2/functions/classes.php
[TEC-4898](https://stellarwp.atlassian.net/browse/TEC-4898)
This update addresses an issue in the Month View where the `tribe-events-calendar-month__day--past` and `tribe-events-calendar-month__day--current` classes were not consistently applied when users navigated away from and back to the current month.
This fix ensures that any custom styling applied to the classes is consistent and persists even after paginating to different months.
https://drive.google.com/file/d/1l5rEByThHHUUvgP6UY5Eierx2MsG03HA/view?usp=sharing
[TEC-4898]: https://stellarwp.atlassian.net/browse/TEC-4898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix CSS class application in Month view for past and current days.

readme.txt, src/Tribe/Rewrite.php, tests/wpunit/Tribe/Events/RewriteTest.php
[TEC-4979](https://stellarwp.atlassian.net/browse/TEC-4979)
The localized `page` URL param was not being detected in the `template_redirect` when resolving canonical URLs. Now we pull the same translation var for the `pagination_base` property used to detect whether a URL is canonical and should redirect.
[TEC-4979]: https://stellarwp.atlassian.net/browse/TEC-4979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix for the pagination base property.

readme.txt, src/Tribe/Aggregator/Record/Abstract.php
[ECP-1603](https://stellarwp.atlassian.net/browse/ECP-1603)
This resolves several php 8.2 deprecation errors. 
Artifact:
```
PHP Deprecated:  Creation of dynamic property Tribe__Events__Aggregator__Record__gCal::$image_uploader is deprecated
```
[ECP-1603]: https://stellarwp.atlassian.net/browse/ECP-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed deprecation errors.

src/Tribe/Main.php, tests/integration/RevisionTest.php
During work done to fix the revision-related issue ([commit](https://github.com/the-events-calendar/the-events-calendar/pull/4326/commits/597a7153ff124cf37cc8ace650c4b45fa33c95c5)), I've forgotten to move the recursion guard down with the effect of preventing the save operation on WordPress versions < 6.4.
The change is already covered by automated tests where possible.
Screencast: [link](https://share.cleanshot.com/JVBpg13n)
=> Set recursion guard later

src/Events/Integrations/Plugins/Event_Tickets/Site_Health/Subsection.php
[ET-2047]
While fixing ET-2047 I noticed that `get_number_of_ticketed_events_happening_now` was not taking into account ticketed events, but rather all events happening now. I added an extra where to only take into account ticketed events.
[et_2047_artifact.webm](https://github.com/the-events-calendar/the-events-calendar/assets/12241059/51c0d266-31e6-4c9b-bc10-88b89e3bfe64)
[ET-2047]: https://stellarwp.atlassian.net/browse/ET-2047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ET-2047] Added `has_tickets` to get correct data.

src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Passes/Apple_Wallet/Event_Modifier.php
[ETWP-95]
While Romine was testing she found that when exporting the Apple Pass for Series Passes the file wouldn't open properly. This was due to the `pass.json` being incorrect and having the `event_date_time_range` twice. I adjusted the logic so this wouldn't happen again. I have attached the new pass with the fix as an artifact.
[event-tickets-wallet-plus-49661c0408.zip](https://github.com/the-events-calendar/the-events-calendar/files/14483203/event-tickets-wallet-plus-49661c0408.zip)
[ETWP-95]: https://stellarwp.atlassian.net/browse/ETWP-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ETWP-95] Series Pass Apple Wallet not opening

src/Events/Integrations/Plugins/Elementor/Controller.php
The call in ECP has been deprecated in: https://github.com/the-events-calendar/events-pro/pull/2417
=> Add the widget category here now.

src/Events/Integrations/Plugins/Elementor/Controller.php, src/Events/Integrations/Plugins/Elementor/Manager_Abstract.php
Add a filter to prevent going from editing an event in Elementor to the blocks editor.
[ECP-1749]
:movie_camera: https://www.loom.com/share/b0569ac552214df1b7e6ad40deac86aa?sid=46732eff-6c85-4d8a-a1a2-0190bfb2a754
[ECP-1749]: https://stellarwp.atlassian.net/browse/ECP-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Force the classic editor for events edited in Elementor

readme.txt, src/views/integrations/event-tickets/emails/template-parts/body/event/venue/website.php
[ET-2019]
The Venue Website URL was not showing within the tickets emails because we were using the wrong property (`website_url` rather than `website`).
[ET-2019]: https://stellarwp.atlassian.net/browse/ET-2019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ET-2019] Tickets Emails: Fix missing venue website URL

src/functions/template-tags/link.php
[ECP-1746]
[ECP-1746]: https://stellarwp.atlassian.net/browse/ECP-1746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Don't use an empty string for the label.

readme.txt, src/Events/Admin/Notice/Provider.php, src/Events/Admin/Notice/Rest_Api.php, src/Tribe/Admin/Notice/Rest_Api.php, src/Tribe/Admin/Provider.php, src/Tribe/Main.php, src/Tribe/REST/V1/Main.php
[TEC-4667]
Added a class names `Rest_Api.php` under `src/Tribe/Admin/Notice` to register an admin notice that would warn the user when our Rest Api endpoints are not accessible.
[TEC-4667]: https://stellarwp.atlassian.net/browse/TEC-4667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-4667 Show Notice when REST API is blocked

package.json, src/Events/Views/Modifiers/Hide_End_Time_Modifier.php, src/admin-views/tribe-options-display.php
Specifically around the default view.
Remove past control and logic
[TEC-4371]
See: https://github.com/the-events-calendar/the-events-calendar/pull/4536
[TEC-4371]: https://stellarwp.atlassian.net/browse/TEC-4371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix logic for applying Hide_End_Time_Modifier. 

readme.txt, src/functions/advanced-functions/event.php
No associated ticket (minor tweak)
Adjusted docblock for tribe_update_delete() to redirect users to use the TEC ORM instead since the function is outdated and will be deprecated in the future.
=> Added deprecation note to docblock for tribe_delete_event()

readme.txt, src/Tribe/Views/V2/Template/Title.php
[TEC-5074]
When we are using a classic theme (not a Block Theme) the filters that adjust the Page Title were fired before the current View of the List page was setup. So the query results were null and the global query fallback had a different events list, of what was eventually displayed. Thus the page titles daterange was wrong.
In this case, we setup the View earlier, with the repository and query arguments and get the proper events list to display the right page title.
[TEC-5074]: https://stellarwp.atlassian.net/browse/TEC-5074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Wrong dates in Page Titles

readme.txt, src/Tribe/Main.php, src/resources/postcss/widgets/full/_events-list.pcss, src/views/single-event.php
[TECTRIA-40]
This CSS rule is bad for localization, because it leads to grammatically incorrect constructs, like "Vis Kalender" in Norwegian (we never capitalize words unless they are proper nouns, and "Kalender" is not a proper noun).
[TECTRIA-40]: https://stellarwp.atlassian.net/browse/TECTRIA-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove text-transform:capitalize;

readme.txt, src/Tribe/Views/V2/Views/Traits/Breakpoint_Behavior.php
N/A - small tweaks to docblocks 
Corrected `@param` and `@return` descriptions in the file `Tribe\Events\Views\V2\Views\Traits\Breakpoint_Behavior.php`. In favor of PR #4614 - credit goes to @iandelmar
=> DocBlocks: `Breakpoint_Behavior.php`

readme.txt, src/Tribe/Views/V2/functions/classes.php
Updated docblock for `month_day_classes` and `tec_events_month_day_classes_comparison_date`
=> docBlock: `month_day_classes` and `tec_events_month_day_classes_comparison_date`

src/admin-views/tribe-options-display.php
Fixed an issue where the variable used for the filter `tec_events_display_settings_toc` was incorrect and didn't exist. Switched to using the original field `$tec_events_general_toc`.
=> [TEC-5119] Incorrect variable used on settings page

changelog/fix-TEC-4941-dont-overwrite-existing-venue, src/Tribe/Venue.php, src/admin-views/tribe-options-general.php, tests/wpunit/Tribe/Events/VenueTest.php
[TEC-4941]
#3285 Introduced some changes to how Venues are handled when an Event is created or updated. Previously, if you did not choose an existing Venue, it was possible to create a new Venue that was a duplicate of an existing Venue. After that PR, some logic was introduced to prevent duplicate Venues from being created. If you created a "new" Venue with the same title as an existing Venue, the existing Venue would be updated.
Since [TEC-4941] includes feedback that the previous behavior is desirable for some users, I thought that adding a setting for users to choose would be the best option of both approaches. Users who like the current duplicate prevention do not need to do anything, and nothing will change. Users who would like to have duplicate Venues can change the option, and …
=> Create an option to allow duplicate venue creation

changelog/fix-docblock-column-mapper-get_column_label, src/Tribe/Importer/Column_Mapper.php
Add docblocks to the following methods in the `Tribe__Events__Importer__Column_Mapper` class.
* `get_column_label()`
* `get_event_column_names()`
* `get_venue_column_names()`
* `get_organizer_column_names()`
=> Docblocks for methods in the `Tribe__Events__Importer__Column_Mapper` class

changelog/BTRIA-2353, src/Tribe/Integrations/WPML/Meta.php
[BTRIA-2353]
Grabbing the change from #4603 this will fix the issue where WPML was breaking the location search from Google Maps API. All that was missing was the list of element ids to be merged into the array returned from `translate_elements()`. Credit goes to @dgwatkins ! 
Uploading CleanShot 2024-08-09 at 16.32.39.mp4…
[BTRIA-2353]: https://stellarwp.atlassian.net/browse/BTRIA-2353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BTRIA-2353 - Fix for WPML Integration with Search Location 

src/Tribe/Admin/Timezone_Settings.php, src/admin-views/tribe-options-imports.php
This fixes the timezone settings being dropped from the Display->Date & Time subtab.
[TEC-5126]
Fixed:
[TEC-5126]: https://stellarwp.atlassian.net/browse/TEC-5126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Missing Timezone settings

changelog/fix-ecp-1562_update_custom_tables_query_filters, src/Events/Custom_Tables/V1/WP_Query/Repository/Custom_Tables_Query_Filters.php
[ECP-1562]
From original PR #4651  : 
Bug fix: php error "WordPress database error Not unique table/alias: 'wp_tec_occurrences' for query SELECT SQL_CALC_FOUND_ROWS..."
Function filter_posts_join needs to check for dups regardless of whether or not there are any redirects because the external join from wp_query still needs to be tested against the existing query vars.
I initially posted a query about this on the WordPress forum: [wordpress.org/support/topic/not-unique-table-alias-wp-tec_occurrences-2#post-17856396](https://wordpress.org/support/topic/not-unique-table-alias-wp-tec_occurrences-2/#post-17856396). The response I received from Jes referred to bug report [ECP-1562](https://stellarwp.atlassian.net/browse/ECP-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
=> [ECP-1562] Update `Custom_Tables_Query_Filters.php` Logic

changelog/BTRIA-2353, changelog/docblock-column-mapper-set_defaults, changelog/fix-Latest_Past_Events_Categories, changelog/fix-TEC-4941-dont-overwrite-existing-venue, changelog/fix-TEC-5105-fix-rest-api-disabled-notice, changelog/fix-docblock-column-mapper-get_column_label, changelog/fix-docblock-make_select_box, changelog/fix-docblock-tribe_embed_google_map, changelog/fix-docblock-tribe_get_listview_dir_link, changelog/fix-docblock-tribe_get_listview_link, changelog/fix-docblock-tribe_get_listview_past_link, changelog/fix-docblock-tribe_show_google_map_link, changelog/fix-ecp-1562_update_custom_tables_query_filters, changelog/tweak-make-string-in-settings-translatable, changelog/tweak-make-string-in-settings-translatable , src/Tribe/Views/V2/Views/Latest_Past_View.php, src/views/v2/latest-past.php
[TEC-4991]
When in the Events page and no current of future events exist, we shoe a Latest Past Events list below the calendar with previous events. If we are in a category archive then that Past Events list should be from the same queried object.
[TEC-4991]: https://stellarwp.atlassian.net/browse/TEC-4991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Latest Past Events list in Category Views

changelog/fix-docblocks-Tribe__Events__Repositories__Organizer, src/Tribe/Repositories/Organizer.php
Update the docblocks in the `Tribe__Events__Repositories__Organizer` class.
=> Docblocks: `Tribe__Events__Repositories__Organizer` class

changelog/enhancement-TEC-5138-filter-additional-venue-data, src/Tribe/Importer/File_Importer_Venues.php
[TEC-5138]
With CSV imports it is possible to add extra columns when importing events and have them saved.
For Organizers and Venues columns can be added for the column mapping, however, it is not possible to save the additional data, because a block of code and filter - what is available for events - is missing.
This PR fixes this for Venues.
[Screencast](https://1drv.ms/v/s!Aqh6lbOjUW1ThaER8QVna74EWGb98w?e=vSEeWF)
[TEC-5138]: https://stellarwp.atlassian.net/browse/TEC-5138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TEC-5138] Filter additional venue data for CSV import

.github/workflows/lint.yml, .github/workflows/phpstan.yml, .github/workflows/tests-integrations.yml, .github/workflows/tests-js.yml, .github/workflows/tests-php-seo-plugin.yml, .github/workflows/tests-php.yml, .github/workflows/zip.yml
to avoid issues with deprecated artifact upload/download actions.
Add summary output to test skip check.
Requires: https://github.com/the-events-calendar/tribe-common/pull/2203
=> Update checkout action to v4

src/functions/template-tags/date.php, tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/EventDatetimeTest__test_render_no_custom_classes__1.php, tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/EventDatetimeTest__test_render_with_multiple_custom_classes__1.php, tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/EventDatetimeTest__test_render_with_single_custom_class__1.php, tests/wpunit/functions/template-tags/date_Test.php
Follow-up to the creation of the template tags to add test coverage and protect from cache poisoning.
=> Cover date and time range separator template tags with tests

changelog/fix-tec-5309-past-events-order, src/Tribe/Views/V2/Views/Latest_Past_View.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
[TEC-5309]
Fix order of past events in the list view when no future events exist. The order should be: the closer to the present past event appears first.
Using the updated code events are displayed from closer to now first.
Before the change you can see the issue in the loom below.
https://www.loom.com/share/63b99b41a5b849aaaca2fbe14659492b
[TEC-5309]: https://stellarwp.atlassian.net/browse/TEC-5309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix order of past events in the list view

changelog/fix-remove-update-page, src/Tribe/Assets.php, src/Tribe/Main.php, src/admin-views/settings/sidebars/default-sidebar.php, src/admin-views/tribe-options-general.php
[TEC-5311]
This removes all the calls for the activation and update page.
[TEC-5311]: https://stellarwp.atlassian.net/browse/TEC-5311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Removing the landing/update page from the plugin, but not the notice.

src/admin-views/settings/sidebars/default-sidebar.php, src/admin-views/tribe-options-general.php
This PR focuses on updating the old Help page slugs from `tec-events-help` to `tec-events-help-hub`
=> Help Hub - Update link slugs

changelog/TEC-5319-move-to-trash-bug, src/Events/Custom_Tables/V1/Events/Event_Cleaner/Event_Cleaner.php, src/Tribe/Event_Cleaner_Scheduler.php, tests/ct1_integration/__snapshots__/Tribe__Events__Event_Cleaner_SchedulerTest__should_have_occurrence_sql__1.php
[TEC-5319]
The "Move events to trash older than" maintenance function checks for all events that don't have the 'trash' post status and deletes them if they are beyond the set threshold. However, there might be "trashed" imported events (with 'tribe-ignored' post status), which are not excluded. So if there are 15 or more 'tribe-ignored' events on a site, the maintenance might keep trashing those (change them to 'tribe-ignored' post status, which they already are).
This PR adjusts the query in question so the 'tribe-ignored' post status will also be ignored, thus making the maintenance work again.
[Screen rec](https://1drv.ms/v/s!Aqh6lbOjUW1ThapLnZO0wKyruqLD5A?e=CTV1TT)
[TEC-5319]: https://stellarwp.atlassian.net/browse/TEC-5319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
=> Fix "Move to trash events older than" bug

changelog/fix-TEC-5326-event-export-template-override, src/views/integrations/elementor/widgets/event-export.php, src/views/integrations/elementor/widgets/event-export/list-item.php
[TEC-5326]
The template override path in the docblock for the files in `src/views/integrations/elementor/widgets/event-export` were suggesting to override the files at `[your-theme]/tribe/events/integrations/elementor/widgets/event-export.php`, which wasn't working. The override path that was working was `[your-theme]/tribe/events/integrations/elementor/views/integrations/elementor/widgets/event-export/[file].php` This is because the `views/integrations/elementor/` part of the override path was getting added a second time when being passed as the `$name` variable to the `template()` method. 
By removing these extra directories from the `$name` string, the override now works using the path suggested in the docblocks. 
After changes: 
[TEC-5326]: …
=> TEC-5326 Correct template override paths Event Export 

changelog/fix-TEC-5337-theme-template-options, src/admin-views/settings/tabs/display/display-calendar.php
[TEC-5337]
When the new Settings UI was added in TEC v6.7, the logic was removed to add the page templates from the theme into the template options. 
[TEC-5337]: https://stellarwp.atlassian.net/browse/TEC-5337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added logic for theme template in display options

src/Events/Admin/Onboarding/Controller.php, src/Events/Admin/Onboarding/Landing_Page.php
Removes all admin notices from the onboarding page.
Hook into the admin_notices the earliest we can and if we are on the onboarding page, remove all other actions attached to the admin_notices hook
=> Remove all notices in onboarding page

src/Tribe/Views/V2/Rest_Endpoint.php, tests/views_integration/Tribe/Events/Views/V2/Rest_EndpointTest.php
[TICKET_ID]
Bug fix: when used on a site with SAM Pro Free, logged-out users’ ajax requests to `/wp-json/tribe/views/v2/html` fail with a `401 Unauthorized` response and this response body:
```json
{
"code": "rest_forbidden",
"message": "Sorry, you are not allowed to do that.",
"data": {
"status": 401
}
}
```
Logged-in user’s ajax requests work fine.
Cause:
- The Events Calendar [generates nonces](https://github.com/the-events-calendar/the-events-calendar/blob/a88c3daa04357c5807211a7a347cdf0dd678500a/src/Tribe/Views/V2/Rest_Endpoint.php#L192-L217) while ignoring the `nonce_user_logged_out` filter
- SAM Pro Free uses that filter to return the logged-out user’s IP address rather than the default `0`
- The Events Calendar does not ignore that filter when [verifying the …
=> fix nonce verification issue

changelog/fix-TEC-5343-disable_blocks_on_display-remove-string-requirement, src/Events/Integrations/Plugins/Elementor/Controller.php
[TEC-5343]
There was a case reported where Elementor and Yoast were causing a fatal error in TEC's Elementor integration due to the return value being `null` instead of a string. This fix adds a conditional to the first part of `disable_blocks_on_display()` to convert the `$content` to an empty string if it is `null` to avoid causing a fatal error. 
[TEC-5343]: https://stellarwp.atlassian.net/browse/TEC-5343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-5343 Add check that `$content` is not `null`

changelog/fix-register_notifications_on_action, src/Events/Integrations/Provider.php, src/Events/Notifications/Notifications.php, src/Events/Notifications/Provider.php
[TEC-5336 ]
During QA for IAN's first release, we discovered that a fatal error was thrown if the user would downgrade from the latest to the previous version of TEC (since the new Notifications class wouldn’t exists in that one).
We patched the fix [with this PR](https://github.com/the-events-calendar/the-events-calendar/pull/4849/files), using a `class_exist()`. 
This PR improves that, by using [register_on_action](https://docs.theeventscalendar.com/reference/classes/tec-common-contracts-container/register_on_action/), and removes the `class_exists()` check.
=> Register IAN on action

changelog/fix-EA-476-replace-deprecated-functions, src/Tribe/Aggregator/Record/Abstract.php, tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php
[EA-476]
The WP function `get_page_by_title` has been deprecated as of version 6.2. This PR replaces the function with an equivalent `WP_Query` call.
https://share.zight.com/7KuwbZgE
[EA-476]: https://stellarwp.atlassian.net/browse/EA-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [EA-476] Event Aggregator: Replace  deprecated `get_page_by_title` function

changelog/fix-ECP-1613-Divi-z-index-conflict, src/resources/postcss/events-admin.pcss
[ECP-1613]
When editing a recurring event, the Divi loader has a z-index of `2000000` while our dialogue box asking which recurring events to apply the changes to (`ui-front`) had a z-index of `1000000`, causing it to be unusable/blocked. 
[ECP-1613]: https://stellarwp.atlassian.net/browse/ECP-1613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECP-1613 Divi Z-Index Conflict

changelog/fix-TEC-5015_additional_fields_in_rest, src/Tribe/API.php, src/Tribe/REST/V1/Post_Repository.php, tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_EventTest.php, tests/wpunit/Tribe/Events/REST/V1/Endpoints/__snapshots__/Archive_EventTest__it_should_hide_password_protected_fields__0.snapshot.json, tests/wpunit/Tribe/Events/REST/V1/Endpoints/__snapshots__/Archive_EventTest__it_should_show_additional_fields__0.snapshot.json
[TEC-5015]
The initial bug report mentioned that when an event was updated via REST API, the additional fields were emptied. By supporting them in our API, we make additional fields available for all operations.
[TEC-5015]: https://stellarwp.atlassian.net/browse/TEC-5015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Support Additional Fields in Events REST API

changelog/tweak-TEC-5352-add-aliases-to-venue-orm, src/Tribe/Repositories/Venue.php
[TEC-5352]
[Original PR](https://github.com/the-events-calendar/the-events-calendar/pull/4870) - credit to @m8nmueller
Currently, our Venue ORM does not have aliases for `_VenueShowMap` or `_VenueShowMapLink` - this PR amends that. 
[TEC-5352]: https://stellarwp.atlassian.net/browse/TEC-5352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-5352 Add Aliases to Venue ORM 

changelog/fix-TEC-5353-Venue-ORM-object-decoration, src/Tribe/Repositories/Venue.php
[TEC-5353]
[Original PR](https://github.com/the-events-calendar/the-events-calendar/pull/4870) - credit to @m8nmueller
This is the second issue addressed in the PR above - currently what is returned from our Venue ORM is a "bare" WP Object:
These changes allow the venue object that is returned to be a decorated object: 
These changes are based on the [same function in the Event Repository](https://github.com/the-events-calendar/the-events-calendar/blob/4d14db270f88d2af1bec67149bb7694392a00393/src/Tribe/Repositories/Event.php#L1499-L1519).
[TEC-5353]: https://stellarwp.atlassian.net/browse/TEC-5353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-5353 Support Venue ORM Results as Decorated Objects

changelog/fix-TEC-5357-add-type-check-for-single-event-links, src/Tribe/Views/V2/iCalendar/Single_Events.php
[TEC-5357]
A user reported that they were getting a fatal error because `$subscribe_links` were somehow `false` and triggering a fatal in the `single_event_links` method. This adds a defensive check for the variable type to avoid that fatal. 
https://github.com/user-attachments/assets/9ee9cf96-4e7b-4e7d-b673-53033f10ed31
[TEC-5357]: https://stellarwp.atlassian.net/browse/TEC-5357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added check for `$subscribe_links` and updated docblock

changelog/fix-ECP-1725-list-view-shortcode-adjustments, src/views/v2/widgets/widget-events-list/event/date-tag.php
[ECP-1725]
The template override path referenced venues but should be pointing to the `date-tag.php` file instead.
[ECP-1725]: https://stellarwp.atlassian.net/browse/ECP-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ECP-1725] Template Override Path Correction for Date-Tag

changelog/fix-TEC-5360-subscribe-to-google-calendar, src/Tribe/iCal.php
[TEC-5360]
On some calendars, clicking on the “Subscribe to… Google Calendar” option makes it seem like the calendar is successfully created, but no events are actually imported. In testing, it seems like the Google Importer never actually makes it to the site’s database.
The source of the issue is that All time zones used in the feed for the different events need to be defined at the top, and all time zone definitions should be in their own block.
The bug is that there is only one time zone block containing info about all time zones.
This PR makes sure that all time zones get their own block.
[Screenshot showing part of the iCal feed and pointing out the lines that were missing.](https://dl.dropbox.com/scl/fi/cy137xc7g0qymc57jdd0k/shot_250205_123047.png?rlkey=jcntz5ql2cj13p32o11di69ab&dl= …
=> TEC-5360 Subscribe to google calendar issue

changelog/tweak-TEC-5363-check-FILES-before-setting-param, src/Events/Custom_Tables/V1/Updates/Requests.php
[TEC-5363]
A user reported there’s a conflict with ECP and ACFE Pro, where we assume that the `$_FILES` variable will be set. ACFE Pro form submission with Events Calendar Pro activated results in PHP error, terminating post submission PHP & JS script loading. They are getting this warning:
```
Warning: Undefined global variable $_ FILES in /Users/dougfoster/Local Sites/illumecollective/app/public/wp- content/plugins/the-events-calendar/src/Events/Custom _ Tables/V1/Updates/Requests.php on line 5 1
```
This seems like a unique edge case scenario of a third-party plugin, but adding a check to not assume that the `$_FILES` variable exists makes our code more defensive and is an easy win. 
[TEC-5363]: https://stellarwp.atlassian.net/browse/TEC-5363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
=> [TEC-5363] Check `$_FILES` before adding param

changelog/fix-hide_Astra_theme_notice, src/resources/postcss/base/full/_view.pcss
[TEC-4853]
[This function](https://themes.trac.wordpress.org/browser/astra/4.8.11/inc/blog/blog.php?rev=257601#L468) in Astra Theme prints the below message in our main Events page:
> It seems we can’t find what you’re looking for. Perhaps searching can help.
Unfortunately they are offering no filters there, thus we can only hide it with CSS.
[TEC-4853]: https://stellarwp.atlassian.net/browse/TEC-4853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Hide notice from Astra Theme archive template

changelog/fix-TEC-5402-adjust-space-below-steps, src/resources/packages/wizard/index.css
[TEC-5402]
Starting on Step 2 and in all subsequent steps, the space between the steps and the current icon/name is too big.
To give the vertical gap some flexibility, I used vh instead of a fixed px value for the row-gap.
[Screen rec](https://1drv.ms/v/s!Aqh6lbOjUW1ThcIWRwNxiFNFzczAEg?e=BdEvrv)
[TEC-5402]: https://stellarwp.atlassian.net/browse/TEC-5402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-5402 Adjust space below steps in the onboarding wizard

changelog/fix-TEC-5409-adjust-feedback-on-install-ET, src/resources/packages/wizard/components/buttons/next.tsx
[TEC-5409]
We were resetting the `isSaving` to `false` too early, causing the 'next' button to never show the 'Saving...' text to give the user feedback that the next tab is coming or on the last tab that the modal is about to close.
This adjustment ensures that i`sSaving` is only reset after the necessary processes complete.
After:
https://github.com/user-attachments/assets/456fe92e-919e-4e15-9628-0694c69bf5b8
[TEC-5409]: https://stellarwp.atlassian.net/browse/TEC-5409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Tweaked when isSaving is set to false

changelog/fix-TEC-5398-add-notice-for-no-views-selected, src/resources/packages/wizard/components/tabs/display/tab.tsx, src/resources/packages/wizard/index.css
[TEC-5398]
Although we were correctly disabling the 'Continue' button if no views were selected on the Display tab for the Onboarding Wizard we needed to add a notice to give feedback to the user so they understand why the button had been disabled. This PR adds that notice and some styling to match other notices in the Wizard. 
Before:
https://github.com/user-attachments/assets/440409d2-8cfc-4aff-b4db-1fb148416d71
After:
https://github.com/user-attachments/assets/567f0b94-0c0e-4913-88ad-8a4a5ecbd2e7
[TEC-5398]: https://stellarwp.atlassian.net/browse/TEC-5398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TEC-5398] Add Notice to Display Tab

changelog/fix-TEC-5411-first-time-setup-page-keeps-appearing, src/Events/Admin/Onboarding/Controller.php, src/Events/Admin/Onboarding/Landing_Page.php
[TEC-5411]
When a user has completed all the steps inside the Wizard, and they click on the "Events" menu item, they are still taken to the “First Time Setup” page, because that is the first menu item. This behavior can be confusing to users, so the submenu item has been moved to the bottom and renamed to "Setup Guide".
[Screen rec](https://docs.google.com/videos/d/1wAVhzQxJo03M6bTcvRKfhoImvDQtPfqyOZy7F6lmQhM/edit?usp=sharing)
[TEC-5411]: https://stellarwp.atlassian.net/browse/TEC-5411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-5411 first time setup page keeps appearing

src/resources/postcss/calendar-embeds/admin/page.pcss
Hide slug input field from quick edit form - We disallow edit from php's side as well. This just amends the specific UI.
sshot with markup attached.
=> Hide second label in inline edit for calendar embeds

changelog/TEC-5430-allow-auto-width-on-subscribe-button, src/modules/blocks/event-links/style.pcss, src/resources/postcss/components/full/_ical-link.pcss
[TEC-5430](https://stellarwp.atlassian.net/browse/TEC-5430)
Some translations make the 'Add to Calendar' string longer and breaks the formatting of the subscribe button. This PR allows for width to be `auto` to accommodate these scenarios. 
Before: 
After:
[TEC-5430]: https://stellarwp.atlassian.net/browse/TEC-5430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow dropdown to be wider

changelog/fix-ECP-1059, src/Tribe/Views/V2/Hooks.php, src/Tribe/Views/V2/Template_Bootstrap.php
[ECP-1059]
-Add detection of Single Venue and Single Organizer in Template_Bootstrap
-Use detection of those to post types to prevent overwrite of custom title tags from SEO plugins, similar to what we do for single events. 
https://cloudup.com/cSduhYsH4QE
[ECP-1059]: https://stellarwp.atlassian.net/browse/ECP-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Support for Detecting Single Organizers and Single Venues.

src/Events/Calendar_Embeds/Calendar_Embeds.php, tests/embed_calendar_integration/Calendar_Embeds_Test.php
Issue 19 from [gsheet](https://docs.google.com/spreadsheets/d/1NzXAjMpzE7Cum9rOix2ctIjEsdpR_YgFLLMKvnGtzkk/edit?gid=439778935#gid=439778935)
Makes sure that the trash-untrash process does not change the ECE's slug.
The test case is an artifact in this case.
=> Dont change the ECE slug when trashed

changelog/fix-TEC-5402-fix-centering, src/resources/packages/wizard/index.css
[TEC-5402]
The form in the onboarding wizard was not centered for some WordPress versions, e.g. 6.5.2
This PR adjusts one CSS property that should fix the issue across the board.
Before
https://dl.dropbox.com/scl/fi/uw695414t83q4o6h1dxab/shot_250324_182147.png?rlkey=9wpxl57ehrabps5o6mhuhhjem&dl=0
After
https://dl.dropbox.com/scl/fi/c1a05ox8or23xchx9t6o0/shot_250324_182311.png?rlkey=evxnex8t5xqc5p7b8qtuj9w59&dl=0
[TEC-5402]: https://stellarwp.atlassian.net/browse/TEC-5402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-5402 fix centering

src/Tribe/Views/V2/Assets.php
Fixes an introduced issue during ECE where we would use wp.hooks into the manager.js without adding it to manager's dependencies though.
=> Add wp-hooks to manager's dependencies

changelog/fix-ECP-1898-builder-cache, src/Events/Custom_Tables/V1/Models/Builder.php, src/Events/Custom_Tables/V1/Models/Occurrence.php, tests/ct1_integration/TEC/Events/Custom_Tables/V1/Models/ModelTest.php
Ticket: [ECP-1898](https://stellarwp.atlassian.net/browse/ECP-1898)
This introduces query caching in the model builder to cache the results of duplicated queries at the builder level without running them twice.
[Demo](https://share.cleanshot.com/QHLG0szn)
Proper cache invalidation was already directly (`ct1_integration/BuilderTest.php`) and indirectly covered in existing tests.
I had to modify a single test that was insisting on the batched fetching functionality since the whole point of the test is to assert on the number of queries made.
[ECP-1898]: https://stellarwp.atlassian.net/browse/ECP-1898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> tweak(CT1) introduce query caching in the Model builder.

changelog/fix-FBAR-333-incorrect-ul-use, src/views/v2/components/messages.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_message_with_html__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_multiple_messages__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/MessagesTest__test_render_with_single_message__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_no_events_today_date_equals_day_date__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_no_events_today_date_not_day_date__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_no_found_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/__snapshots__/Widget_Events_ListTest__test_render_with_no_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_hide_endtime__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php, tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php, tests/views_widgets/Tribe/Events/Views/V2/Widgets/__snapshots__/Widget_ListTest__test_render_empty__1.php
[FBAR-333]
[FBAR-336](https://stellarwp.atlassian.net/browse/FBAR-336)
This PR is to address when there are no results returned from a FilterBar search, previously the alert was not being read by screen readers and not accessible by tabbing through elements on the page. 
https://github.com/user-attachments/assets/f320f5ce-0d01-4694-abff-e6990ee269e2
[FBAR-333]: https://stellarwp.atlassian.net/browse/FBAR-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FBAR-336]: https://stellarwp.atlassian.net/browse/FBAR-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FBAR-333 Tweaks to user-facing messages to improve accessibility

composer.json
I believe this is the key to adjusting the order (but I'm not entirely sure). The `Fix` type should appear above `Tweak`.
=> Ensure that Fix appears before Tweak in changelogs

src/views/v2/widgets/widget-events-list/event/date-tag.php
Summary: 
This edit fixes a typo to the template override path in the comment block. 
Backstory:
I noticed while I was upgrading a site to new V2 templates that the path suggested for the template override was not overriding. I tested changing the file name from `venue.php` to `date-tag.php` and it worked in overriding. I believe this possibly was a typo.
=> Fix path in doc comment

changelog/fix-ensure-ajax-complete-is-fired-after-ajax, src/resources/js/views/manager.js
[FBAR-344]
Ensures ajax complete is fired after AJAX has actually completed. Watch the loom, the issue is being explained there.
https://www.loom.com/share/5ed8a4fec1254746a4b3312c517c407f
[FBAR-344]: https://stellarwp.atlassian.net/browse/FBAR-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure ajax complete is fired after ajax

changelog/fix-delete-custom-tables-only-for-events, src/Events/Custom_Tables/V1/Updates/Controller.php, tests/ct1_integration/TEC/Events/Custom_Tables/V1/Updates/ControllerTest.php
[TEC-5445]
`delete_custom_tables_data` should be called only for events! During darkhawk work it ended up being called for attachment deletion during plugin update causing a fatal.
Test case is artifact enough to serve as artifact here.
[TEC-5445]: https://stellarwp.atlassian.net/browse/TEC-5445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensures delete custom tables is called only for events

src/Events/Classy/Controller.php
Related to [TEC-5416]
Updates `Classy\Controller::unregister()` to also remove the back-compat registrations from the container.
[TEC-5416]: https://stellarwp.atlassian.net/browse/TEC-5416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove back-compat classes upon Classy unregistration

changelog/fix-prevent-fatal-during-upgrade, src/Events/Custom_Tables/V1/Models/Builder.php, src/Events/Custom_Tables/V1/Models/Model.php, src/Tribe/Main.php
[TEC-5445]
Prevents fatal during update to dartkhawk.
The register_on_action will not prevent the fatal now - but it is used as a safeguard for the future.
What is happening during an upgrade request is that CT1 hooks are registered without the common having loaded yet. As a result functions or singleton bound during common's loading are not available.
The hooks are registered by rpevious version of TEC during upgrade.
But during upgrade all the classes that are being called by the hooks down the road are not in memory - so they are being loaded by the new TEC's zip... aka 💥 
This PR amends to make those hooks fired not fatal out for that single problematic request.
[TEC-5445]: https://stellarwp.atlassian.net/browse/TEC-5445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
=> Prevents fatal during update while ECP is also active

src/Events/QR/Shortcode.php, src/Tribe/Views/V2/Widgets/Widget_QR_Code.php, src/admin-views/settings/tabs/display/display-qr-codes.php, tests/integration/Tribe/Events/Integrations/QR/ShortcodeTest.php
[TEC-5396]
Fixing [QA reported issues](https://docs.google.com/spreadsheets/d/1NzXAjMpzE7Cum9rOix2ctIjEsdpR_YgFLLMKvnGtzkk/edit?gid=2103530230#gid=2103530230). This PR fixes:
- validates the default `id` argument of the shortcode, so it can use the fallback from the settings
- shows a notice when our Events/Series dropdowns are empty
[TEC-5396]: https://stellarwp.atlassian.net/browse/TEC-5396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> QA fixes for QR code

changelog/fix-FBAR-332-focus-on-results-of-filter, src/resources/js/views/manager.js, src/views/v2/list.php, tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - cats__0.snapshot.html, tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - no cats__0.snapshot.html, tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags - no cats__0.snapshot.html, tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags and cats__0.snapshot.html, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php, tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
[FBAR-332]
When a user selects a filter option, the page refreshes and displays the search results. However, the focus is directed to the top of the filters rather than to the number of results or the first event in the list, which may be confusing for users. 
This change should immediately set the focus to the results of the filtering or the 'No events found' message. 
https://drive.google.com/file/d/1WV_x7bZk3yGn-2nezoY0hfg-LJR50Fov/view?usp=drive_link
[FBAR-332]: https://stellarwp.atlassian.net/browse/FBAR-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FBAR-332 Move focus to results after filtering

package-lock.json, package.json, src/resources/packages/classy/elements/Classy.tsx, src/resources/packages/classy/elements/components/Provider.tsx, src/resources/packages/classy/elements/fields/EventTitle.tsx, src/resources/packages/classy/functions/classy.ts, src/resources/packages/classy/index.ts, src/resources/packages/classy/store/index.ts, src/resources/packages/classy/store/registry.ts, src/resources/packages/classy/store/registry/index.ts, src/resources/packages/classy/store/registry/registry.ts, src/resources/packages/classy/store/registry/with-registry-provider.tsx, src/resources/packages/classy/store/store.ts
This work starts the update of the Classy application to use a
dedicated registry, separate from the WordPress Block Editor one.
Why?
Since the application must work in the Block Editor context, and outside
of it, it cannot rely on the WordPress Core stores being present and
initialized on the page.
The app is using components (e.g. the `PostFeaturedImage` one) that have
hard-codeded dependencies on the Core stores (e.g. the `core` and the
`core/editor` stores); to intercept those dependencies, the only option
I could find is to create a new registry and, in that, re-route the
request to the correct core store in the core registry, if available.
At this stage the components render without crashing, but the featured
image one will not update correctly.
Tests will need update too to use a …
=> refactor(Classy) scaffold dedicated registry

changelog/fix-no-telemetry-modal-on-wizard-page, src/Events/Admin/Onboarding/Controller.php, src/Events/Admin/Onboarding/Landing_Page.php, src/Events/Telemetry/Telemetry.php, src/resources/packages/wizard/index.tsx
[ET-2380]
This stops the Telemetry modal from showing on the Onboarding page - any opt-in here should be handled by the wizard.
Also:
- Switch to React 18 render method.
- Change constant we're using to dismiss the page. (the value doesn't change, just the constant name)
Not adding a screenshot because can't prove this negative that way.
[ET-2380]: https://stellarwp.atlassian.net/browse/ET-2380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Hide telemetry modal on wizard page.

src/Tribe/Views/V2/Widgets/Widget_QR_Code.php
Bug found during regression test of release/T25.ego
We fix this notice:
`PHP Notice:  Undefined index: event_id in /.../wp-content/plugins/the-events-calendar/src/Tribe/Views/V2/Widgets/Widget_QR_Code.php on line 193`
`PHP Notice:  Undefined index: series_id in /.../wp-content/plugins/the-events-calendar/src/Tribe/Views/V2/Widgets/Widget_QR_Code.php on line 194`
=> Fix notice about undefined index

changelog/fix-TEC-3424-change-div-to-section, src/views/v2/day.php, src/views/v2/list.php, src/views/v2/month.php, tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - cats__0.snapshot.html, tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - no cats__0.snapshot.html, tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags - no cats__0.snapshot.html, tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags and cats__0.snapshot.html, tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_hide_endtime__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php, tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
[TEC-3424]
This is an alternative solution to [this PR](https://github.com/the-events-calendar/the-events-calendar/pull/5093). 
For better accessibility, the document should not have more than one banner landmark. The banner landmark is implicitly added to `<header>` tags, which is causing this to get flagged in our plugins. 
This PR adjusts the `tribe-common-l-container tribe-events-l-container` wrapper `<div>` to a `<section>` to semantically describe the contents of the page and fix the flag for multiple banner landmarks. 
https://drive.google.com/file/d/1gy0lk3_1JJQKwfhxQBarhA1cOOxEKpOc/view?usp=sharing 
[TEC-3424]: https://stellarwp.atlassian.net/browse/TEC-3424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-3424 Change div to section for TEC views

changelog/fix-make-ece-callbacks-not-strict, src/Events/Calendar_Embeds/Admin/List_Page.php, src/Events/Calendar_Embeds/Admin/Singular_Page.php, src/Events/Calendar_Embeds/Calendar_Embeds.php
[TEC-5484]
Making callbacks hooked tp WP-core hooks, in the ECE feature less strict on the expected arguments.
As a result fixing possible fatal errors when the arguments are not of the expected type.
[TEC-5484]: https://stellarwp.atlassian.net/browse/TEC-5484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix too strict ECE callbacks

phpcs.xml
[TICKET_ID]
Fix PHPCS errors for the `bin/source-updater/` directory by excluding that directory from PHPCS entirely.
[skip-changelog]
=> Exclude bin/source-updater files from PHPCS

changelog/fix-text-domain-path, the-events-calendar.php
This allows WP JIT translations to find our files in the `plugins/lang` directory.
[TEC-5520]
Languages without language packs (like Suomi/Finnish) don't have language packs. Those need to get the files in `plugin/lang` but the JIT language engine can't find them because it doesn't default to the `/lang` folder for some strange reason. 
[TEC-5520]: https://stellarwp.atlassian.net/browse/TEC-5520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add missing Domain Path to the plugin file header.

changelog/fix-build, package-lock.json, webpack.config.js
Ticket: [TCMN-188]
Requires: https://github.com/the-events-calendar/tribe-common/pull/2619
Before:
After:
[TCMN-188]: https://stellarwp.atlassian.net/browse/TCMN-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update to properly use svg-inline in our build process

src/resources/packages/classy/fields/EventCost/CurrencySelector.tsx
[TICKET_ID]
This fixes the Currency Position save/display for the Classy editor.
Notable changes:
* Add a `CurrencyPosition` type instead of hardcoding strings
* Update how the currency position is saved to ensure we save the actual set value rather than the default for the currency selected
* Use `prefix` and `postfix` for the settings instead of `before` and `after`.
**Before:**
The currency symbol always shows after the currency, regardless of the settings in the event.
**After:**
The currency symbol is in the correct place based on the event settings.
=> (Classy) Fix currency position saving

src/Events/Category_Colors/Migration/Controller.php
Victor uncovered a fatal when updating the plugin before running category color migrations. This was due to changing a method name last minute.
=> Updated method name to new one.

src/resources/js/views/category-color-selector.js, src/views/v2/components/top-bar/category-color-picker.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/Category_Color_PickerTest.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_day_view__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_day_view_superpowers_disabled__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_day_view_superpowers_enabled__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_list_view__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_list_view_superpowers_disabled__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_list_view_superpowers_enabled__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_month_view__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_month_view_superpowers_disabled__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_month_view_superpowers_enabled__1.php
DQA - 
- 52 - When superpowers are disabled the category colors legend isn't populated.
- 53 - When superpowers are disabled the label for the dropdown doesn't make sense.
To fix this issue I moved the data-category attribute to the label since that is always rendered. I updated the JS accordingly.
For the label, when the superpowers are disabled we show different text.
=> Category Colors - Legend Superpowers logic

src/Events/Custom_Tables/V1/Integrations/ACF/Query_Modifier.php, tests/views_integration/Tribe/Events/Views/V2/Repository/Event_Period_Test.php
These are from someone's malformed docblock template - they need to go.
Requires: https://github.com/the-events-calendar/tribe-common/pull/2637
=> Remove ${CARET} from docblocks.

src/resources/packages/classy/fields/EventAdmission/EventAdmission.tsx, src/resources/packages/classy/fields/EventDateTime/EventDateTime.tsx, src/resources/packages/classy/fields/EventLocation/EventLocation.tsx, src/resources/packages/classy/store/reducer.ts, src/resources/packages/classy/store/selectors.ts, src/resources/packages/classy/types/Store.d.ts, src/resources/packages/classy/types/StoreState.d.ts
This PR updates the types defined for the TEC Classy store to provide the `StoreSelect` and `StoreDispatch` types similarly to what is done in the Common Classy package.
=> Classy - rework store types

src/Events/Classy/Controller.php, src/Events/Classy/Meta.php, src/resources/packages/classy/constants.tsx, src/resources/packages/classy/fields/EventCost/EventCost.tsx, tests/classy_integration/Meta_Test.php, tests/classy_jest/fields/EventCost/EventCost.spec.tsx, tests/classy_jest/fields/EventCost/__snapshots__/EventCost.spec.tsx.snap, tests/classy_jest/functions/renderFields.spec.tsx
* Fixed an issue where setting offset timezones i.e `UTC+6` were not updating the date UTC value and hence not showing the Event in FE.
* Fixed saving `Free` value on toggle properly for Event Cost block.
* Removed redundant `update_cost` method, the cost value is properly updated with REST already.
* Switched to handling `-` instead of `,`  for cost range to keep backwards compatibility.
* Updated tests for JEST and integration.
🎥 screencast(s): https://www.loom.com/share/909def4a61524c2ea8130f803e34f1c2
=> Add support for manual offset and fix Event cost block.

src/Tribe/Admin/Event_Meta_Box.php, tests/classy_integration/Tribe/Events/Admin/Event_Meta_Box_Test.php, tests/integration/Tribe/Events/Admin/Event_Meta_Box_Test.php
This adds a check on the method that would remove the `custom-fields` support from the Events post type if not using the Block Editor to keep it when using Classy.  
The `custom-fields` support is required to correctly process Event meta updates during saves in new installations.
**Issue**
When saving data through the REST API (as the Block Editor and Classy do), meta fields must be registered using the `register_post_meta` function (already handled in the `Classy\Meta` controller) ...
... And the post type must support `custom-fields`.
By default, the `Tribe__Events__Main::registerPostType` method already registers the Event post type with `custom-fields` support.
To avoid custom fields, enabled by the `custom-fields` support, to show uncontrolled to the user in the context of the …
=> Classy - fix issue 20

src/Events/REST/TEC/V1/Endpoints/Event.php, src/Events/REST/TEC/V1/Endpoints/Events.php, src/Events/REST/TEC/V1/Endpoints/Organizer.php, src/Events/REST/TEC/V1/Endpoints/Venue.php, src/Events/REST/TEC/V1/Traits/With_Transform_Organizers_And_Venues.php, src/Tribe/Linked_Posts.php, src/Tribe/Repositories/Event.php, src/functions/template-tags/venue.php, tests/wpunit/Tribe/Events/ORM/Events/UpdateTest.php
These commits fix the issue where multiple venues were being filtered to only the first venue when passed through the REST API or not being assigned at all.
**Requires:** https://github.com/the-events-calendar/tribe-common/pull/2694
- Modified With_Transform_Organizers_And_Venues trait to check the
venue linked post type's 'allow_multiple' setting before deciding
whether to use all venues or just the first one
- When Events Pro is active and multiple venues are allowed, the full
venues array is now preserved instead of being truncated
- Fixed missing return statement in filter_by_cost_less_than method
- Removed debug error_log statements from Event repository
- Fixed inconsistent return statements in cost filter methods
- Removed redundant transform_input_params calls from Event and …
=> Fix multiple venue support in REST API and ORM

src/resources/packages/classy/fields/EventAdmission/EventAdmission.tsx, src/resources/packages/classy/fields/EventDateTime/EventDateTime.tsx
* Updated StartSelector to always show all time options and not be limited by end time.
Screencast: https://share.cleanshot.com/tjyjGCJC
=> Fix - Start Time picker should show all options.

docs/REST/TEC/V1/creating-endpoints.md, docs/REST/TEC/V1/definitions.md, src/Events/REST/TEC/V1/Endpoints/Event.php, src/Events/REST/TEC/V1/Endpoints/Events.php, src/Events/REST/TEC/V1/Endpoints/Organizer.php, src/Events/REST/TEC/V1/Endpoints/Organizers.php, src/Events/REST/TEC/V1/Endpoints/Venue.php, src/Events/REST/TEC/V1/Endpoints/Venues.php
No ticket ID found
This PR applies code review suggestions by renaming methods from `*_args()` to `*_params()` throughout the TEC REST API v1 endpoints for consistency and clarity.
**Type of changes:** Code improvement (non-breaking change which improves code clarity and consistency)
**Changes made:**
- Updated all REST API endpoint classes to use `*_params()` method naming instead of `*_args()`
- Affected endpoints: Events, Event, Venues, Venue, Organizers, Organizer
- Updated corresponding documentation to reflect the method name changes
- Updated filter names to maintain consistency (`tec_events_rest_v1_events_read_params`, `tec_events_rest_v1_venues_read_params`)
**Files changed:**
- `src/Events/REST/TEC/V1/Endpoints/Event.php`
- `src/Events/REST/TEC/V1/Endpoints/Events.php` 
- …
=> tweak: rename parameter to argument

changelog/fix-TEC-4242-no-subscribe-on-mobile-js, src/resources/postcss/components/skeleton/_ical-link.pcss, src/views/blocks/parts/subscribe-list.php, src/views/v2/components/subscribe-links/item.php, tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_no_custom_classes__1.php, tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_with_multiple_custom_classes__1.php, tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_with_single_custom_class__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_single_with_all__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_all__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_gcal_only__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_ical_only__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_icalendar_export_only__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_hide_endtime__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php, tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
[TEC-4242]
Choosing Subscribe to calendar > Google Calendar on a calendar page does not work on Android phones, simply because it is not properly supported. The case is similar when choosing iCalendar.
So, we decided to hide those options on the calendar pages entirely and create a KB article about the why's.
The links work on single event pages, so there is no change there.
The part in TEC adds the necessary CSS selectors and rules.
The PR for Common: [link](https://github.com/the-events-calendar/tribe-common/pull/2742)
[Screen recording](https://docs.google.com/videos/d/16fXO6t7mP3QJw-XNjJQ9jQ_bPxkMHl1boNsJCJL5Nk0/edit?usp=sharing)
[TEC-4242]: https://stellarwp.atlassian.net/browse/TEC-4242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-4242 no subscribe on mobile js

src/resources/packages/wizard/index.css
[TEC-5579]
Quick follow up to a recently merged PR to remove unnecessary padding and the shadow-box from some dropdown options in the onboarding wizard. 
No changelog is needed since this is to tweak a PR recently merged with a changelog. 
Before: 
After:
[TEC-5579]: https://stellarwp.atlassian.net/browse/TEC-5579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-5579 Remove padding from dropdown

src/resources/js/events-admin.js
[CE-278] 
Tweaked the code again, when Romine tested there was a specific scenario that would cause the datepicker to be fully destroyed and the field would lose the mask.
https://github.com/user-attachments/assets/08ae91a7-4da5-481e-8dba-35c1b2268b2f
[skip-changelog]
[CE-278]: https://stellarwp.atlassian.net/browse/CE-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CE-278] Close on escape

changelog/fix-missing-map-option-TEC-5092, src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php, tests/elementor_integration/Widgets/Controls/Events_VenueTest.php
[TEC-5092]
* Fixed showing the Map option by removing an invalid condition.
* Fixed the condition to show the map style option properly.
* Added tests coverage to validate added control settings.
🎥 screencast: https://share.cleanshot.com/8NwkDvH6
[TEC-5092]: https://stellarwp.atlassian.net/browse/TEC-5092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix - Elementor starter template missing map show or hide option.

src/Events/Integrations/Plugins/Elementor/Template/Controller.php, tests/elementor_integration/ControllerTest.php
While testing, Victor received a fatal 
```
PHP Fatal error:  Uncaught TypeError: Return value of TEC\Events\Integrations\Plugins\Elementor\Template\Controller::filter_events_template_setting_option() must be of the type string, null returned in /.../wp-content/plugins/the-events-calendar/src/Events/Integrations/Plugins/Elementor/Template/Controller.php:124
Stack trace:
#0 /.../wp-includes/class-wp-hook.php(326): TEC\Events\Integrations\Plugins\Elementor\Template\Controller->filter_events_template_setting_option(NULL)
#1 /.../wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)
#2 /.../wp-content/plugins/the-events-calendar/common/src/functions/template-tags/general.php(57): apply_filters('tribe_get_optio...', NULL, 'tribeEventsTemp...', 'default')
#3 …
```
=> Cast return as string.
