the-events-calendar/the-events-calendar

readme.txt, src/views/month/loop-grid.php
Bump views version, set new release date
=> Bump `views` version, change release date

src/Tribe/REST/V1/Post_Repository.php
Ticket: https://central.tri.be/issues/108022
Based on: https://github.com/moderntribe/tribe-common/pull/716
=> Refactor REST API code to be reused in ET REST API

readme.txt, src/functions/template-tags/general.php
https://central.tri.be/issues/64807
=> Add event ID parameter to tribe_events_event_classes filter

readme.txt
=> Fix grammatical error (thanks to @The_UCF for highlighting this!) | spotfix

src/Tribe/Main.php
=> Bump Version for QA

src/Tribe/REST/V1/Endpoints/Single_Event.php, src/Tribe/REST/V1/Validator/Base.php
https://central.tri.be/issues/109482
=> Allow venue and organizer fields to be intentionally empty on Event Singular REST API calls (RER)

src/Tribe/Linked_Posts.php, src/Tribe/REST/V1/Endpoints/Linked_Post_Base.php, src/Tribe/REST/V1/Endpoints/Single_Event.php, src/functions/template-tags/organizer.php, tests/restv1/EventUpdateCest.php
https://central.tri.be/issues/109482
=> Don't filter $postarr for updateEvent (RER)

src/Tribe/REST/V1/Endpoints/Single_Event.php, src/Tribe/REST/V1/Endpoints/Single_Organizer.php, tests/restv1/EventUpdateCest.php, tests/restv1/OrganizerUpdateCest.php
https://central.tri.be/issues/109482
Further addresses work done in #2077 and makes it work for REST API (testing was done on series, but did not address the full issue).
=> Don't filter $postarr for updateEvent

readme.txt, src/Tribe/Aggregator/CLI/Command.php
https://central.tri.be/issues/108027
=> Add support for feature_event column to the CLI importer

src/Tribe/Aggregator/CLI/Command.php
QA repairs for https://central.tri.be/issues/108027
Changelog entry already in place  from prev PR https://github.com/moderntribe/the-events-calendar/pull/2070
=> WP CLI CSV import add support for feature events - QA repair

readme.txt, src/Tribe/Main.php, src/Tribe/Privacy.php, src/admin-views/privacy.php
🎫 https://central.tri.be/issues/108454
=> Add privacy policy guide for TEC.

src/admin-views/privacy.php
🎫 https://central.tri.be/issues/108454
=> Privacy Policy: Modify template to pick strings added to clipboard.

package-lock.json, package.json, readme.txt, src/Tribe/API.php, src/Tribe/Privacy.php, src/Tribe/REST/V1/Validator/Base.php, src/functions/template-tags/general.php, tests/wpunit/Tribe/Events/TimezonesTest.php, the-events-calendar.php
✔️ Bump version number
✔️ Checked views.
✔️ Replace TBD with the new version number
=> Bump version number

src/Tribe/Aggregator/Processes/Import_Events.php
Ticket: #109833
This PR just adds a log entry when an error happens during the EA import.
http://p.tri.be/QWcSCY
=> Add log functionality when errors occur in EA import

readme.txt, src/Tribe/Aggregator/Record/Abstract.php
Ticket: https://central.tri.be/issues/109938
=> Fire an action when imports are finalized

readme.txt, src/Tribe/Integrations/WPML/Meta.php, src/Tribe/Integrations/WPML/WPML.php, tests/aggregatorv1.suite.dist.yml, tests/restv1.suite.dist.yml
🎫 https://central.tri.be/issues/106798
Bringing back the WPML contribution from PR #1908, with some tweaks to avoid errors and malfunctioning.
=> Added WPML metadata improvements for Organizers and Venue.

src/Tribe/Linked_Posts.php, src/Tribe/Organizer.php
https://central.tri.be/issues/105116#note-37
=> Fix tribe_get_linked_posts_by_post_type() ordering

src/Tribe/REST/V1/Endpoints/Single_Event.php
https://central.tri.be/issues/109627
Fixes a bug introduced by the original PR for this ticket.
=> Fix tax_input usage

src/Tribe/Linked_Posts.php
Per QA from https://central.tri.be/issues/105116
=> Fix returning all posts if none assigned

src/Tribe/Assets.php
🎫 https://central.tri.be/issues/40267
=> Assets: Remove js dependency from css enqueueing

package.json, readme.txt, src/Tribe/Main.php, the-events-calendar.php
_Ref:_ [C#110463](https://central.tri.be/issues/110463)
=> #110463 - add change log for 2 community prs and update version numbers.

src/Tribe/Assets.php
🎫 https://central.tri.be/issues/40267
Change the priority of the mobile styles in order to make it work with PRO styles
=> Assets QA fixes

readme.txt, src/Tribe/Main.php
_Ref:_ [C#110463](https://central.tri.be/issues/110463)
=> #110463 - change filter to action for template_redirect

readme.txt, src/Tribe/Aggregator/Record/Abstract.php, src/Tribe/Aggregator/Record/Async_Queue.php, tests/_support/Factories/Aggregator/V1/Import_Record.php, tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php
ticket: https://central.tri.be/issues/96059
Screencast: http://p.tri.be/2a9gff
This PR adds tests and code to make sure that iCal (and ICS file) imports will correctly import the Organizer
=> Fix issue w/ ICS organizers not being imported

readme.txt
🎫 https://central.tri.be/issues/109618
=> M18.11 Update Release date

readme.txt
🎫 https://central.tri.be/issues/109618
=> Group changelog entries by type

readme.txt
🎫 https://central.tri.be/issues/109618
=> M18.11 Add deprecations to the changelog

readme.txt, src/Tribe/Query.php
_Ref:_ [C#70769](https://central.tri.be/issues/70769)
=> #70769 - setup future event display

readme.txt, src/Tribe/Query.php
_Ref:_ [C#70769](https://central.tri.be/issues/70769)
=> #70769 - add future event display

readme.txt, src/Tribe/Main.php
🎫 https://central.tri.be/issues/111672
=> Fix the classic header option not working

readme.txt, src/Tribe/Assets.php
🎫 https://central.tri.be/issues/112301
=> Fix for the "full styles" mobile view display

src/Tribe/Aggregator/Record/Queue_Realtime.php
_Ref:_ [C#112750](https://central.tri.be/issues/112750)
Fixes an issue introduced in 18.12, therefore, no changelog entry.
=> #112750 - fix queue progress from not completing

readme.txt, src/Tribe/Linked_Posts.php
🎫 https://central.tri.be/issues/113147
Move the filter to include other's venues
=> Add param to function.

readme.txt, src/Tribe/REST/V1/Endpoints/Single_Venue.php, tests/restv1/VenueUpdateCest.php
https://central.tri.be/issues/108834
=> Allow empty venue fields from REST updates

src/Tribe/Aggregator/Migrate.php, src/admin-views/tribe-options-addons-api.php
**Code Review Note:** No readme edits required here, as these changes are from QA feedback on the ticket.
**Ticket:** [**⌗112432**](http://central.tri.be/issues/112432)
=> ⌗112432 Remove Calls to Deprecated FB Functions; Fix Meetup API Fields

src/views/default-template.php
Spotfix - Corrected setting path in description
=> Spotfix - Corrected setting path in description

src/Tribe/Aggregator/Tabs/New.php, src/Tribe/Embedded_Maps.php, src/Tribe/Main.php, src/admin-views/aggregator/banners/eventbrite-upsell.php, src/admin-views/aggregator/status.php, src/functions/template-tags/general.php
_Ref:_ [C#86104](https://central.tri.be/issues/86104)
=> #86104 - change to use tribe_events_resource_url()

readme.txt, src/Tribe/Template_Factory.php
**Ticket:** [**⌗102643**](http://central.tri.be/issues/102643)
**Related PR:** https://github.com/moderntribe/event-tickets/pull/864
=> ⌗102643 Don't Show Event Meta if Password Required

readme.txt, src/Tribe/Aggregator/Cron.php
https://central.tri.be/issues/114555
=> Fix log_debug EA Cron fatal error

src/Tribe/Aggregator/Cron.php
https://central.tri.be/issues/114555
RER-specific PR
=> Fix log_debug fatal (RER)

readme.txt, src/Tribe/Gutenberg.php
https://central.tri.be/issues/114577
=> Fix Events Gutenberg extension install check

readme.txt, src/Tribe/Template/Month.php
Ticket: #114041
This PR supports the work done in the ticket by adding a filter to replace the Month view daily events queries.
=> Add filter for daily events in Month view

readme.txt, src/Tribe/List_Widget.php, src/admin-views/widget-admin-list.php
**Ticket:** [**⌗113541**](http://central.tri.be/issues/113541)
**Code Review Note:** Sorry for some whitespace cleanup/churn here.
=> ⌗113541 Ensure "Enable JSON-LD" Widget Option Can be Unchecked

readme.txt
https://central.tri.be/issues/79081
=> Add Other URLs as EA source to readme

src/Tribe/Google/Maps_API_Key.php
**Ticket:** [**⌗114442**](http://central.tri.be/issues/114442)
**Code Review Note:** No readme changes needed for this.
=> ⌗114442 Better Settings UI for Fallback Maps API Key

src/Tribe/Google/Maps_API_Key.php, src/Tribe/Main.php
**Ticket:** [**⌗114442**](http://central.tri.be/issues/114442)
**Code Review Note:** No readme changes are required here.
=> Spotfix: ⌗114442 Ensure Tooltip Shows Correct Label

src/Tribe/Aggregator/Cron.php, src/Tribe/Aggregator/Record/Unsupported.php, src/Tribe/Aggregator/Records.php, src/Tribe/Aggregator/Tabs/Abstract.php, tests/_support/Factories/Aggregator/V1/Import_Record.php, tests/_support/Traits/Aggregator/BatchDataMaker.php, tests/_support/Traits/Aggregator/RecordMaker.php, tests/aggregatorv1/Import/Batch/ForcedImportStatusCest.php, tests/aggregatorv1/Import/Batch/IntervalCest.php, tests/aggregatorv1/Import/Batch/ProcessingCest.php, tests/aggregatorv1/Import/Batch/ValidationCest.php, tests/wpunit/Tribe/Events/Aggregator/CronTest.php, tests/wpunit/Tribe/Events/Aggregator/Processes/Import_EventsTest.php, tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php, tests/wpunit/Tribe/Events/Aggregator/Record/ItemsTest.php, tests/wpunit/Tribe/Events/Aggregator/Record/UnsupportedTest.php, tests/wpunit/Tribe/Events/Aggregator/RecordsTest.php
https://central.tri.be/issues/115624
Merging fixes needed for this ticket.
=> Cherry pick fixes merged from M18.15 into M18.14.1

readme.txt, src/Tribe/Aggregator/Settings.php
https://central.tri.be/issues/115704
=> Add new tribe_aggregator_import_setting_origins filter for EA origins in default import settings

readme.txt, src/Tribe/Admin/Notice/Marketing.php
🎫 https://central.tri.be/issues/115543
=> Add gutenberg extension and eBook notice

src/admin-views/tribe-options-general.php
**Ticket:** [**⌗115399**](http://central.tri.be/issues/115399)
**Code Review Note:** No readme entry needed for this change 😎
=> Spotfix ⌗115399: More Descriptive Field Name for Maps Settings Title

readme.txt, src/Tribe/Aggregator/Record/Abstract.php
https://central.tri.be/issues/114171
=> Add geolocation hook to disable Geocoding of addresses by EA

src/Tribe/Aggregator/Service.php
**Ticket:** [**⌗116162**](http://central.tri.be/issues/116162)
**Code Review Note:** No readme tweaks needed for this.
=> Spotfix ⌗116162: Clear EA Transients When Appropriate

tests/_support/Factories/Fluent_Event.php
Ticket: https://central.tri.be/issues/115582
=> Support PRO ORM filters

src/Tribe/Repositories/Event.php, src/Tribe/Repositories/Linked_Posts.php, tests/wpunit/Tribe/Events/ORM/Events/FetchOtherFiltersTest.php
https://central.tri.be/issues/115581
=> Add other event filters

src/admin-views/aggregator/settings.php
**Ticket:** [**⌗114865**](http://central.tri.be/issues/114865)
**Code Review Note:** Readme entry already exists for this ticket; this was caught in QA.
=> M18.16 Spotfix: Remove Extra Google String

src/Tribe/REST/V1/Endpoints/Archive_Event.php, src/Tribe/REST/V1/Endpoints/Archive_Organizer.php, src/Tribe/REST/V1/Endpoints/Archive_Venue.php, src/Tribe/REST/V1/Post_Repository.php
https://central.tri.be/issues/117159
=> Cache REST API requests and Post Reposity objects

src/Tribe/Repositories/Event.php, tests/_support/Factories/Event.php, tests/wpunit/Tribe/Events/ORM/Events/DeleteTest.php, tests/wpunit/Tribe/Events/ORM/Events/UpdateTest.php
Ticket: https://central.tri.be/issues/114070
Based on: https://github.com/moderntribe/tribe-common/pull/802
This PR adds update/delete support to events and tests.
=> Add delete/update support to Events ORM

src/Tribe/Repositories/Event.php, tests/_support/Factories/Event.php, tests/wpunit/Tribe/Events/ORM/Events/CreateTest.php, tests/wpunit/Tribe/Events/ORM/Events/DeleteTest.php, tests/wpunit/Tribe/Events/ORM/Events/UpdateTest.php
Ticket: https://central.tri.be/issues/117165
Based on:
* https://github.com/moderntribe/tribe-common/pull/806
* https://github.com/moderntribe/the-events-calendar/pull/2232
* https://github.com/moderntribe/tribe-common/pull/802
=> Add support for event cretion, no PRO methods yet.

src/Tribe/Google/Maps_API_Key.php
**Ticket:** [**⌗115426**](http://central.tri.be/issues/115426)
**Code Review Note:** No readme entry is needed for this change.
=> ⌗115426 Spotfix: Improve API Key Settings Field Text

src/Tribe/Repositories/Event.php
Ticket: https://central.tri.be/issues/117165
Some smaller fixes I found out while working with it.
=> Add default ordering of event, remove timezone requirement.

src/Tribe/Repositories/Organizer.php, src/Tribe/Repositories/Venue.php, tests/wpunit/Tribe/Events/ORM/Organizers/CreateTest.php, tests/wpunit/Tribe/Events/ORM/Organizers/DeleteTest.php, tests/wpunit/Tribe/Events/ORM/Organizers/UpdateTest.php, tests/wpunit/Tribe/Events/ORM/Venues/CreateTest.php, tests/wpunit/Tribe/Events/ORM/Venues/DeleteTest.php, tests/wpunit/Tribe/Events/ORM/Venues/UpdateTest.php
https://central.tri.be/issues/114072
=> Add update field aliases for organizers and venues

src/modules/blocks/classic-event-details/event-details-organizers/template.js, src/modules/blocks/event-organizer/container.js, src/modules/blocks/event-price/container.js, src/modules/blocks/event-venue/container.js, src/modules/blocks/event-venue/template.js, src/modules/blocks/event-website/container.js, src/modules/data/details/reducers/details.js, src/modules/data/details/selectors.js, src/modules/data/details/thunks.js, src/modules/data/index.js, src/modules/data/search/reducers/search.js
Fix imports using direct files
=> Fix common imports

src/Tribe/Query.php
https://central.tri.be/issues/117962
=> Cache last_found_ids() and fix Tribe__Cache calls

src/Tribe/REST/V1/Post_Repository.php
https://central.tri.be/issues/117159
=> Cache should not cache per user at a per-post level

readme.txt, src/Tribe/Query.php, src/Tribe/REST/V1/Endpoints/Archive_Event.php, src/Tribe/REST/V1/Endpoints/Archive_Organizer.php, src/Tribe/REST/V1/Endpoints/Archive_Venue.php, src/Tribe/REST/V1/Post_Repository.php
https://central.tri.be/issues/117159
=>  Add REST API caching for archives and post repository

src/Tribe/Editor/Blocks/Event_Links.php
Ticket: https://central.tri.be/issues/118127
=> Fix error when the function does not exists

src/Tribe/REST/V1/Endpoints/Archive_Event.php, src/Tribe/REST/V1/Endpoints/Archive_Organizer.php, src/Tribe/REST/V1/Endpoints/Archive_Venue.php
https://central.tri.be/issues/117159
=> Handle errors in cached data

src/views/editor/blocks/event-venue.php
🎫 https://central.tri.be/issues/118268
=> Fix > Venue doesn't display in the front-end 

src/modules/blocks/classic-event-details/event-details-organizers/template.js
Ticket: https://central.tri.be/issues/114554
=> Fix undefined variable

src/modules/blocks/event-datetime/style.pcss
🎫 https://central.tri.be/issues/118125
=> Date & Time > enlarge clickable area

src/Tribe/Editor/Template/Overwrite.php, src/views/editor/single-event.php, src/views/single-event.php
Use old view for single events that were created with classic editor and use the new view structure for events that were created with blocks editor
Ticket: https://central.tri.be/issues/118491
=> Create views for classic and blocks editor

src/views/editor/blocks/classic-event-details.php, src/views/editor/blocks/event-datetime.php, src/views/editor/blocks/event-links.php, src/views/editor/blocks/event-tags.php, src/views/editor/blocks/parts/details.php, src/views/editor/blocks/parts/organizer.php
Update the name use on the text domain for strings that were part of the
extension
=> Use plugin text-domain instead of Extension

package.json, readme.txt, src/Tribe/Main.php, the-events-calendar.php
**Ticket:** [**⌗117507**](http://central.tri.be/issues/117507)
=> Final Merge of Nov 21 Hotfix into M18.17 Branch

readme.txt, src/Tribe/Query.php, src/Tribe/REST/V1/Endpoints/Archive_Event.php, src/Tribe/REST/V1/Endpoints/Archive_Organizer.php, src/Tribe/REST/V1/Endpoints/Archive_Venue.php, src/Tribe/REST/V1/Post_Repository.php
Ticket: https://central.tri.be/issues/114078
This is not the finished version of M18.17 but still it does contain a number of fixes the `bucket/orm` branch needs.
=> Merge current version of M18.17 into bucket/orm

src/modules/elements/month/element.js
Ticket: https://central.tri.be/issues/117612
Requires: https://github.com/moderntribe/tribe-common/pull/845
=> Remove styles from TEC in favor of common

readme.txt, src/Tribe/Google/Maps_API_Key.php, src/functions/template-tags/google-map.php
**Ticket:** [**⌗110008**](http://central.tri.be/issues/110008)
**Related PR:** https://github.com/moderntribe/events-pro/pull/1066
=> ⌗110008 Feature: Two Google Maps API Keys

src/Tribe/Editor/Compatibility.php, src/Tribe/Editor/Provider.php, src/Tribe/Main.php
_Ref:_ [C#117544](http://central.tri.be/issues/117544)
---
🎥  http://i.bordoni.me/cadb60840527
=> Deactivate Gutenberg Extension when The Events Calendar is active

package-lock.json, package.json, readme.txt, src/Tribe/Main.php, the-events-calendar.php
🎫 https://central.tri.be/issues/117666
=> Set release version number

src/Tribe/Main.php
When we are activating The Events Calendar and we have an outdated version of Common we need to make sure we are not triggering the activation hook of The Events Calendar, because it could lead into fatals due to older version of Common been loaded first.
The implementation here delays that Activation trigger to another request, so it can have the latest Common loaded via normal common-lib version comparing.
📹 http://i.bordoni.me/b9d029f2e388
=> Prevent loading of an Activation hook when outdate Common

readme.txt, src/Tribe/Editor/Configuration.php, src/modules/blocks/event-datetime/index.js, src/modules/blocks/event-datetime/subblocks/content/index.js, src/modules/data/blocks/datetime/thunks.js
🎫 https://central.tri.be/issues/ 118682
=> Make the date time block respect the timezone settings.

readme.txt, src/Tribe/Google/Maps_API_Key.php, src/functions/template-tags/google-map.php
Reverts moderntribe/the-events-calendar#2301
**Ticket:** [**⌗110008**](http://central.tri.be/issues/110008)
=> Revert "⌗110008 Feature: Two Google Maps API Keys"

src/Tribe/Editor/Configuration.php
Set the default values for start / end time on the TEC configuration
file
=> Add default values for "start/end" time

readme.txt, src/modules/blocks/event-price/style.pcss, src/modules/elements/dashboard/style.pcss
🎫 https://central.tri.be/issues/ 118683
=>  Fix > Price block dashboard issue

src/Tribe/Aggregator/Record/Abstract.php
quick fix found on activation test of 18.17
=> #117508 - fix stray backslash

src/modules/blocks/event-organizer/index.js, src/modules/data/blocks/venue/reducer.js
Ticket: https://central.tri.be/issues/118680
=> Set default values as they come from the REST API

readme.txt, src/Tribe/Main.php
_Ref:_ [C#119262](http://central.tri.be/issues/119262)
---
=> Make sure we update on Pro

readme.txt, src/modules/data/blocks/datetime/thunks.js
_Ref:_ [C#119337](http://central.tri.be/issues/119337)
---
=> Prevent Undefined Separator on Blocks editor

readme.txt, src/Tribe/Template_Factory.php, src/functions/template-tags/general.php
🎫 https://central.tri.be/issues/117385
=> Fix > Password protected event breaks month view

readme.txt, src/modules/elements/terms-list/element.js
🎫 https://central.tri.be/issues/119393
=> Fix the tags block delimiter

codeception.dist.yml, composer.json, composer.lock, src/Tribe/Query.php, tests/wpunit/Tribe/Events/TimezonesTest.php
https://central.tri.be/issues/114667
=> Allow event_start hack to be disabled by filter

readme.txt, src/Tribe/Main.php, src/admin-views/admin-welcome-message.php
**Ticket:** [**⌗117795**](http://central.tri.be/issues/117795)
**Code Review Note:** This replaces https://github.com/moderntribe/the-events-calendar/pull/2342/.
---
This PR is of a piece with these other two PRs:
* https://github.com/moderntribe/tribe-common/pull/890
* https://github.com/moderntribe/event-tickets/pull/1016
=> ⌗117795 TEC and ET Welcome Page Refreshes

src/admin-views/admin-welcome-message.php
**Ticket:** [**⌗117795**](http://central.tri.be/issues/117795)
=> M18.19 Spotfix — Change Help Desk Links

readme.txt, src/admin-views/admin-welcome-message.php
_Ref:_ [C#117795](http://central.tri.be/issues/117795)
---
=> Revert the new Welcome pages, they included external JS, not good for WP.org

src/Tribe/Main.php, src/Tribe/Repositories/Event.php
Tickets:
* https://central.tri.be/issues/117811
* https://central.tri.be/issues/114674
Based on https://github.com/moderntribe/tribe-common/pull/904
=> Add support for order in order_by method

src/admin-views/tribe-options-general.php
Clarifying that some settings only impact the classic editor.
=> Helper text update

src/modules/elements/terms-list/style.pcss, src/views/blocks/event-tags.php
🎫 https://central.tri.be/issues/119393
**Notes from QA:** Not related to this ticket but Nico asked to have the same title in the editor and the front-end. Plus, spacing between tags. We already have a readme entry for this one.
=> Tags Block > Consistent title and tags spacing in editor

readme.txt, src/Tribe/Editor/Meta.php
🎫 https://central.tri.be/issues/120399
The changes are blocking QA from doing their job. We're removing this and working in a separate branch, maybe punting it.
=> Revert #2371

readme.txt, src/resources/js/tribe-events.js
🎫 https://central.tri.be/issues/119271
=> Make sure the setting for "Default mobile view" is respected.

src/admin-views/admin-welcome-message.php
**Ticket:** [**⌗117795**](http://central.tri.be/issues/117795)
**Code Review Note:** No readme tweaks needed for this change.
=> Spotfix: Tweak Welcome Page's Support Label and URL

package-lock.json, package.json
Fixes ref to a branch that has been merged and throws an error on `npm install`
Will go look if needed in the FR branch as well.
=> Fix ref to non-existent branch

src/Tribe/Repositories/Event.php, src/Tribe/Template/Month.php, tests/wpunit/Tribe/Events/ORM/Events/FetchByDateTest.php
_Ref:_ [C#121632](http://central.tri.be/issues/121632)
---
=> Makes sure All Day Events show up

src/Tribe/Query.php, src/Tribe/Repositories/Event.php, src/Tribe/Template/Month.php
_Ref:_ [C#121846](http://central.tri.be/issues/121846)
---
=> Make sure we are passing in search params

readme.txt
_Ref:_ [C#121577](https://central.tri.be/issues/121577)
=> #122099 - fix spacing

readme.txt
_Ref:_ [C#121577](https://central.tri.be/issues/121577)
=> #121577 - removecommit hash

readme.txt, src/Tribe/Aggregator/API/Import.php, src/Tribe/Aggregator/Record/Abstract.php, src/admin-views/aggregator/settings.php, src/admin-views/aggregator/tabs/import-form.php
**Ticket:** [**⌗112346**](http://central.tri.be/issues/112346)
**Related PR:** https://github.com/moderntribe/events-eventbrite/pull/287
=> Add New "(do not override)" Eventbrite Import Status — ⌗112346

package.json, readme.txt, src/Tribe/Main.php, the-events-calendar.php
_Ref:_ [C#122368](https://central.tri.be/issues/122368)
=> #122368 - update common and change readme and version numbers

src/Tribe/Repositories/Event.php, src/Tribe/Template/Day.php
_Ref:_ [C#121868](http://central.tri.be/issues/121868)
---
=> Include a clause for properly finding Multi-day on date search

.travis.yml, composer.json
_Ref:_ [C#122388](http://central.tri.be/issues/122388)
---
=> Deactivate Aggregator tests until Rest Tests are realiable

src/Tribe/Aggregator/Record/Abstract.php, src/Tribe/Aggregator/Record/Eventbrite.php, src/Tribe/Aggregator/Records.php, src/admin-views/aggregator/origins/eventbrite.php
**Ticket:** [**⌗122747**](http://central.tri.be/issues/122747)
**Related PR:** https://github.com/moderntribe/events-eventbrite/pull/293
**Code Review Note:** No readme entry needed for this, already exists.
=> Move Some (do not override) Status Handling from EB Tickets to TEC — ⌗122747

src/Tribe/Aggregator/Record/Eventbrite.php
**Ticket:** [**⌗122747**](http://central.tri.be/issues/122747)
=> Spotfix: Make Methods Static — ⌗122747

.travis.yml, src/Tribe/Linked_Posts.php, src/Tribe/List_Widget.php, tests/restv1/EventInsertionCest.php, tests/restv1/EventUpdateCest.php
Tickets: 
* https://central.tri.be/issues/122071
* https://central.tri.be/issues/122068
This PR: 
* fixes an issue where the Events List widget would show all events, not just the upcoming ones.
* fixes an issue where the Events List widget would not correctly handle featured events
* disables `aggregatorv1` tests in CI due to a webserver issue
* fixes some RESTv1 tests issues I've found while running them locally
=> Fix list widget issues

readme.txt, src/Tribe/Main.php
_Ref:_ [C#121977](http://central.tri.be/issues/121977)
---
=> Add Image Widget Plus unload

src/admin-views/admin-welcome-message.php
**Ticket:** [**⌗121464**](http://central.tri.be/issues/121464)
=> Change H2s to H4s in Admin Welcome Message — ⌗121464

src/Tribe/Aggregator/Service.php
_Ref:_ [C#123383](http://central.tri.be/issues/123383)
---
=> When EA service fails, we shouldnt throw a notice with EBT

readme.txt, src/admin-views/aggregator/origins/refine.php, src/resources/js/aggregator-fields.js
_Ref:_ [C#121979](http://central.tri.be/issues/121979)
---
=> Eventbrite Ticket correct order and Required Started Date

readme.txt, src/Tribe/Admin/Notice/Timezones.php
_Ref:_ [C#123221](http://central.tri.be/issues/123221)
---
=>  Modify behavior for the UTC notice, resets 4 times a year

readme.txt, src/Tribe/Query.php, src/Tribe/Template/List.php, src/functions/template-tags/link.php, src/functions/template-tags/loop.php
_Ref:_ [C#123616](http://central.tri.be/issues/123616)
---
=> Improve sanitization on tribe_paged to avoid themes failing

src/Tribe/Query.php
_Ref:_ [C#123950](http://central.tri.be/issues/123950)
---
=> Use UTC for queries for all things

src/Tribe/Template/Day.php
_Ref:_ [C#124221](http://central.tri.be/issues/124221)
---
=> Totally forgotten param for searching on Day view ajax

readme.txt, tests/wpunit/Tribe/Events/JSON_LD/EventTest.php, tests/wpunit/Tribe/Events/JSON_LD/OrganizerTest.php, tests/wpunit/Tribe/Events/JSON_LD/VenueTest.php
🎫 https://central.tri.be/issues/123965
=> JSON_LD > Add tests

src/Tribe/Integrations/Freemius.php, src/Tribe/Integrations/Manager.php
Not sure what ticket to associate this with…
=> fix some Freemius fatals

src/Tribe/Template/List.php
Ticket: https://central.tri.be/issues/123950
Based on: https://github.com/moderntribe/tribe-common/pull/981
More info in the commits.
=> Fix List view AJAX hashing.

src/Tribe/Adjacent_Events.php, src/Tribe/Query.php
_Ref:_ [C#125795](http://central.tri.be/issues/125795)
---
=> Resolve SQL errors around ORM and direct modifications to SQL

src/Tribe/Integrations/Freemius.php
_Ref:_ [C#125929](http://central.tri.be/issues/125929)
---
=> Include Constant for Freemius loading

readme.txt
This PR contains the changelog entries review.
=> B19.04 Readme entries review

readme.txt, src/Tribe/Main.php, src/Tribe/Query.php, the-events-calendar.php
_Ref:_ [C#126124](http://central.tri.be/issues/126124)
---
=> Add backwards compatibility for Upcoming + Hide Recurrence

readme.txt, src/Tribe/Adjacent_Events.php
_Ref:_ [C#126144](http://central.tri.be/issues/126144)
---
=> Adjust Navigation usage of ORM

src/Tribe/Importer/File_Importer_Events.php, src/Tribe/Linked_Posts/Base.php, src/Tribe/Query.php, src/Tribe/Repositories/Event.php, src/Tribe/Template/List.php, src/functions/template-tags/organizer.php, src/functions/template-tags/venue.php, tests/wpunit/_bootstrap.php
_Ref:_ [C#126259](http://central.tri.be/issues/126259)
---
=> Make sure past events show correctly on views

src/Tribe/Query.php
_Ref:_ [C#126411](http://central.tri.be/issues/126411)
---
=> Add one more conditional for admin main query modifications

src/Tribe/Query.php
_Ref:_ [C#126448](http://central.tri.be/issues/126448)
---
=> Move the insertion to only Event Queries

readme.txt, src/Tribe/List_Widget.php
_Ref:_ [C#126837](http://central.tri.be/issues/126837)
---
=> List events Widget will display events until their end date has passed

readme.txt, src/Tribe/Query.php
_Ref:_ [C#126686](http://central.tri.be/issues/126686)
---
=> Include some more backwards compatibility for tribe_get_events

readme.txt, src/Tribe/Query.php
_Ref:_ [C#126790](http://central.tri.be/issues/126790)
---
=> Prevent main WP query to throw 404 when on Recurrence all page

src/Tribe/List_Widget.php, src/Tribe/Query.php
_Ref:_ [C#126790](http://central.tri.be/issues/126790)
---
=> Prevent notices around multiple Queries with `start_date`

.travis.yml, src/Tribe/Views/V2/Hooks.php, src/Tribe/Views/V2/Service_Provider.php, src/Tribe/Views/V2/Theme_Compatibility.php
🎫 https://central.tri.be/issues/127066
Add body classes for the themes we'll include compatibility.
=> VR > Add body classes for themes with compatibility

src/resources/postcss/views/_list.pcss, src/views/v2/list/event/title.php
🎫 https://central.tri.be/127066
=> VR > Theme compatibility

src/Tribe/Customizer/General_Theme.php
This was reported in a support thread. I can't reproduce the issue -
however, I can see where it could occur in the code, so, fixing.
#2471
=> Check for variable on Customizer

src/resources/postcss/views/_list.pcss
https://central.tri.be/issues/128344
=> set event contents left if image does not exist

src/Tribe/Rewrite.php, src/views/v2/index.php
_Ref:_ [C#128976](http://central.tri.be/issues/128976)
---
=> Use the correct logic for Rewrite depending on the version of common.

composer.lock, readme.txt, src/Tribe/Main.php, src/Tribe/Rewrite.php, the-events-calendar.php
_Ref:_ [C#129035](http://central.tri.be/issues/129035)
---
=> Removes the caching of get_bases() which was preventing external base

tests/views_integration/Tribe/Events/Views/V2/HTML/ListTest.php, tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/Event/ListEventDateTest.php, tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/Event/ListEventDescriptionTest.php, tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/Event/ListEventTitleTest.php, tests/views_integration/Tribe/Events/Views/V2/HTML/ListView/ListEventTest.php
🎫 https://central.tri.be/issues/129078
I was adding/fixing a couple for month, so I thought it would be a good moment to add some for List View as we haven't added those when we worked on the view.
=> VR > List View > Add tests

tests/features/front-end/list-view/event-display-order.feature
Scenario for events with different time zones
=> Event order in List View

tests/features/front-end/list-view/view-layout.feature
Details on how elements should display in List View - Venue and Excerpt
=> list-view/view-layout

src/Tribe/Views/V2/View.php, src/Tribe/Views/V2/Views/Day_View.php, src/resources/postcss/views/_all.pcss, src/resources/postcss/views/_day.pcss, src/views/v2/day.php, tests/views_integration/Tribe/Events/Views/V2/HTML/DayTest.php, tests/views_integration/Tribe/Events/Views/V2/Views/Day_ViewTest.php
🎫 https://central.tri.be/issues/129230
Init class, and add the basic required things to start working on top.
=> VR > Day View > Init class

tests/views_ui/_bootstrap.php
This resolves an issue with the views_ui tests where they continually failed.
=> Fix views ui tests

src/Tribe/Views/V2/View.php, src/resources/js/views/manager.js, src/views/v2/list.php, src/views/v2/month.php, src/views/v2/top-bar/today.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_base_template_if_view_has_no_template__1.php
_Ref:_ [C#127995](http://central.tri.be/issues/127995)
---
Depends #2556 https://github.com/moderntribe/events-pro/pull/1161
=> Views V2 shortcode support

src/Tribe/iCal.php
Ticket: https://central.tri.be/issues/89999
=> Remove references to `array_sort`

src/Tribe/REST/V1/Endpoints/Archive_Event.php
Ticket: https://central.tri.be/issues/129858
=> Add request argument into the filter

src/resources/postcss/components/_events-bar.pcss, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
🎫 https://central.tri.be/issues/129301
=> VR > Events Bar > Filters Button Styles

src/resources/postcss/components/_all.pcss, src/resources/postcss/components/_datepicker.pcss
🎫 https://central.tri.be/issues/129302
=> VR > Events Bar > Datepicker styles

readme.txt, src/Tribe/Featured_Events.php, src/Tribe/Template/Day.php, src/Tribe/Template/List.php, src/Tribe/Template/Month.php
_Ref:_ [C#127272](http://central.tri.be/issues/127272)
---
https://github.com/moderntribe/events-pro/pull/1178
=> Correct handling of Featured param for all views.

.travis.yml
_Ref:_ [C#131016](http://central.tri.be/issues/131016)
---
=> Correct URL replacement for submodules

tests/views_integration/Tribe/Events/Views/V2/Views/Day_ViewTest.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
_Ref:_ [C#130580](http://central.tri.be/issues/130580)
---
=> Add snapshot testing for day view data.

src/views/v2/month/calendar-body/day/calendar-events/calendar-event/title.php, src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip.php, src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/featured-image.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TitleTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Calendar_Events/__snapshots__/Calendar_EventTest__test_render_with_recurring_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/__snapshots__/Calendar_BodyTest__test_static_render__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php
Making it consistent with the changes we're making on tooltips for week view.
=> VR > Month > Tooltips

src/resources/postcss/components/_navigation.pcss, src/views/v2/day/time-separator.php, src/views/v2/list/month-separator.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
A couple tweaks MattCR asked last sprint.
=> VR > DQA refinements.

tests/views_integration/README.md
Add the first version of the `tests/views_integration/REDME.md` document for us to discuss.
I've called out each user expected to contribute to the doc in the file, push to this PR.
=> doc(tests/views_integration/README.md) add

src/resources/postcss/views/month/_calendar-event.pcss, src/resources/postcss/views/month/_mobile-events.pcss
🎫 https://central.tri.be/issues/131754
=> VR > Featured Events > Month View

readme.txt, src/resources/js/tribe-events-bar.js, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
🎫 https://central.tri.be/issues/125567
📹 https://www.loom.com/share/10bac7512e0f4216b9bca1d429e4641e
=> Fix > default view mobile loop

src/Tribe/Views/V2/Views/Month_View.php, src/resources/postcss/views/month/_day.pcss, src/views/v2/list/nav/next-disabled.php, src/views/v2/list/nav/next.php, src/views/v2/list/nav/prev-disabled.php, src/views/v2/list/nav/prev.php, src/views/v2/month/calendar-body/day.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/DayTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/__snapshots__/Calendar_BodyTest__test_static_render__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
🎫 https://central.tri.be/issues/133035
🎥 https://www.loom.com/share/1cbf2df2fb2541e6bd7291f95dc38a4c
- Add past day classes
- Add links to day date number when there are events.
- Add data attributes.
- Add a11y data.
- Add template var for day link.
- Fix `texdomain` for some templates.
=> VR > Month View > Dates should link to day view

src/views/v2/month/calendar-body/day.php, src/views/v2/month/calendar-body/day/more-events.php, tests/views_integration/Tribe/Events/Views/V2/HTML/MonthTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_BodyTest.php
_Ref:_ [C#133011](http://central.tri.be/issues/133011)
---
http://i.bordoni.me/ff90d8113a9f
=> More link using the manager + dayview link

src/Tribe/Views/V2/Views/Day_View.php
_Ref:_ [C#132681](http://central.tri.be/issues/132681)
---
http://i.bordoni.me/5b348fe82eda
=> Make the Previous day queries more consistent

src/Tribe/Views/V2/Views/Month_View.php
_Ref:_ [C#133006](http://central.tri.be/issues/133006)
---
http://i.bordoni.me/77c25b6ed6a2
=> Add logic to the Month view Previous and Next URL

src/functions/template-tags/event.php
_Ref:_ [C#133098](http://central.tri.be/issues/133098)
---
=> Use tribe_is_truthy to verify Meta values to allow other false/truthy

src/resources/postcss/views/month/_calendar-event.pcss, src/resources/postcss/views/month/_day.pcss, src/resources/postcss/views/month/_multiday-event.pcss, src/views/v2/month/calendar-body/day/multiday-events/multiday-event.php, tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthEventMultidayTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Calendar_Body/Day/Multiday_EventsTest.php
🎫 https://central.tri.be/issues/133035
🎥 https://www.loom.com/share/5af2f4c2710e4079ac649a44876a746e
=> VR > Month View > Past events

readme.txt, src/Tribe/Importer/File_Importer.php
Ticket: https://central.tri.be/issues/127132
Based on: https://github.com/moderntribe/tribe-common/pull/1123 
The work is pretty much all done in `common` and this PR only adds some logging.
That saved my life.
=> EA CSV Imports - fix thumbnail set

src/Tribe/Aggregator/Record/CSV.php
_Ref:_ [C#131510](http://central.tri.be/issues/131510)
---
=> Prevent notices when the Index are not set by default

src/resources/postcss/views/month/_mobile-events.pcss, src/views/v2/month/mobile-events/mobile-day/mobile-event/date.php, src/views/v2/month/mobile-events/mobile-day/mobile-event/title.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_recurring_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_recurring_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
🎫 https://central.tri.be/issues/133609
🎥 https://www.loom.com/share/22a488d2a1e8495c987951073212e173
=> VR > Alpha 3 DQA

src/Tribe/Views/V2/Template_Bootstrap.php
_Ref:_ [C#133425](http://central.tri.be/issues/133425) [C#133426](http://central.tri.be/issues/133426)
---
📹 http://i.bordoni.me/953c31c31027
=> Address problems with Single V1 compatibiltiy

src/resources/postcss/views/month/_day.pcss
https://central.tri.be/issues/133204
https://www.loom.com/share/b4b0fd7b01614bfd92abe96b6c2010d2
=> fix up styles for mobile icons for past events

src/resources/js/views/datepicker.js
https://central.tri.be/issues/134041
Incorrect behaviour:
https://www.loom.com/share/7b47fe6743f144adafe35a2276029351
Fixed behaviour:
https://www.loom.com/share/487cd92b0187404a97f71acc78e3608d
=> add touch event to handle mouse down

src/resources/postcss/views/month/_mobile-events.pcss
🎫 https://central.tri.be/issues/133609
🎥 https://www.loom.com/share/9595a50609a648f58e1d58ac03201774
=> VR > DQA - Featured icon on month mobile

src/views/v2/day/event.php, src/views/v2/day/event/date.php, src/views/v2/day/event/date/meta.php, src/views/v2/day/event/description.php, src/views/v2/day/event/featured-image.php, src/views/v2/day/event/title.php, src/views/v2/day/event/venue.php, src/views/v2/list/event.php, src/views/v2/list/event/date-tag.php, src/views/v2/list/event/date.php, src/views/v2/list/event/date/meta.php, src/views/v2/list/event/description.php, src/views/v2/list/event/featured-image.php, src/views/v2/list/event/title.php, src/views/v2/list/event/venue.php, src/views/v2/month/mobile-events/mobile-day/mobile-event.php, src/views/v2/month/mobile-events/mobile-day/mobile-event/cta.php, src/views/v2/month/mobile-events/mobile-day/mobile-event/date/meta.php, src/views/v2/month/mobile-events/mobile-day/mobile-event/featured-image.php
🎫 https://central.tri.be/issues/133424
🎥 https://www.loom.com/share/bac025bb5b8a4ffeb3d914a0a900ce5c
=> VR > Update docblocks with received vars

package-lock.json, package.json, src/Tribe/Models/Post_Types/Venue.php, src/Tribe/Venue.php, src/functions/template-tags/event.php, src/functions/template-tags/venue.php, src/resources/css/aggregator-page.css, src/resources/css/events-admin.css, src/resources/css/freemius.css, src/resources/css/tribe-events-full.css, src/resources/css/tribe-events-skeleton.css, src/resources/css/tribe-events-theme-mobile.css, src/resources/css/tribe-events-theme.css, tests/wpunit/functions/template-tags/venueTest.php
_Ref:_ [C#132725](http://central.tri.be/issues/132725) [C#132727](http://central.tri.be/issues/132727)
---
📹 http://i.bordoni.me/326845646be6
=> Use the model from tribe_get_event to create a tribe_get_venue_object

src/functions/template-tags/venue.php
_Ref:_ [C#134532](http://central.tri.be/issues/134532)
---
=> Revert change to tribe_get_venue_details() since we are no longer using it

src/Tribe/Views/V2/Hooks.php, src/Tribe/Views/V2/Template/Page.php
_Ref:_ [C#133426](http://central.tri.be/issues/133426)
---
Simple but a big mess to figure it out, since this interacts so much with our old Views for the Single page.
📹 http://i.bordoni.me/aac5e5375861
=> Only hijack on loop start once and only after main query has been flagged.

src/views/v2/month/mobile-events/mobile-day/mobile-event/date.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/DateTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/DateTest__test_render_with_featured_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_multiday_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_normal_and_multiday_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_multiday_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_found_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
🎫 https://central.tri.be/issues/134674
🎥 https://www.loom.com/share/15642220e2e64b298a88272ba63d141c
Adding the same we have in list view.
=> VR > Month > Mobile > Multiday events show dates

src/resources/postcss/views/month/_calendar-header.pcss, src/views/v2/month/calendar-header.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Calendar_HeaderTest__test_render__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
🎫 https://central.tri.be/issues/134672
🎥 https://www.loom.com/share/a8b653d42e244540b795d594d71472ca
=> VR > Month > Mobile month abbreviation.

src/views/blocks/event-organizer.php
Pls don't make me create a central ticket for this. Waste of time :)
=> Updated override URL in header

src/resources/postcss/views/_loader.pcss, src/views/v2/components/loader.php, tests/views_integration/Tribe/Events/Views/V2/HTML/LoaderTest.php, tests/views_integration/Tribe/Events/Views/V2/HTML/__snapshots__/LoaderTest__it_should_render__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/LoaderTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
🎫 https://central.tri.be/issues/135105
🎥 https://www.loom.com/share/e6518b7c3ef64688b4a86842aa8a8f66
=> VR > Loader

src/Tribe/Views/V2/Hooks.php, src/Tribe/Views/V2/Template/Excerpt.php, src/resources/postcss/components/_small-cta.pcss, src/views/v2/components/read-more.php
🎫 https://central.tri.be/issues/131088
🎥 https://www.loom.com/share/a81a41a0447247638decdd51a7ccc574
=> VR > Filter excerpt length for list and day views.

src/Tribe/Views/V2/View.php
_Ref:_ [C#135538](http://central.tri.be/issues/135538)
---
=> Add before and after actions for Making views.

src/Tribe/Views/V2/Messages.php, src/Tribe/Views/V2/View.php, src/Tribe/Views/V2/Views/Day_View.php, src/Tribe/Views/V2/Views/List_View.php, src/views/v2/day.php, tests/views_integration/Tribe/Events/Views/V2/Views/Day_ViewTest.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
Ticket: https://central.tri.be/issues/135478
Screencap: https://drive.google.com/open?id=10A78MIbXBMBjejR234nQQn-Z_GnoIQUI&authuser=luca@tri.be&usp=drive_fs
Final screencap: https://drive.google.com/open?id=10D7VDwZPjqDszXvCGTIQc-LkjGDInR6A&authuser=luca@tri.be&usp=drive_fs
This PR adds TEC suppor for Day View messages on the front-end.
=> VR - final No Events Found messages support

src/views/v2/day/event/venue.php, src/views/v2/list/event/venue.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/VenueTest__test_render_with_event_with_venue__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/VenueTest__test_render_with_event_without_venue__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/EventTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/EventTest__test_render_with_featured_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/VenueTest__test_render_with_event_with_venue__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/VenueTest__test_render_with_event_without_venue__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_featured_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
🎫 https://central.tri.be/issues/131086
🎥 https://www.loom.com/share/4c41026cdff348efa2f8fc5cb7adb326
=> VR > List View & Day View > Address Meta

src/views/v2/day/event/title.php, src/views/v2/list/event/title.php, src/views/v2/month/calendar-body/day/calendar-events/calendar-event/title.php, src/views/v2/month/mobile-events/mobile-day/mobile-event/title.php
🎫 https://central.tri.be/issues/136097
🎥 https://www.loom.com/share/f918e9c3fac94d2887b66c8f10f68eb5
=> VR > Allow HTML in title

src/Tribe/Views/V2/Assets.php, src/Tribe/Views/V2/Hooks.php
_Ref:_ [C#135366](http://central.tri.be/issues/135366)
---
📹 http://i.bordoni.me/844f3917e967
=> Remove all assets from V1, in the correct way for all uses.

src/Tribe/Views/V2/Assets.php
_Ref:_ [C#136196](http://central.tri.be/issues/136196)
---
=> Load full only when not on Skeleton settings

src/resources/postcss/components/full/_messages.pcss, src/resources/postcss/components/skeleton/_all.pcss, src/resources/postcss/components/skeleton/_messages.pcss
🎫 https://central.tri.be/issues/133311
🎥 https://www.loom.com/share/247cbf75511e427f80ae72d4e7dc5acd
=> VR > Messages > Skeleton & full

src/resources/postcss/views/full/day/_event.pcss, src/resources/postcss/views/full/list/_event.pcss, src/resources/postcss/views/full/month/_calendar-event.pcss, src/resources/postcss/views/full/month/_mobile-events.pcss
🎫 https://central.tri.be/issues/135356
🎥 https://www.loom.com/share/a07d0b88b4ad4443a6f16f47cf6a3e57
=> VR > Recurring events.

src/Tribe/Views/V2/Hooks.php, src/Tribe/Views/V2/Template_Bootstrap.php
🎫 https://central.tri.be/issues/134863
🎥 https://www.loom.com/share/3b71d00074b64f118982de472397dc1a
=> VR > Add compatibility for single and different themes.

src/resources/postcss/components/skeleton/_top-bar.pcss
https://central.tri.be/issues/136755
https://www.loom.com/share/2886cc16d2924f09a6dc3969bfd3398d
=> increase breakpoint for compact date format

src/Tribe/Views/V2/Manager.php, src/Tribe/Views/V2/Template_Bootstrap.php, tests/views_integration/Tribe/Events/Views/V2/TemplateBootstrapTest.php
Ticket: https://central.tri.be/issues/136631
Based on: https://github.com/moderntribe/the-events-calendar/pull/2810
[Screencap](https://drive.google.com/open?id=12rM91vpKrtcVk-CFlrb_ev-vYHoW5Tj7&authuser=luca@tri.be&usp=drive_fs)
=> VR - respect enabled views option

src/Tribe/Views/V2/Views/Month_View.php
Ticket: https://central.tri.be/issues/136622
Based on: https://github.com/moderntribe/tribe-common/pull/1200
This PR fixes an issue where the Month View would display the "Nothing found" message when filtering by location and that search would yield results. 
[Screencap](https://drive.google.com/open?id=12rQjXnpLgIKG27dpUbenhTUxTRDB2f6u&authuser=luca@tri.be&usp=drive_fs)
=> fix(Views/V2/Views/Month_View.php) correctly build messages

src/views/v2/month/calendar-body/day.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
🎫 https://central.tri.be/issues/136971
🎥 https://www.loom.com/share/2b3100a42cdc4376a5eaa31ae793c7c9
Fix `id` so it matches the  `aria-control`.
=> VR > Month Mobile > Fix tapping

tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/DayTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php
🎫 https://central.tri.be/issues/136971
=> VR > Month view mobile > Fix test

src/Tribe/Views/V2/Template_Bootstrap.php
🎫 https://central.tri.be/issues/137008
🎥 https://www.loom.com/share/34e3e5196b1d470791a8c8f852e4c630
Don't redirect if they're trying to access singular or taxonomy (event, organizer, venue).
=> VR > Fix mobile redirection.

src/resources/postcss/components/full/_breadcrumbs.pcss, src/resources/postcss/components/skeleton/_top-bar.pcss
🎫 https://central.tri.be/issues/137029
🎥 https://www.loom.com/share/7833c906748a4e1c9ea9788b2690315a
**Bonus** set font family for breadcrumbs to fix compatibility issues.
=> VR > Fix pagination arrows

src/Tribe/Views/V2/View.php, src/Tribe/Views/V2/View_Interface.php
Ticket: https://central.tri.be/issues/135490
This PR adds, during the View building, special care and handling for shortcodes.
This supports PRO pr: https://github.com/moderntribe/events-pro/pull/1305
📹 https://drive.google.com/file/d/1i2t14_3r73NAf4Kik0j09IZM9QwnKpBd/view
=> fix(Views v2) take shortcode into acount

src/Tribe/Views/V2/View.php
_Ref:_ [C#136977](http://central.tri.be/issues/136977)
---
📹 https://drive.google.com/file/d/14u1XF0tgnW41jMN0uBf3NOz5T1B6reHg/view
=> Remove a legacy todo and use get_query() again

src/Tribe/Views/V2/Hooks.php
_Ref:_ [C#132725](http://central.tri.be/issues/132725)  [C#136934](http://central.tri.be/issues/136934)
---
Changed how the filter actually is on shortcodes.
=> Change filter name for shortcode assets

readme.txt, src/modules/data/blocks/datetime/thunks.js
🎫 https://central.tri.be/issues/132735
🎥 https://www.loom.com/share/47be6e45983d419d9e8fe0f9d6914e89
=> Blocks Editor > Date time not working on edit.

src/Tribe/Views/V2/View.php
_Ref:_ [C#135490](http://central.tri.be/issues/135490)
---
I found a notice when visiting the Category archives while I was fixing Featured param on shortcodes. So these changes are to support those fixes.
📹 https://i.bordoni.me/4gu78LWj
=> Respect Featured params + Remove tax archive notice

src/Tribe/Views/V2/Manager.php, src/Tribe/Views/V2/View.php, src/resources/js/views/datepicker.js, src/resources/js/views/manager.js, src/views/v2/day.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_multiple_events_on_day__1.php
_Ref:_ [C#135490](http://central.tri.be/issues/135490)
---
📹 📹 📹 📹 📹 📹 
- List: https://i.bordoni.me/2NuAoPZy
- Month: https://i.bordoni.me/nOuW29bD
- Day: https://i.bordoni.me/v1uyqg4y
- Week: https://i.bordoni.me/L1uYERY4
- Photo: https://i.bordoni.me/NQue9NxX
- Map: https://i.bordoni.me/8LuZeDYm
=> Make Manager.js and Backend navigation more sturdy.

src/resources/js/views/manager.js
_Ref:_ [C#137312](http://central.tri.be/issues/137312)
---
📹 https://i.bordoni.me/yAu4RwmD
=> Support all browsers + better container selection for Navigation

src/Tribe/Editor/Meta.php
There are two problems that this PR fixes. One is silly. One is a result of a WP 5.3 change.
* Silly fix: The timestamps were H:I:s rather than H:i:s. The `I` is a boolean indicator of whether or not the date is on DST.
* WP 5.3 fix: With the block editor, WP 5.3 now submits _all_ fields during the REST call regardless of whether we wish to update those fields or not. This butchers our UTC fields that we had historically updated manually upon submission. This fix moves our datetime handling to a point _after_ WP does its thing with the data. Then we fix it.  # Please enter the commit message for your changes. Lines starting
:ticket: https://central.tri.be/issues/137421
:movie_camera: http://p.tri.be/K3Xnbw (9 minutes)
=> Prevent butchering of UTC dates on submission in the block editor

src/Tribe/Views/V2/Template/Title.php
_Ref:_ [C#137571](http://central.tri.be/issues/137571)
---
📹 https://i.bordoni.me/RBu0x7e8
=> On single event page we bail on Updating the title.

src/resources/postcss/views/skeleton/day/_event.pcss
🎫 https://central.tri.be/issues/137284
🎥 https://www.loom.com/share/68c771fee58640fb84efdec17fbf64dd
Add fix for twentynineteen on first event for day view.
=> VR > Day View > fix for twentynineteen

src/resources/postcss/views/full/day/_event.pcss, src/resources/postcss/views/full/list/_event.pcss
🎫 https://central.tri.be/issues/137451
🎥 https://www.loom.com/share/1632cf2edb4d466da6b8b500f28d0b4d
=> VR > Address not italic in list and day

src/views/v2/month/calendar-body/day/multiday-events/multiday-event.php
🎫 https://central.tri.be/issues/137619
🎥 https://www.loom.com/share/bd06352982c6408cbff0e1b5945f5d1e
Add post classes to the multiday/all-day events.
=> VR > Post classes in multiday/all day events.

src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/date.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/DateTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/DateTest__test_render_with_event_same_start_end_time__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/DateTest__test_render_with_featured_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_with_description_with_cost__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_with_description_without_cost__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_without_description_with_cost__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_with_featured_image_without_description_without_cost__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_with_description_with_cost__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_with_description_without_cost__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/__snapshots__/TooltipTest__test_render_with_event_without_featured_image_without_description_with_cost__1.php
🎫 https://central.tri.be/issues/137113
🎥 https://www.loom.com/share/77cf2adc940a4ef9b1c63ca3e870f1c9
Use full date instead of time in the tooltip.
=> VR > Tooltip full date

src/Tribe/Views/V2/Hooks.php
_Ref:_ [C#128241](http://central.tri.be/issues/128241)
---
https://i.bordoni.me/eDuLGxRn
=> Add the template changing to View V2

src/Tribe/Cost_Utils.php
_Ref:_ [C#136635](http://central.tri.be/issues/136635)
---
https://i.bordoni.me/QwuQNK7E
=> Make setting more reliable using tribe_is_truthy

src/Tribe/Service_Providers/Context.php, src/Tribe/Views/V2/View.php
_Ref:_ [C#135422](http://central.tri.be/issues/135422)
---
I've added the WP Matched Query since it was being reset on the `setup_the_loop`.
📹 https://i.bordoni.me/P8ulnX1D
=> Featured Archive Views V2

src/Tribe/Views/V2/Utils/Separators.php, src/views/v2/day/time-separator.php
_Ref:_ [C#137303](http://central.tri.be/issues/137303)
---
📹 https://i.bordoni.me/04ugbAJv
=> Round to the nearest 30 minutes not Hour

readme.txt, src/Tribe/Main.php, src/functions/utils/install.php
_Ref:_ [C#137510](http://central.tri.be/issues/137510)
---
📹 https://i.bordoni.me/4gux0RZl
=> Trigger smart activation on the correct location

src/Tribe/Views/V2/Views/Day_View.php
🎫 https://central.tri.be/issues/137365
🎥 https://www.loom.com/share/6d73780bcea64e629a311aa862a2f09d
=> VR > Day > Multiday on timed section if first appearance.

src/Tribe/Views/V2/Template.php, src/views/v2/day.php, src/views/v2/list.php, src/views/v2/list/event.php, src/views/v2/month/calendar-body/day/calendar-events.php, src/views/v2/month/calendar-body/day/multiday-events.php, src/views/v2/month/mobile-events/mobile-day.php
_Ref:_ [C#137977](http://central.tri.be/issues/137977)
---
=> Overwrite the global Post  using WP_Query::setup_postdata

src/resources/postcss/views/full/month/_calendar-event.pcss, src/resources/postcss/views/full/month/_day.pcss, src/resources/postcss/views/full/month/_multiday-event.pcss, src/resources/postcss/views/skeleton/month/_calendar-event.pcss, src/resources/postcss/views/skeleton/month/_multiday-event.pcss, src/views/v2/month/mobile-events/mobile-day/mobile-event/title.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/TitleTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/__snapshots__/Mobile_EventTest__test_render_with_featured_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_multiple_multiday_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_normal_and_multiday_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/Mobile_DayTest__test_render_with_one_multiday_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_found_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php
🎫 https://central.tri.be/issues/137523
🎥 https://www.loom.com/share/ca21cecb64994617ab667f20ff346834
=> VR > Month View > DQA

src/Tribe/Views/V2/Hooks.php, src/admin-views/tribe-options-general.php, tests/wpunit/Tribe/Events/ORM/Organizers/FetchTest.php
_Ref:_ [C#138045](http://central.tri.be/issues/138045)
---
=> V2 text added to live update tooltip

src/resources/js/views/tooltip.js
🎫 https://central.tri.be/issues/137523
🎥 https://www.loom.com/share/08dfa22aceeb4a27ae6e51cdf1d10788
=> VR > Orphaned tooltip

src/Tribe/Views/V2/Hooks.php
🎫 https://central.tri.be/issues/129761
🎥 https://www.loom.com/share/22673bbe5fa1476db67f7bfffc0cc147
=> VR > Flush permalinks on site language setting change

src/resources/postcss/views/skeleton/month/_multiday-event.pcss
🎫 https://central.tri.be/issues/137442
🎥 https://www.loom.com/share/c98689b183ff43a4bc8ab928052393de
=> VR > Month multiday hidden title in one line.

src/resources/postcss/components/skeleton/_tooltip.pcss
🎫 https://central.tri.be/issues/137400
🎥 https://www.loom.com/share/4cd6ca71a0224ff682e84ec6d7560b73
=> VR > Tooltip: break words and wrap overflow for really really really really really long words.

src/Tribe/Views/V2/Hooks.php
🎫 https://central.tri.be/issues/137651
🎥 https://www.loom.com/share/3e6093bcb04a4226ba18be0710de05b3
=> VR > Fix YOAST interfering with our titles.

src/Tribe/Customizer/Global_Elements.php, src/Tribe/Main.php
_Ref:_ [C#138125](http://central.tri.be/issues/138125)
---
📹 https://i.bordoni.me/5zuJ5ZG5
=> Remove required sections from Customizer code for V2 enabled sites

src/resources/postcss/base/skeleton/_layouts.pcss
https://central.tri.be/issues/137403
=> add min height to layout

src/Tribe/Views/V2/Template_Bootstrap.php
🎫 https://central.tri.be/issues/137370
🎥 https://www.loom.com/share/d6ed0c1039f04fbfa0b6bf3e8a728b3d
=> VR > Don't take over if 404

tests/views_integration/Tribe/Events/Views/V2/HTML/Month/CalendarEvent/MonthCalendarEventDateTest.php, tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthDayTest.php, tests/views_integration/Tribe/Events/Views/V2/HTML/Month/MonthEventMultidayTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/DatepickerTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/__snapshots__/DatepickerTest__test_render__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_Bar/__snapshots__/DatepickerTest__test_render_without_submit__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Top_BarTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/Top_BarTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/__snapshots__/Top_BarTest__test_render_without_submit__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_BarTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/Top_BarTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/Top_BarTest__test_render_without_submit__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/DatepickerTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/__snapshots__/DatepickerTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_Bar/__snapshots__/DatepickerTest__test_render_without_submit__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Top_BarTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Top_BarTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Top_BarTest__test_render_without_submit__1.php
🎫 https://central.tri.be/issues/133929
=> VR > Re-activate and fix tests.

src/Tribe/Views/V2/Assets.php
🎥 https://www.loom.com/share/a90160eeb90d4a49bed091f6ca7bdabb
=> VR > Include customization stylesheet.

src/Tribe/Views/V2/Template/Page.php, tests/_support/Factories/Event.php
This ports over the lines that are present in the v1 hijack method so we don't hijack:
* a password protected page
* a feed post
:movie_camera: http://p.tri.be/oGKHTK
see/138862
=> Ensure password-protected events in V2 are...well...password protected

src/Tribe/Main.php
Added 'to' to a string. (Discovered it by chance.)
=> Grammar fix

src/resources/postcss/components/skeleton/_top-bar.pcss
https://central.tri.be/issues/135382
https://moderntribe.atlassian.net/browse/ECP-184
On hold until we have MR branch ready.
=> fix max width of datepicker container

src/Tribe/Views/V2/View.php
🎫 https://moderntribe.atlassian.net/browse/TEC-3127
🎥 https://www.loom.com/share/6d69fb573d45441ab3df129fd7076737
=> VR > Breadcrumbs > Tax & featured

src/resources/js/views/manager.js
🎟 TEC-3132
---
📹 https://i.bordoni.me/WnuEyrob
=> Before encoding the URl we decode to prevent double encoding.

package-whitelist.json
See: https://moderntribe.atlassian.net/browse/TEC-3031
=> adding uninstall.php to the whitelist

readme.txt, src/views/blocks/event-venue.php
https://moderntribe.atlassian.net/browse/BTOH-79
Updating template version and reflecting modified templates in readme.
=> v4.9.14 > release mods

src/Tribe/Views/V2/Repository/Event_Period.php, src/Tribe/Views/V2/View.php, src/Tribe/Views/V2/Views/By_Day_View.php, src/Tribe/iCal.php
=> PHP 5.6 compatibility with `array_column`

src/Tribe/Views/V2/Views/Traits/HTML_Cache.php
=> HTML Cache replacement for Nonces.

readme.txt, src/Tribe/Customizer/Text.php, src/Tribe/Main.php
🎫 https://moderntribe.atlassian.net/browse/TEC-3068
🎫 https://moderntribe.atlassian.net/browse/TEC-3070
🎫 https://moderntribe.atlassian.net/browse/TEC-3071
🎥 https://www.loom.com/share/32e7446d83ae4b5ebe128e5543df3b64
=> VR > Add the customizer Text section for views V2

src/Tribe/Views/V2/Template_Bootstrap.php
🎟  [TEC-3167]
---
https://i.bordoni.me/2Nur9ge6
[TEC-3167]: https://moderntribe.atlassian.net/browse/TEC-3167
=> Look into the correct folder for old default-template.php

src/Tribe/Views/V2/Template_Bootstrap.php
🎟 TEC-3167
---
📹  https://i.bordoni.me/9ZuN9WkG
=> When dealing with other templates we dont hijack.

phpcs.xml, src/Tribe/Views/V2/View.php, tests/views_integration/Tribe/Events/Views/V2/ViewTest.php
Reverts moderntribe/the-events-calendar#3007
These changes were creating: [TEC-3173]
[TEC-3173]: https://moderntribe.atlassian.net/browse/TEC-3173
=> Revert "Adjust the structure of next/prev URLs so they can be properly tested"

src/Tribe/Views/V2/View.php
🎟 [TEC-3137]
---
📹 https://i.bordoni.me/5zuJkKJN
📹 https://i.bordoni.me/Jru7YEPr
[TEC-3137]: https://moderntribe.atlassian.net/browse/TEC-3137
=> We need to make sure tho remove the inverted key from page/paged to avoid loops

readme.txt, src/Tribe/Views/V2/Template_Bootstrap.php
🎫 https://moderntribe.atlassian.net/browse/TEC-3214
🎥 https://www.loom.com/share/24965a73bdb34799ae11b7782fd7a407
=> VR > Fix `the_post` parameters.

src/Tribe/Views/V2/Utils/Stack.php, src/Tribe/Views/V2/Views/By_Day_View.php, src/Tribe/Views/V2/Views/Month_View.php
🎟 [TEC-3210] [TEC-3208]
---
[TEC-3210]: https://moderntribe.atlassian.net/browse/TEC-3210
[TEC-3208]: https://moderntribe.atlassian.net/browse/TEC-3208
=> Modify the Stacking and Backfilling to account for the new logic

src/functions/template-tags/venue.php, tests/wpunit/functions/template-tags/venueTest.php
Ticket: https://moderntribe.atlassian.net/browse/TEC-3223
This PR adds tests to the [original PR](https://github.com/moderntribe/the-events-calendar/pull/3015) by @steve-brett (Thanks!)
to make sure the issue fixed is covered by tests.
=> Fix tribe_get_region issue

readme.txt, src/Tribe/Customizer/Global_Elements.php, src/Tribe/Customizer/Text.php, src/Tribe/Main.php
🎫 https://moderntribe.atlassian.net/browse/TEC-3067
🎫 https://moderntribe.atlassian.net/browse/TEC-3069
🎥 https://www.loom.com/share/03fb8a858bed44658ac4131ed51d5d9b
=> VR > Customizer > Add accent color & move link color 

readme.txt, src/Tribe/Views/V2/Assets.php, src/Tribe/Views/V2/Hooks.php, src/admin-views/tribe-options-display.php
Reverts moderntribe/the-events-calendar#3053
=> Revert "Task/tec 3125 remove full styles"

src/Tribe/Aggregator/Cron.php
The import is not a failure but was send to the Queue.
Task: [TEC-3232]
[TEC-3232]: https://moderntribe.atlassian.net/browse/TEC-3232
=> Usually if we reach this point it means we Queued the import

src/Tribe/Views/V2/Template_Bootstrap.php
🎟 [TEC-3242]
---
In branch QA happening here.
We need to make sure 404's are respected for which template is loaded.
[TEC-3242]: https://moderntribe.atlassian.net/browse/TEC-3242
=> Make sure 404s are respected from WordPress base.

src/Tribe/Views/V2/View.php
🎟 [TEC-3120]
---
When dealing with plain permalinks we were not properly handling the usage of Event Date params, params from the URL should be overwritten by the other ones which take priority.
📹 https://i.bordoni.me/rRu6y7k7
[TEC-3120]: https://moderntribe.atlassian.net/browse/TEC-3120
=>  Add proper checks for plain permalinks when dealing with AJAX. 

readme.txt, src/Tribe/Views/V2/Assets.php, src/Tribe/Views/V2/Hooks.php, src/admin-views/tribe-options-display.php
"Merge pull request #3056 from moderntribe/revert-3053-task/TEC-3125-remove-full-styles"
This reverts commit f4376b6f9407159acc2d9638e3da940bc508ba67, reversing
changes made to 409c67131a9f9a6de18bc845446b92f93284c3d3.
_______Original Commit Message________
[TEC-3125]
Change the options on the style setting based on whether the new views are active or not.
🎥 http://p.tri.be/KerIf8
[TEC-3125]: https://moderntribe.atlassian.net/browse/TEC-3125
=> Revert the 5.0.1 reversion for 5.0.2

src/Tribe/Integrations/Freemius.php
🎟 [TEC-3218]
---
So there isn't a video here because I wasn't able to reproduce the problem locally in any capacity, my user gets redirected to the correct page, but I worked backward from what Joel sent me as the page he was getting redirected to.
The goal is to make sure the user lands into `tribe-common` admin page instead of `tribe-common-account` which doesn't exist.
I will ask Joel to do a round of in-branch QA on this since we dont have videos.
[TEC-3218]: https://moderntribe.atlassian.net/browse/TEC-3218
=> Freemius - Properly catch users email activation

src/Tribe/Aggregator/Record/Abstract.php
Updates to the code to use the new short syntax `[]` instead of `array()`
Ticket: [TEC-3255]
[TEC-3255]: https://moderntribe.atlassian.net/browse/TEC-3255
=> Update `array` with short syntax instead

src/Tribe/Views/V2/Template/Page.php, src/Tribe/Views/V2/Template_Bootstrap.php, tests/views_integration/Tribe/Events/Views/V2/TemplateBootstrapTest.php
Custom templates are chosable in the admin but are not used on the FE.
📷 http://p.tri.be/TmvjQn
[TEC-3253]
[TEC-3253]: https://moderntribe.atlassian.net/browse/TEC-3253
=> fix(custom templates): Correct the logic to check for custom templates and load them if necessary.

readme.txt, src/Tribe/Views/V2/Hooks.php, src/Tribe/Views/V2/Query/Abstract_Query_Controller.php, src/Tribe/Views/V2/Query/Event_Query_Controller.php
Ticket: https://moderntribe.atlassian.net/browse/TEC-3252 
Screencast: https://drive.google.com/open?id=141BPU9hSaxSWIg_9OIbTJU9hOir6zvlz&authuser=luca@tri.be&usp=drive_fs
=> fix(src) restore correct event RSS feed handling

readme.txt, src/Tribe/Aggregator/Record/List_Table.php, src/Tribe/Aggregator/Tabs/Abstract.php, src/admin-views/aggregator/tabs/import-form.php
Add the option to set a name to imports (optional field)
Ticket: [TEC-3286]
[TEC-3286]: https://moderntribe.atlassian.net/browse/TEC-3286
=> TEC-3286: Allow to named schedule imports

package-whitelist.json, src/Tribe/Integrations/Freemius.php
https://github.com/moderntribe/events-pro/pull/1514
=> Properly load all Assets on final zip

readme.txt, src/Tribe/Views/V2/View.php
...and tribe-header links.
📷 http://p.tri.be/bmVpdp
[TEC-3282]
[TEC-3282]: https://moderntribe.atlassian.net/browse/TEC-3282
=> fix (views selector): ensure we pass keyword search in the views selector

src/Tribe/Aggregator/Tabs/Abstract.php
Needed for an extension in this area.
=> Support filtering the meta so custom options can be added and hashed

src/Tribe/Aggregator/Tabs/New.php, src/admin-views/aggregator/tabs/import-form.php
=> Allow output of custom import preview options

readme.txt, src/Tribe/Views/V2/Views/Day_View.php, src/Tribe/Views/V2/Views/Month_View.php
Also fix use canonical link for fast-forward link and tweak styles.
TEC-3400
=> fix(Views v2) usages of ORM in Views

src/Tribe/Aggregator/Tabs/New.php
Follow up fix for https://github.com/moderntribe/the-events-calendar/pull/3146
=> Fix action name

package-lock.json, readme.txt, src/Tribe/Views/V2/Views/Day_View.php, src/Tribe/Views/V2/Views/Month_View.php, src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
=> Tweak the logic.

readme.txt
This is a complete overhaul of the language in our readme to improve how
it appears on our wordpress.org listing page.
=> overhaul of the readme / .org listing

src/Tribe/Views/V2/Hooks.php, tests/wpunit/Tribe/Events/RewriteTest.php
Issue: https://moderntribe.atlassian.net/browse/TEC-3460 
Based on: https://github.com/moderntribe/tribe-common/pull/1386
This PR: 
1. Fixes an issue I found where we were incorrectly redirecting in Views V2.
2. Adds coverage for the handling of sub-directory installations in the `common` Rewrite component.
[Screencast](https://drive.google.com/open?id=18Gl1Spg6DiGEev7OJHJpHDhBahRsLKOA&authuser=luca%40tri.be&usp=drive_fs)
=> Fix issues with rewrites and redirection on subdir

src/Tribe/Aggregator/Page.php
Improve the documentation around the filters setting the right type of
parameter used on the filter, as well with the `@since` attribute.
=> TEC-3473: Better documentation for filters

readme.txt, src/Tribe/Aggregator/Record/Abstract.php, src/Tribe/Aggregator/Record/Activity.php, src/Tribe/Aggregator/Tabs/New.php
Add a new status for "scheduled" or background tasks.
Ticket: [TEC-3475]
[TEC-3475]: https://moderntribe.atlassian.net/browse/TEC-3475
=> TEC-3475: Add a new scheduled status

readme.txt
This updates the minimum version to the appropriate WP version.
=> Updating "Requires at Least" value

src/Tribe/Views/V2/Hooks.php, src/Tribe/Views/V2/Template_Bootstrap.php, src/Tribe/Views/V2/Theme_Compatibility.php
To ensure we have already parsed the query and added our params.
Fix a few typos
[TEC-3238]
[TEC-3238]: https://moderntribe.atlassian.net/browse/TEC-3238
=> TEC-3238 Trigger the classes later

src/resources/postcss/freemius.pcss
Make the "band" white.
Reduce the spacing above the "band".
📷 http://p.tri.be/6CNpWr
=> Small style tweaks via MattCR

readme.txt, src/Tribe/REST/V1/Main.php
📹 https://i.bordoni.me/X6uomRXG
Related PRs:
https://github.com/moderntribe/event-tickets-plus/pull/1009
https://github.com/moderntribe/event-tickets/pull/1727 
https://github.com/moderntribe/tribe-common/pull/1413
https://github.com/moderntribe/the-events-calendar/pull/3245
=>  Include permission_callback to avoid notice on WP 5.5

src/admin-views/admin-update-message.php
tr1b0t pointed this out right after I merged…
=> fix translator comment

src/admin-views/admin-welcome-message.php
See: https://moderntribe.atlassian.net/browse/TEC-3559
=> fixing a link

src/Tribe/Importer/File_Importer_Events.php, src/Tribe/Importer/File_Importer_Organizers.php
Issue: n/a
This PR fixes a syntax issue in the Importer code.
=> Fix syntax issue

src/resources/postcss/widgets/full/_events-list.pcss, src/resources/postcss/widgets/skeleton/_events-list.pcss, src/views/v2/widgets/events-list.php, src/views/v2/widgets/events-list/event.php, src/views/v2/widgets/events-list/event/organizer.php, src/views/v2/widgets/events-list/view-more.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/View_MoreTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/__snapshots__/View_MoreTest__test_render_with_link__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Widgets/Events_List/__snapshots__/View_MoreTest__test_render_without_link__1.php
**Ticket:** [TEC-3600]
This PR adds templates and styles for the view more link in the events list widget.
**Artifact:**
[TEC-3600]: https://moderntribe.atlassian.net/browse/TEC-3600
=> Events list widget view more link

src/Tribe/Integrations/WPML/Views/V2/Filters.php, src/Tribe/Integrations/WPML/WPML.php, src/Tribe/Views/V2/View.php
Issue: https://moderntribe.atlassian.net/browse/ECP-512
This PR solves an issue caused by the use of the `str_contains` function that does not exist.,
=> Disable faulty Views v2 code

readme.txt, src/Tribe/Views/V2/View.php
Props @lucatume for the easier method!
:camera: http://p.tri.be/qchGDl (corrected link)
:camera: http://p.tri.be/GIffFo (page loaded, no errors)
:camera: http://p.tri.be/nhNTR8 (working with Filter bar)
[ECP-492]
[ECP-492]: https://moderntribe.atlassian.net/browse/ECP-492
=> Simpler fix for categories in the url.

src/Tribe/Views/V2/Assets.php, src/Tribe/Views/V2/Widgets/Widget_Abstract.php
Based on filters in `Assets.php` and `Widget_Abstract.php`.
Create filters for other widgets to hook into if necessary.
[TEC-3597]
📷 (no widget): http://p.tri.be/Sgi0QR
📸  (widget): http://p.tri.be/R3bcMY
Related: https://github.com/moderntribe/tribe-common/pull/1465 (not required)
[TEC-3597]: https://moderntribe.atlassian.net/browse/TEC-3597
=> Make asset enqueues conditional.

src/resources/postcss/widgets/full/_events-list.pcss, src/resources/postcss/widgets/skeleton/_events-list.pcss
**Ticket:** [TEC-3661]
This PR tackles the P4 items of the DQA list in the ticket above.
**Artifact:**
[TEC-3661]: https://moderntribe.atlassian.net/browse/TEC-3661
=> Events list widget DQA pass 2

readme.txt, src/resources/postcss/freemius.pcss
🎫 [TEC-3668]
---
[TEC-3668]: https://moderntribe.atlassian.net/browse/TEC-3668
=> Update common with Freemius 2.4.1

src/Tribe/Customizer/Global_Elements.php, src/Tribe/Customizer/Single_Event.php, src/Tribe/Views/V2/Customizer.php, src/Tribe/Views/V2/Hooks.php
Issue: https://moderntribe.atlassian.net/browse/TEC-3686 
This PR refactors the existing Customizer code to move the Views v2 specific modifications to Views v2 dedicated Customizer handlers.
=> Move Views v2 Customizer settings into dedicated class

src/views/embed/image.php, src/views/kitchen-sink/page.php, src/views/modules/bar.php, src/views/modules/meta/details.php, src/views/month/loop-grid.php
This PR adds the missing `@link` to the Views that require it.
=> Add missing @link in Views

src/Tribe/Views/V2/Customizer.php, tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
**Description:** Adds specific title/datetime overrides for the Latest Past Events view
**Ticket:** https://moderntribe.atlassian.net/browse/TEC-3651
=> Feature / TEC-3651 latest past events

src/Tribe/Customizer/Single_Event.php, src/Tribe/Views/V2/Customizer.php, src/Tribe/Views/V2/Hooks.php
This adds the single_event control I missed.
[TEC-3684]
old: http://p.tri.be/sNOqaC
new: http://p.tri.be/FiE0pP
Will require some logic tweaks where we use the single-event color, the same as the ones for the global elements.
[TEC-3684]: https://moderntribe.atlassian.net/browse/TEC-3684
=> TEC-3684 This adds the single_event control I missed.

src/Tribe/Customizer/Single_Event.php, src/Tribe/Views/V2/Customizer.php
Removes the description and the word "Color" from the control title.
[TEC-3684]
:camera: http://p.tri.be/11J7Be
[TEC-3684]: https://moderntribe.atlassian.net/browse/TEC-3684
=> This changes some text around the event single customizer title color control.

src/Tribe/Admin_List.php
JIRA Ticket: [EA-310](https://moderntribe.atlassian.net/browse/EA-310)
- add link to filter events by aggregator record
=> feature/EA-310 - add link to filter events by aggregator record

readme.txt, src/Tribe/Template/Month.php, src/Tribe/Views/V2/Messages.php
**Description:** Updates the no results copy for the month view by removing "Try searching next month."
**Ticket:** https://moderntribe.atlassian.net/browse/TEC-3567
=> Task / TEC-3567 copy updates

readme.txt, src/resources/postcss/views/full/list/_event.pcss, src/resources/postcss/views/skeleton/list/_event.pcss
**Description:** Adds a few visual enhancements:
- Increase top padding above date stamp in list view
- Reduce bottom margin of the event title in list/day views
- Round featured event line corners
**Ticket:** https://moderntribe.atlassian.net/browse/TEC-3656
=> Feature / TEC-3656 spacing enhancements

readme.txt, src/Tribe/Aggregator/Record/Queue_Realtime.php, vendor/ForceUTF8/Encoding.php
🎫 [TEC-3769]
---
[TEC-3769]: https://theeventscalendar.atlassian.net/browse/TEC-3769
=> ASYNC failing to import

src/resources/js/events-admin.js
🎫 [BTRIA-714]
---
[BTRIA-714]: https://theeventscalendar.atlassian.net/browse/BTRIA-714
=> Fix a IndexOf problem

readme.txt, src/Tribe/Views/V2/View.php
🎫 [FBAR-222]
---
📹 https://i.bordoni.me/12uo182n
Depends on https://github.com/the-events-calendar/events-pro/pull/1687
[FBAR-222]: https://theeventscalendar.atlassian.net/browse/FBAR-222
=> Resolve problem on First navigation with Recurrence settings on.

src/resources/postcss/views/skeleton/_single-event.pcss
**Description:** Updates the Event Single featured image styles for V2
**Ticket:** https://theeventscalendar.atlassian.net/browse/TEC-3754
=> Feature / TEC-3754 featured image

package.json, src/Tribe/Views/V2/Template_Bootstrap.php, src/Tribe/Views/V2/Theme_Compatibility.php
[ECP-604]
Requires/required by: https://github.com/the-events-calendar/tribe-common/pull/1548
[ECP-604]: https://theeventscalendar.atlassian.net/browse/ECP-604
=> Add compatibility functionality for Twenty Twentyone theme.

src/Tribe/REST/V1/Endpoints/Archive_Organizer.php, src/Tribe/REST/V1/Endpoints/Archive_Venue.php, src/Tribe/Views/V2/Interfaces/Repository_User_Interface.php, src/Tribe/Views/V2/View.php, src/views/v2/components/data.php, tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_VenueTest.php
🎫 [FBAR-36]
---
https://i.bordoni.me/L1uN6Pqk
[FBAR-36]: https://theeventscalendar.atlassian.net/browse/FBAR-36
=> Add Hooks to Views codebase.

src/Tribe/Views/V2/Customizer.php, src/resources/postcss/views/full/_single-event.pcss, src/resources/postcss/views/skeleton/_single-event.pcss
**Description:** Contains various DQA updates.
**Ticket:** https://theeventscalendar.atlassian.net/browse/TEC-3766
=> Feature / dqa updates

readme.txt, src/Tribe/Integrations/Fusion/Service_Provider.php, src/Tribe/Integrations/Fusion/Widget_Shortcode.php, src/Tribe/Integrations/Manager.php
🎫 [ECP-538]
---
[ECP-538]: https://theeventscalendar.atlassian.net/browse/ECP-538
=> Add Fusion Core integration to fix fusion_widget

readme.txt, src/Tribe/Models/Post_Types/Event.php
🎫 [BTPLAN-121]
---
Resolved the problem around the saving on blocks editor.
https://i.bordoni.me/jkuL7NGW
[BTPLAN-121]: https://theeventscalendar.atlassian.net/browse/BTPLAN-121
=> Update code to resolve the problem on BTPLAN-121

readme.txt, src/Tribe/Views/V2/Views/Traits/HTML_Cache.php
This PR simply adds some filters. The artifact for this work will be done in the ECP PR that leverages these filters.
:ticket: [ECP-770]
[ECP-770]: https://theeventscalendar.atlassian.net/browse/ECP-770
=> Adding filters for cached view HTML

src/Tribe/Views/V2/Customizer.php, tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
I dropped a style when updating. Replaced.
https://d.pr/i/DBmPfs
[TEC-3781]
(no changelog, this is code that got removed accidentally)
[TEC-3781]: https://theeventscalendar.atlassian.net/browse/TEC-3781
=> D/QA Feature/widget mini calendar and week

src/Tribe/Views/V2/Customizer.php, tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
[TEC-3781]
Normal: https://d.pr/i/AkrBwA
Hover: https://d.pr/i/c0Lz65
[TEC-3781]: https://theeventscalendar.atlassian.net/browse/TEC-3781
=> Correct hover colors on export button.

src/Tribe/Views/V2/Customizer.php, tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__should_allow_taking_a_css_template_snapshot__1.php
[ECP-758]
[ECP-758]: https://theeventscalendar.atlassian.net/browse/ECP-758
=> Fix CTA link color

readme.txt, src/Tribe/Views/V2/Views/Latest_Past_View.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/EventTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__should_render_and_event_with_a_featured_image__1.php
Make sure events that are displayed on the latest past events
list display correctly the featured image if any.
Ticket: TEC-3655
Artifact: https://d.pr/v/zO4CH9
=> TEC-3655: Display featured images for Latest Past Events

readme.txt, src/Tribe/Integrations/Hello_Elementor/Service_Provider.php, src/Tribe/Integrations/Hello_Elementor/Templates.php, src/Tribe/Integrations/Hello_Elementor/hello-elementor-functions.php, src/Tribe/Integrations/Manager.php, tests/wpunit/Tribe/Events/Integrations/Hello_Elementor/TemplatesTest.php
Issue: https://theeventscalendar.atlassian.net/browse/ECP-648
This PR is a reproposition of the code from [the PRO
PR](https://github.com/the-events-calendar/events-pro/pull/1766) to
ensure compatibility between TEC, Elementor and the "Hello Elementor"
theme in the base plugin.
While the issue emerged as a ECP issue, the issue would affect TEC
default Calendar View too, once the "Hello Elementor" theme is active.
[Screeencap](https://www.dropbox.com/s/5mqwiu7ae0qd6bo/ecp-648-self-qa-pass-3.png?dl=0)
=> Fix Hello Elementor theme compat

src/resources/js/views/manager.js
Use a solution that only compares the path and origin to make sure
a real URL change happen before moving forward.
=> TEC-3890: Create a more robust solution for URL changes.

CONTRIBUTING.md
This is been outdated for a while. Hopefully this will help contributors!
=> Update documentation found in CONTRIBUTING.md

src/Tribe/Views/V2/Customizer/Section/Month_View.php
📷 https://d.pr/i/QjKZaq
[TEC-3892]
[TEC-3892]: https://theeventscalendar.atlassian.net/browse/TEC-3892
=> Add missing label

readme.txt, src/Tribe/Aggregator/REST/V1/Endpoints/Base.php, src/Tribe/Main.php, src/Tribe/Repositories/Event.php, src/Tribe/Views/V2/Template_Bootstrap.php, src/Tribe/Views/V2/Utils/Stack.php, src/views/default-template.php, src/views/single-event-blocks.php, src/views/single-event.php, src/views/v2/default-template.php
This adds a collection of hooks to the single event templates per the ticket.
[TEC-3948]
[TEC-3948]: https://theeventscalendar.atlassian.net/browse/TEC-3948
=> Kadence hooks

readme.txt, src/Tribe/Admin/Notice/Legacy_Views_Deprecation.php
📷 https://d.pr/i/hPqHTX
[TEC-3958]
[TEC-3958]: https://theeventscalendar.atlassian.net/browse/TEC-3958
=> Change the text of the message and the link.

readme.txt, src/Tribe/Views/V2/Views/By_Day_View.php
No modifications to the functionality of the By Day View, we are just adding a filter here.
No tests or artifact required.
=> Introducing a hook to allow modifications to grid query

.github/workflows/tests-php.yml, src/Tribe/Views/V2/Assets.php, src/Tribe/Views/V2/Template_Bootstrap.php
[TEC-3975]
[TEC-3975]: https://theeventscalendar.atlassian.net/browse/TEC-3975
=> Alter the single event checking logic.

readme.txt, src/functions/template-tags/general.php, tests/restv1/EventArchiveCest.php
[ECP-912]
:camera: https://d.pr/i/uhziWH (no error)
[ECP-912]: https://theeventscalendar.atlassian.net/browse/ECP-912
=> Test the return of tribe_events_get_current_month_day before we use it.

src/Tribe/Google/Maps_API_Key.php, src/admin-views/aggregator/settings.php, src/admin-views/tribe-options-addons-api.php
[TEC-4015]
:camera: https://d.pr/i/23t2K4
[TEC-4015]: https://theeventscalendar.atlassian.net/browse/TEC-4015
=> Change "APIs" tab to "Integrations"

readme.txt, src/modules/blocks/event-datetime/style.pcss
Here's a description of what this PR fixes - https://www.loom.com/share/c2e5c1e4a7a148d4b0835025e453d10a
Jira Ticket - https://theeventscalendar.atlassian.net/browse/TEC-4029
=> Fix the issue of the Event Date Time block > Timezone dropdown taking up a lot of space. [TEC-4029]

src/resources/postcss/components/full/_events-bar.pcss, src/resources/postcss/components/full/_ical-link.pcss, src/resources/postcss/components/full/_search.pcss
**Ticket:** N/A
This PR fixes a few outstanding issues:
* https://github.com/the-events-calendar/the-events-calendar/pull/3574#discussion_r683628896
* https://github.com/the-events-calendar/the-events-calendar/pull/3574#discussion_r682814676
No new code was added here, just moved some CSS around to the proper location.
**Artifact:** N/A
=> Customizer work cleanup

src/resources/postcss/tribe-events-single-full.pcss
Just had something commented out. 🤦🏼
=> Fix missing custom props on event single.

src/resources/postcss/components/full/_events-bar.pcss
Style bug found during zip test.
[TEC-4063]
:camera: https://d.pr/i/oTyzxf
[TEC-4063]: https://theeventscalendar.atlassian.net/browse/TEC-4063
=> Correct events bar search background color on small screens.

readme.txt, src/views/v2/list/event/venue.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/VenueTest__test_render_with_event_with_venue__1.php
Ticket : https://theeventscalendar.atlassian.net/browse/TEC-3332
Artifact : https://www.loom.com/share/4bb7d07f03954fa8bfd9b2458ef54351
=> [TEC-3332] Ensure that venue state or province are displayed next to the city in list view.

src/Tribe/Views/V2/Hooks.php
📷 https://d.pr/i/lDXyV2
🎫 [ECP-921]
Requires/required by: https://github.com/the-events-calendar/events-pro/pull/1822
[ECP-921]: https://theeventscalendar.atlassian.net/browse/ECP-921
=> Be sure it's the right URL field before we alter the label.

readme.txt
Just missed a changelog entry - this fixes it.
For ECP-921
Related: https://github.com/the-events-calendar/events-pro/pull/1823
=> Missing readme.

readme.txt
This PR contains an update to a change log entry to include information about bypassing the changes post release. The update is also intended to give the release team sufficient information when creating the release notes for the upcoming release of the Event Single Reskin.
Ticket : https://theeventscalendar.atlassian.net/browse/TEC-3979
No artifact is required because this is an update to an existing change log entry.
=> [TEC-3979] Update change log to include bypass constant.

src/admin-views/metabox/compatibility/events-control-extension/mark-online.php, src/admin-views/metabox/event-status.php, src/resources/images/alert.svg, src/resources/postcss/events-admin.pcss, src/resources/postcss/views/full/_event-status.pcss, src/resources/postcss/views/skeleton/_event-status.pcss, tests/event_status/Tribe/Events/Event_Status/Compatibility/__snapshots__/Events_Control_ExtensionTest__it_should_return_template_when_extension_found__1.php, tests/event_status/Tribe/Events/Event_Status/__snapshots__/Classic_EditorTest__should_test_render_with_event__1.php, tests/event_status/Tribe/Events/Event_Status/__snapshots__/Classic_EditorTest__should_test_render_with_event_and_status_data__1.php
DQA Fixes
-Style Updates
-Processed the SVG through svgomg
=> TEC-3464 - DQA Fixes

src/Tribe/Views/V2/Customizer/Configuration.php
[TEC-4055]
https://d.pr/v/JqvWVd
[TEC-4055]: https://theeventscalendar.atlassian.net/browse/TEC-4055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure the Customizer doesn't customize itself.

readme.txt
[TEC-4126]
[TEC-4126]: https://theeventscalendar.atlassian.net/browse/TEC-4126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add missing readme entry

readme.txt, src/Tribe/Assets.php, src/Tribe/Views/V2/iCalendar/Links/Google_Calendar.php, src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php, src/Tribe/Views/V2/iCalendar/Links/Link_Interface.php, src/Tribe/Views/V2/iCalendar/Links/iCal.php, src/Tribe/Views/V2/iCalendar/Links/iCalendar_Export.php, src/Tribe/Views/V2/iCalendar/iCalendar_Handler.php, src/deprecated/Tribe__Events__Asset__Calendar_Script.php, src/functions/template-tags/ical.php, src/resources/js/tribe-events.js, src/resources/postcss/components/full/_ical-link.pcss, src/resources/postcss/components/skeleton/_ical-link.pcss, src/resources/postcss/views/skeleton/_single-event.pcss, src/views/v2/components/subscribe-links/item.php, src/views/v2/components/subscribe-links/legacy.php, src/views/v2/components/subscribe-links/single.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Ical_LinkTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_legacy_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_all__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_gcal_only__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_ical_only__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_icalendar_export_only__1.php
Fix a couple QA things.
Style bug when tribe-theme.css is loaded
Text change to single links.
URL change for single links - remove some v1 js.
Update readme.
=> Subscribe to calendar integration QA

readme.txt, src/views/v2/components/subscribe-links/list.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_all__1.php
[BTRIA-1077]
[BTRIA-1077]: https://theeventscalendar.atlassian.net/browse/BTRIA-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Close a div in the new subscribe dropdown that was left open.

readme.txt
=> FBAR-92 - readme entry

src/views/v2/components/subscribe-links/item.php, src/views/v2/components/subscribe-links/legacy.php, src/views/v2/components/subscribe-links/list.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_all__1.php
A couple of typos that snuck through.
[TEC-4166]
[TEC-4166]: https://theeventscalendar.atlassian.net/browse/TEC-4166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix a few typos.

readme.txt, src/resources/postcss/components/skeleton/_ical-link.pcss, src/views/v2/components/subscribe-links/list.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Ical_LinkTest__test_render_with_all__1.php
No pushing the sidebar down due to float!
=> Get rid of the float so we don't inadvertently break some site layouts.

readme.txt
Adds missing change log entry for the joulutorttu release in TEC.
Ticket : https://theeventscalendar.atlassian.net/browse/ECP-1016
=> Change log entry for the joulutorttu release. [ECP-1016]

readme.txt, src/Tribe/Importer/Column_Mapper.php, src/Tribe/Importer/File_Importer.php, src/Tribe/Importer/File_Importer_Events.php, src/Tribe/Importer/File_Importer_Organizers.php
_Ref:_ [VE-387](https://theeventscalendar.atlassian.net/browse/VE-387)
This PR adds some comments to the CSV Import coding and adds a hook after an event is created or updated so that Virtual Events can then process its meta. 
No artifact for this PR, see the VE PR for more details. 
https://github.com/the-events-calendar/events-virtual/pull/350
=> CSV Importer Hook and Comments

src/views/v2/latest-past/event/date-tag.php, src/views/v2/latest-past/event/featured-image.php, src/views/v2/list/event/date-tag.php, src/views/v2/list/event/featured-image.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/Date_TagTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/Date_TagTest__test_render_with_featured_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__should_render_and_event_with_a_featured_image__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Latest_Past_View/__snapshots__/EventTest__test_render_with_featured_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set on_same_day__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set on_same_day_past__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_after__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_after_past__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_before__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_featured_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php
On [this Gist](https://gist.github.com/mrwweb/6f5ba48873d9bd24dfc23eed7ad934df) @mrwweb  makes some suggestions on Accessibility that we can add to this release.
Not all suggestions are included in this PR as some of them are decisions we made in the past because they are better suited for the event structure. Example, Date/Time appearing before the Title of the Event on List view.
=> Improve accessibility based on @mrwweb suggestions

src/admin-views/aggregator/settings.php
This is minor enough to not need a changelog entry.
Here's the artifact:
=> Escape a URL

src/Tribe/Views/V2/Assets.php
=> Fix enqueue of single event block assets on FE

readme.txt, src/Tribe/Main.php, src/Tribe/Organizer.php, src/Tribe/Venue.php
[BTRIA-1152]
[BTRIA-1152]: https://theeventscalendar.atlassian.net/browse/BTRIA-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix the organizer/venue metaboxes on new posts.

readme.txt, src/Tribe/Views/V2/Views/Month_View.php
Add filter for folks who want it to start at the beginning of the month anyway.
[TEC-4223]
[TEC-4223]: https://theeventscalendar.atlassian.net/browse/TEC-4223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make month view exports start on today.

src/resources/postcss/tribe-admin-single-blocks.pcss
This fix ensures we set the correct color variables on the admin as we have on the FE in order to maintain consistency in the look and feel.
Ticket: https://theeventscalendar.atlassian.net/browse/TEC-4250
https://www.loom.com/share/851a132c94f044e4961eeea2bb6e8556
=> Apply correct color variables. [TEC-4250]

src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
Tweak the logic around FBAR view_data/filters - no real logic change except existing tax does not automatically disable the FF link.
Tidy a bit ( no need to check a var before unset() )
Erroneously tagged as an ECP bug as it was first discovered with shortcodes. All the code needing changes is in TEC.
[ECP-957]
[ECP-957]: https://theeventscalendar.atlassian.net/browse/ECP-957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow categories to be honored in fast-forward links.

readme.txt, src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
[ECP-957]
Required by: https://github.com/the-events-calendar/events-pro/pull/1921 
🎥 https://d.pr/v/fVNRkk
[ECP-957]: https://theeventscalendar.atlassian.net/browse/ECP-957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow filtering of the "next event" query in the fast-forward link.

package-lock.json, package.json, readme.txt, src/Tribe/Main.php, src/Tribe/Plugin_Register.php, the-events-calendar.php
[ET-1335] 
- Setting version number.
- Adding dependencies.
- Adding readme entry.
[ET-1335]: https://theeventscalendar.atlassian.net/browse/ET-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Events/Tickets menu] Set version number, dependencies, readme.

src/Tribe/Admin/Settings.php, src/admin-views/aggregator/settings.php, src/admin-views/tribe-options-addons-api.php
[ET-1335] 
- Fixing network settings hijack.
https://cloudup.com/cg0ZH33ryhM
[ET-1335]: https://theeventscalendar.atlassian.net/browse/ET-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixing network settings for ET/TEC (and all the suite)

src/Tribe/Admin/Settings.php
Early bail if the plugin is not enabled for the network.
https://user-images.githubusercontent.com/252415/168826096-22e9a6ef-0200-4fed-b9b0-b1b370517dad.mov
=> Bail if the plugin is not enabled for the network.

src/Tribe/Admin/Settings.php
[ET-1335] 
- Return options on early bail.
[ET-1335]: https://theeventscalendar.atlassian.net/browse/ET-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC Network settings > Return `$options` on early bail.

readme.txt, src/Tribe/Plugin_Register.php
[ET-1335]
- Adding min version for EBT.
[ET-1335]: https://theeventscalendar.atlassian.net/browse/ET-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add EBT min version.

readme.txt, src/Tribe/Main.php
🎫 [BTRIA-1243]
[BTRIA-1243]: https://theeventscalendar.atlassian.net/browse/BTRIA-1243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevent fatals between Yoast and TEC

readme.txt, src/views/v2/month/mobile-events/nav/next.php, src/views/v2/month/mobile-events/nav/prev.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Nav/NextTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Nav/PrevTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Nav/TodayTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Nav/__snapshots__/NextTest__test_render_with_label_and_link__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Nav/__snapshots__/PrevTest__test_render_with_label_and_link__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/NavTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/NavTest__test_render_with_prev_url_with_next_url__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/NavTest__test_render_with_prev_url_without_next_url__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/__snapshots__/NavTest__test_render_without_prev_url_with_next_url__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_EventsTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_found_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_days_with_no_found_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Mobile_EventsTest__test_render_with_empty_days__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
[TEC-4354]
[TEC-4354]: https://theeventscalendar.atlassian.net/browse/TEC-4354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make the same changes for the mobile nav we did for desktop.

readme.txt, src/Tribe/Views/V2/Widgets/Widget_Abstract.php, the-events-calendar.php
[TEC-4048]
[TEC-4048]: https://theeventscalendar.atlassian.net/browse/TEC-4048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Widgets don't use the search param - so don't send it.

readme.txt, src/Tribe/Organizer.php, src/Tribe/Venue.php
Add edit links to single venue and organizer pages to improve user experience. [ECP-1181]
https://theeventscalendar.atlassian.net/browse/ECP-1181
[ECP-1181]: https://theeventscalendar.atlassian.net/browse/ECP-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://www.loom.com/share/fa1eeda6f1c74068a29e0827a72dff3d
=> Add admin bar edit links to single venue and organizer pages. [ECP-1181]

lang/the-events-calendar.pot, package-lock.json, package.json, readme.txt, src/Tribe/Aggregator/Page.php, src/Tribe/Aggregator/Record/Queue_Realtime.php, src/Tribe/Main.php, src/resources/js/aggregator-fields.js, the-events-calendar.php
[BTRIA-1285]
[BTRIA-1285]: https://theeventscalendar.atlassian.net/browse/BTRIA-1285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> hotfix - release/b22.pampushka.1

src/Tribe/Organizer.php, src/Tribe/Venue.php
Ensure the edit links are displayed on the venue and organizer pages respectively. 
https://theeventscalendar.atlassian.net/browse/ECP-1181
[ECP-1181]: https://theeventscalendar.atlassian.net/browse/ECP-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://www.loom.com/share/fa1eeda6f1c74068a29e0827a72dff3d
=> Ensure the edit links are displayed on the venue and organizer pages respectively. [ECP-1181]

src/Tribe/Views/V2/Template/Title.php, src/Tribe/Views/V2/View.php
...and then pass it to `get_term_by()`.
[ECP-1186]
[ECP-1186]: https://theeventscalendar.atlassian.net/browse/ECP-1186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Handle occasions where we get an array for `$term` 

src/Tribe/Admin/Notice/Update.php
Resolving item 340 on the Spreadsheet.
=> Remove the warning icon from the update warning

src/admin-views/notices/update-6-0-0.php
Resolves the problem since it was looking into the common folder by default, which when ET was available, it would default to look into the ET folders. Now it will always look into the TEC folders.
=> Make sure we are not looking at the warning in Common, but in TEC

readme.txt, src/Tribe/Main.php, the-events-calendar.php
[TEC-4430]
[TEC-4430]: https://theeventscalendar.atlassian.net/browse/TEC-4430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Hotfix: freemius update

src/Events/Custom_Tables/V1/Migration/Process.php, src/Events/Custom_Tables/V1/Migration/Process_Worker.php, src/Events/Custom_Tables/V1/Migration/Reports/Site_Report.php
Ticket: https://theeventscalendar.atlassian.net/browse/ECP-882
Related: https://github.com/the-events-calendar/support-api/pull/53
=> Provide dry-run info in migration complete filter

src/Tribe/Views/V2/Assets.php
Related: https://github.com/the-events-calendar/tribe-common/pull/1784
=> Make sure we have properly setup Datepicker

src/Events/Custom_Tables/V1/admin-views/migration/maintenance-mode/phase/migration-in-progress.php
=> Removed class that hides button.

src/Events/Custom_Tables/V1/Models/Occurrence.php
Just a small doc block update to support https://github.com/the-events-calendar/events-pro/pull/2006
=> Add missing prop docs on Occ. model

readme.txt, src/Tribe/REST/V1/Endpoints/Archive_Event.php, src/Tribe/Validator/Base.php, src/Tribe/Validator/Interface.php
[TEC-4439]
[TEC-4439]: https://theeventscalendar.atlassian.net/browse/TEC-4439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TEC-4439] Add support for `ticketed` param on REST API Event Archive.

composer.json, composer.lock, phpcs.xml
This update changes the repo name and references for our coding-standards repository.
=> Updating coding standards repo

src/Tribe/Integrations/Freemius.php
Related: https://github.com/the-events-calendar/tribe-common/pull/1798
=> Freemius Update page compatibility

package.json, src/admin-views/updates/6.0.0.php, src/resources/postcss/admin-update-page.pcss, src/resources/postcss/custom-tables-v1/ct1-upgrade.pcss
📷  http://i.bordoni.me/v1Hk1wk44MPAJQI7X0LL
=> Make sure we have a link to Settings page on the Update page

src/admin-views/updates/6.0.0.php, src/resources/postcss/admin-update-page.pcss
This adds the missing box at the bottom of the update page.
**Full width**
**Less than 1217px**
=> Add "Take me to Settings" box at the bottom of the update page

src/Events/Custom_Tables/V1/Migration/Strategies/Single_Event_Migration_Strategy.php
Wording change following reply on [ECP-1304](https://theeventscalendar.atlassian.net/browse/ECP-1304) to provide the user with an actionable solution to the problem.
=> Reword missing ECP report message

readme.txt, src/Tribe/Integrations/WPML/Meta.php
[TEC-4428]
See: https://github.com/the-events-calendar/the-events-calendar/pull/3888
[TEC-4428]: https://theeventscalendar.atlassian.net/browse/TEC-4428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add caching for translated venue/organizer.

readme.txt
Added readme entry for CE-165 and CE-11
=> CE-165 & CE-11 Readme update

readme.txt, src/Tribe/Integrations/WPML/Meta.php, src/Tribe/Integrations/WPML/WPML.php
...when WPML + Block editor are active
props @dgwatkins
[TEC-4498]
original PR: https://github.com/the-events-calendar/the-events-calendar/pull/3983
[TEC-4498]: https://theeventscalendar.atlassian.net/browse/TEC-4498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix an issue with venue ID not saving properly

readme.txt, src/Tribe/Plugin_Register.php
Set up dependencies, set proper version on readme.
=> Set up dependencies for panoplausarus.

readme.txt, src/admin-views/create-venue-fields.php, src/admin-views/venue-meta-box.php
Update the venue website field to type URL.
https://theeventscalendar.atlassian.net/browse/TEC-4349
https://www.loom.com/share/db210d48d0ed4a85816bcc84618bbc6e
=> Venue website field validation. [TEC-4349]

src/Tribe/Integrations/WPML/Views/V2/Filters.php, src/Tribe/Plugin_Register.php
Also: Remove an old TODO
https://d.pr/i/CaadGt
=> Use static for called functions.

readme.txt, src/modules/blocks/event-organizer/index.js
Related to [TEC-4466](https://theeventscalendar.atlassian.net/browse/TEC-4466)
Updates some incorrect text domains in the Organizer block.
=> Add correct text domain

readme.txt, src/resources/js/views/manager.js
Ticket: [FBAR-273](https://theeventscalendar.atlassian.net/browse/FBAR-273)
Reverts the changes made by this [PR](https://github.com/the-events-calendar/the-events-calendar/pull/4058) to allow for in-branch QA to take take place based on these [comments](https://github.com/the-events-calendar/the-events-calendar/pull/4058#issuecomment-1333237845).
=> Revert [FBAR-273]

readme.txt, src/Tribe/Query.php
For Context : https://lw.slack.com/archives/C01QK7V0883/p1671082869823789
**Artifact 🎥**
https://www.loom.com/share/c739dcb6432a498aafd4bcf9910d0513
=> Bail if we're not dealing with any event or event related queries.

readme.txt, src/admin-views/tribe-options-general.php
TEC only: https://d.pr/i/JAz7PB
With ECP: https://d.pr/i/t26pqQ 
Required by https://github.com/the-events-calendar/events-pro/pull/2160
[TEC-4627]
[TEC-4627]: https://theeventscalendar.atlassian.net/browse/TEC-4627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Reorganize settings.

readme.txt
Adds missing change log entry for [TEC-4608](https://theeventscalendar.atlassian.net/browse/TEC-4608)
Updates the change log entry for [TEC-4613](https://theeventscalendar.atlassian.net/browse/TEC-4613) to reflect the ticket code.
[TEC-4608]: https://theeventscalendar.atlassian.net/browse/TEC-4608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TEC-4613]: https://theeventscalendar.atlassian.net/browse/TEC-4613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Clean up a couple of change log entries for B23.alexa.

readme.txt, src/Events/Integrations/Plugins/WordPress_SEO/Provider.php
🎫 [BTRIA-1585]
---
[BTRIA-1585]: https://theeventscalendar.atlassian.net/browse/BTRIA-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevent Yoast SEO 16.2 Notice

.gitignore, composer.json, composer.lock, package-safelist.json, src/Events/Installer/Provider.php, src/Tribe/Admin/Notice/Install_Event_Tickets.php, src/Tribe/Main.php, src/admin-views/notices/install-event-tickets.php, src/resources/js/admin/notice-install-event-tickets.js, tests/integration/Tribe/Events/Integrations/__snapshots__/Install_Tickets_NoticeTest__it_should_render_notice_activate__1.php, tests/integration/Tribe/Events/Integrations/__snapshots__/Install_Tickets_NoticeTest__it_should_render_notice_install__1.php, tests/views_integration/Tribe/Events/Views/V2/iCalendar/RequestTest.php, the-events-calendar.php
Since we'll want to use install functionality in more places than one, I've extracted out @juanfra's install/activate logic into a library that can be used in multiple places. That can be seen here: https://github.com/stellarwp/installer
Related:
* https://github.com/the-events-calendar/the-events-calendar/pull/4110
* https://github.com/the-events-calendar/tribe-common/pull/1872
🎥 https://d.pr/v/MqNRTp
:ticket: [TEC-4663]
[TEC-4663]: https://theeventscalendar.atlassian.net/browse/TEC-4663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TEC-4663] Implement the new stellarwp/installer library for install actions

readme.txt, src/admin-views/tribe-options-display.php
Also sneaks in a text change we (I) messed up last release 😉
=> Update for DQA tweaks

src/Tribe/iCal.php
[TEC-4664] (updated in common)
[TEC-4619]
[TEC-4664]: https://theeventscalendar.atlassian.net/browse/TEC-4664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TEC-4619]: https://theeventscalendar.atlassian.net/browse/TEC-4619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix for both TEC-4664 (in common) and TEC-4619

src/Events/Custom_Tables/V1/Activation.php, src/Events/Custom_Tables/V1/Health_Check.php, tests/ct1_migration/TEC/Events/Custom_Tables/V1/Activation_StateTest.php, tests/ct1_migration/TEC/Events/Custom_Tables/V1/Health_CheckTest.php
Adding a health check section for our troubleshooting info.
Artifacts:
=> Adding basic healthcheck

readme.txt, src/Tribe/iCal.php
🎫 [TEC-4726]
---
[TEC-4726]: https://theeventscalendar.atlassian.net/browse/TEC-4726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Modify the code for iCal to prevent PHP 8+ fatal

readme.txt, src/Events/Integrations/Plugins/Colbri_Page_Builder/Provider.php, src/Events/Integrations/Provider.php
Ticket : [TEC-4735](https://theeventscalendar.atlassian.net/browse/TEC-4735)
Resolves the issue of the WP customizer not loading correctly when the Colbri Page Builder plugin is active.
https://www.loom.com/share/063c50530e47417a88a1547149e6c38e
[TEC-4735]: https://theeventscalendar.atlassian.net/browse/TEC-4735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Colbri Page Builder integration.

readme.txt, src/Events/Custom_Tables/V1/Full_Activation_Provider.php
[ET-1495](https://theeventscalendar.atlassian.net/browse/ET-1495) 
Fire an action when the CT1 feature is fully activated to allow depending feature to boot correctly.
[ET-1495]: https://theeventscalendar.atlassian.net/browse/ET-1495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fire an action on CT1 full activation

.github/workflows/tests-php.yml, readme.txt, src/Events/Custom_Tables/V1/Activation.php, src/Events/Custom_Tables/V1/Full_Activation_Provider.php, tests/ct1_multisite_integration/TEC/Events/Custom_Tables/V1/Schema_Builder/Schema_BuilderTest.php
Wrap #4191 to run tests, rebase and update readme files.
Artifacts:
* [screencast](https://share.cleanshot.com/M2fQxhlb) 
* tests
=> Wrap User PR 4191

readme.txt
Pre-release tested up to version bump.
=> Version bump

src/Events/Integrations/Plugins/Elementor/Provider.php
Ticket : [TEC-4685](https://theeventscalendar.atlassian.net/browse/TEC-4685)
This is an offshoot of this [PR](https://github.com/the-events-calendar/the-events-calendar/pull/4222), to address these [comments](https://github.com/the-events-calendar/the-events-calendar/pull/4222#discussion_r1173877144).
[TEC-4685]: https://theeventscalendar.atlassian.net/browse/TEC-4685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Elementor Posts widget [TEC-4685]

src/admin-views/tribe-options-general.php
[ECP-1475](https://theeventscalendar.atlassian.net/browse/ECP-1475)
Just added a link to the WP trash wiki on the settings page.
[ECP-1475]: https://theeventscalendar.atlassian.net/browse/ECP-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added link to trash wiki page.

readme.txt, src/Tribe/Views/V2/iCalendar/Links/Link_Abstract.php, src/Tribe/iCal.php, tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_restricted__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php, tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
[TEC-4584]
[TEC-4584]: https://theeventscalendar.atlassian.net/browse/TEC-4584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Correct issue with event subscriptions not passing events past the first 30.

src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php, src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php, src/Events/Integrations/Plugins/Event_Tickets/Emails/Emails.php
This code depends on: https://github.com/the-events-calendar/event-tickets/pull/2616
=> Prevent the usage of __get and __set which were being used wrong

readme.txt, src/Tribe/Organizer.php, src/Tribe/Venue.php, tests/views_integration/Tribe/Events/Views/V2/Template/TitleTest.php
Ticket : [ECP-1173](https://theeventscalendar.atlassian.net/browse/ECP-1173)
Ensure the page titles on the single venue and organizer pages include the respective post titles for improved SEO.
https://drive.google.com/file/d/1qvh5ucJyHLVvH3hnHzSe2XoTe0OMMzJC/view?usp=share_link
[ECP-1173]: https://theeventscalendar.atlassian.net/browse/ECP-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SEO Improvement on Venue and Organizer pages.

src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php, src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php
Updating the settings as per David's comments.
https://github.com/the-events-calendar/the-events-calendar/assets/252415/c7af5226-bbf8-453e-af06-141f688e4aab
=> Tickets Emails: DQA changes.

src/Events/Integrations/Plugins/Event_Tickets/Emails/Emails.php
🎫 [ET-1746]
--- 
📷 Screenshot
[ET-1746]: https://theeventscalendar.atlassian.net/browse/ET-1746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Tickets Emails: HTML is not permitted on placeholders

readme.txt, src/Tribe/Main.php, src/Tribe/Views/V2/Template/Title.php, tests/views_integration/Tribe/Events/Views/V2/Template/TitleTest.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view __1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view default__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view list__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view month__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - view __1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - view default__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - view list__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2017-02-02 - view month__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - view __1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - view default__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - view list__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-01-05 - view month__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - view __1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - view default__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - view list__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2018-02-01 - view month__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - view __1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - view default__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - view list__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2019-02-03 - view month__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - view __1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - view default__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - view list__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date 2022-06-06 - view month__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_w_date_w_posts__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_w_date_w_posts__2.php
[TEC-4692](https://theeventscalendar.atlassian.net/browse/TEC-4692)
Updates the title tag generated on views to be unique based on date range, view and page.
Artifacts:
See tests and snapshots.
[TEC-4692]: https://theeventscalendar.atlassian.net/browse/TEC-4692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated to do unique title tags in various scenarios.

src/Tribe/Views/V2/Template/Title.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view __1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view default__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view list__1.php, tests/views_integration/Tribe/Events/Views/V2/Template/__snapshots__/TitleTest__test_title_with_views with data set 2 events - event_date  - view month__1.php
QA Fix for pagination not showing titles.
=> Should not rely on date param.

src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/RSVP.php, src/Events/Integrations/Plugins/Event_Tickets/Emails/Email/Ticket.php
[ET-1754]
[ET-1754]: https://theeventscalendar.atlassian.net/browse/ET-1754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ET-1754 Enhance -  Fix Toggle RSVP preview

src/Events/Integrations/Plugins/Event_Tickets/Emails/Emails.php, src/views/integrations/event-tickets/emails/template-parts/body/event/title.php, src/views/integrations/event-tickets/emails/template-parts/header/head/tec-styles.php
[ET-1757]
Screenshot: https://share.cleanshot.com/DwTdnlcg
[ET-1757]: https://theeventscalendar.atlassian.net/browse/ET-1757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ET-1757] Enhance - Make Event title clickable with link to the event.

src/views/integrations/event-tickets/emails/template-parts/header/head/tec-styles.php
- TE-55EA
- TE-7C40
- TE-DECF
Several small tweaks to fix some CSS override issues and spacing issues found during DQA.
=> Tickets Emails: Various Styling Fixes

src/Events/Integrations/Plugins/Event_Tickets/Emails/Hooks.php
[TE-8A46]
* Changed target template from Tickets to Additional Content.
* Changed priorities to allow space in between for customizations.
Related to: https://github.com/the-events-calendar/event-tickets/pull/2678
=> [TE-8A46 ] - Fix change target template to add Event templates.

src/Events/Telemetry/Telemetry.php
(no edit screens, no post list screens)
Slack ref: https://lw.slack.com/archives/C01SYM19N7K/p1686145011350859
=> Only show the modal on screens where our nonce wil validate

src/Events/Custom_Tables/V1/Schema_Builder/Abstract_Custom_Table.php
Just to keep common up to date.
Requires https://github.com/the-events-calendar/tribe-common/pull/1935
=> Ensure we extend/use the right class in our tests

readme.txt, src/Tribe/iCal.php, tests/wpunit/Tribe/Events/iCalTest.php
[TEC-4837](https://theeventscalendar.atlassian.net/browse/TEC-4837)
Ensuring valid events are being passed to the ical generation.
**Artifact**:
[TEC-4837]: https://theeventscalendar.atlassian.net/browse/TEC-4837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding some permission checks to the filter.

src/Events/Integrations/Plugins/Event_Tickets/Emails/Hooks.php
🎫 [ET-1781]
---
[ET-1781]: https://theeventscalendar.atlassian.net/browse/ET-1781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Move towards Service Provider Contract

readme.txt, src/views/integrations/event-tickets/emails/template-parts/header/head/tec-styles.php
[TEC-4849]
Refactoring the CSS styles based on experimenting with Gmail and adding in mobile style for the venue section, which didn't make it into Escarole.
Desktop:
Mobile:
[TEC-4849]: https://theeventscalendar.atlassian.net/browse/TEC-4849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TEC-4849] Tickets Emails: Refactor TEC CSS Styles and Add Mobile Styling to Venue

src/Tribe/iCal.php, tests/wpunit/Tribe/Events/iCalTest.php
[TEC-4837](https://theeventscalendar.atlassian.net/browse/TEC-4837)
Fix for QA fail. Images where being shown when they shouldn't.
[TEC-4837]: https://theeventscalendar.atlassian.net/browse/TEC-4837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix for attachments in ical

src/Events/Custom_Tables/V1/Models/Builder.php, tests/ct1_integration/TEC/Events/Custom_Tables/V1/Models/BuilderTest.php
The memoize was failing to clear in static upserts, and chained deletes - tests were failing,
=> This fixes a test failing in ECP.

src/Events/Custom_Tables/V1/Models/Builder.php, tests/ct1_integration/TEC/Events/Custom_Tables/V1/Models/BuilderTest.php
Fix for test failure.
Needs to handles mixed values for serialization.
=> Fix array to string conversion notice error.

src/Events/Site_Health/Info_Section.php, src/Events/Telemetry/Provider.php, src/Events/Telemetry/Telemetry.php
[TEC-4851]
Related: https://github.com/the-events-calendar/event-tickets/pull/2711
[TEC-4851]: https://theeventscalendar.atlassian.net/browse/TEC-4851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Modify conditionals and Hook to load telemetry modal on all pages

readme.txt, src/views/blocks/parts/details.php
[TEC-4870]
[TEC-4870]: https://theeventscalendar.atlassian.net/browse/TEC-4870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix typo - remove stray "w" in template.

src/Tribe/Assets.php, src/Tribe/Linked_Posts.php, src/resources/js/event-editor.js, src/resources/js/events-admin.js
There were a lot of unnecessary code around the Linked Post duplication and removal.
@borkweb if you can please test this if you get the chance.
📹  https://i.bordoni.me/ZKMysqsY
---
Video With the Demo of the whole behavior working requested by @borkweb after some extra changes.
📹  https://i.bordoni.me/xBMb2qQs
---
📹 https://i.bordoni.me/L1dT9G5v
=> Resolving multiple problems with Linked Posts UI for Add/Remove

src/Tribe/Admin/Settings.php
Ticket : [TEC-4854](https://theeventscalendar.atlassian.net/browse/TEC-4854)
Ensure we're using the correct text domain.
[TEC-4854]: https://theeventscalendar.atlassian.net/browse/TEC-4854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update text domain.

tests/views_integration/Tribe/Events/Views/Blocks/Classic_Event_DetailsTest.php, tests/views_integration/Tribe/Events/Views/Blocks/Event_CategoryTest.php, tests/views_integration/Tribe/Events/Views/Blocks/Event_DatetimeTest.php, tests/views_integration/Tribe/Events/Views/Blocks/Event_LinksTest.php, tests/views_integration/Tribe/Events/Views/Blocks/Event_PriceTest.php, tests/views_integration/Tribe/Events/Views/Blocks/Event_TagsTest.php, tests/views_integration/Tribe/Events/Views/Blocks/Event_VenueTest.php
Refactored the test cases to streamline the rendering of the blocks within each individual test method.
=> Update Block Tests.

readme.txt, src/Tribe/Views/V2/Views/Latest_Past_View.php, tests/restv1/OrganizerInsertionCest.php, tests/restv1/OrganizerUpdateCest.php, tests/restv1/VenueInsertionCest.php, tests/restv1/VenueUpdateCest.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
Resolving some problems Victor reported on Smoketest.
=> Past View inherits templates from view, and safelist a couple more template items

readme.txt, src/functions/template-tags/organizer.php, src/functions/template-tags/venue.php, src/views/blocks/parts/organizer.php, src/views/modules/meta/organizer.php, src/views/modules/meta/venue.php
Ticket: [TEC-4874](https://theeventscalendar.atlassian.net/browse/TEC-4874)
Enhanced venue and organizer labels by updating aria labels with additional placeholders and revised translator comments, improving internationalization and accessibility.
**Screenshot 📸**
[TEC-4874]: https://theeventscalendar.atlassian.net/browse/TEC-4874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Accessibility improvement

src/Tribe/Aggregator.php, src/Tribe/Assets.php, src/Tribe/Constants.php, src/Tribe/Event_Status/Classic_Editor.php, src/Tribe/Main.php, src/Tribe/Organizer.php, src/Tribe/REST/V1/Messages.php, src/Tribe/Updater.php, src/Tribe/Venue.php
More PHP compatibility fixes.
[TEC-4847]
[TEC-4847]: https://theeventscalendar.atlassian.net/browse/TEC-4847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix more undeclared/dynamic properties.

src/Events/Telemetry/Telemetry.php
https://github.com/the-events-calendar/event-tickets/pull/2786
=> Ensure telemetry opt-in works across TEC and ET

lang/the-events-calendar.pot, readme.txt, src/Tribe/Main.php, src/Tribe/Views/V2/Hooks.php, src/admin-views/admin-update-message.php, the-events-calendar.php
[TEC-4946]
[TEC-4946]: https://stellarwp.atlassian.net/browse/TEC-4946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevents a fatal caused by get_noindex_events on PRO views if PRO has not been updated.

src/Tribe/Admin/Notice/Full_Site_Editor.php
[TEC-4947](https://stellarwp.atlassian.net/browse/TEC-4947)
Minor copy tweak.
[TEC-4947]: https://stellarwp.atlassian.net/browse/TEC-4947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated text.

readme.txt
[TEC-4807](https://stellarwp.atlassian.net/browse/TEC-4807)
Check accompanying [PR](https://github.com/the-events-calendar/tribe-common/pull/1994) in Common
[TEC-4807]: https://stellarwp.atlassian.net/browse/TEC-4807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix AM/PM time format for French locale in the `tribe_format_date()` function.

readme.txt, src/Events/SEO/Controller.php
[TEC-4949]
[TEC-4949]: https://stellarwp.atlassian.net/browse/TEC-4949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> This updates the noindex code to specifically exclude single posts/pages.

readme.txt, src/Tribe/Event_Tickets/Attendees_Report.php
[ET-1810]
[ET-1810]: https://stellarwp.atlassian.net/browse/ET-1810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ET-1810] Feat - add event date to ticket reporting

readme.txt, src/Tribe/Linked_Posts/Chooser_Meta_Box.php
[BTRIA-2088](https://stellarwp.atlassian.net/browse/BTRIA-2088)
Req: https://github.com/the-events-calendar/tribe-common/pull/2003
```
Deprecated: Creation of dynamic property TEC\Event...
```
[BTRIA-2088]: https://stellarwp.atlassian.net/browse/BTRIA-2088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump + dynamic prop fix

readme.txt
=> Add ETWP to readme.

src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Controller.php, src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Passes/Apple_Wallet/Event_Modifier.php
- Adding event data to the sample Apple Wallet pass.
- Fixing textdomain and lint.
- Remove checks to see if TEC is active, as we're already in TEC.
https://github.com/the-events-calendar/the-events-calendar/assets/252415/088c1d5e-3d4e-48d9-9d6e-a74784bfdb6a
=> Add event data to wallet pass sample.

src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Controller.php, src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Passes/Apple_Wallet/Event_Modifier.php
See https://github.com/the-events-calendar/event-tickets-wallet-plus/pull/79 for more details
[ETWP-82]
[ETWP-82]: https://stellarwp.atlassian.net/browse/ETWP-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Modify filters to match new sample implamentaton for Apple Wallet

readme.txt, src/views/v2/list/event/featured-image.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image_with_alt__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image_without_alt__1.php
[TEC-4919](https://stellarwp.atlassian.net/browse/TEC-4919)
SEO Improvement - define image sizes on the List view featured image to avoid Content Layout Shifting.
[TEC-4919]: https://stellarwp.atlassian.net/browse/TEC-4919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> List View SEO Improvement.

readme.txt, src/Tribe/Views/V2/Hooks.php, src/Tribe/Views/V2/Template_Bootstrap.php, tests/wpunit/Tribe/Events/VenueTest.php
Reverts the-events-calendar/the-events-calendar#4420
=> Revert "Fix/ecp 1059 venue title"

readme.txt, src/Tribe/Rewrite.php, tests/wpunit/Tribe/Events/RewriteTest.php
Reverts the-events-calendar/the-events-calendar#4443
=> Revert "Fix for the pagination base property."

readme.txt, src/Tribe/Rewrite.php, tests/wpunit/Tribe/Events/RewriteTest.php
Reverts the-events-calendar/the-events-calendar#4458
=> Revert "Fix/tec 4979 pagination base localized"

readme.txt, src/Tribe/Rewrite.php, tests/wpunit/Tribe/Events/RewriteTest.php
Reverts the-events-calendar/the-events-calendar#4461
=> Revert "Revert "Fix/tec 4979 pagination base localized""

readme.txt
Release: Update pot file and readme.
=> Release: Pot file changes

readme.txt, src/Events/Integrations/Plugins/Event_Tickets/Site_Health/Controller.php, src/Events/Integrations/Plugins/Event_Tickets/Site_Health/Subsection.php
Update changelog
Replace TBD with version num
=> Release: Changelog

readme.txt
=> date change

src/functions/template-tags/loop.php, src/views/blocks/event-links.php, src/views/single-event.php, src/views/v2/components/data.php
Fixing several PHPStan errors, such as:
```
Line   src/functions/template-tags/loop.php                               
------ ------------------------------------------------------------------- 
111    One or more @param tags has an invalid name or invalid syntax.     
212    @param Context $context does not accept actual type of parameter:  
Tribe__Context.                                                    
532    Expected 3 @param tags, found 2.                                   
542    One or more @param tags has an invalid name or invalid syntax. 
```
=> Several doc and type updates.

src/Tribe/Assets.php
=> Bump common.

readme.txt
Moving release date from 3/11/2024 to 3/12/2024
=> Release date bump

src/Events/Integrations/Plugins/Elementor/Assets_Manager.php, src/Events/Integrations/Plugins/Elementor/Widgets/Contracts/Abstract_Widget.php, src/Events/Integrations/Plugins/Elementor/Widgets/Event_Datetime.php, src/resources/postcss/integrations/plugins/elementor/icons.pcss, src/resources/postcss/integrations/plugins/elementor/widgets/event-categories.pcss, src/resources/postcss/integrations/plugins/elementor/widgets/event-export.pcss, src/resources/postcss/integrations/plugins/elementor/widgets/event-navigation.pcss, src/resources/postcss/integrations/plugins/elementor/widgets/event-organizer.pcss, src/resources/postcss/integrations/plugins/elementor/widgets/event-status.pcss, src/resources/postcss/integrations/plugins/elementor/widgets/event-tags.pcss, src/resources/postcss/integrations/plugins/elementor/widgets/event-venue.pcss, src/resources/postcss/integrations/plugins/elementor/widgets/event-website.pcss, src/views/integrations/elementor/templates/starter.php
@todo: remove VE and ECP widgets!
=> Fix namespacing and update some of the template widgets.

src/Events/Integrations/Plugins/Elementor/Controller.php, src/Events/Integrations/Plugins/Elementor/Template/Controller.php, src/admin-views/integrations/plugins/elementor/switch-warning.php, src/resources/postcss/integrations/plugins/elementor/admin.pcss
[ECP-1696]
Prevent switching to Elementor before the Event is properly set.
https://i.bordoni.me/f1ltY0wS
[ECP-1696]: https://stellarwp.atlassian.net/browse/ECP-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevent switching to Elementor before Events is Saved

src/Events/Integrations/Plugins/Elementor/Template/Controller.php, src/admin-views/tribe-options-display.php
[ECP-1698]
[ECP-1698]: https://stellarwp.atlassian.net/browse/ECP-1698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> When using Elementor force Events Template settings

src/Events/Integrations/Plugins/Elementor/Widgets/Event_Datetime.php, src/Events/Integrations/Plugins/Elementor/Widgets/Traits/Has_Preview_Data.php, src/views/integrations/elementor/widgets/event-datetime.php, src/views/integrations/elementor/widgets/event-datetime/all-day.php, src/views/integrations/elementor/widgets/event-datetime/end-date.php, src/views/integrations/elementor/widgets/event-datetime/end-time.php, src/views/integrations/elementor/widgets/event-datetime/separator.php, src/views/integrations/elementor/widgets/event-datetime/start-date.php, src/views/integrations/elementor/widgets/event-datetime/start-time.php
[ECP-1745]
Break up the template and fix some of the display logic
[ECP-1745]: https://stellarwp.atlassian.net/browse/ECP-1745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Break up the template and fix some of the display logic

readme.txt
=> Bump tested

src/Events/Integrations/Plugins/Event_Tickets/Emails/Emails.php
Fix the Venue Website URL in the Email Preview
=> Fix the Venue Website URL in the Email Preview

readme.txt, src/Tribe/Main.php
=> Readme change and change to get tests to run.

src/Events/Integrations/Plugins/Elementor/Controller.php, src/Events/Integrations/Plugins/Elementor/Template/Controller.php, src/Tribe/Views/V2/Template_Bootstrap.php, src/views/integrations/elementor/templates/blank.php
[ECP-1608]
Watch the video, it's a bit complicated.
https://i.bordoni.me/FSby0nmF
[ECP-1608]: https://stellarwp.atlassian.net/browse/ECP-1608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Elementor Pro ThemeBuilder locations working as expected

readme.txt, the-events-calendar.php
=> Corgi: Update Release Date

src/Events/Integrations/Plugins/Elementor/Assets_Manager.php, src/Events/Integrations/Plugins/Elementor/Widgets/Contracts/Abstract_Widget.php, src/Events/Integrations/Plugins/Elementor/Widgets/Event_Calendar_Link.php, src/Events/Integrations/Plugins/Elementor/Widgets/Event_Status.php, src/resources/postcss/integrations/plugins/elementor/widgets/widget-base.pcss, src/views/integrations/elementor/widgets/empty.php, src/views/integrations/elementor/widgets/event-status.php, tests/elementor_integration/Widgets/partials/__snapshots__/Event_CostTest__render_filtered__header_tag__0.snapshot.html
Remove unused param in calendar link widget.
[ECP-1781]
[ECP-1781]: https://stellarwp.atlassian.net/browse/ECP-1781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add event query to status widget.

src/Events/Integrations/Plugins/Elementor/Widgets/Event_Categories.php
Fix mismatched control name
[ECP-1779]
[ECP-1779]: https://stellarwp.atlassian.net/browse/ECP-1779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Category html tag

src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php
Make the map height attribute 100% to prevent weirdness. Remove the width control - it does nothing.
Rename the max-width control to width to make it more intuitive.
[ECP-1771]
[ECP-1771]: https://stellarwp.atlassian.net/browse/ECP-1771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Correct map style applications to apply to the container properly.

src/Events/Integrations/Plugins/Elementor/Widgets/Event_Venue.php, tests/elementor_integration/Widgets/partials/__snapshots__/Event_CostTest__render_filtered__header_tag__0.snapshot.html
[ECP-1772]
[ECP-1772]: https://stellarwp.atlassian.net/browse/ECP-1772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add control for mocking multiple venues

src/views/integrations/elementor/widgets/event-datetime.php, src/views/integrations/elementor/widgets/event-datetime/end-date.php, src/views/integrations/elementor/widgets/event-datetime/end-time.php, src/views/integrations/elementor/widgets/event-datetime/start-time.php
Also, don't show any times for all day events.
=> Remove the "all day" text for all day events.

src/resources/postcss/integrations/plugins/elementor/widgets/export.pcss, src/views/integrations/elementor/widgets/event-export/button.php
Tweak caret in export button to scale with text.
[ECP-1775]
[ECP-1775]: https://stellarwp.atlassian.net/browse/ECP-1775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Tweak button to resize based on content. 

readme.txt, src/views/v2/list/event/featured-image.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/Featured_ImageTest.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image_with_alt__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image_without_alt__1.php
[TEC-5023]
Add "aria-hidden=true" on the image in `the-events-calendar\src\views\v2\list\event\featured-image.php`
[TEC-5023]: https://stellarwp.atlassian.net/browse/TEC-5023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-5023 Add "aria-hidden=true" on the events list image

.github/workflows/phpstan.yml, src/functions/template-tags/general.php, src/functions/template-tags/loop.php, src/views/single-event/recurring-description.php
Fixing several PHPStan errors, and removing all phpstan tests except for php 7.4
=> Fix several phpstan errors.

readme.txt, src/Tribe/Views/V2/Views/Reflector_View.php
[SVUL-2]
Hotfix
[SVUL-2]: https://stellarwp.atlassian.net/browse/SVUL-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Sanitize JSON

readme.txt, src/Events/Integrations/Integration_Abstract.php, src/Events/Integrations/Plugins/Elementor/Controller.php, src/Events/Integrations/Plugins/Elementor/Widgets/Event_Status.php, src/Tribe/Shortcode/Event_Details.php
Clearing house for fixes related to the ESET release.
- fix a typo
- fix potential to call an undefined method in the Status Widget
- Fix an incorrect permission check 
- Add a hook to the controller to signal it is loaded.
[ECP-1797]
[ECP-1797]: https://stellarwp.atlassian.net/browse/ECP-1797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ESET fixes

src/Events/Integrations/Plugins/Elementor/Template/Controller.php
Instead, override the selected template for single events. With filters.
[BTRIA-2395]
[BTRIA-2395]: https://stellarwp.atlassian.net/browse/BTRIA-2395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Stop hiding the template selector.

readme.txt, src/Events/Integrations/Plugins/Elementor/Widgets_Manager.php
[TEC-5091]
[TEC-5091]: https://stellarwp.atlassian.net/browse/TEC-5091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a new hook.

readme.txt, src/functions/advanced-functions/event.php
=> DocBlock: `tribe_update_event()`

readme.txt, src/Events/Integrations/Plugins/Tickets_Wallet_Plus/Controller.php, src/Tribe/Main.php, tests/wpunit/Tribe/Events/CommonTest.php
[ETP-917]
Updating the template paths for ETWP integrations
[ETP-917]: https://stellarwp.atlassian.net/browse/ETP-917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix ETWP paths after merger

readme.txt, src/functions/advanced-functions/event.php
=> DocBlock: `tribe_create_event()`

readme.txt, src/functions/advanced-functions/organizer.php
=> DocBlock: `tribe_create_organizer()`

src/Tribe/Main.php, the-events-calendar.php
Bump our version for upcoming release. We will need to use this for ECP and ET+ due to EVA moving into `common`.
=> Bump version for upcoming release.

.github/workflows/tests-php.yml, package.json
=> Bump version.

readme.txt, src/functions/advanced-functions/venue.php
Minor tweak to add a legacy note to docblock for `tribe_create_venue()`
=> DocBlock: `tribe_create_venue()`

readme.txt, src/functions/advanced-functions/organizer.php
Minor tweak to add a legacy note to docblock for `tribe_update_organizer()`
=> DocBlock: `tribe_update_organizer()`

readme.txt, src/Tribe/Featured_Events/Permalinks_Helper.php
Minor tweak adding docblocks to the `Tribe__Events__Featured_Events__Permalinks_Helper` class
=> DockBlock: `Tribe__Events__Featured_Events__Permalinks_Helper`

package.json, readme.txt, src/Tribe/Main.php, the-events-calendar.php
=> Prep for final release: asag

readme.txt, src/Events/Installer/Provider.php
=> Update language in readme

readme.txt, src/Tribe/Main.php
Update readme's language entry for 6.5.1.2
=> Update readme's language

readme.txt
=> Update readme's lang

readme.txt, src/Tribe/Views/V2/View.php
N/A - small tweak not requiring QA. 
Adds `@param` and corrected `@return` to docblock for `filter_display_events_bar()`. In favor of #4613 - credit goes to @iandelmar for the fix.
=> DocBlock: `filter_display_events_bar`

readme.txt
=> Update changelog for release 6.5.1.4

readme.txt, src/Tribe/Views/V2/functions/classes.php
Updated docblock and notes for the `month_multiday_classes` method and the `tribe_events_views_v2_month_multiday_classes` filter.
=> docBlock: `month_multiday_classes` and `tribe_events_views_v2_month_multiday_classes`

readme.txt, src/functions/template-tags/link.php
- Added a detailed description of the function's parameters and return value.
- Included information about the applied filters and their parameters.
[TICKET_ID]
=> Enhanced docblock for tribe_get_view_permalink function

src/Tribe/Assets.php
[ECP-1811]
[ECP-1811]: https://stellarwp.atlassian.net/browse/ECP-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Force a check for the override stylesheet before enqueuing it.

composer.json, composer.lock
No ticket
Small tweak to the changelogger tool to add the "Version" type of changelog.
=> Changelogger - Add Version Type

readme.txt, src/Tribe/Assets.php
[ECP-1811]
[ECP-1811]: https://stellarwp.atlassian.net/browse/ECP-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure we don't try to enqueue nonexistent override stylesheets.

composer.json, composer.lock
None
In addition to the global file addition in PR #4684  this PR adds the rest of the changes in https://github.com/the-events-calendar/the-events-calendar/pull/4682/ to add the file path to the composer.json and update the composer.lock hash.
=> Changelogger SemVer - TEC specific composer changes 

changelog/fix-docblock-make_select_box, src/Tribe/Importer/Column_Mapper.php
Add docblock for `make_select_box()`
Readme is missing. Will be done with changelogger.
=> Docblock:  `make_select_box()`

src/admin-views/tribe-options-general.php, src/admin-views/tribe-options-imports.php
[TEC-5133]
Before this change:
After this change:
[TEC-5133]: https://stellarwp.atlassian.net/browse/TEC-5133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix import settings output

src/admin-views/settings/tabs/display/display-calendar.php, src/admin-views/settings/tabs/display/display-date-time.php, src/admin-views/settings/tabs/display/display-maps.php
- **Update display-calendar section to match design**
- **Fix the date & time display tab**
- **Move Google Maps infobox to top**
[TICKET_ID]
=> Fix the display settings sections

src/Tribe/Admin/Provider.php, src/Tribe/Admin/Settings.php, src/admin-views/settings/sidebars/default-sidebar.php, src/admin-views/tribe-options-general.php
- **:fast_forward: https://github.com/the-events-calendar/tribe-common/commit/0e62dded808175ee53ff44ef130e32902ddf48ab**
- **Delete general sidebar, create default sidebar**
- **Register default sidebar**
[TICKET_ID]
=> Use default sidebar for all tabs

changelog/enhancement-TEC-4846-1-filter-additional-organizer-data, composer.lock, src/Tribe/Importer/File_Importer_Organizers.php
[TEC-4846]
With CSV imports it is possible to add extra columns when importing events, and have them saved.
For Organizers and Venues columns can be added for the column mapping, however, it is not possible to save the additional data, because a block of code and filter - what is available for events - is missing.
This PR fixes this for Organizers.
[Screen recording](https://1drv.ms/v/s!Aqh6lbOjUW1ThZhvEm-i-8104YtYUg?e=o7pD2T)
[TEC-4846]: https://stellarwp.atlassian.net/browse/TEC-4846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TEC-4846] Filter additional organizer data for CSV import

changelog/fix-docblock-tribe_get_listview_next_link, src/functions/template-tags/link.php
Added detailed descripions, parameter types, and return structure.
[TICKET_ID]
=> Updated docblock for `tribe_get_listview_args` 

src/admin-views/settings/tabs/display/display-date-time.php, src/admin-views/tribe-options-imports.php
- **Add proper class to date/time description**
- **Remove unnecessary HR elements**
- **Wrap settings in content block divs**
- **:fast_forward: https://github.com/the-events-calendar/tribe-common/commit/230384e90e9a065c4637c237d5a8fbad76442ee1**
- **:fast_forward: https://github.com/the-events-calendar/tribe-common/commit/ea0827674bcc0c7b67f156f81eb04b173064d0d2**
=> DQA fixes for Admin Settings

changelog/fix-docblock-tribe_get_event_link, src/functions/template-tags/link.php
Added detailed description, parameter types, and return structure.
[TICKET_ID]
=> Updated docblock for `tribe_get_event_link` 

changelog/fix-docblock-tribe_get_listview_prev_link, src/functions/template-tags/link.php
Added detailed descriptions, parameter types, and return structure.
[TICKET_ID]
=> Updated docblock for `tribe_get_listview_prev_link`

src/Events/Custom_Tables/V1/WP_Query/Custom_Tables_Query.php
[TEC-5155]
[TEC-5155]: https://stellarwp.atlassian.net/browse/TEC-5155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix regex for determining order and orderby

src/Tribe/Views/V2/Views/Latest_Past_View.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php
Bug was introduced at some point, which was causing an error when running the `views_integration` tests. This PR fixes the bug that was causing the error and updates the related snapshots.
=> Fixing broken tests

changelog/docblock-Tribe__Events__Aggregator__Records, src/Tribe/Aggregator/Records.php
Update docblocks in the `Tribe__Events__Aggregator__Records` class.
=> Docblock: `Tribe__Events__Aggregator__Records`

changelog/fix-docblock-tribe_get_listview_display, src/functions/template-tags/link.php
Include changelog file
[TICKET_ID]
=> Enhance docblock for `tribe_get_listview_display` function.

changelog.md
=> update changelog release date

changelog/feat-update-seating-requirements, changelog/feat-update-seating-requirements-2, changelog/feat-update-seating-requirements-3, src/Tribe/Main.php, src/Tribe/Plugin_Register.php
=> Update TEC requirements for seating

package.json, readme.txt, src/Tribe/Main.php, the-events-calendar.php
=> Fext Version Update

changelog/feat-seating-changelogs
=> Added Seating changelog

changelog.md, changelog/feat-seating-changelogs, changelog/feat-update-seating-requirements, changelog/feat-update-seating-requirements-2, changelog/feat-update-seating-requirements-3, readme.txt
=> process changelogs

changelog.md, readme.txt
=> Update changelog for fext

changelog/TEC-5316-tec-tweaks-compatibility, src/Events/Integrations/Plugins/TEC_Tweaks_Extension/Provider.php
[TEC-5316]
With TEC 6.5.0 we added code for compatibility with the TEC Tweaks extension. The code hooks into a filter with 2 params, but the filter only accepts one parameter, and as a result, throws a fatal error when visiting any Events > Settings page.
[Screenshot the of fatal.](https://www.dropbox.com/scl/fi/afp7n8yn8xtn2nzz3pa8r/shot_241105_133205.jpg?rlkey=jogsddtmennrnqxkv5yx5u6sz&e=1&dl=0)
[Screenshot of the Tweaks settings page when fixed.](https://www.dropbox.com/scl/fi/a548uj990inlp1nacfa0w/shot_241105_133229.jpg?rlkey=6pec229ibnxelvv3hxtbad4yh&e=1&dl=0)
[TEC-5316]: https://stellarwp.atlassian.net/browse/TEC-5316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-5316 Fix TEC Tweaks compatibility

src/Tribe/Admin/Bar/Default_Configurator.php
The link for "Help" needed to be updated since it was going to the old one.
=> Help Hub - Help Menu

changelog/fix-docblock-tribe_the_prev_event_link, src/functions/template-tags/link.php
Adding detailed descriptions and missing tags
[TICKET_ID]
=> Enhance docblock for tribe_the_prev_event_link

src/Events/Telemetry/Telemetry.php
=> Fix phpcs for freybug

src/Events/Admin/Help_Hub/TEC_Hub_Resource_Data.php, src/Tribe/Admin/Settings.php, src/Tribe/Assets.php, src/Tribe/Main.php
=> Replace TBDs for freybug

src/Events/Telemetry/Telemetry.php
=> Prevent showing the opt in telemetry modal in events list page

readme.txt
Update tested up to header for freybug
=>  Update tested up to header

src/Events/Telemetry/Telemetry.php, tests/views_v2_customizer_integration/__snapshots__/CustomizerSettingsTest__it_should_allow_taking_a_snapshot_from_database__1.php
Make sure we access a property that exists.
=> Make sure we access a property that exists

changelog/fix-docblock-tribe_get_previous_events_link, src/functions/template-tags/link.php
=> Fix/docblock tribe get previous events link function.

src/Events/Notifications/Provider.php
🎫 Ticket
[TEC-5165](https://stellarwp.atlassian.net/browse/TEC-5165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Fixes a fatal when downgrading TEC. Followup to https://github.com/the-events-calendar/the-events-calendar/pull/4798
[TEC-5165]: https://stellarwp.atlassian.net/browse/TEC-5165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Avoid fatal when downgrading TEC

changelog/tweak-tectria-568, src/Events/Telemetry/Telemetry.php
[TECTRIA-568]
Heading needed to be updated to "Data share consent".
[TECTRIA-568]: https://stellarwp.atlassian.net/browse/TECTRIA-568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TECTRIA-568] Updated label for Telemetry heading.

src/Events/Admin/Onboarding/Steps/Venue.php
Sheet issue
We have to get the country name from the list, we were passing the abbreviation (which still should save)
=> Fix the Venue country not saving

src/resources/packages/wizard/components/tabs/welcome/inputs/opt-in.tsx
Smoketest issue
URL was missing from permissions link
=> Add the missing URL to the anchor

src/Events/Admin/Settings/Community_Upsell.php, src/Events/Admin/Settings/Filter_Bar_Upsell.php
Requires filter alteration in common. See https://github.com/the-events-calendar/tribe-common/pull/2325
=> Add a sanity check for the upsell classes.

.github/workflows/zip.yml
=> Add more checks for final zips

changelog/fix-jit-translation-aggregator-origins, src/Tribe/Aggregator/API/Origins.php, tests/wpunit/Tribe/Events/Aggregator/API/OriginsTest.php
[TEC-5341]
Modifies the EA fix to ensure it does not throw JIT translation errors.
Note: Debug Bar throws these errors, so you have to be ready to wade through them when testing.
Fixed: 
[TEC-5341]: https://stellarwp.atlassian.net/browse/TEC-5341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update EA code change for translations and add changelog

package.json, readme.txt, src/Tribe/Main.php, the-events-calendar.php
=> Version bumped

src/Events/Custom_Tables/V1/Migration/Provider.php, src/Events/Integrations/Plugins/Elementor/Controller.php, src/Tribe/Aggregator/API/Origins.php, src/Tribe/Aggregator/Errors.php, src/Tribe/Views/V2/Rest_Endpoint.php, src/admin-views/settings/tabs/display/display-calendar.php
=> TBD replacements

composer.json, composer.lock
=> update to stable

changelog.md, readme.txt
=> Update changelog for imp

changelog.md, readme.txt
=> Re update changelog entries

changelog/fix-ECP-1613-Divi-z-index-conflict, src/resources/postcss/events-admin.pcss
Reverts the-events-calendar/the-events-calendar#4880
=> Revert "ECP-1613 Divi Z-Index Conflict"

phpcs.xml, src/admin-views/settings/tabs/general/general-debugging.php, src/admin-views/settings/tabs/general/general-viewing.php
Fixing a couple of wrong text-domain calls.
Adding phpcs rule for catching those in the future during CRs.
=> Fix wrong text domain

.github/workflows/tests-integrations.yml, .github/workflows/tests-php-seo-plugin.yml, .github/workflows/tests-php.yml
=> Fix - updated deprecated action cache version.

changelog/docblock-ical-php, src/Tribe/iCal.php
Update docblocks in the iCal.php file
=> Docblock: ical.php

src/modules/elements/dashboard/element.js, src/modules/elements/date-picker/element.js, src/modules/elements/input/element.js, src/modules/elements/month/element.js, src/modules/elements/search-posts/template.js, src/modules/elements/terms-list/element.js, src/modules/elements/timezone/element.js, src/modules/elements/venue-form/element.js, src/resources/postcss/base/full/_view.pcss
N/A
On a mission to fix all linting tests for the TEC plugin. I'll be doing these in bite-sized chunks so they're not too overwhelming to review.
This PR covers the element modules and a single pcss error that was occurring.
=> Fix linting errors for element modules

changelog/fix-TEC-5397-add-ecp-link-to-onboarding, src/resources/packages/wizard/components/tabs/display/tab.tsx
[TEC-5397]
Added the URL for the ECP download in the Onboarding Wizard process when you choose a calendar layout view.
Before: 
After:
[TEC-5397]: https://stellarwp.atlassian.net/browse/TEC-5397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TEC-5397] Added link for ECP in Onboarding Wizard

changelog/feature-add_ian_for_et, src/Events/Notifications/Notifications.php
🎫 Ticket
[ET-2294](https://stellarwp.atlassian.net/browse/ET-2294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
🗒️ Description
Load IAN notifications in ET. These changes are alongside these:
https://github.com/the-events-calendar/event-tickets/pull/3563
https://github.com/the-events-calendar/tribe-common/pull/2396
[ET-2294]: https://stellarwp.atlassian.net/browse/ET-2294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add notifications for ET

src/Events/Calendar_Embeds/Admin/List_Table.php, src/Events/Calendar_Embeds/Admin/Page.php, src/Events/Calendar_Embeds/Calendar_Embeds.php, src/Events/Calendar_Embeds/Controller.php, src/Tribe/Assets.php, src/admin-views/calendar-embeds/embed-snippet-content.php, src/admin-views/calendar_embeds/modal.php, src/resources/js/admin/calendar-embeds-page.js, src/resources/postcss/admin/calendar-embeds-page.pcss, tests/wpunit/TEC/Events/Calendar_Embeds/Admin/List_TableTest.php, tests/wpunit/TEC/Events/Calendar_Embeds/Admin/PageTest.php, tests/wpunit/TEC/Events/Calendar_Embeds/Admin/__snapshots__/List_TableTest__testManageColumnContent__1.php, tests/wpunit/TEC/Events/Calendar_Embeds/Calendar_EmbedsTest.php
[TEC-5388]
Admin Table List customizations. 
[TEC-5388]: https://stellarwp.atlassian.net/browse/TEC-5388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TEC-5388] Calendar Embeds: Admin List Table Customizations

changelog/task-run-analuze-batman-1, changelog/task-run-analuze-batman-2, changelog/task-run-analuze-batman-3, changelog/task-run-analuze-batman-4
=> Analyze changelogs added

.github/workflows/phpstan.yml, .github/workflows/tests-integrations.yml, .github/workflows/tests-php-seo-plugin.yml, .github/workflows/tests-php.yml
Update workflows to use ubuntu-latest
=> update GH workflows

.github/workflows/tests-php-seo-plugin.yml
Fixing Yoast SEO workflow by updating wp core version to wp 6.6
=> Fix Yoast SEO workflow

.distfiles
=> Include ECE assets

package.json, readme.txt, src/Tribe/Main.php, the-events-calendar.php
Reverts the-events-calendar/the-events-calendar#4996
=> Revert "[BOT] Version bump for 'release/T25.colossus'"

src/Tribe/Admin/Notice/Install_Event_Tickets.php
Release task for Colossus
Replace `TBD` with `6.10.3`.
=> Replace TBD with 6.10.3

src/Tribe/Editor.php, src/Tribe/Main.php
Fixes group path registations to avoid double `//`
=> fix group path registration and phpcs

changelog/fix-enable-copy-widgets-from-diff-site, src/Tribe/Views/V2/Hooks.php, src/Tribe/Views/V2/Widgets/Service_Provider.php
This resolves a problem reported internally in preparation for an internal project, where copying any of our widgets across sites would break.
https://i.bordoni.me/hc4Yg75F
=> Enable sharing Widgets across diff Block Editors

src/Events/QR/Controller.php, src/Events/QR/QR_Code.php, src/Events/QR/Redirections.php, src/Events/QR/Settings.php, src/Tribe/Views/V2/Widgets/Widget_QR_Code.php, src/admin-views/settings/tabs/display/display-qr-codes.php, tests/integration/Tribe/Events/Integrations/QR/QR_CodeTest.php, tests/integration/Tribe/Events/Integrations/QR/RoutesTest.php, tests/integration/Tribe/Events/Integrations/QR/SettingsTest.php
[TEC-5396]
Fixing [QA reported issues](https://docs.google.com/spreadsheets/d/1NzXAjMpzE7Cum9rOix2ctIjEsdpR_YgFLLMKvnGtzkk/edit?gid=2103530230#gid=2103530230). This PR fixes:
- `wp_safe_redirect()` didn't allow for external links as fallbacks
- order of operations issue: Routes class properties were empty when QR class was calling them
- when the option to enable QR does not exist (clean WP) initialize it with true
- do not show Next_in_Series option anywhere if ECP is not enabled
- adds a filter to delete images so that they can be regenerated
- fixes wording in Settings page to be more clear
- makes the Event/Series input fields as dropdowns
[TEC-5396]: https://stellarwp.atlassian.net/browse/TEC-5396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> QA fixes for QR code

changelog/fix-TEC-5447-solving-saving-render-widget, src/Tribe/Views/V2/Widgets/Service_Provider.php
[TEC-5447]
[TEC-5447]: https://stellarwp.atlassian.net/browse/TEC-5447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Changelog + Fixing the Blocks for Event Widgets

.puprc, src/Tribe/Editor/Blocks/Block_Trait.php, src/Tribe/Editor/Blocks/Featured_Image.php
Prevent asset registration when there are none to be registered
=> Prevent asset registration when there are none to be registered

src/resources/postcss/qr-code.pcss
so it starts with mobile and changes on larger screens
=> Fix media query for QR code

src/Events/Admin/Onboarding/Data.php
Bug found during regression test of T25.ego
Exclude QR Widget View from onboarding Wizard
=> Exclude QR Widget View from onboarding Wizard

.puprc, src/Events/Admin/Onboarding/Controller.php, src/Events/Admin/Onboarding/Landing_Page.php, src/resources/packages/wizard/components/tabs/welcome/tab.tsx, webpack.config.js
It also adds a new filter to allow users to force-ignore the checks and display the wizard. 
And a new filter to allow users to force-redirect to the Guided Setup page.
AND a workflow that allows us to rebuild just TEC without rebuilding TCMN to save time. `pup do rebuild`
Also tweaks the zip workflow for creating a zip locally (still needs some testing)
Those filters should likely be removed before deploy, but they will make dev and QA lives easier
[TEC-5425]
This is a tweak to the implementation of "Tyson"
[TEC-5425]: https://stellarwp.atlassian.net/browse/TEC-5425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> This PR fixes some asset-path issues with the new build process.

src/Tribe/Main.php
Introduces action for the fully loaded event
=> Fully loaded action introduction for TEC

src/Events/Admin/Help_Hub/TEC_Hub_Resource_Data.php
[ET-2407](https://stellarwp.atlassian.net/browse/ET-2407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
See https://github.com/the-events-calendar/tribe-common/pull/2523 for main PR
This work refactors the Resource class for TEC based off changes in common.
[ET-2407]: https://stellarwp.atlassian.net/browse/ET-2407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ET-2407] Refactor Help Hub for ET Work

changelog/fix-tec-a11y-updates, src/views/blocks/parts/subscribe-list.php, src/views/v2/components/subscribe-links/single-event-list.php, tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_no_custom_classes__1.php, tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_with_multiple_custom_classes__1.php, tests/views_integration/Tribe/Events/Views/Blocks/__snapshots__/Event_LinksTest__test_render_with_single_custom_class__1.php
[TEC-5088]
* Add aria-label attribute to View calendar button.
🎥 screencast(s): https://www.loom.com/share/6a7de26cfd6c477ba033f9480ea3291d
Note: First showing the applied fix, then showing the before state from demo site.
[TEC-5088]: https://stellarwp.atlassian.net/browse/TEC-5088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix - TEC a11y - Render missing aria label.

.github/workflows/tests-php.yml
=> Update min WP version

tests/ct1_integration/TEC/Events/Custom_Tables/V1/WP_Query/__snapshots__/Custom_Tables_QueryTest__should_not_run_found_rows_query_twice_per_single_query__1.php, tests/ct1_integration/__snapshots__/Tribe__Events__Query_CT1_Test__should_not_filter_and_order_query_for_not_only_events__1.php
=> Update snapshots for ct1_integration

tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php, tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
[TICKET_ID]
[skip-changelog]
Update the test snapshots after changes in a different PR.
=> Update snapshots for views integration

src/Events/QR/Controller.php, src/deprecated/Tribe__Events__Integrations__Freemius.php
Addresses issue in QA
https://lw.slack.com/archives/C0714HQSMEW/p1747407258176479
=> use `tec_asset` instead of `tribe_asset`

src/Events/Traits/Block_Trait.php, src/Tribe/Editor/Blocks/Classic_Event_Details.php, src/Tribe/Editor/Blocks/Event_Category.php, src/Tribe/Editor/Blocks/Event_Datetime.php, src/Tribe/Editor/Blocks/Event_Links.php, src/Tribe/Editor/Blocks/Event_Organizer.php, src/Tribe/Editor/Blocks/Event_Price.php, src/Tribe/Editor/Blocks/Event_Tags.php, src/Tribe/Editor/Blocks/Event_Venue.php, src/Tribe/Editor/Blocks/Event_Website.php, src/Tribe/Editor/Blocks/Featured_Image.php
[TICKET_ID]
1. Move `Block_Trait` into the `src/Events/Traits/` directory.
2. Update references to the trait to use the new namespace.
3. Use string interpolation for strings in the Block_Trait
[skip-changelog]
=> Move Block_Trait into Traits directory

src/resources/js/events-admin.js
Exposing the tribe_datepicker_opts object into the global scope
=> Exposing the tribe_datepicker_opts object into the global scope

src/Events/Category_Colors/Admin/Controller.php, src/admin-views/category-colors/add-category-fields.php, src/admin-views/category-colors/category-color-preview.php, src/admin-views/category-colors/edit-category-fields-table.php, src/admin-views/category-colors/quick-edit-color-selection.php, src/resources/js/admin/category-colors/admin-category.js, src/resources/postcss/admin/category-colors/admin-category.pcss, src/resources/postcss/admin/category-colors/wp-picker.pcss, tests/integration_category_colors/Admin/__snapshots__/Quick_Edit_Test__should_add_quick_edit_fields__1.php, tests/integration_category_colors/Admin/__snapshots__/Quick_Edit_Test__should_add_quick_edit_fields_for_category_color_column__1.php
This fixes issues 23,24,25,26
- Added "None" as the placeholder text to the inputs
- Fixed missing styles/incorrect variable names
- Rewrote JS so that multiple color pickers don't open
- Fixed issue with color pickers randomly opening/closing
https://github.com/user-attachments/assets/81eeda3d-f5d5-470a-8ef3-3c587cf03633
=> Category Colors - DQA 23 24 25 26

src/Events/Classy/Controller.php, src/Events/Classy/Meta.php, src/Events/Classy/Supported_Post_Types.php, src/Tribe/Editor/Meta.php, src/Tribe/Editor/Provider.php, src/resources/packages/classy/constants.tsx, tests/classy_integration/Controller_Test.php, tests/classy_integration/Meta_Test.php
[TICKET_ID]
This updates Classy so that the date data is properly saved.
Notable changes:
1. Move the Classy meta handling into a new `Meta` class
2. Expand the Meta class functionality to include everything that used to be handled by the `Tribe__Events__Editor__Meta` class
* All of the fields from the old class have been added
* The `sanitize_callback` properties have been added, with logic for handling the different types of meta data
* The handling for custom UTC date generation has been added
* The handling for `_EventCost` meta has been added
3. The `Supported_Post_Types` trait has been added
4. Tests for Classy updated to match the new behavior, with a new test class added for the `Meta` class
Proof of Classy event **not** triggering a 404 with these changes: …
=> (Classy) Fix REST date save

changelog/fix-build-asset-paths, package-lock.json, package.json, src/Events/Custom_Tables/V1/Migration/Asset_Loader.php, src/Tribe/Admin/Timezone_Updater.php, src/Tribe/Integrations/ACF/ACF.php
[TECTRIA-1060]
Requires: https://github.com/the-events-calendar/tribe-common/pull/2622
[TECTRIA-1060]: https://stellarwp.atlassian.net/browse/TECTRIA-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix hardcoded asset paths

src/resources/packages/classy/index.ts, src/resources/packages/classy/store/selectors.ts
This updates the code relying on the Common component of Classy to use the correct `select` and `dispatch` functions and ensure the new initialization flow works correctly.
=> refactor(Classy) update following Common

src/Events/Category_Colors/Controller.php, src/Events/Category_Colors/Migration/Controller.php, src/Events/Category_Colors/Migration/Notice/Migration_Notice.php, src/Events/Category_Colors/Migration/Plugin_Manager.php, src/Events/Category_Colors/Migration/Processors/Post_Processor.php, src/resources/js/views/category-color-selector.js, src/resources/postcss/base/full/_variables.pcss, src/resources/postcss/category-colors/frontend-category.pcss, src/views/v2/list/event/date-tag.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_List_ViewTest__test_render_with_category_colors_disabled__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_List_ViewTest__test_render_with_event_list_view__1.php, tests/integration_category_colors/Migration/Notice/Migration_Notice_Test.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set on_same_day__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set on_same_day_past__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_after__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_after_past__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Date_TagTest__test_render_with_req_dates_and_multi_day_event_combination with data set one_week_before__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/EventTest__test_render_with_featured_event__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php
DQA Issues
- 38
- 39
- 43
- 44
- 45
- 46
Fixed an issue where the category color dropdown would not work once you switched between views and hovered over a tooltip.
Updated the featured labeling so that it defaults to a color if no category color is set. Also updated the styling so the icon/text is decoupled.
Updated the category color dropdown logic involving the default color circles, and displaying what circles are selected.
Fixed the migration modal to only appear on TEC pages.
The old category colors plugin should properly disable when the migration is completed.
https://github.com/user-attachments/assets/cfdc3db2-9bdc-4052-b231-16ea85665bcf
=> Small tweaks to get the frontend to look correct.

src/resources/js/views/category-color-selector.js
DQA Item
- 54 - Fixes an issue where the dropdown for Category Colors could render partially outside of the viewport on different themes.
https://github.com/user-attachments/assets/127ba925-87a0-4a07-8021-76d6a556a66f
=> Category Colors - Dropdown sometimes renders outside of viewport

changelog/tweak-TEC-5179-featured-alt, src/views/v2/day/event/featured-image.php, src/views/v2/list/event/featured-image.php, src/views/v2/month.php, src/views/v2/month/calendar-body/day.php, src/views/v2/month/calendar-body/day/calendar-events/calendar-event/featured-image.php, src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/featured-image.php, src/views/v2/month/calendar-body/day/cell-title.php, src/views/v2/month/calendar-header.php, tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - cats__0.snapshot.html, tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__no tags - no cats__0.snapshot.html, tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags - no cats__0.snapshot.html, tests/embed_calendar_integration/__snapshots__/Frontend_Test__it_should_overwrite_content__tags and cats__0.snapshot.html, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image_with_alt__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Day_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image_without_alt__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image_with_alt__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/Featured_ImageTest__test_render_with_event_with_featured_image_without_alt__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Calendar_Body/__snapshots__/DayTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/__snapshots__/Calendar_HeaderTest__test_render__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_hide_endtime__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php
Reverts the-events-calendar/the-events-calendar#4886
=> Revert "Updated featured images on calendar views, removed link wraps for accessibility."

src/views/v2/components/events-bar/views/list/item.php, tests/integration_category_colors/Frontend/Category_Color_Priority_Provider_Test.php, tests/integration_category_colors/Frontend/__snapshots__/CSS_Generator_Test__should_handle_hidden_categories__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/Views/Views_List/__snapshots__/ItemTest__test_render_with_view_is_current_view__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/Views/Views_List/__snapshots__/ItemTest__test_render_with_view_is_not_current_view__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/Views/__snapshots__/Views_ListTest__test_render_with_views__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/__snapshots__/ViewsTest__test_render_with_views_with_disabled_event_search__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/__snapshots__/ViewsTest__test_render_with_views_with_label_style__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/Events_Bar/__snapshots__/ViewsTest__test_render_with_views_with_tabs_style__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Events_BarTest__test_render_with_views__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Components/__snapshots__/Events_BarTest__test_render_with_views_disabled_event_search__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/Featured_ImageTest__test_render_with_featured_event_with_featured_image__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/Integrations/__snapshots__/Restrict_Content_Pro_Test__test_render_unrestricted__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Day_ViewTest__test_render_w_events_w_taxonomies__2.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Day View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set Month View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_hide_endtime__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Month_ViewTest__test_render_with_events_w_taxonomies__2.php, tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
[TEC-4402]
* The active list item was missing the aria-current attribute.
📷 screenshot(s): https://share.cleanshot.com/4YmGK2fk
[TEC-4402]: https://stellarwp.atlassian.net/browse/TEC-4402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TEC-4402] - add missing ARIA attribute.

src/resources/packages/classy/fields/EventDateTime/EventDateTime.tsx, src/resources/packages/classy/fields/EventLocation/EventLocation.tsx, src/resources/packages/classy/functions/renderFields.tsx
In this PR:
- **refactor(Classy) remove unused imports**
- **build(Common) track fix branch on common**
- **build(Common) track fix branch**
- **fix(Classy) date time field**
- **fix(Classy) start, end, timezone defaults on first save**
- **refactor(Classy) move Organizers after location**
- **fix(Classy) all-day toggle behavior**
Most of the changes to fix the `EventDateTime` field to rely on the updates to the `StartSelector` and `EndSelector` components in the [Common PR](https://github.com/the-events-calendar/tribe-common/pull/2669).
=> Classy - pre-demo fixes

changelog/tweak-tec_5533_add_disable_category_colors, changelog/tweak_5534_reset_button_tooltip, src/Events/Category_Colors/Controller.php, src/Events/Category_Colors/Settings/Settings.php, src/resources/js/views/category-color-selector.js, src/views/v2/components/top-bar/category-color-picker.php, tests/integration_category_colors/Frontend/CSS_Generator_Test.php, tests/integration_category_colors/Frontend/Category_Color_Priority_Provider_Test.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_day_view_superpowers_disabled__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_day_view_superpowers_enabled__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_list_view_superpowers_disabled__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_list_view_superpowers_enabled__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_month_view_superpowers_disabled__1.php, tests/integration_category_colors/Frontend/Views/V2/Partials/Components/__snapshots__/Category_Color_PickerTest__test_render_with_category_colors_enabled_month_view_superpowers_enabled__1.php
[TEC-5533]
[TEC-5536]
[TEC-5534]
This PR focuses on a few small changes for Category Colors:
- Added additional tooltip text to the "Reset Button" option to clearly point out that Legend Superpowers must be enabled.
- Added a new "Enable" option that enables/disables the frontend functionality for Category Colors. This option is enabled by default and must be disabled.
- Added the category class to the list item in the dropdown for more customization.
https://github.com/user-attachments/assets/5c8feeb9-148d-46ba-ada8-6b6c41bef97e
https://github.com/user-attachments/assets/42ff788a-c769-49c5-99fd-272b1bb2f655
[TEC-5533]: https://stellarwp.atlassian.net/browse/TEC-5533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TEC-5536]: …
=> Category Colors - FF

src/Tribe/Main.php
To intgegrate shepherd the priority of TCMN init needed to be lowered.
=> Needed for shepherd integration

docs/REST/TEC/V1/README.md, docs/REST/TEC/V1/creating-endpoints.md, docs/REST/TEC/V1/endpoints.md, docs/REST/TEC/V1/index.md, src/Events/REST/TEC/V1/Endpoints/Event.php, src/Events/REST/TEC/V1/Endpoints/Events.php, src/Events/REST/TEC/V1/Endpoints/Organizer.php, src/Events/REST/TEC/V1/Endpoints/Organizers.php, src/Events/REST/TEC/V1/Endpoints/Venue.php, src/Events/REST/TEC/V1/Endpoints/Venues.php
Updates The Events Calendar REST API documentation to reflect the architectural change of using WordPress core's validation/sanitization system instead of custom validation.
The common library has been refactored to:
- Delegate all validation/sanitization to WordPress REST API core
- Use a bridge pattern (`RequestBodyCollection::to_query_argument_collection()`) to maintain OpenAPI compatibility
- Let WordPress handle parameter type coercion, required field validation, and sanitization
- **README.md**: Added validation pipeline and RequestBodyCollection information
- **creating-endpoints.md**: Updated with new patterns for parameter definition
- **endpoints.md**: Clarified which collections to use for different operations
1. **Request Body Collections**: Documented that POST/PUT/PATCH …
=> feat(REST API): Update documentation with latest implementation

changelog/fix-TEC-5579-add-search-timezone, changelog/fix-TEC-5580-add-search-with-react-select, src/resources/packages/wizard/components/tabs/settings/tab.tsx, src/resources/packages/wizard/index.css
[TEC-5579]
[TEC-5580]
This PR primarily changes the dropdown from a `<select>` to a `<Select>` with `react-select` to allow for searching through the many timezone options. 
I also added some small tweaks to fix some errors I was seeing, such as:
- removing a rogue comma in the CSS file.
- ensuring that the select values for the start day of the week to be an integer as expected. 
- adding a dependency array to the `useSelect` hook to match the other `useSelects` and improve performance.
Before:
https://share.cleanshot.com/vnc89Bdy
After:
https://github.com/user-attachments/assets/2313dd6a-2803-44ca-9222-eef547d58cd2
[TEC-5579]: https://stellarwp.atlassian.net/browse/TEC-5579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TEC-5580]: …
=> TEC-5579 Add search with react-select

src/resources/packages/wizard/components/tabs/settings/tab.tsx
[TEC-5579]
I had added a small tweak to fix a linting issue:
However, adding the `parseInt` was causing console errors, and removing this tweak resolves that and the onboarding wizard functions as expected, so this PR just reverts that tweak. 
https://github.com/user-attachments/assets/26162188-7c31-4c7b-8809-5310e12a716a
[TEC-5579]: https://stellarwp.atlassian.net/browse/TEC-5579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEC-5579 - Remove parseInt causing console errors

changelog/tut-analyze, changelog/tweak-analyze-views
=> Tut Analyze.

changelog.md, readme.txt, src/Tribe/Plugin_Register.php
=> Add dependency for newer version of ECP.

changelog/fix-TEC-5208-landmarks-2, src/views/v2/list/nav.php, src/views/v2/list/top-bar/nav.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/NavTest__test_render_with_all_links__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/NavTest__test_render_without_next_url__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/NavTest__test_render_without_prev_and_next_url__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Top_Bar/__snapshots__/NavTest__test_render_without_prev_url__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/NavTest__test_render_with_all_links__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/NavTest__test_render_without_next_url__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/NavTest__test_render_without_prev_and_next_url__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/NavTest__test_render_without_prev_url__1.php, tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/__snapshots__/Top_BarTest__test_render_with_context__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/Latest_Past_ViewTest__should_correctly_render_in_the_context_of_month_view with data set List View__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_empty__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__1.php, tests/views_integration/Tribe/Events/Views/V2/Views/__snapshots__/List_ViewTest__test_render_with_upcoming_taxonomy_events__2.php, tests/views_integration/Tribe/Events/Views/V2/__snapshots__/ExtendingViewTest__should_render_the_default_view_if_view_not_found__1.php
[TEC-5208]
📷 screenshot(s):
Before: https://drive.google.com/file/d/1PkS9Bp8PUgvkIZCihEA2-dp8iaKuGiKv/view
After: https://share.cleanshot.com/X3F1CV2W
[TEC-5208]: https://stellarwp.atlassian.net/browse/TEC-5208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix - Nav tag aria labels added to avoid multiple landmarks with same generic role.
