public/template-tags/link.php

Currently the filter is called **tribe_get_next_event_link** however, the function is called **tribe_get_prev_event_link** so I think the filter should be named according to the function.

Rename tribe_get_prev_event_link filter

---

lib/API.php

When writing an import script that would check if the event already exists before creating a new one I would have a look at **Tribe__Events__API:: createEvent** to see what arguments were required. I saw that it sets the `post_type` argument to **Tribe__Events__Events::POSTTYPE** which is nice, so I don't have to.
Later I stumbled upon that when I found that my import script was not properly updating the existing events and I discovered that **Tribe__Events__API:: updateEvent** requires the `post_type` to be set properly in the passed arguments.
The behavior of updateEvent should be consistent with createEvent so this PR removes the if-clause and instead sets the post_type to the arg.

Let updateEvent set the 'post_type' arg like createEvent does

---

lib/the-events-calendar.class.php

mqTranslate saves all translations of a post title inside its `post_title` attribute. As such, when `get_event_link` retrieves it, it will display all translations concatenated instead of only the correct one.
Applying the `the_title` filter will only display the correct one.

Apply `the_title` filter to event title

---

admin-views/app-shop.php
admin-views/tribe-options-general.php
admin-views/tribe-options-help.php
lib/Activation_Page.php
lib/io/csv/admin-views/in-progress.php
lib/pue/lib/pue_plugin_info.class.php
lib/pue/lib/pue_plugin_update_engine.class.php
lib/template-classes/month.php
lib/the-events-calendar.class.php
lib/tribe-amalgamator.php
lib/tribe-ical.class.php
lib/tribe-settings.class.php
public/advanced-functions/meta.php
public/template-tags/day.php
public/template-tags/general.php
public/template-tags/google-map.php
public/template-tags/link.php
public/template-tags/loop.php
public/template-tags/month.php
public/template-tags/options.php
public/template-tags/organizer.php
public/template-tags/venue.php
views/day/single-event.php
views/list/nav.php
views/list/single-event.php
views/month/single-day.php
views/single-event.php
views/tickets/email.php
views/widgets/list-widget.php

This adds more extensive URL escaping for the core Events Calendar plugin.  In addition to addressing URLs that were manipulated with `add_query_arg()` / `remove_query_arg()`, we are adding escaping to other programmatically constructed URLs.

Escape URLs

---

resources/events-admin.css

The margins and background color are the defaults. The border color gets overridden by the WP dashboard styles. Removing this style declaration removes unneeded duplicate styles and eliminates the border that causes our notices to differ from default notices in WP.

Remove custom styles for the notice box.

---

src/Tribe/Tickets/Tickets_Pro.php

Just a simple change here. The path property was 1 directory too shallow in its definition, so all of the templates it was attempting to load were failing as they all had a `src/src/` in the path instead of `src/`.

fix Tickets_Pro path property

---

src/Tribe/Asset/Factory.php
src/Tribe/Template_Factory.php

Since PHP 5.2 doesn't like `static`, I needed to restructure my recent restructure a bit so other plugins can have their own Assets.
Related: https://github.com/moderntribe/events-pro/pull/12
See: https://central.tri.be/issues/36164 and https://central.tri.be/issues/33500

PHP 5.2 doesn't do `static`. Use `self`

---

dev/README.md
dev/grunt_options/clean.js
dev/grunt_options/csslint.js
dev/grunt_options/cssmin.js
dev/grunt_options/jshint.js
dev/grunt_options/preprocess.js
dev/grunt_options/uglify.js
dev/grunt_options/watch.js
dev/package.json

Related:
* https://github.com/moderntribe/events-community/pull/8
* https://github.com/moderntribe/events-eventbrite/pull/14
* https://github.com/moderntribe/events-facebook/pull/7
* https://github.com/moderntribe/events-filterbar/pull/5
* https://github.com/moderntribe/events-pro/pull/16
* https://github.com/moderntribe/events-tickets-edd/pull/5
* https://github.com/moderntribe/events-tickets-shopp/pull/4
* https://github.com/moderntribe/events-tickets-woo/pull/10
* https://github.com/moderntribe/events-tickets-wpec/pull/7
See: https://central.tri.be/issues/36506

Update grunt paths to match the restructured plugin directory

---

src/admin-views/tribe-options-display.php

Note: The link currently points to an unpublished page (see Leah's note [here](https://central.tri.be/issues/33364#note-5))
See: https://central.tri.be/issues/36369

Adding missing link to the Month Cache blurb on display settings page

---

src/Tribe/Tickets/Tickets.php

`! empty( $ticket->price )` evaluates to false if price is `0`. Using `isset` instead allows 0 to be interpreted as a number.
See: https://central.tri.be/issues/36107
---
This fix allows events with `$0` tickets to display `Free` next to it!

Allow tickets with a cost of 0 to affect the event price

---

src/functions/template-tags/loop.php

Ideally, the logic in these two functions would be merged in some way to keep it DRY, however, this late in the release cycle means that I shouldn't refactor at this time. Instead, a duplicated change can be seen in both of the modified functions.
See: https://central.tri.be/issues/36766

Identify the 0th page when paging as page 1 for the purposes of nav

---

src/Tribe/API.php
src/Tribe/Admin/Event_Meta_Box.php
src/Tribe/Date_Utils.php
src/functions/template-tags/general.php

The checkbox for determining if something was AllDay was different than the logic in tribe_event_is_all_day where any truthy value (including `'no'` and `'false'`) would be considered true. The new `Tribe__Events__Date_Utils::is_all_day()` method now looks for explicitly true values (`true`, `'true'`, `'TRUE'`, and `'yes'`) and considers all other values to be false.
See: https://central.tri.be/issues/36928

Centralize and make consistent the logic for checking for AllDay

---

src/functions/template-tags/date.php

The `tribe_get_datetime_separator` should not be escaped by default

---

src/functions/template-tags/general.php

Instead of exposing protected content in tooltips, this change supplies a message telling the user to visit the event and enter the password.

Event descriptions (of password protected events) should not be exposed in tooltips (#29379)

---

src/Tribe/Query.php

Stops events where hide-from-listings is enabled from showing in day view.
See: https://central.tri.be/issues/29508

Day view should respect the hide-from-listings setting (#29508)

---

src/Tribe/Main.php

Month view is our default calendar view (and shows as such in *Events > Settings > Display* in a clean install).
This fixes a problem where:
* Within a brand new install, month view shows as default in Events → Settings → Display
* On following the view events link we are presented with list view instead
* Behind the scenes, the default view option was also then changed to month view creating a janky experience

Default view is month (#29374)

---

src/functions/advanced-functions/meta_registration.php

Changed the check so we *do* register meta groups etc when the relevant class exists.

Register meta if Register Meta class exists (#37024)

---

src/Tribe/Query.php

This resolves a long-standing conflict with the Posts 2 Posts plugin which has historically required [a workaround](https://github.com/scribu/wp-posts-to-posts/issues/249).
**Note:** ~~This probably needs a QA pass before merging and smoketesting.~~ This has been QA'd and can be merged.
See: https://central.tri.be/issues/33288

Only inject date fields into queries when appropriate

---

src/Tribe/App_Shop.php

Checks for `install_plugins` permissions to use App Shop. Includes `tribe_events_addon_page_capability` filter that @garrettjohnson suggested on #32 #37
_Ref:_ [#33911](https://central.tri.be/issues/33911)

App Permissions filterable

---

src/Tribe/Activation_Page.php
src/Tribe/Main.php
the-events-calendar.php

When activating a plugin, there is a `nonce`, `action`, and `s` parameter on the URL which prevents the splash screen from displaying. Don't worry about those vars.
See: https://central.tri.be/issues/34265

Suppress splash screen sometimes. Don't be as nitpicky about showing it

---

src/resources/js/tickets.js

See (internal ref) #30688 for context: the same form is reused for each ticket that is edited in the event editor. This change prevents the min/max date options set for the first ticket being inherited by the next.

Tickets: datepicker opts for one ticket shouldn't be inherited by other tickets (#30688)

---

src/Tribe/Templates.php

WordPress always outputs a pubDate set to 00:00 (UTC) so this takes that
into account with the event date.
Resolves this ticket:
https://central.tri.be/issues/29769

BugFix #29769 - Convert RSS Event Date to UTC000

---

src/functions/template-tags/general.php

This change lets users successfully escape chars in the date format settings (internal ref #35633 for context).

After retrieving date format from db, strip slashes (#35633)

---

src/Tribe/Query.php

Sometimes `orderby` will be set to `rand` for event queries (example: `tribe_get_related_posts()`) - this change ensures that is respected and not overridden - internal ref #33626.

Support random ordering of events (#33626)

---

src/Tribe/Admin_List.php

Follow-up to: https://github.com/moderntribe/the-events-calendar/pull/148
This changeset makes the date joins smarter about when they get added to the Event list query.
See: https://central.tri.be/issues/36187

Conditionally add the start/end date meta queries

---

src/Tribe/API.php
src/Tribe/Date_Utils.php

I was trying a bit more the DatePicker with a few different dates, and I found a bug related to another Pull Request I've created #113.
With formats like `dd/mm/yyyy` or `d/m/yy` it would break the date on saving because our plugin was only passing the dates via `strtotime` which breaks on these formats and return a 1970 date.
Since PHP 5.2 doesn't have a `date_parse_from_format` for us to deal with formatted date parsing I've created a Reversed engineer method on our `Date_Utils` that will get these formats and return a Database formatted String that we can pass to `strtotime`.
**E.g.:**
- `15/01/2015` to `2015-01-15`
- `2/9/2015` to `2015-9-2`
- `12/09/2012 21h 02m 00s` to `2012-09-12 21:02:00`

Resolving DatePicker saving bug

---

src/Tribe/Template/Month.php

I'd have liked to take this a little further and eliminate more of the static members, but this smaller change is safer and should require less QA - while still resolving the problem in the [linked bug report](https://central.tri.be/issues/36593).

Minimum changes to prevent month view args from being overwritten (#36593)

---

src/resources/js/embedded-map.js

[PR/38](https://github.com/moderntribe/the-events-calendar/pull/38) by @tddewey was a great idea and is encapsulated by this new PR, which targets the `release/119` branch and incorporates some further tweaks to ensure we don't overwrite the map object where multiple maps are delivered in the same page.
Props: [@tddewey](https://github.com/tddewey)

Expose embedded map objects for easier customization potential (#33910)

---

readme.txt

Redirecting @sumobi's [pull request](https://github.com/moderntribe/the-events-calendar/pull/143) to our `release/118` branch. Here's the original PR description:
> This fixes various incorrect quote marks in the readme. Some links worked but added the ” to the end of the URL, other links such as the GitHub one did not open at all.
Thanks @sumobi! (sorry for all the github spam, sir). This time I'm PRing it against the correct branch :D

Fix readme quote marks

---

src/Tribe/Importer/Column_Mapper.php

Phone numbers should be imported via venue or organizer data. They have been disappearing into the ether for a while now (deprecated in 2.0).
See: https://central.tri.be/issues/28448

Remove phone as a mappable field (it hasn't gone anywhere for a while)

---

src/Tribe/Template/Month.php

This is a sister-commit to one in Pro where the Mini Calendar widget - when no results are found - causes a global notice to be applied to a page despite the presence of results in the main event loop.
Related: https://github.com/moderntribe/events-pro/pull/48
See: https://central.tri.be/issues/37194

Support the suppression of "Results not found" notices

---

src/admin-views/tribe-options-general.php

Wrapped debugMode fields in is_super_admin(). Chose to do it inline instead of hooking in and removing, that way the logic would be consolidated and easy to understand. Formatted code a bit better to remove the multiple levels of indentation.
See: https://central.tri.be/issues/33566

 #33566 - Only super admins should be able to turn on debug in multisite environments

---

src/Tribe/Query.php
src/Tribe/Template/Month.php
src/views/month/single-day.php

I've cherry-picked @jazbek's work from https://github.com/moderntribe/the-events-calendar/pull/144 into an isolated set of changes that we can merge into `release/118` rather than `release/119`.
This has already been code reviewed, and needs a round of QA before merging.
See: https://central.tri.be/issues/32067 and https://central.tri.be/issues/37143

Month view speed improvements & code cleanup

---

src/views/modules/meta/organizer.php

If multiple organizers have been partially set up on the back end (i.e.  organizer data partially filled out), only show the organizers that have been set up in their entirety on the front end
See: [#33808](https://central.tri.be/issues/33808#note-7)

Don't show undefined organizers on the front end

---

src/Tribe/Main.php

Use a WP_Query to build the prev/next event links, and avoid linking to events that have been hidden from listings.

Move single event nav logic to WP_Query and skip hidden events (#35041)

---

src/Tribe/Main.php

Takes Koop's nice idea submitted in [PR/23](https://github.com/moderntribe/the-events-calendar/pull/23/) and reworks it for inclusion in release/119, with some slight changes:
* Filter is applied within `generatePostTypeLabels()` instead of `registerPostType()`
* The idea is extended to cover our custom post types
Props: @kopepasah for the idea and original PR.

Filters to simplify changes to custom post/taxonomy labels

---

src/Tribe/PUE/Checker.php

See [#36065](https://central.tri.be/issues/36065) for context. Small enhancement which applies wp_kses() as an extra safeguard before displaying service messages.

Use wp_kses as an additional safeguard 

---

src/Tribe/Main.php

Casting as a float butchers the version numbers. Examples:
* `(float) '3.10'` becomes `3.1`
* `(float) '3.9.3'` becomes `3.9`
* `(float) '3.9a'` becomes `3.9`
Right now, if someone has upgraded TEC to 3.10 and they have Pro at 3.9, the version check sees that 3.9 is greater than 3.10 (float value comparison: `3.9 > 3.1`). PHP's `version_compare` function supports the version numbers that we tend to use, so let's not cast. This fix will allow the outdated-plugin notification message to display once again.
~~Add-ons do a good job of making sure TEC is up to snuff. The area of code that is being changed is the reverse check - making sure that add-ons are up to date after core has been updated.  We only care about the first to parts of a version number when checking the add-ons. (e.g. We …

Allow version_compare to compare real values rather than (float) vals

---

src/Tribe/Main.php

Context: https://central.tri.be/issues/37362

Require update_plugins cap before showing the licenses tab (#37362)

---

src/Tribe/Asset/Admin.php

`events-admin[.min].js` uses `wp.template` - a function found in the `wp-util` js file. To ensure that the object/function is available when `events-admin` executes, set it as a dependency.
See: https://central.tri.be/issues/23902

Set wp-util as a dependency when enqueuing events-admin.js

---

src/admin-views/tickets/attendees.php

Repointing @aaemnnosttv's [excellent work](https://github.com/moderntribe/the-events-calendar/pull/56) at our `release/120` branch. Description from the original PR:
>This PR does a few things:
> - Cleaner markup, and more readable php
- Uses `div` instead of `br` for vertical separation
- Add classes to venue divs to easier allow for potential alternate styling / custom JS
- Adds full venue address (it can be very difficult to discern between venues with the same name without it.  e.g. "Holiday Inn")
- Displays the venue's website in a much cleaner way, especially for long URLs:
- yuck: http://cl.ly/image/3E3v2y3r282m
- much better: http://cl.ly/image/3a3I1w2B1y2B

Enhance venue details on Event Attendees screen

---

src/Tribe/Tickets/Attendees_Table.php

Repointing @aaemnnosttv's [original PR](https://github.com/moderntribe/the-events-calendar/pull/58) to `release/120`. Outputs the order id in the Attendees table as a link.
Related: https://github.com/moderntribe/events-tickets-woo/pull/22
See: https://central.tri.be/issues/37569

Display proper order_id for ticket orders

---

src/Tribe/Tickets/Attendees_Table.php

Another excellent change by @aaemnnosttv [repointed](https://github.com/moderntribe/the-events-calendar/pull/68) at `release/120`!
> This PR makes the attendee's list table top/bottom nav extendable by first restructuring the output into an array, and then making that filterable via a new filter `tribe_events_tickets_attendees_table_nav ` before output.
> The structure of the array, in combination with the `$which` position passed by the filter, makes extending any combination of the `top`, `bottom`, `left`, `right` nav very easy.
> No real change in the current behavior here, but there is one minor change which may not be obvious that _could_, which is the use of `esc_attr__()` for the _Print_ and _Email_ action buttons (instead of `__()`, since those translations are passed into the …

Make attendee table nav filterable

---

src/Tribe/Templates.php

Following our changes to stop returning a 404 status for empty views, this PR should resolve an [annoying issue](https://central.tri.be/issues/34202#note-11) triggering a notice level error when empty views were served using something other than the Default Events Template.
* After spoofing the post we bring the loop to a stop via `Tribe__Events__Templates::endQuery()`
* Previously this was setting the query's `post_count` to `1` 
* In a case where no events had actually returned, this meant WP tried to `rewind_posts()` despite having no posts to rewind (result was a notice level error as it attempted to reset the query's `post` property)
As I was working through this, I also flattened out `Tribe__Events__Templates::restoreQuery()` a little.

Make spoofing work gracefully when there are no events (#34202)

---

src/functions/template-tags/organizer.php

Related: https://github.com/moderntribe/events-pro/pull/57
See: https://central.tri.be/issues/33808

Pass along an organizer_id to the tribe_get_organizer filter

---

src/Tribe/Asset/Admin.php

The new multiple-organizer functionality requires it.
See: https://central.tri.be/issues/37673

Add jQuery UI sortable as a dependency for events-admin.js

---

src/Tribe/Template/Month.php

Add `__return_true` filter to `'tribe_events_month_has_events'` if the month has events. Remove the filter during view shutdown.
Internal reference: https://central.tri.be/issues/37672

Reinstate functionality of tribe_events_month_has_events()

---

src/Tribe/Main.php

`$show_tab` should hold `true` if we want to show the tab rather than false.
See: https://central.tri.be/issues/37677

Invert the logic for $show_tab so it holds the value we expect

---

src/Tribe/Template/Month.php

Change query so it uses EOD cutoff instead of midnight
Change dates on the query only because the first_grid_date is expected in Y-m-d format
Updates #37867

Change month view query so it uses EOD cutoff

---

src/Tribe/Admin_List.php

If another plugin has not properly appended a space in their filtering of the JOIN query, the lack of space here results in an invalid SQL query. As is elsewhere in The Events Calendar, there should be a
space before and after the query string.
Note that the same thing is in Events Calendar Pro as well.

[PR] Prepend space when building JOIN query to prevent conflicts.

---

src/Tribe/Main.php

Note: @bordoni asked if I checked if all of the actions/filters in Tribe__Events__Admin_List still fire. The answer is: **Yes, they all still fire (on the Events Admin List) with this tweak in place**.
See: https://central.tri.be/issues/38105

Only bootstrap the Admin_List class on event list pages in dashboard

---

src/Tribe/Template/Month.php

Queries executed from the confines of the Month View template class should be flagged as such so that other plugins can identify and react to the queries as needed.
The foremost example of this is Pro's ability to suppress recurring events. Without labeling the query as a month view query, those event queries are instead identified as `custom`, causing the recurring events to be hidden.
Related: https://github.com/moderntribe/events-pro/pull/64
See: https://central.tri.be/issues/37629

Label all of the queries in month view as such with eventDisplay

---

src/Tribe/iCal.php

And by "All", I mean all events that aren't hidden. Without doing `posts_per_page = -1`, the query was only retrieving events up to the "Number of events to show per page" setting.
See: https://central.tri.be/issues/38182

Make sure we export ALL events when exporting from month view

---

src/Tribe/Advanced_Functions/Register_Meta.php
src/Tribe/Main.php
src/functions/advanced-functions/meta_registration.php
src/functions/template-tags/google-map.php

_Ref:_ [C#37660](https://central.tri.be/issues/37660)
- Deprecating `tribe_event_meta_gmap_link` filter
- Deprecating `Tribe__Events__Advanced_Functions__Register_Meta::gmap_link`

Google Maps venue Links fixed

---

src/io/csv/admin-views/general.php

Minor fix, highlighted in the wp.org forums by @tititou36

Spotfix for untranslated string in import general options (#38234)

---

src/Tribe/Advanced_Functions/Register_Meta.php

We removed a method but there was one reference still hanging around.
See: https://github.com/moderntribe/the-events-calendar/pull/233 and https://central.tri.be/issues/37660

Follow-up to PR #233 that fixes fatal for gmap link

---

src/Tribe/Main.php

The location that this `remove_action` was placed was causing incompatibilities. When `wp_insert_post` was called during hooks like `save_post`/`transition_post_status`/etc (that execute before addEventMeta) those post insertions were triggering the `remove_action` call on `addEventMeta`. When it came time for the actual event to be inserted, the addEventMeta hook was non existent and the meta data wouldn't get inserted. This fixes that.
See: https://central.tri.be/issues/35491

Only unhook addEventMeta if the function is actually executing

---

src/Tribe/Query.php

Hi,
This is a fix for an issue that I (and several others) have been having where TEC is trying to use `get_current_screen()`, but for some reason it's unavailable, which is breaking the entire admin side when trying to add a new event.
The bug can be recreated by creating a WordPress plugin that use ```WP_Query``` when ```wp_loaded``` is fired.  The ```pre_get_posts``` hook in TEC then fires and tries to use ```get_current_screen()```, which is undefined at this point.  Which is weird because WP_ADMIN *is* defined, so that function should exist.  Oh well.

Added check for get_current_screen() before trying to use it

---

src/Tribe/Date_Utils.php

When a date format contains a single-digit month or single-digit day, the `Tribe__Events__Date_Utils::datetime_from_format()` returns those months/days in the datetime as single digit rather than the desired `Y-m-d` format.
Examples:
Format: `j/n/Y`
Input: `15/1/2015`
Returns: `2015-1-15`
Should be: `2015-01-15`
Format: `j/n/Y`
Input: `1/1/2015`
Returns: `2015-1-1`
Should be: `2015-01-01`
See: https://central.tri.be/issues/38451

When parsing dates w/ single digit months/days, convert them to 2-digits

---

src/Tribe/Activation_Page.php

See: https://central.tri.be/issues/38061

Avoid a notice when _GET['plugins'] isn't set on the update page

---

readme.txt
src/Tribe/API.php

This function is only called when via an ajax request when a user edits a ticket while editing an event. A separate function updates these fields when the page is POSTed (The user clicks the Update button). That function worked flawlessly, but this called via ajax did not.
I am not sure what the code was supposed to do before, why there was an array shift nor why we had a $base_cost variable. However, the filter 'tribe_events_event_costs' is only applied in one other place in all of our plugins, and in that place it passes an empty array exactly like this now does. Now that there are no values passed, it behaves as expected and never has a duplicate value.

Fix #36153 issue where _EventCost would not update when tickets updated

---

src/Tribe/View_Helpers.php

@d4mation- had [an _excellent_ mod](https://github.com/moderntribe/the-events-calendar/pull/242) that allows sites to filter the increment value for the minutes drop-down boxes rather than always forcing a 5-minute increment. Thank you for the original PR, @d4mation-!
See internal ticket ref: https://central.tri.be/issues/38550

Adopt suggestion by d4mation- and add minute increment filter

---

src/Tribe/Template/Month.php

We need to respect events that have been set as 'sticky in month view' (ie, they have a negative menu_order to float them to the top). Like [PR/259](https://github.com/moderntribe/the-events-calendar/pull/259) this targets an existing feature branch.

Alter query to respect events that are set to be 'sticky in month view' (#32067)

---

src/Tribe/Cost_Utils.php
src/Tribe/Template/Month.php

Note: I'm Pull Requesting this into a feature branch (that is [this PR](https://github.com/moderntribe/the-events-calendar/pull/192)) so the code within this changeset can be reviewed in isolation.
**The Cost_Utils class**
`get_cost_by_func` was pretty slow for two reasons: `array_merge` is kind of slow _and_ when there are a large number of events, fetching every non-unique cost means we have to loop over and parse each one.  That's expensive. Let's select distinct costs and avoid doing `array_merge`.
**Month view class**
When fetching the daily events, we were looping over every event in the month and determining if it fell on the given day. Instead, we could reduce the number of times we loop by _instead_ looping over all the events in the month and breaking them out into the days that …

Performance enhancements that target month view

---

src/Tribe/Admin_List.php

This filter was added during the development cycle of release/120 [by me](https://github.com/moderntribe/the-events-calendar/pull/148) and it was really stupid.
See: https://central.tri.be/issues/38329

Don't override ORDER BY with a blank string. That's silly.

---

src/Tribe/iCal.php

As highlighted by a customer (props owed to [@Jon](http://theeventscalendar.com/support/forums/users/dclodging/) here) we were flipping coordinates in the ical feed.

Flip order of coordinates per RFC2445 4.8.1.6 (spotfix)

---

src/functions/template-tags/general.php

Minor formatting changes, but the key difference is addition of context to the translated string (should make it easier for GP to differentiate between these strings and others set elsewhere in the codebase).

Transform _n() call into _nx() (spotfix for translation issue)

---

src/Tribe/Template/Month.php

Please see [#38398](https://central.tri.be/issues/38398) for reference - should avoid problems where the incorrect day is highlighted in month view due to timezone issues.

Month view day classes should work regardless of WP timezone (#38398)

---

src/Tribe/Timezones.php

Bad datetime/offset data can lead to us trying to call a method on a non-object as described in [C#39204](https://central.tri.be/issues/39204) - this guards against that.

Timezones: improve fallback logic

---

src/Tribe/Template_Factory.php

`Tribe__Events__Template_Factory::getMinFile()` will fallback to the unminified asset whenever `$default_to_original` is true. All calls to this method I can find across our suite accordingly set that to true (as the default, bizarrely, is false). This PR changes that default to help avoid annoying bugs when laying out new code.

Adjust default for $default_to_original arg to true (spotfix)

---

src/Tribe/API.php

When `Tribe__Events__API::saveEventMeta()` is called to create/update an event, timezone data should be created and default to the site settings if not explicitly provided.

API cannot rely on a timezone being posted in when setting up event datetime data | 39235

---

src/Tribe/Timezones.php

We're making use of procedural datetime functions for brevity: the try/catch isn't appropriate here and means we're potentially missing some errors during conversion that we could otherwise handle fairly gracefully.
See: https://central.tri.be/issues/39204

Improve handling of errors where timezone conversion cannot be made (#39204)

---

src/Tribe/Main.php
src/Tribe/Settings.php

Fixes a great catch by @leahkoerper (re [C#37716](https://central.tri.be/issues/37716)) - a couple of references to `tribe-events-calendar` were updated in [PR/305](https://github.com/moderntribe/the-events-calendar/pull/305) but should have been left alone.

Undo string change inadvertently applied to non-textdomains (#37716)

---

src/Tribe/Changelog_Reader.php

Re [C#39386](https://central.tri.be/issues/39386) the changelog reader was failing to locate the default `readme.txt` file. This can be reviewed but I've applied the hold label since we may wait until MR2 before merging.

Look up one more level to find the readme.txt file (#39386)

---

src/Tribe/Template/Month.php

Correct code for highlighting the current day (see [C#39420](https://central.tri.be/issues/39420)).

Use site timezone (not UTC) when selecting current day in month view

---

src/Tribe/Rewrite.php

Re [C#39391](https://central.tri.be/issues/39391) makes core consistent with changes re PRO event view slugs ([PR/114 for PRO](https://github.com/moderntribe/events-pro/pull/114)).

Support both the original and translated/custom slugs (#39391)

---

src/Tribe/Main.php

Re [C#39736](https://central.tri.be/issues/39736), ensure there are slashes in all the right places for pathinfo-based permalinks.

Fix pathinfo support (#39736)

---

src/Tribe/Admin/Organizer_Chooser_Meta_Box.php

If a user cannot create organizers, remove the default organizer 0 from the list of current organizers so that an event with no organizer does not automatically get the first one (alphabetically) re-assigned to it every time the user saves the event - updates pr #289, central https://central.tri.be/issues/39179

remove empty default organizer for restricted users

---

src/Tribe/Main.php

Same change as [PR/279](https://github.com/moderntribe/the-events-calendar/pull/279) - but targeting `release/120`. Ref: [C#33497](https://central.tri.be/issues/33497)

Modify workaround for handling WP imports of recurring events (#33497)

---

src/Tribe/Main.php

Searched for this method throughout the codebase, we're not using it. Also seems unnecessary. Deprecating instead of removing because it's public.
Internal Ref: https://central.tri.be/issues/28005

Deprecate public method that's unused in our codebase

---

src/Tribe/Google_Data_Markup.php
src/Tribe/Google_Data_Markup/Event.php
src/Tribe/Template/Single_Event.php

Moved google data markup to an abstract class, base "thing" properties are set in the abstract class, events, venues, and organizers will extend and add to the base data. Most properties are shared between schema.org objects and are pulled the same way from different wp post types, so this is keeping it DRY.
Also made it not be a singleton anymore because we have to support php 5.2 which doesn't have late static binding.
Ref: [C#39616](http://central.tri.be/issues/39616)

Move base google data markup to abstract class; extend to event

---

src/Tribe/Rewrite.php

Re [C#39935](https://central.tri.be/issues/39935) this change moves the setup of core's rewrite rules to the `tribe_events_pre_rewrite` hook.

Make it easier for other plugins to add rewrite rules before/after core's own

---

src/Tribe/Template/Month.php

Ensure we have accurate daily counts in month view. [C#39994](https://central.tri.be/issues/39994)

Do not overwrite the query's found_posts param with the wrong total

---

src/Tribe/Settings.php

Reverting a change to the admin slug made inadvertently in https://github.com/moderntribe/the-events-calendar/commit/ed9e9b6c1d494afde54b067873ffe591a455ecab: Filter Bar tests against this and expects the original value of `tribe_events_calendar` - and so it's also probable other addons/customizations do the same.

Revert change to admin slug made in ed9e9b6c1d (spotfix)

---

src/Tribe/Rewrite.php

We moved the setup of core rewrite rules to its own method but failed to move the $options definition, which they rely on.

Move options definition to correct method (spotfix)

---

tests/functional/functions/template-tags/metaTest.php

A test from the branch `feature/38899-better-field-separators` has been removed, this PR re-adds it.
Ticket: https://central.tri.be/issues/36584

added removed test

---

src/functions/template-tags/general.php

Somewhere along the way this was accidentally removed.
See: https://central.tri.be/issues/38488

restoring the accidentally removed tribe_get_render_context

---

src/Tribe/Cost_Utils.php

Query was returning costs where nothing had been specified, causing breakages downstream.

We are not interested in empty costs values (spotfix)

---

src/Tribe/Main.php

In testing the various activated states of our plugins, @zbtirrell and I discovered that tickets was _always_ active.

Only activate the ticket plugin if other ticket plugins are active

---

.gitmodules

Now that the ticket repo has been renamed, let's point to the new GitHub repo.

Repoint tickets submodule to new tickets repo

---

src/Tribe/Timezones.php

As Jessica highlighted - we were testing for the existence of properties but weren't forming the property name correctly (ie, instead of checking for `EventStartDate` we were checking for `EventStartStartDate`) ... this fixes that.

Form correct strings for start/end date (spotfix | props: jazbek)

---

src/Tribe/Asset/Admin.php
src/Tribe/Asset/Admin_Menu.php
src/Tribe/Asset/Admin_Ui.php
src/Tribe/Asset/Ajax_Calendar.php
src/Tribe/Asset/Ajax_Dayview.php
src/Tribe/Asset/Ajax_List.php
src/Tribe/Asset/Calendar_Script.php
src/Tribe/Asset/Ecp_Plugins.php
src/Tribe/Asset/Events_Css.php
src/Tribe/Asset/Settings.php
src/Tribe/Asset/Tribe_Events_Bar.php
src/Tribe/Embedded_Maps.php
src/Tribe/Main.php
src/functions/template-tags/deprecated.php
src/functions/template-tags/general.php

When The Events Calendar and Event Tickets are both active, the common library's tribe_resource_url() function returns an incorrect URL for TEC resources when Tickets is the plugin that runs common libs.
See: https://central.tri.be/issues/40451

Bring back tribe_events_resource_url()

---

src/Tribe/Capabilities.php
src/Tribe/Deactivation.php
src/Tribe/Updater.php

It shouldn't be generic
Related: https://github.com/moderntribe/tribe-common/pull/7
See: https://central.tri.be/issues/40455

Move Tribe__Capabilities back to Tribe__Events__Capabilities

---

src/Tribe/Main.php

TEC's plugins_loaded was firing at the same time as some of our other plugins which wasn't early enough to initialize the new autoloader for 4.0. This ensures that TEC is initialized before any other plugin regardless of 3.x or 4.x release.
See: https://central.tri.be/issues/40281

Prevent fatal when TEC is upgraded and other plugins are not

---

src/Tribe/Main.php

This Pull request is more of a question to @borkweb in regards to if these lines belong here or not. 
Both @mastromktg and @WayneStratton reported this problem this week. Seem like when you open the administration it gives you the following error;
```
'Tribe__Tickets__Metabox' not found in /wp-includes/plugin.php on line 503
```
Could be:
1. These action were left there, by mistake.
2. The Autoloader is not working properly.
If it's the first one just merge the PR, if not the problem seems to be that our autoloader method doesn't take in consideration `Tribe__Tickets` as a prefix.
https://github.com/moderntribe/the-events-calendar/blob/release/121/src/Tribe/Main.php#L4481-L4502

Tickets metabox out of place?

---

src/Tribe/Main.php

Let's check if we need to initialize the tickets plugin when we're bootstrapping all of the hooks and libraries for TEC.
Related: https://github.com/moderntribe/event-tickets/pull/17
See: https://central.tri.be/issues/40590

Don't double-nest initialization of ticket plugin under 2 plugins_loaded

---

readme.txt
src/Tribe/Template_Factory.php
src/Tribe/Templates.php
src/functions/template-tags/general.php

See: https://central.tri.be/issues/40833

Support wp_get_document_title in response to WP 4.4 deprecated wp_title

---

src/Tribe/Main.php
src/Tribe/Rewrite.php

Previously we were forming links where tag/category was translated, but our rewrite rules only covered the English terms - leading to unexpected results when users try to load taxonomy views in a non-English language setup.
[C#40579](https://central.tri.be/issues/40579)

Ensure rewrite rules included translated forms for "tag" and "category" (#40579)

---

src/Tribe/Template/Month.php

This block of code changes in `release/121` and `$current_day` becomes a declared variable with useful data. But not in `release/120`
See: https://central.tri.be/issues/40980

Use the declared $calendar_day rather than the non-existent $current_day

---

src/Tribe/Capabilities.php
src/Tribe/Main.php
src/Tribe/Updater.php
tests/functional/Capabilities_Test.php
tests/functional/Updater_Test.php

* bugfix in the Updater so it does not run the upgrade functions on a new install
* changing functions from `protected` to `public` to make them more testable
* capturing the updater object in a `static` variable to make it more testable
* fix the Capabilities Venue/Organizer tests to use the right data provider
* add a bunch of Updater tests

a few testing and test-ability changes

---

src/Tribe/Main.php

Partner to [Event Tickets PR/28](https://github.com/moderntribe/event-tickets/pull/28) - we need to set up the main tickets class (when we decide to load the tickets framework as a submodule) directly.
[C#41099](https://central.tri.be/issues/41099)

Don't rely on the WP hook system to setup the tickets module (#41099)

---

src/functions/template-tags/date.php
src/functions/template-tags/general.php
src/functions/template-tags/tickets.php

In an effort to prevent fatals when running event-tickets and a pre-4.0 version of the-events-calendar, we need to wrap a number of functions with if statements. While this won't help any TEC install less than 3.12.4, we can at least prevent the issue with the latest version.
See: https://central.tri.be/issues/40986

Prevent throwing function declaration fatals when running event-tickets

---

src/admin-views/tickets/list.php

The "Edit in" and "View" links are being added in two places. That's silly.
See: https://central.tri.be/issues/41150

Remove duplicate links

---

src/Tribe/Template/Month.php

Restores the expected CSS classes for each day in month view:
* Compares timestamps with timestamps (was comparing a timestamp with an array)
* Drops unneeded use of `date_i18n()` for day numbers (was effectively converting them all to `01`)
[C#41258](https://central.tri.be/issues/41258)

Restore expected day classes in month view | #41258

---

readme.txt
src/views/single-event.php

Original [PR from @wpexplorer](https://github.com/moderntribe/the-events-calendar/pull/419). This is being re-pull-requested to resolve the merge conflicts.
See: https://central.tri.be/issues/41300

For SEO reasons, use an h1 rather than an h2

---

src/Tribe/Tickets/Tickets_Pro.php

See: https://central.tri.be/issues/41327

Hide the orders report for non-wootickets setups

---

src/Tribe/Query.php
tests/functional/Query/Date_Filter_Test.php

The Facebook importer lives on the "same" current screen as the event list in the dashboard, however, it _should not_ have the date filters removed like the event list requires. This fixes that so that duplicate Facebook imports can be identified.
This changeset includes tests.
~~This change set _requires_ [this PR](https://github.com/moderntribe/tribe-common/pull/28) to be merged into tribe-common (and the hash will need an update)~~ The hash for the `common/`directory has been updated.
Best reviewed with `?w=1`
See: https://central.tri.be/issues/41385

Ensure that EventStartDate isn't stripped from importer page queries

---

readme.txt
src/Tribe/Main.php
src/admin-views/new-organizer-meta-section.php

Some untested code relating to capabilities for venue and organizer post types snuck into core and caused breakages. This strips those back out.
[C#41329](https://central.tri.be/issues/41329)

Remove some capability checks that should have been held back until r/121

---

src/Tribe/Query.php

_Ref:_ [C#38473](https://central.tri.be/issues/38473)

Re-structure Query::set_order() to allow better support on WP 4.2

---

src/Tribe/Template/Month.php

There can be more than one month view (and so more than one month template object) per request - ie one or more calendar widgets might be used alongside the main month view. In such a case, the widget-related object could remove a filter added by the main view object, causing unusual results.
This change should prevent that at least with regards to the `tribe_events_month_has_events` hook.
[C#41332](https://central.tri.be/issues/41332)

Smarter handling of tribe_events_month_has_events | #41332

---

src/Tribe/Tickets/Tickets_Pro.php

There's a fatal, otherwise.
See: https://central.tri.be/issues/41327#note-9

Hide the Orders report for Woo if version is less than 3.12

---

src/Tribe/Updater.php
tests/functional/Updater_Test.php

To more easily test `get_updates()` and `constant_updates()`, those methods were converted to public. This causes fatals when Pro 3.12.x is active because Pro has a class that extends `Tribe__Events__Updater` and overrides the `protected` methods.
The fix is to retain those methods as protected and make new ones that are public.
See: https://central.tri.be/issues/40281

Don't change the visibility of these methods. Make new methods

---

src/Tribe/Query.php

Within `Tribe__Events__Query` if `self::should_remove_date_filters( $query )` is true we unhook our `posts_fields` filter but not our `posts_orderby` filter (which depends on the aliases set up by the former). This change ensures they are all unhooked together - otherwise we hit things like:
*Unknown column 'EventStartDate' in 'order clause'*
[C#35479](https://central.tri.be/issues/35479)

If we unhook posts_fields() we should also unhook posts_orderby()

---

src/Tribe/Admin/Organizer_Chooser_Meta_Box.php

See: https://central.tri.be/issues/40036

use the filtered function and escape properly

---

src/Tribe/Query.php
tests/functional/Query/Date_Filter_Test.php

With [this fix](https://github.com/moderntribe/the-events-calendar/pull/445), we don't really need filters on the import pages. In fact, excluding them is necessary. Previous tests returned false positives that were caused by the date of the event and the injected date aligning just so...through crazy random happenstance. When looking for importable events, we won't need to have a date-beefed-up query.
See: https://central.tri.be/issues/41385

Remove date filters on import pages

---

src/functions/template-tags/month.php

On a brand spankers install / if no events have yet been added to the db, then we don't have such a thing as a date for the earliest event and we shouldn't display a link to the previous month.
[C#33449](https://central.tri.be/issues/33449)

Do not output a prev month link if the earliest event date is unknown | #33449

---

composer.lock
tests/acceptance/Issue_38042_Dropping_CategoryCest.php

ticket: https://central.tri.be/issues/38042
I've updated the broken acceptance test to use latest WPDb methods as such it will require a `composer update lucatume/wp-browser` call to pass

Fixed broken acceptance test

---

composer.json
tests/_support/Helper/Phantomjs.php
tests/_support/Modules/Acceptance/Options.php
tests/_support/PhantomjsTester.php
tests/phantomjs.suite.dist.yml
tests/phantomjs.suite.yml
tests/phantomjs/Issue_38042_Dropping_CategoryCest.php
tests/phantomjs/_bootstrap.php

Ticket: https://central.tri.be/issues/40423
I've moved the only acceptance test we have in the new `phantomjs` suite and solved the problem (window size) that would prevent it from running.  
Along with it I've added a Tribe module to handle options in acceptance tests.
I've PRed on core as the issue under test (https://central.tri.be/issues/38042) was really a core issue. We currently have the same exact test on Pro and filters and I can easily replicate the test, the module and the suite set up there too should that be the case.

Created the phantomjs suite

---

src/Tribe/Importer/Options.php

Fire an action once importer options have been updated.
[C#41714](https://central.tri.be/issues/41714)

Allow plugins to do something once importer options have updated | 41714

---

src/Tribe/Main.php

With the existing redirect, http://example.com/events/upcoming would redirect to http://example.com/events/upcoming, since it lacks the trailing slash to match the `str_replace()`. We can be more accommodating with a `preg_replace()`.
https://central.tri.be/issues/41869
https://central.tri.be/issues/41937

add slash to past/upcoming redirect URL to prevent redirect loop

---

readme.txt
src/functions/template-tags/general.php

We set the default view to `month`, however, our default list of enabled views was empty. On a new install, this caused a 404 until the user set the views they wanted to enable via Events > Settings > Display.
This change sets `month` as an enabled view by default so that `/events/` can render before the user hits _Save_ on Events > Settings > Display
See: https://central.tri.be/issues/41981

Default the enabled views to "month"

---

src/admin-views/tribe-options-display.php
src/admin-views/tribe-options-general.php

I did some changes yesterday to move settings fields from common to TEC.  In doing so, the textdomain was not updated from tribe-common to the-events-calendar. This was noticed while testing translations for tribe-common.

Fixing some textdomain issues that were introduced in late changes

---

src/Tribe/Admin_List.php

A query with hardcoded `wp_` table prefixes had snuck in, breaking the admin events list when ordered by tag or category. This change should fix (for any sites that don't use `wp_` as their prefix).
[C#42021](https://central.tri.be/issues/42021)

Avoid hardcoded table prefixes | 42021

---

src/Tribe/Importer/File_Importer_Events.php

Events imported via CSV were getting the `_EventHideFromUpcoming` meta key inserted blank. That's pretty silly, and the next/previous link generation dies a horrible death if the meta key even exists.
See: https://central.tri.be/issues/42054

Don't inject the _EventHideFromUpcoming on CSV import if it isn't needed

---

src/Tribe/Event_Tickets/Attendees_Report.php
src/Tribe/Event_Tickets/Main.php
src/Tribe/Main.php

The `Tribe__Events__Event_Tickets__Attendees_Report` injects tribe_events specific fields into the Event Details section of the report. The fields/HTML are simply lifted from the event-tickets plugin and relocated to an action. I _did_ update the textdomain, though.
Related: https://github.com/moderntribe/event-tickets/pull/81
See: https://central.tri.be/issues/41975

Add classes to handle hooking to and overriding things in Event Tickets

---

src/Tribe/Admin_List.php

Previously, ordering the admin event list by date failed because we were *appending* the extra rules. This change prepends the rules instead, restoring proper ordering by start/end date.
Example, instead of:
`ORDER BY wp_posts.post_date DESC, tribe_event_start_date.meta_value DESC, tribe_event_end_date.meta_value DESC`
We now get:
`ORDER BY tribe_event_start_date.meta_value DESC, tribe_event_end_date.meta_value DESC,  wp_posts.post_date DESC`
[C#42022](https://central.tri.be/issues/42022)

Admin events list: ensure date ordering is applied | 42022

---

src/resources/js/tribe-events-ajax-calendar.js

Removes a section of code that was wiping the title of the list which displays below month view in mobile mode. Props will be due to Jason on the forum for this one.
[C#41574](https://central.tri.be/issues/41574)

Remove unneeded (and problem-causing) code | 41574

---

src/functions/template-tags/general.php

When running multi-day all-day events, we were not looking at the end of day cutoff when building the date range. Instead, we blindly took the end date/time and displayed that. Example:
End of day cut-off: 3am
Event: All-day, December 8 to December 10
*With the bug:*
* Event dates would be stored as 2015-12-08 03:00:00 to 2015-12-11 02:59:59
* Event would be rendered as December 8 - December 11
*With the fix:*
* Event dates would be stored as 2015-12-08 03:00:00 to 2015-12-11 02:59:59
* Event would be rendered as December 8 - December 10
See: https://central.tri.be/issues/40555

Observe the end-of-day cutoff when building the date range for multi-day

---

src/Tribe/Admin/Timezone_Updater.php

This class was moved to tribe-common and back to core again, but on restoring it to core we didn't fix the path for a script we were enqueueing - so it was 404ing :sob:

Correct asset url (spotfix)

---

src/functions/template-tags/general.php

I had nicely functioning code and then I made a last minute change with timestamps to shorten the code needed to generate the correct date range. I obviously didn't test it well enough with multi-day all-day events with a non 12am end of day cutoff. This update rolls back the 12th hour timestamp tweaks and renders the dates as they should.
See: https://central.tri.be/issues/40555#note-10

Don't use a timestamp when calling tribe_beginning_of_day()

---

src/admin-views/new-organizer-meta-section.php

https://central.tri.be/issues/41497

Don't try to validate empty strings as organizer names | 41497

---

src/Tribe/Admin_List.php
src/functions/template-tags/date.php
src/views/modules/meta/details.php

All-day Multi-day events have their end dates displayed individually in a few locations - when viewing a single event and viewing the event in the admin dashboard. In those instances, the true end date is not what is desired, but, rather an end date that observes the end of day cutoff.
This changeset adds a new method ( `tribe_get_display_end_date()` ) that calls `tribe_get_end_date()` and adusts the output based on the multi-day/eod status of the event whose end date is being fetched.
**Note:** I'm also removing `tribe_get_start_date()` and `tribe_get_end_date()` from TEC because those are duplicated in tribe-common now. Which meant that the ones in TEC were never declared because the functions already existed. That was a fun frustration as I worked on stuff.
See: …

Multi-day All-day events may require an adjusted date by eod cutoff

---

readme.txt
src/Tribe/Main.php

Tested against WP 4.4, the `$post_type` variable is passed in as an object whereas in WP 4.3 it is passed in as an array where the `args` index holds the object we care about. This changeset supports both structures to prevent the fatal that was being thrown.
See: https://central.tri.be/issues/42220

In WP 4.4, the $post_type is no longer an array but an object

---

src/Tribe/Main.php

Strangely, the default venue wasn't respected in the admin event editor (but was in the frontend submission form if CE was active). This change corrects that.
https://central.tri.be/issues/42170

Respect default venue

---

src/Tribe/iCal.php

Use the event-specific or sitewide timezone as appropriate when generating iCal data.
[C#42213](https://central.tri.be/issues/42213)

Make iCal generator respect the timezone settings | 42213

---

src/admin-views/venue-meta-box.php

The venue meta box (within the event meta box) was attempting to use the default country value, making it the odd man out amongst its fellow fields.
https://central.tri.be/issues/42170 but see also https://central.tri.be/issues/29366

Don't use the default country for new venues within the event editor | 42170

---

src/Tribe/Cost_Utils.php
tests/functional/Tribe__Events__Cost_Utils_Test.php

When the cost meta holds something other than a numeric string (parseable by our regex), there are a few array operations that throw notices. This changeset sets some defaults in the event that the regex fails.
See: https://central.tri.be/issues/42174

If cost holds non-numeric text, use 0 for the cost range

---

src/Tribe/Cost_Utils.php
tests/functional/Tribe__Events__Cost_Utils_Test.php

During 4.0, we started tossing out explicit 0-cost events when, in fact, we want them (and need them) identified separately so we can throw the `Free` label on events.
See: https://central.tri.be/issues/42173

Allow 0-cost (free) events. Don't consider non-numeric as '0'

---

src/Tribe/Main.php
src/Tribe/Rewrite.php

The venue and organizer CPT slugs can already be localized - but the end result with non-Roman alphabets like Greek is not always a happy one. This change corrects that, potentially paving the way for us to finally offer more complete support for Shavian.
[C#40385](https://central.tri.be/issues/40385)

Better handling of internationalized slugs

---

src/Tribe/Query.php

This change better isolates the logic for ordering by venue/organizer from the logic used to order by date (which doesn't always run, depending on the context) - letting users successfully order the admin events list by organizer/venue (such as if APM is enabled and has made those particular columns sortable).
[C#37286](https://central.tri.be/issues/37286)

Make it possible to order the admin events list by organizer/venue

---

src/Tribe/Query.php

Ticket https://central.tri.be/issues/42331
We came across this in a service project.
Set up is multisite, WPML used on subdomain site and languages are English and Chinese simplified.
A notice is thrown as the `postmeta_table` var is not defined in the `Tribe__Events__Query` class on some queries in the simplified Chinese version.
The simple fix is to default the `postmeta_table` variable to `$wpdb->postmeta`.

added postmeta_table default value

---

src/Tribe/Query.php
src/Tribe/Template/List.php

This change ensures that a) the `$query->tribe_is_past` flag is set during past event requests made by ajax and b) the order is set to `DESC` (a recent-ish change to the default args used in `tribe_get_events()` requires this).
[C#42371](https://central.tri.be/issues/42371)

Explicitly set order for past event queries (ajax) | 42371

---

src/Tribe/List_Widget.php

Avoid notice level errors caused by trying to access non-existent array elements. 
[C#42156](https://central.tri.be/issues/42156)

Avoid notice-level errs (set defaults) | 42156

---

readme.txt
src/Tribe/Main.php
src/Tribe/Query.php
tests/functional/Tribe/Events/Navigation_Test.php

I've commented the code heavily, but the gist is - when we were fetching next/previous events, the query that was being generated excluded events that had identical times to the event being viewed. Additionally, sometimes events with duplicate times wouldn't show up in the single-event navigation at all.
This fix reworks the WHERE clause meta query for the date selection to add additional meta/post_id statements that aren't possible with the standard WP_Query parameters. It includes a heavily commented regex that I tried to make _very_ targeted to avoid accidental butchery.
This code includes tests.
See: https://central.tri.be/issues/41290

Mod the WHERE clause when fetching next/prev events to avoid exclusions

---

src/Tribe/Main.php

If $term is a boolean value we shouldn't cast it to an int and try to fetch that term. See also [PRO PR 248](https://github.com/moderntribe/events-pro/pull/248).
[C#42381](https://central.tri.be/issues/42381)

Avoid accidentally fetching event category #1 

---

src/Tribe/Cost_Utils.php
tests/functional/Tribe__Events__Cost_Utils_Test.php

This fix ensures that the min/max cost ranges only include numeric values while allowing single events to preserve their string-based cost formatting.
Cost range tests pass.
Related: https://github.com/moderntribe/events-filterbar/pull/54
See: https://central.tri.be/issues/39041

Don't include string-based costs when fetching max/min costs in range

---

readme.txt
src/views/modules/meta/details.php

Recurring events need to be able to output multiple times on the single-event template. This twiddles the template to allow that by adding a few filters.
Related: https://github.com/moderntribe/events-pro/pull/252
See: https://central.tri.be/issues/39821

Make the time section hookable so that Recurring events can override

---

readme.txt
src/Tribe/Admin_List.php

This partial reversion/hybrid is a best-of-both-worlds of a few previous renditions of this code. This allows any non-post_date field to take precedence over the start/end date of the event _*except*_ the post_date, which largely doesn't matter for Events.
See: https://central.tri.be/issues/38331

Only append the original orderby if it is an orderby post_date

---

tests/functional/functions/template-tags/metaTest.php

Run the `template-tags/metaTest.php` test without a class not found error.

Change superclass for metaTest (spotfix)

---

src/Tribe/iCal.php

Ticket: https://central.tri.be/issues/39455
I've set the length of the has to 11 for the aestethic reason that the generated filename will not be cut with ellipsis in many browsers download windows.
I'm not that concerned about uniqueness as any system, being it a file, will attach a `(1)` or something to it to distinguish.

modified ical file name to use 11 digit hash

---

src/Tribe/Query.php

Prevents PHP warning produced from passing DateTime() object into `start_date` or `end_date` args of `tribe_get_events`

Prevent strtotime warning for `new DateTime()` obj

---

src/Tribe/Templates.php

Register TEC's view path and override path with the template updates checker.
[C#28582](https://central.tri.be/issues/28582)

Register core views/overrides (with the template update checker)

---

src/Tribe/Importer/Admin_Page.php
src/Tribe/Importer/File_Uploader.php

[C#37186](https://central.tri.be/issues/37186) - prevent a fatal/WSOD that can occur in some edge case-like scenarios.

Prevent fatal if import/continue screen is refreshed | 37186

---

src/Tribe/iCal.php

Per [C#38124](https://central.tri.be/issues/38124) `{sitename}-{hash}.ics` is probably better than `ical-events-{hash}.ics` since even if we ignore the .ics extension the user is probably well aware that it is iCal format and that it contains events ;-)

Replace "ical" and "events" (from the suggested filename for .ics downloads) | 38124

---

src/Tribe/iCal.php

https://central.tri.be/issues/38124 - follow up from [PR 523](https://github.com/moderntribe/the-events-calendar/pull/523) - makes the default filename for iCal feeds filterable.

Make (suggested) iCal filename filterable | 38124

---

src/Tribe/Template/Month.php

Ticket: https://central.tri.be/issues/41383
The events, on the Month view, were being sorted by menu order causing some mispositioning.

modified month event ordering to by start time

---

src/Tribe/Template/Month.php

_Ref:_ [C#38137](https://central.tri.be/issues/38137)
Added a filter to change query for the month daily events use this filter to change the order:
```
add_filter('tribe_events_month_daily_events_query_args', 'tribe_change_single_day_order' );
function tribe_change_single_day_order( $args ) {
$args['order'] = 'DESC';
return $args;
}
```

Add Filter to Month Day Query

---

readme.txt
src/Tribe/Templates.php

So, I made this change and activated all of our plugins and loaded our single event page (with tickets) and nothing seemed awry.
Here's [the request](https://wordpress.org/support/topic/the-load_ecp_into_page_template-method-overrides-page-builder-content)
See: https://central.tri.be/issues/37991

Hook to the_content on 9 rather than 10 for better plugin compatibility

---

src/Tribe/Utils/DST.php

Before the offset would be given and instead of giving the hour difference it was making it a 2 hour difference. What you were suppose to be taking away an hour from was adding an extra hour.
I found this error when trying to run the DST test.

Fixed the offset so it would take the difference of just one hour

---

src/views/modules/meta/details.php

This is a re-done PR of https://github.com/moderntribe/the-events-calendar/pull/555 that pulls the desired commit into `release/4.0.6`.
This has already been code reviewed and is ready for merge.
See: https://central.tri.be/issues/42530

Cherry pick of commit from #555: removed updated hentry from meta details start time

---

src/functions/template-tags/general.php

`rebuild_known_range` was moved to `Tribe__Events__Dates__Known_Range`

Reference the class of the relocated method

---

src/functions/template-tags/general.php

This was another change that didn't need to happen in 4.0.6 but was done because of the funky merge commit. Let's revert it.
Reverts moderntribe/the-events-calendar#559

Revert "Reference the class of the relocated method"

---

src/Tribe/Cost_Utils.php

Ticket: https://central.tri.be/issues/33491#note-15
This PR adds two missing array castings that would prevent the price merging from correctly happening

added missing array cast

---

src/Tribe/Shortcode/Event_Details.php

Support expected formatting of `[tribe:event-details]` shortcode even outside of event views.
[C#37918](https://central.tri.be/issues/37918)

Ensure availability of styles for the event details shortcode | 37918

---

src/functions/template-tags/venue.php
tests/functional/functions/template-tags/Venue_Template_Tags_Test.php

Restore work [done here](https://github.com/moderntribe/the-events-calendar/pull/517) (looks like it was overwritten when the last MR was merged in).
[C#26901](https://central.tri.be/issues/26901)

Restore tribe_get_venue_website_url()  | 26901

---

src/Tribe/iCal.php

Changes for [C#39455](https://central.tri.be/issues/39455) | [C#38124](https://central.tri.be/issues/38124) (both relate to the default filename for ical feeds) were dropped during bad merges. This PR restores them.

Restore short default filenames for iCal downloads | #39455

---

src/Tribe/Dates/Known_Range.php
src/Tribe/Main.php
src/functions/template-tags/general.php

Seems [this work](https://github.com/moderntribe/the-events-calendar/pull/519/commits) was also lost to weird merge issues. This PR restores it (the test cases added in PR 519 survived so didn't need to be restored).
[C#33205](https://central.tri.be/issues/33205)

Restore PR 519 (fix known range build and update) | #33205

---

src/Tribe/Dates/Known_Range.php

Ticket: https://central.tri.be/issues/33205
Rebuild the known date range anytime an event goes over boundaries

rebuild known range when event goes over boundaries

---

src/functions/template-tags/organizer.php

_Ref:_ [C#44285](https://central.tri.be/issues/44285)
If there is no pro then we should call the original function and return the Organizer Name only 
I believe this will enable us to keep the changes made for this ticket:
https://central.tri.be/issues/29941

Display Organizer Name if Pro is not active

---

src/Tribe/Query.php

Restores a change that seems to have been accidentally dropped due to merging issues. Basically a repeat of [PR 520](https://github.com/moderntribe/the-events-calendar/pull/520/).
[C#42940](https://central.tri.be/issues/42940)

Restore safety check introduced in PR 520 | #42940

---

src/views/month/mobile.php
src/views/month/tooltip.php

_Ref:_ [C#42701](https://central.tri.be/issues/42701)
The excerpt comes with p tags and our wrap was p tags so it would close our wrap , changed to a div to prevent this.

Fix description wrap in month mobile and tooltip

---

src/Tribe/Google_Data_Markup/Event.php

tribe_get_full_address provides inconsistent data for the markup, especially if the output have been modified by themes. (Since the `tribe_get_full_address` tag is built using the `modules/address` template.) This change guarantees consistent JSON-LD location output.
[C#44700](https://central.tri.be/issues/44700)

Update JSON-LD Address Output

---

src/Tribe/Query.php

Resolves a problem introduced in [PR 520](https://github.com/moderntribe/the-events-calendar/pull/520) which saw us trying to access the `date` property of `DateTime` objects, which isn't actually a real thing.
[C#44736](https://central.tri.be/issues/44736)

Fix handling of datetime objects passed in custom event queries | #44736

---

src/Tribe/Timezones.php

See: https://central.tri.be/issues/44790

Separate function return and object reference into two lines for PHP 5.2

---

src/Tribe/Cost_Utils.php

This modifies the regex to allow for the cost separators to _begin_ the cost regex in addition to appearing in the middle. This _may_ cause issues with costs entered as `0.0.0`, but I'm willing to deal with that problem later if a user raises it in the interest of keeping the regex simpler.
_Note: This passes our functional tests for cost ranges_
See: https://central.tri.be/issues/44711

Support costs that begin with a decimal

---

src/Tribe/Default_Values.php

In the absence of a default country, let's return an empty string.
[C#44829](https://central.tri.be/issues/44829)

If there is no default country, return an empty string | #44829

---

src/Tribe/Default_Values.php
src/admin-views/venue-meta-box.php

The `Tribe__Events__Default_Values` class returned a default ID of 0 if there was no default venue specified. Let's do two things:
1. Let's avoid placing non-truthy values in the field.
1. Let's not return 0 as a default venue ID - null is more appropriate if there isn't a venue
See: https://central.tri.be/issues/44826

If $_VenueVenue holds the default value of 0, don't fill the input value

---

src/Tribe/Default_Values.php
src/functions/template-tags/venue.php

This was removed in #609, however, it is relied on by Pro. The exected data stored for countries is the country id (i.e. US) and the country name (i.e. United States). When the default country is blank, let's provide the expected array.
Then, in `tribe_get_event_country()`, make sure we handle the array and return the country _name_.
See: https://central.tri.be/issues/44929

Bring back the default country array

---

src/Tribe/Main.php

Related: https://github.com/moderntribe/tribe-common/pull/73
See: https://central.tri.be/issues/45005

Only attempt to do the archive slug notice check on non-ajax requests

---

readme.txt
src/Tribe/iCal.php

The iCal spec doesn't call for it and it breaks some parsers (including the one we use in our iCal importer)
See: https://central.tri.be/issues/42795

Don't quote TZID in DTSTART/END

---

src/Tribe/Importer/File_Importer.php

Helps to avoid image URLs being rejected where they contain leading or trailing whitespace - [example in team chat](https://tribe.slack.com/archives/products-dev/p1458925376001083).

Strip leading/trailing whitespace from prospective image URLs (spotfix)

---

readme.txt
src/Tribe/Main.php

While looking into the WP 4.5 breaking changes surrounding admin pages for tags, I discovered that our one hook to `load-edit-tags.php` didn't do anything of note.
The associated functions attempt to add a `post_type` argument to the term cloud links on the `edit-tags.php` page for our Event post type. I commented out the hook and then rolled back my WP through the 4.x versions and all the way back to 3.9 - the earliest that we claim to support - and the `post_type` argument was still present.
As such...let's deprecate the two functions and get rid of the hook rather than keeping useless code around.
See: https://central.tri.be/issues/45431

Removing unneeded hook

---

src/Tribe/Rewrite.php

wp_kses is expensive and there's no case where even partial HTML in the lang get var makes sense.
Follow up to: https://central.tri.be/issues/45516

wp_strip_all_tags on the lang var

---

src/Tribe/PUE/Checker.php

Problem
* The following PHP Notices are triggered when WordPress is bootstrapped via WP-CLI on the command line:
```sh
$ wp plugin list
PHP Notice:  Undefined index: SERVER_NAME in wp-content\plugins\the-events-calendar\src\Tribe\PUE\Checker.php on line 517
PHP Stack trace:
PHP   1. {main}() bin\wp:0
PHP   2. include() bin\wp:4
PHP   3. include() phar://bin/wp/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar://bin/wp/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->_run_command() phar://bin/wp/php/WP_CLI/Runner.php:723
PHP   6. WP_CLI\Runner->run_command() phar://bin/wp/php/WP_CLI/Runner.php:320
PHP   7. WP_CLI\Dispatcher\Subcommand->invoke() phar://bin/wp/php/WP_CLI/Runner.php:313
PHP   8. call_user_func:{phar://bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:294}() …
```

[develop] Fixed PHP Notice: "Undefined index: SERVER_NAME" upon every WP-CLI command

---

src/Tribe/Importer/Admin_Page.php
src/Tribe/Importer/File_Importer.php
src/Tribe/Updater.php
src/io/csv/admin-views/columns.php

I was testing out some stuff and got tired of resetting these mappings each time I changed an import type. This changes the option name to include the type, so you can switch between venue, event, and
organizer without having to reset field mappings.
Also adds Tribe__Events__Importer__File_Importer::get_type() which might be useful for something.
Related to #634

Allow imports to save mappings for each different type

---

src/Tribe/Importer/File_Importer.php
src/Tribe/Importer/File_Importer_Events.php

_Ref:_ [C#46286](https://central.tri.be/issues/46286)
In WordPress 4.5 they wrapped the post_search filter in a conditional for not having a suppress_filters aregument:
https://github.com/WordPress/WordPress/commit/e6d2b6cab0702a480efc7de0c63467a858f32f8b#diff-8e20e94124dba46643814ef699330737
I believe the change I made by adding suppress_filters=false to the query should not cause earlier versions of WordPress to not have problems. 
I did this in both places we use the post_search filter

Fix Importer due to change in WordPress 4.5

---

readme.txt
src/functions/template-tags/general.php

No functional changes, this is just a follow up on [PR 645](https://github.com/moderntribe/the-events-calendar/pull/645) (props @fabianmarz) that adds some extra inline documentation and a changelog entry :smile:
[C#45603](https://central.tri.be/issues/45603)

Add hooks to featured image code

---

readme.txt
src/Tribe/Template/Month.php

_Ref:_ [C#46113](https://central.tri.be/issues/46113)
Change so Month View single days events are in this order Sticky Events, then All Day Events, then Events by Start Time.
meta_value_datetime was not ordering the dates correctly, not sure why, but the meta_value worked in my tests

Fix the order in Month View

---

src/Tribe/Linked_Posts/Chooser_Meta_Box.php

Looks like the constructor was set to protected - but this class isn't using the singleton pattern so we need to undo that.
(Spotfix)

Make constructor public (class isn't using the singleton pattern) | spotfix

---

src/Tribe/Linked_Posts.php

Changes a use of `empty()` so we examine a variable instead of a function's return value, for compatibility with PHPs 5.2 -> 5.4.

PHP compat re empty() | Spotfix 

---

src/functions/template-tags/general.php

The `tribe_events_get_the_excerpt()` function does a lot, and it's not rare that we get folks on the forums to alter the excerpt output in some way. It's unfortunately not always as easy a process as it might seem, because if they want the excerpt to do something that a code-stripping or word-trimming function *within* the function will override, then the only option is to make a template override _just_ so that they can use a different excerpt-getting function.
The introduction of this filter should hopefully help to simplify this process.
[C#46477](https://central.tri.be/issues/46477)

Add new filter to tribe_events_get_the_excerpt | #46477

---

src/Tribe/Importer/File_Importer_Organizers.php

This is a suggestion that arose from a user named Geir [in the forums](). This new filter, `tribe_events_csv_import_organizer_fields()`, should help simplify the process of importing custom data for Organizers.
[C#46476](https://central.tri.be/issues/46476)

Add a filter for customizing the Organizer import fields | #46476

---

src/Tribe/Cost_Utils.php

Stops our uncosted events query from looking at auto-drafts and revisions.
Ultimately, we probably want to be smarter in a number of places like this and match the same set of post statuses that the main query is interested in, but that's out of scope for this issue.
[C#46403](https://central.tri.be/issues/46403)

Ignore drafts, revisions when looking at event costs | #46403

---

src/Tribe/Admin/Organizer_Chooser_Meta_Box.php
src/resources/js/events-admin.js

Makes the organizer fields 'sticky', to avoid data loss during frontend event submission (such as if the submission is initially rejected due to missing required fields, etc).
[C#44457](https://central.tri.be/issues/44457)

Make organizer fields sticky

---

src/Tribe/Main.php

Removes two deprecated methods:
* Been deprecated since 4.0, seems like a good time
* They are marked protected, I'd be surprised if 3rd party code uses them
* If other code did/does use them, fatals will occur anyway as they are themselves trying to call protected methods

Remove deprecated methods | spotfix

---

src/Tribe/Linked_Posts.php

Ticket: https://central.tri.be/issues/45030
This PR is born while working on the ticket. Changes made to Tribe__API saving method and submission handling would break iCal importer (see related PR https://github.com/moderntribe/events-importer-ical/pull/86)

allow for submission data to be under ucfirst key too

---

src/Tribe/Importer/File_Importer_Events.php
tests/functional/Tribe/Events/Importer/File_Importer_Events_MultipleOrganizersTest.php

Ticket: https://central.tri.be/issues/39038#note-44
This PR adds support in the importer for multiple organisers specified as a comma separated list.
e.g. `"12, 3434, 434"` or `"34,343,345"`

added comma sep. org. ID list support

---

readme.txt
src/Tribe/iCal.php

_Ref:_ [C#46320](https://central.tri.be/issues/46320)
This fixes the block that Trisha found when trying to create a shortcode for the Month View. Using have_posts() in the maybe_add_link causes the query to be reset. Changed to checked against the global instead. 
Also, changed the method to be and action as it hooks into an action not a filter.

Fix infinite loop caused by Maybe iCal Method

---

package-whitelist.json

See: https://central.tri.be/issues/61694

Whitelist the vendor lib that does UTF8 Encoding

---

readme.txt
src/Tribe/Importer/File_Importer_Organizers.php

Adds changelog entry and inline docs for new hook, also makes the original $record array available to callbacks.
https://central.tri.be/issues/46476

Document new filter, add changelog entry | #46476

---

src/Tribe/Linked_Posts.php

Found this en route to fixing [#61871](https://central.tri.be/issues/61871) though this isn't directly related and [#61847](https://central.tri.be/issues/61847) may be a better fit: ensures when a new single linked post (ie a venue) is submitted it retains the correct field values.
Previously, `$key` would be `0` in these situations so if `$submission[ $field_name ] == 'String'` then `$submission[ $field_name ][ $key ]` would reference the first character, `S`, effectively lopping off the remainder.
https://central.tri.be/issues/61847

Fix for single/multiple linked post submission handling | spotfix

---

src/Tribe/Linked_Posts.php

Eventbrite imports events and formats venues/organizers with the old pre-linked post method...where the fields are not arrays. This changes ensures that the fields are all arrays as the new way expects. This change should help any third party submissions to saveEventMeta in the API class as well!
See: https://central.tri.be/issues/61942

Ensure that submitted venue/organizer fields are arrays

---

src/Tribe/Embedded_Maps.php

Ticket: https://central.tri.be/issues/44827#note-16
Small tweak: all Google Maps API requests should hit the `https` site.

modified GMaps API requests to always run on SSL

---

src/deprecated/Tribe__Events__Google_Data_Markup.php

Fix call to get_markup() method | Spotfix

---

readme.txt
src/functions/template-tags/link.php

See: https://central.tri.be/issues/61891
Note: we never call the function in this manner within our own code, this would only be used for theme-ing and customizations
Side note: I'm also sneaking in a submodule hash update to the latest common.

fix tribe_get_event_link function when passing 2nd param as true 

---

readme.txt
src/Tribe/Template/Month.php
src/Tribe/iCal.php

* Adds a new hook to make it easier to control when month view caching kicks in
* Adds some default rules to limit the occasions month view caching is used
* Depends on [Tribe Common PR 104](https://github.com/moderntribe/tribe-common/pull/104)
https://central.tri.be/issues/46581

Add some default constraints to month view caching | #46581

---

readme.txt
src/Tribe/Templates.php
src/functions/template-tags/general.php

_Ref:_ [C#62577](https://central.tri.be/issues/62577) - We use is_embed 4 different times in this template: the-events-calendar/src/Tribe/Templates.php 
Instead of wrapping those with a version check I added one to the general.php file 
Not sure if this is the best approach, but this would help prevent fatals in WordPress 3.9 to WordPress 4.3
Method for commit is in common: https://github.com/moderntribe/tribe-common/pull/108

is_embed fix for older versions of WordPress

---

readme.txt
src/Tribe/Importer/File_Importer_Events.php

_Ref:_ [C#62699](https://central.tri.be/issues/62699) This is late in the game, but the only change is to remove the short array syntax and use the 5.2 and 5.3 compatible array().

Use array instead of [] for PHP 5.2 compatibility

---

src/Tribe/Linked_Posts/Chooser_Meta_Box.php

This is a follow-up fix to #744
This issue was found while testing: https://central.tri.be/issues/63148

Avoid empty() call on a function call - use a variable

---

src/Tribe/Main.php

The `GLOB_BRACE` flag for `glob()` is not available on all systems. Most notably it's not supported on Solaris and Alpine (a quite popular lightweight linux distribution used mostly for running docker containers). On this PR I propose a way of achieving the same result which doesn't use such flag and hence improves compatibility.
Related: https://github.com/moderntribe/event-tickets/pull/227
See: https://central.tri.be/issues/63172

Stop using the GLOB_BRACE flag

---

readme.txt
src/Tribe/Main.php

Following this [community PR](https://github.com/moderntribe/the-events-calendar/pull/753), tidies up some whitespace issues and adds a changelog entry.
https://central.tri.be/issues/63474

Tidy whitespace, add changelog entry | #63474

---

src/Tribe/iCal.php

Hi,
I encounter an issue regarding the iCal Export template button from a single event view.
The errors I got is "Cannot modify header information - headers already sent by..." This issue appears because you have some code inside your `Tribe__Events__iCal` class that is called after some rendered output in the browser.
Here are the lines the error report points to:
```php
$filename = apply_filters( 'tribe_events_ical_feed_filename', $site . '-' . $hash . '.ics', $post );
header( 'Content-type: text/calendar; charset=UTF-8' );
header( 'Content-Disposition: attachment; filename="' . $filename . '"' );
```
This code is run once the hook `tribe_tec_template_chooser` is called which is too late.
By changing the hook name to a more appropriate one: `template_redirect`, no more errors were …

Fix iCal export.

---

src/functions/template-tags/venue.php

Further update to remove meta factory related calls, can achieve the same using template tags.
[#39905](https://central.tri.be/issues/39905)

Tidy tribe_get_venue_details() to avoid using meta factory API | #39905

---

src/Tribe/Templates.php

Ticket: https://central.tri.be/issues/62525
Simply call the same filter we call when a template file is not found when a template file is found.

added missing found file filtering

---

src/Tribe/API.php

See: https://central.tri.be/issues/65030

Don't throw notices when old and new meta values are not set

---

src/Tribe/API.php

emerged while working on ticket https://central.tri.be/issues/61724 to restore ET tests:
add an `isset` check to avoid errors when a meta field is not set on `old`

add an isset check

---

src/Tribe/Aggregator/Record/CSV.php
src/admin-views/aggregator/tabs/import-form.php
src/resources/js/aggregator-fields.js

Additionally rolling back width=100% issue because it broke wide, scrollable tables.

Fixing bug with manual imports where they were no longer possible

---

src/Tribe/Aggregator/Event.php

We were sanitizing aggressively for no real reason. We need to search for the uid values that are inserted.
See: Findings compilation doc

We don't need to sanitize in such a limited manner. wpdb prepare is fine

---

src/Tribe/Aggregator/Record/Abstract.php
src/Tribe/Aggregator/Tabs/Edit.php

We set that field for the Last Import date, so we don't want to update it
if the settings change.
Also fixed a couple of notices.

don't change post modified on schedule update

---

src/Tribe/Aggregator/Record/Abstract.php

This is a spotfix with the wrong branch name. Sue me.

Return the WP_Error, not an ID when the daily limit is reached

---

src/Tribe/Aggregator/Record/CSV.php
src/Tribe/Aggregator/Tabs/New.php
src/Tribe/Importer/Column_Mapper.php

This resolves a couple of issues:
* CSV saving when mapping fields failed to render fields that _must_ be mapped
* CSV field settings for organizers and venues were not auto-selected because the wrong option was being saved
See: https://central.tri.be/issues/65945

Better handling of CSV headers

---

src/Tribe/iCal.php

According to [RFC 5545 section 3.8.7.3](https://tools.ietf.org/html/rfc5545#section-3.8.7.3) and [section 3.8.7.1](https://tools.ietf.org/html/rfc5545#section-3.8.7.1) the LAST-MODIFIED and CREATED properties are of DATE-TIME type and MUST be specified in UTC time format.
The current code in src/Tribe/iCal.php is buggy: It switches the type for these two fields (together with DTSTART and DTEND, where that's allowed) between DATE and DATE-TIME based on the _EventAllDay meta. For an "all day" event, invalid output (such as `CREATED:20160831`) is generated. Other software doesn't react well to this (Example: Python [vobject](http://eventable.github.io/vobject/): `vobject.base.ParseError: At line 13: '20160831' is not a valid DATE-TIME`).
This pull request changes both fields to UTC DATE-TIME …

Fix CREATED and LAST-MODIFIED fields in iCal export

---

src/Tribe/Aggregator/Record/CSV.php
src/Tribe/Aggregator/Tabs/New.php
src/Tribe/Importer/File_Importer.php
src/Tribe/Importer/File_Importer_Events.php

Post statuses, when submitted via the New Import form, were not getting applied when inserting posts during CSV imports. This resolves that as well as ensures that default categories are set appropriately.
See: https://central.tri.be/issues/65358

Set CSV default post status and categories correctly

---

src/Tribe/Importer/File_Importer.php

Changes the `skipped` field's access modifier to protected: as subclasses like `Tribe__Events__Importer__File_Importer_Events` try to work with the property it cannot be private.

Skipped field is used by subclasses and so should not be private | spotfix

---

src/Tribe/Aggregator/Records.php
src/Tribe/Ignored_Events.php

Ensures that the `_EventOrigin` is reliably set for all events pulled in through EA, and removes the exception for CSV-sourced events re Hide & Ignore (ie, make it so they can be ignored rather than trashed).
[#61161](https://central.tri.be/issues/61161)

Remove exception for CSV-imported events re Hide & Ignore functionality

---

src/Tribe/Ignored_Events.php

Form the correct link to the ignored event list even if all we have are legacy, as yet unconverted deleted_posts. 
The problem this solves is that (if we have no EA-style ignored events, but we do have as yet unconverted 'legacy' ignored events) we don't present the user with a list of _all_ events when they click the _Ignored (X)_ link.
[#61161](https://central.tri.be/issues/61161)

Always form the correct link to the ignored event list 

---

src/Tribe/Aggregator/Page.php

Either Safari does not properly observe the .ics extension in plupload settings or the version of plupload in WP does not communicate well with Safari. As such, we're just going to remove the mime type restrictions on the EA import page.
See: Findings doc

Remove mime type restrictions

---

src/Tribe/Aggregator/Tabs/New.php

*View your event categories* should link to event categories list, not the list of organizers.

Fix view categories link | spotfix

---

src/Tribe/Aggregator/API/Origins.php

Forcing a fetching of origin data all the time is stupid. Let's not do that.
See: https://central.tri.be/issues/66538

Don't make a useless call to fetch data

---

src/Tribe/Aggregator/Service.php

Even if `$response` is not a `WP_Error`, there may be no `status` property (if the site doesn't have an EA key for example).

Bail if $response does not have a status property | spotfix

---

src/Tribe/Aggregator/Record/List_Table.php

For consistency, use GMT datetimes when figuring out how long ago / how far in the future an import occurred.
https://central.tri.be/issues/66521

Use GMT for comparisons when determining relative times for imports | #66521

---

src/Tribe/Aggregator/Tabs/New.php

Ticket: https://central.tri.be/issues/66691
* avoid calling queue methods on WP_Error object
* fix the exit status check

fix failed import detection

---

src/Tribe/Aggregator/Tabs/New.php

Resolves some notices/warnings where various message arrays are not set or are empty.

Test if messages are set before generating notice | spotfix

---

src/Tribe/Aggregator/Cron.php
src/Tribe/Aggregator/Record/Abstract.php
src/Tribe/Aggregator/Record/List_Table.php
src/Tribe/Aggregator/Tabs/Scheduled.php

Allows a scheduled import to be deactivated (so that automatic imports stop happening) and for deactivated imports to be reactivated (restoring the previously scheduled interval).
https://central.tri.be/issues/66838

Let scheduled imports be deactivated and reactivated

---

src/Tribe/Admin/Bar/Default_Configurator.php

Simplify the admin toolbar entry for the importer page (no sub-menu required).
[#66707](https://central.tri.be/issues/66707)

Reduce importer entry in admin toolbar to a straightforward link | #66707

---

src/Tribe/Aggregator/Cron.php
src/Tribe/Aggregator/Record/Abstract.php
src/Tribe/Aggregator/Record/List_Table.php
src/Tribe/Aggregator/Tabs/Scheduled.php

This change has us using an update query instead of `wp_update_post()` when we modify the import interval, because the latter function has a side effect of updating `post_modified_gmt` (which we use to track the last import operation - and so is something we don't want to alter when the interval changes).
[#66838](https://central.tri.be/issues/66838)

DRY-up interval change code; avoid side effect of updating post_modifed_gmt

---

src/Tribe/Rewrite.php

Hi!
I propose to remove the filter 'tribe_events_rewrite_rules' because it conflicts with a WordPress filter of the same name. See https://github.com/WordPress/WordPress/blob/4.5.3/wp-includes/class-wp-rewrite.php#L1416
The WP filter has only one argument. Attempting to use the second argument of the TEC filter creates an error.
The WP filter sends only the rules related to the 'tribe_events' post type, while the TEC filter sends all rewrite rules. This can raise all sorts of conflicts in plugins using the WP filter and not aware of the existence of the TEC filter.
As is, the TEC filter is not very useful as the WP filter 'rewrite_rules_array' is already there to filter all rewrite rules if someone needs it.
Considering the inline comment, I propose to simply remove the existing filter, …

Remove the 'tribe_events_rewrite_rules' filter

---

src/Tribe/Aggregator/Record/Abstract.php
src/Tribe/Aggregator/Tabs/New.php

This way we can track hard limits remotely.
See: https://central.tri.be/issues/66891

Communicate that a preview is a preview to the EA Service

---

src/Tribe/Main.php

Builds on tribe-common pr 210: moves the task of loading tribe-common's deprecated classes from the dependent plugin to tribe-common itself.
https://github.com/moderntribe/tribe-common/pull/210
https://central.tri.be/issues/66872

TEC should let tribe-common handle its own deprecated classes | #66872

---

src/Tribe/Aggregator/Record/Abstract.php
src/Tribe/Aggregator/Tabs/Scheduled.php

See: https://central.tri.be/issues/66891

Properly handle error states when running schedule records interactively

---

src/Tribe/Aggregator/Migrate.php

I _was_ going to also display the notice on the Legacy Import page, but there's already a huge pile of notices. We can add it if we _want_, but I don't think it is necessary. As soon as the legacy plugin is deactivated, the Legacy Import pages will go away.

Only show the legacy plugin migrator notice on EA pages

---

src/Tribe/Aggregator.php

Events Importer: iCal does a silly thing. When you deactivate the plugin, it purges the saved recurring imports with a deactivation hook.  This PR removes iCal's action that does the purging.
See: https://central.tri.be/issues/61940#note-15

Unhook iCal deactivation hook so recurring imports aren't purged

---

src/Tribe/Aggregator/Record/Queue.php

`activity` property may be null.

Use activity() to avoid calling methods on null | spotfix

---

src/admin-views/aggregator/origins/facebook.php

Without the field, `dependency.js` flips its lid and goes crazy-recursive
See: https://central.tri.be/issues/67214

When FB creds are NOT SET, include a hidden field indicating as much

---

src/Tribe/Aggregator.php

Avoids registering the EA status section of the help page when something other than the help page has been registered. This helps prevent an HTTP request (to check the status) being made on each request.

Do not register status section unless we are within the help tab [spotfix]

---

src/Tribe/Aggregator/Cron.php

`$queue->activity` may be null; prefer `$queue->activity()` instead. Thanks to Jeff for [catching this!](https://tribe.slack.com/archives/quality-assurance/p1475188920001344)

Prefer the activity() getter function over naked access to the (possibly null) property

---

src/Tribe/Template/Month.php

`get_daily_events()` is not a static method.

get_daily_events() is an instance method, call it appropriately | spotfix

---

src/Tribe/Integrations/WPML/Rewrites.php
src/Tribe/Integrations/WPML/Utils.php

Ticket: https://central.tri.be/issues/63262#note-19
This PR makes sure we take WPML slug translation into account when generating our rewrite rules.
The `$wpdb` low level access is to circumvent the lack of a function to do so.

take slug translation of post slug into account

---

src/Tribe/Admin/Bar/Default_Configurator.php

Sydney found a bug related to Admin Menu bar. The Help page link was broken, pointing to the old Settings tab.

Modify the Link to Admin bar Help Page

---

src/Tribe/Aggregator/Record/CSV.php

Found this while hunting down a CSV state/province import bug

Prevent notice when executing CSV import and created|updated|skipped = 0

---

src/Tribe/Aggregator/Tabs/New.php

Also:
* Only show the "Show All" link if there's a page for viewing posts of that type (example: Tickets don't have a browsable page)
* Use the post type name being imported rather than always using "Events" when nothing has been imported/updated
See: https://central.tri.be/issues/67878

Failover to non-lowercase labels if lowercase not set

---

src/Tribe/Aggregator/Page.php

See: https://central.tri.be/issues/67915

Move tribe_assets for EA to init so csv_mappings can be filtered by ET+

---

src/Tribe/Main.php

Since we aren't releasing 4.3 versions of those plugins.

Avoid throwing "mismatched version" notices for Facebook and iCal

---

src/Tribe/Integrations/WPML/Defaults.php
src/Tribe/Main.php
src/Tribe/Organizer.php
src/Tribe/Venue.php
src/admin-views/organizer-meta-box.php
src/admin-views/venue-meta-box.php

Ticket https://central.tri.be/issues/25084
This PR removes the use in read and write operations of the `OrganizerOrganizer` meta field when creating organizers; the same I've applie to venues due to similarity removing use of the `VenueVenue` meta field.
Note the consequent PR here: https://github.com/moderntribe/events-eventbrite/pull/137

Remove duplicate meta for Org and Venue title

---

readme.txt
src/Tribe/Rewrite.php

Ticket: https://central.tri.be/issues/68062
This PR handles the case where we want to suport translated version of our rewrite bases, `/all` in the ticket instance but it would apply to *any*, when a site language is not English.  
What we were previously relying on WPML to do can be done by WPML *and* the available translations.  
In case you are wondering the WPML integration fires off on the `tribe_events_rewrite_i18n_slugs_raw` filter.

Fetch locale translation for bases

---

src/Tribe/Aggregator/Cron.php
src/Tribe/Aggregator/Record/Abstract.php
src/Tribe/Aggregator/Record/List_Table.php

This will help ensure that the "Last Import" tab has the info for the most recent scheduled execution.
See: https://central.tri.be/issues/68283#note-8

Avoid purging the most recent child records for Schedules

---

src/Tribe/Aggregator/Meta_Box.php

Additionally, make sure the origin gets pretty-fied.
See: https://central.tri.be/issues/68288

Remove two null overrides that were there for debug purposes

---

src/Tribe/Aggregator/Cron.php
src/Tribe/Aggregator/Service.php
src/Tribe/Aggregator/Tabs/Scheduled.php
src/admin-views/aggregator/status.php

* Make sure we don't fetch cached usage limits when creating a schedule child - we always want fresh usage info
* Observe the usage limits when attempting to run a schedule interactively
* Resolve issues with the EA usage status on the Help page
See: https://central.tri.be/issues/68286#note-8

Better messaging/use of usage limits

---

src/Tribe/Template/Month.php

Ticket: https://central.tri.be/issues/67495
This PR removes the `_EventStartDate` query args from the query.
At that point the events have been already pruned and sorted by the `_EventStartDate` meta and doing it again causes those that start at the start of day cutoff to "disappear".
This could very much use a second pair of eyes.

removed redundant meta key

---

src/Tribe/Main.php

Fix an error due to no more loaded ical template tag; I've also removed a deprecated function.

restored ical template tag load

---

readme.txt
src/Tribe/Aggregator/Page.php

Ticket: https://central.tri.be/issues/68662
Add a check to avoid checks versus a `null` value ID and hence always apply the "New Import" label.

Avoid hijacking the page title

---

src/functions/template-tags/general.php

By default, apply `.tribe-event-featured` if the event is featured.
https://central.tri.be/issues/65895

Use 'tribe-event-featured' CSS class for featured events | #65895

---

src/functions/template-tags/general.php

Addresses Leah's feedback [here](https://tribe.slack.com/archives/products-dev/p1478656237009966) - stupid oversight in a change I made yesterday :dunce:
https://central.tri.be/issues/65895

Fix oversight where the featured img HTML was returned twice | #65895

---

src/Tribe/Aggregator/Page.php

Further fix in the saga of select2 problems.
See also: https://central.tri.be/issues/69468

Update select2 slug for tribe-ea-fields dependencies | spotfix

---

src/Tribe/Featured_Events/Permalinks_Helper.php

Do not modify single event slugs/URLs in the context of featured event archives.
https://central.tri.be/issues/68051

Don't append /featured/ to single event slugs | #68051

---

src/Tribe/Main.php

Restores line responsible for enqueuing `event-editor.js` (which was clobbered by a later commit).
https://central.tri.be/issues/65897

Restore enqueuing of event-editor.js in event edit screen | #65897

---

src/Tribe/Front_Page_View.php

The global `$wp_query` object for CE pages passes the `is_home()` test. This can lead to breakages when front page events are enabled, which this change aims to fix.
https://central.tri.be/issues/38757

Avoid breakages when front-page-events are enabled alongside Community Events

---

src/Tribe/Admin/Front_Page_View.php

Follow up: ensure a piece of text used by our JS is localized.
https://central.tri.be/issues/38757

Translate the main events page text (Settings > Reading) | #38757

---

src/Tribe/Main.php

Supply the datepicker with _full_ month names in place of short month names (we want the full month names to render in the month selector dropdown within that widget).
No changelog entry added as this is essentially a child of [#66550](https://central.tri.be/issues/66550).
https://central.tri.be/issues/69246 (Item 1)

Supply the datepicker with *full* month names (for the month dropdown)

---

src/Tribe/Main.php

Remove EDD's bundled jQuery UI and admin styles from the event editor.
[EDD issue #3033](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3033) | [#69686/R125 findings](https://central.tri.be/issues/69686)

Stop EDD-enqueued styles from mangling the event editor's datepicker

---

src/admin-views/linked-post-meta-box.php
src/resources/js/events-admin.js

Transitioning from Chosen to Select2 for various elements and some other adjustments left the add-new-linked-post functionality broken; this should fix.
Depends on [tribe-common PR 285](https://github.com/moderntribe/tribe-common/pull/285) for access to existing dropdown methods.
[#69686/R125 findings](https://central.tri.be/issues/69686)

Update add-new-linked post handler to match other changes

---

src/Tribe/Admin/Event_Meta_Box.php

When setting up the datepicker, if a date hasn't been selected let's use `date_i18n()` rather than `date()` to avoid discrepancies between the local timezone and UTC.
[#69686/R125 findings](https://central.tri.be/issues/69686)

Use date_i18n() to get the date in the current site timezone | #69686

---

src/Tribe/Customizer/Global_Elements.php

With the defaults in place, they override all kinds of things. Let's let the theme's stylesheet (and TEC stylesheet) be the base and allow users to set/clear their selections rather than always forcing a default.
See: https://central.tri.be/issues/69755

Remove defaults in the Customizer for links and buttons

---

src/Tribe/Aggregator/Record/Abstract.php

Ticket: https://central.tri.be/issues/69465
This PR fixes a check to make sure we set the featured image on EA imported posts if there is any image; whatever state of import the image is in.

Set the featured image on posts if there is an image

---

src/Tribe/Admin/Event_Meta_Box.php

Default end time in the event editor was 'today' in UTC, let's use 'today' in the local timezone instead.
https://central.tri.be/issues/69979

Default end date should be based on site timezone | #69686

---

readme.txt
src/Tribe/Main.php

Fixes a typo/oversight: we need to test against `$display` rather than `$this->displaying`: the latter isn't set until the end of the method.
This change should restore normal behaviour of the `/all/` view. Placing on hold in case we need to re-target to a hotfix branch.
https://central.tri.be/issues/70623

Fix broken 'all' page

---

src/Tribe/Aggregator/Record/Queue_Processor.php

Tickets:
* https://central.tri.be/issues/69542
* https://central.tri.be/issues/69824
Fixes a notice popping up during the "fetch" phase of the import that would generate a PHP error.

avoid notice during fetch phase

---

readme.txt
src/Tribe/Main.php

Ticket: https://central.tri.be/issues/68599
When in the context of the network admin do not append the post type query arg: the menu is now in Settings.

avoid appending post type to network admin pages

---

readme.txt
src/Tribe/Integrations/WPML/Language_Switcher.php
src/Tribe/Integrations/WPML/WPML.php

Ticket: https://central.tri.be/issues/67134
This PR adds a filter in the WPML integration to make sure archive links are still built in a way that makes sense.

add language switcher filter

---

src/Tribe/Aggregator/Record/Queue.php

Ensure calls to `$queue->activity` are routed through `$queue->activity()` (so we can be sure a record activity object is returned to the caller).

Do not allow access to uninitialized activity member | spotfix

---

src/Tribe/Customizer/General_Theme.php

Further adjustment to support light featured event accents.
https://central.tri.be/issues/69978

Support a light featured-event accent in the core event list widget

---

package.json
readme.txt
src/Tribe/Main.php
the-events-calendar.php

Helps prevent fatal errors during plugin activation (if an earlier than required version of Tribe Common is already present and loaded).

Add safety check 

---

src/Tribe/Aggregator/Page.php
src/Tribe/Aggregator/Service.php
src/Tribe/Aggregator/Tabs/New.php
src/Tribe/Main.php
src/Tribe/REST/V1/EA_Messages.php
src/Tribe/REST/V1/Main.php
src/Tribe/REST/V1/Messages.php
src/resources/js/aggregator-fields.js

Ticket: https://central.tri.be/issues/71337
Builds on: https://github.com/moderntribe/tribe-common/pull/313
This PR makes sure REST V1 messages are handled and used in 2 moments:
1. when the EA service answers the request and the response is packaged (especially errors)
2. when data is handled on the JS side

Add and handle REST V1 (Other URL) messages

---

src/Tribe/Cost_Utils.php
src/Tribe/Main.php
src/Tribe/REST/V1/Post_Repository.php
src/functions/template-tags/general.php
tests/_support/Testcases/Events_TestCase.php
tests/integration/Tribe/Events/REST/V1/Post_RepositoryTest.php
tests/integration/Tribe__Events__Cost_Utils_Test.php
tests/restv1/SingleEventCest.php

Tickets:
* https://central.tri.be/issues/70386
* https://central.tri.be/issues/70385
This PR:
* will make sure that the REST response for an event website will be set to the event permalink itself if empty
* will set the cost of the event according to how we would format it on the front-end returning the complete cost string ("Free" or "$34") and the cost components in ASC order (`[0, 12, 15,30]` for an event that has tickets with prices ranging from free to $30)
* updates the tests (REST and Integration) accordingly
Notice that while the ticket deals with the other side of the import (the destination) setting the event data in the REST response makes sense.

Smart event cost and website fields in the REST API response

---

readme.txt
src/Tribe/Linked_Posts.php

_Ref:_ [C#71369](https://central.tri.be/issues/71369)

Attach wp_localize_script to the correct handle, jQuery is unsafe.

---

src/Tribe/Asset/Events_Css.php

Since the tribe-events.css override comes from the theme, it makes sense
to use the theme version when enqueuing the css. This makes it possible
for themes to release an update that changes the css override. Otherwise
browsers can have the old version of the theme's css cached.

add theme version to css override

---

src/Tribe/Inactive_Events.php
src/Tribe/Main.php

Adds our inactive post type as required by the recurrence architecture docs. I've located it within TEC as it could potentially be useful outside of ECP.
https://central.tri.be/issues/71509

Register an 'inactive event' post type | #71509

---

src/Tribe/Main.php

~https://central.tri.be/issues/66545~
Whoops, looks like that ticket was a different issue.
So this is just a spotfix...
Re: https://theeventscalendar.com/support/forums/topic/google-map-link/

Google Maps HTTP to HTTPS

---

src/Tribe/Asset/Events_Css.php

See: https://wordpress.org/support/topic/fatal-error-in-4-4-1/

Use the correct var name and double check the var before usage

---

src/functions/template-tags/google-map.php

`googleMapLink()` is in core, not PRO

Change variable name to avoid confusion with PRO | spotfix

---

readme.txt
src/functions/template-tags/google-map.php

Historically `'1'` was used to indicate a positive show map/map link value, though we began using `'yes'` in EA. This changes makes the editor UI tolerant of both possibilities.
https://central.tri.be/issues/67228

Aggregator > global/source specific show-map setting fix

---

readme.txt
src/Tribe/List_Widget.php

Ensure the show/hide if no upcoming events configuration of the events list widget is respected.
https://central.tri.be/issues/72965

Show when no upcoming events

---

src/Tribe/Main.php
the-events-calendar.php

Ticket: https://central.tri.be/issues/69583
We now have a plugin file constant like we do in our other plugins, and like our plugins this one will now register itself `Tribe__Dependency`. 
I rebased the changes in `feature/66657-register-plugins` to the MR's code. That branch was meant to be submitted a few MR's back, but slipped through the cracks.

Register TEC with Tribe__Dependency

---

src/Tribe/Aggregator/Record/Abstract.php
src/Tribe/Aggregator/Settings.php
src/admin-views/aggregator/settings.php

Ticket: https://central.tri.be/issues/72911
This PR adds an option field to control whether an event presentation settings should be imported or not alongside its content when importing from the Other URL source.

Add policy control for URL import settings

---

src/Tribe/REST/V1/Settings.php

Ticket: https://central.tri.be/issues/72911
Remove the option to disable the REST API but leave the Settings structure in place as we might need it

remove rest api settings

---

readme.txt
src/Tribe/Aggregator/API/Image.php

`wp_remote_retrieve_headers()` returns an array of headers, not an object
See: https://central.tri.be/issues/72764

Resolve EA Facebook image import problem caused by object vs array bug

---

readme.txt
src/admin-views/tribe-options-display.php

I know this allows for values less than -1, but I'm not concerned on that front.
Requires: https://github.com/moderntribe/tribe-common/pull/333
See: https://central.tri.be/issues/70497

Allow for negative numbers for "Month view events per day" setting

---

src/functions/template-tags/loop.php

Month and day view title strings were the same which doesn't work in some languages.
https://central.tri.be/issues/70068
https://central.tri.be/issues/68999

Enable month view and day view titles to be translated separately

---

readme.txt
src/Tribe/Main.php
src/Tribe/Rewrite.php

Ensure that the translated version of the /all/ slug is respected.
This is in the-events-calendar rather than events-pro simply because, for whatever historic reason, most of our code that relates to this sort of permalink lives here (and it wasn't within the scope of this fix to resolve that).
https://central.tri.be/issues/71996

Fix /all/ slug for users of translation packs | #71996

---

src/Tribe/Meta/Save.php
src/admin-views/widget-admin-list.php

This is a follow up of #753.
The goal of this PR was to avoid calling remove_action on 'save_post' while already running this action. The PR was merged in develop branch for the 4.3 main release. But the function was refactored in parallel in the 4.2.x branch and it looks like the merge lost the main purpose of #753, i.e removing the call to remove_action.

Don't call remove_action in a function hooked to the same action

---

src/Tribe/Templates.php

Using `locate_template()` effectively bypasses all of the normal template hierarchy filters that are normally made available to developers at this stage when loading a page. This PR ensures developers can still hook into those filters by using the same function that WordPress core uses in [**wp-includes/template-loader.php**](https://github.com/WordPress/WordPress/blob/master/wp-includes/template-loader.php#L56).
Full disclosure: I haven't tested this. A user was having difficulty with your plugin, and I noticed this issue when I was diving into your code. A workaround was possible for his particular issue, but I figured I would still bring this to your attention.

Use `get_page_template()` not `locate_template()`

---

src/Tribe/Venue.php

The meta box title "Location" when creating / editing an event was not translated.

Added translation option for 'Location' meta box title

---

readme.txt
src/Tribe/Template/Month.php
src/admin-views/tribe-options-display.php

For new installations/where the month view cache setting has not already been saved, default to enabling it.
https://central.tri.be/issues/74867

Enable month view cache by default

---

src/Tribe/Aggregator/Event.php

Resolves Nico's finding in [#72876 (note 12)](https://central.tri.be/issues/72876#note-12) - we explicitly need to set the start and end _hour_ and _minute_ values if we want to preserve them, in addition to the date itself.

Start/end hour and minute require special handling | #72876

---

src/Tribe/REST/V1/EA_Messages.php

Ticket: https://central.tri.be/issues/71337
See PR: https://github.com/moderntribe/event-aggregator-site/pull/144
This PR changes the wording of the message reporting a site as one not exposing any information about TEC REST API as per Leah's request here: https://central.tri.be/issues/71337#note-21

Change wording of non TEC site message

---

src/Tribe/Aggregator.php

Ticket: https://central.tri.be/issues/75561
Origins limit should be purged when the license string is updated.

Purge import usage count on license update

---

src/Tribe/API.php
src/Tribe/Aggregator/Event.php

Ticket: https://central.tri.be/issues/74264
This PR taps into the `Tribe_Tracker` class to avoid resetting an imported event local changes pertaining tags and categories to the imported data.

Avoid category and tag override during import

---

src/Tribe/Main.php

Ticket: https://central.tri.be/issues/74
This PR makes sure we are tracking the `post_tag` and the `tribe_events_cat` taxonomies for our post types to avoid them being overriden in imports.

add taxonomy tracking in Main

---

readme.txt
src/Tribe/Template/Month.php

If month view caching is enabled let's persistently cache both the result of the events-in-the-month query and the month's JSON LD output (in addition to the month view HTML, which is already covered).
In local testing, this reduced the total number of queries required to build month view by 90% (given a month containing 100 events). Props to @elimn for laying the groundwork here.
:ticket: [#74656](https://central.tri.be/issues/74656)

Improvements to month view caching

---

src/Tribe/Aggregator/Service.php

Ticket (contetxt): https://central.tri.be/issues/72634
This PR adds support for the `no-results` message when a fetch from a feed is successful but simply yields no results; this could happen when using keywords or dates or whatever.
This avoids the client hanging up on an empty events array after receiving the response.

Add the no-results message for feeds

---

src/functions/template-tags/date.php

I noticed that more up to date versions of `tribe_get_start_time()` and `tribe_get_end_time()` are [in common](https://github.com/moderntribe/tribe-common/blob/ce0aadeffee590b2416a076ec45f00be5df80447/src/functions/template-tags/date.php#L156-L256). The ones here are duplicates, which is both unnecessary and going to make things harder to debug.
Then I added a filter to `tribe_get_display_end_date()` to bring it inline with our other template functions.

Removed duplicate date functions and added a filter.

---

src/Tribe/Aggregator/Settings.php
src/Tribe/Aggregator/Tabs/Abstract.php
src/admin-views/aggregator/origins/url.php
src/admin-views/aggregator/settings.php

`MONTH_IN_SECONDS` is not available on versions prior to 4.4 of WP

Replace MONTH_IN_SECONDS with 30 * DAY_IN_SECONDS

---

src/Tribe/Main.php
src/Tribe/Venue.php

_Ref:_ [C#64088](https://central.tri.be/issues/64088)
---
This one has been pretty challenging for me, but I say with caution that I _think_ I have implemented a solution here that:
- Reliably prevents duplicate venues from existing after "Previewing" an Event.
- Doesn't require reworking the whole way venues/linked posts are saved.
What I spent a lot of time untangling here was the following problem:
- When "previewing" an event, it's saved as a draft.
- This fact was useful to me at first—by watching for the transition of an event's post status from _draft_ to _publish_, for example, I was able to capture "duplicate" venues from when the event was previewed and delete those duplicate venues.
- *But*, an event's being a draft is totally arbitrary. There's nothing about the post status …

64088 | Prevent Duplicate Venues After "Previewing" an Event

---

readme.txt
src/functions/template-tags/general.php

Following user feedback, makes it easier to exercise control over the inclusion or exclusion of the year in the event schedule details string.
:ticket: [#78070](https://central.tri.be/issues/78070)

New hook to control inclusion/exclusion of year

---

readme.txt
src/Tribe/Aggregator/Record/Queue_Cleaner.php

Initialize the `$time_to_live` property in a way that is compatible with PHP 5.5 and earlier.
:ticket: [#79208](https://central.tri.be/issues/79208)

Change field initialization for pre-5.6 compatibility | #79208

---

src/Tribe/REST/V1/Main.php

Ticket: https://central.tri.be/issues/78582
Due to the changes made in common to use the Formatter here: https://github.com/moderntribe/tribe-common/pull/397 the REST API validator has been made a general purprse one.

Change the class of the validator

---

src/Tribe/Aggregator/Record/Abstract.php

`$type` isn't actually defined, so it makes more sense to pass the `$meta` array (which will contain the type if set, besides potentially conveying other information).

Pass $meta array as the error context | spotfix

---

readme.txt
src/Tribe/Main.php

Keep markup and translatable elements separate.
:ticket: [#79729](https://central.tri.be/issues/79729)

Make the update confirmation message easier to translate

---

src/Tribe/Aggregator/Cron.php
src/Tribe/Aggregator/Record/Queue.php

Ticket: https://central.tri.be/issues/79587
This PR removes an over-zealous inconsistency check I have added (so yes: this issue is completely my fault) to allow scheduled imports to run free again.

Fix scheduled imports not running

---

src/Tribe/Main.php

Part of the work done for https://central.tri.be/issues/79791
The binding is needed to rebuild the known range in the Instance Engine on update.

bind the Known Range class in Main

---

src/Tribe/iCal.php

I had a photo gallery's shortcode showing within the iCal Export's description area. This wasn't happening for the Google Calendar link so I made the iCal description filtering setup match the Google Calendar description filtering a bit more.
Also, I had tabs showing as "\t" within macOS Calendar... I replaced that within the str_replace array with an actual tab and it's working perfectly now.
:ticket: [#80452](https://central.tri.be/issues/80452)

Make it so the iCal description accounts for shortcode

---

src/functions/template-tags/general.php

Ran into an issue on one of our sites with a shortcode partially showing in an excerpt. 
From looking at the `tribe_events_get_the_excerpt` function, trimming the text _after_ running the shortcodes seemed to make the most sense for this scenario. Not sure if there may be other implications I haven't seen. Tested this on our sites & the patch worked out great.

Filter shortcodes before trimming excerpt

---

readme.txt
src/Tribe/Integrations/WPML/Category_Translation.php
src/Tribe/Integrations/WPML/Rewrites.php
src/Tribe/Integrations/WPML/Utils.php
src/Tribe/Integrations/WPML/WPML.php

If WPML is active it attempts to translate the events category base slug: let's ensure we update the permalink rules accordingly to support this.
:ticket: [#73478](https://central.tri.be/issues/73478)

WPML compatibility: support translated event slugs | #73478

---

readme.txt
src/Tribe/Linked_Posts.php

Adds a new filter to control where the create new linked post type options are rendered as part of the linked post dropdown.
:ticket: [#80487](https://central.tri.be/issues/80487)

Add new hook for control over linked post dropdown UI | #80487

---

readme.txt
src/Tribe/Templates.php

Instead of doing `wp_get_theme()->Template` each request - which makes WordPress parse the theme header file - use `get_stylesheet()`.
:ticket: [#71974](https://central.tri.be/issues/71974)

Minor performance enhancement (theme compat code)

---

readme.txt
src/Tribe/Main.php
src/Tribe/Rewrite.php

Removes permalink logic that ought to belong in PRO.
:ticket: [#74153](https://central.tri.be/issues/74153)

Strip single recurrence and `/all/` permalink logic from TEC (belongs in ECP)

---

readme.txt
src/Tribe/Aggregator/Service.php

Ticket: https://central.tri.be/issues/71505 and https://central.tri.be/issues/82713
This is the Client side of the fix put in place on EA to tackle the issue (https://github.com/moderntribe/event-aggregator-site/pull/208); it just adds a message to state that no events were found while fetching from FB.

Add a no results message for FB fetch

---

readme.txt
src/Tribe/Aggregator/Event.php
src/Tribe/Aggregator/Record/Abstract.php

Ticket: https://central.tri.be/issues/75370
This PR uses, in the case of FB and Meetup origins, the ID provided by the origin to look for duplicates and avoid false positives while doing so.
What was happening in the ticket is that `Venue Foo` with a FB ID of `12345` and `Venue Foo` with a FB ID of `678910` would, incorrectly, be matched as same.

Avoid overwriting FB Venues and Organizers when they have the same name

---

composer.lock
src/Tribe/REST/Interfaces/Post_Repository.php
src/Tribe/REST/V1/Endpoints/Single_Category.php
src/Tribe/REST/V1/Endpoints/Single_Event.php
src/Tribe/REST/V1/Endpoints/Single_Organizer.php
src/Tribe/REST/V1/Endpoints/Single_Tag.php
src/Tribe/REST/V1/Endpoints/Single_Venue.php
src/Tribe/REST/V1/Endpoints/Term_Single_Base.php
src/Tribe/REST/V1/Main.php
src/Tribe/REST/V1/Post_Repository.php
tests/_support/Helper/TribeDb.php
tests/restv1/CategoryDeletionCest.php
tests/restv1/CategoryInsertionCest.php
tests/restv1/CategoryUpdateCest.php
tests/restv1/SingleCategoryCest.php
tests/restv1/SingleTagCest.php
tests/restv1/TagDeletionCest.php
tests/restv1/TagInsertionCest.php
tests/restv1/TagUpdateCest.php

Ticket:  https://central.tri.be/issues/82414
Based on: https://github.com/moderntribe/tribe-common/pull/452
This PR adds the code and the tests to fully support CRUD operations for event Categories and Tags.

Add support for CRUD operations for Categories and Tags

---

readme.txt
src/Tribe/Aggregator/API/Import.php
src/Tribe/Aggregator/Record/Abstract.php
src/Tribe/Aggregator/Service.php

Ticket: https://central.tri.be/issues/83344
This PR follows up the research work done by @borkweb (https://tribe.slack.com/archives/C1SMDBJQ7/p1500615585145005) to make sure we cast error responses coming from the service to proper WP_Errors.
Using the EA Mocker it observable that, without this, error responses would be queued and try to fetch forever.

Cast error responses to WP_Error

---

src/Tribe/Aggregator/Record/Abstract.php

Ticket: https://central.tri.be/issues/75370#note-19
This PR adds a check to address a PHP notice spotted in the note. There is no changelog entry as there is one already for the ticket.

Avoid PHP notice

---

readme.txt
src/Tribe/Aggregator/Record/Abstract.php

Ticket: https://central.tri.be/issues/67038#note-14
Due to a stupid (mine) choice of var names in some instances the imported events UID might not be saved hence triggering duplicated import.
This fixes it.

Avoid duplicated events on import

---

readme.txt
src/Tribe/Aggregator/Record/Queue_Processor.php

Fixes the way we call an instance method (previously being called as if it were a static method).
:ticket: [#84020](https://central.tri.be/issues/84020)

Call using correct syntax for an instance method | #84020

---

src/Tribe/Main.php

Moving the `HTML` tags out of the translation strings.
This makes it much easier to translate the strings to RTL languages.

Don't use HTML tags in translation strings

---

src/Tribe/Query.php

By including the seconds string in the default list query mysql has a difficult/impossible time caching the query results, because the query changes every second. By replacing `H:i:s` with `H:i:00` mysql can cache the query for 60s, which results in events being displayed with the same precision, since events do not use seconds, and better performance out of the box.

Update Query.php to allow 60s query caching

---

src/Tribe/REST/V1/Endpoints/Single_Event.php

Ticket:   https://central.tri.be/issues/76729
This PR removes the check made on the requesting REST user to create or update an event for `publish` and `edit_other_posts` capacities to set the following event presentation fields:
* show map
* show map link
* featured
* sticky in month view
* hide from listings
This to reflect the capacities as those are set in the event editor accessible from the admin UI.

Allow authors and contributors to set presentation fields

---

codeception.dist.yml
src/Tribe/Aggregator/Record/Abstract.php
tests/_data/classes/Tribe__Events__Aggregator__Record__Scheduled_Test.php
tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php

Ticket: https://central.tri.be/issues/81639
This PR modifies the way EA Client detects if a scheduled import is in schedule or not to allow failed, not on-demand, scheduled imports to be rescheduled before their frequency.
While testing the ticket in question with the database attached to the ticket I noticed that yes, we would now pick up correct imports but a weekly import that failed 4 days ago would be given another chance to run in 3 days (a week); this modifications tries to address this issue putting in code the following reasoning:
* do this once a week...
* ...but keep trying until if it fails, do not wait the next week
Furthermore the code tries some fallback strategies to handle some incoherent records found in the db:
* missing `last_import_status` meta
* incoherent children …

Reschedule failed scheduled imports

---

src/Tribe/Organizer.php
src/views/day/single-event.php
src/views/list/single-event.php

Additionally fixing some view version numbers
See: https://central.tri.be/issues/71802

Prevent notice when organizer_ids is not an array

---

readme.txt
src/Tribe/Aggregator/Event.php

Ticket: https://central.tri.be/issues/87654
During the work done for ticket 79975 I put in place the `array_map` code that tries to convert alphanumeric strings (UIDs) to ints; the consequence is the array is filled with `0` and `1` and EA Client will never spot an existing ID thus duplicating the events.

Avoid duplicating events upon import

---

readme.txt
src/Tribe/Aggregator/Tabs/Scheduled.php

Ticket: https://central.tri.be/issues/87321
This PR makes sure the import ID assigned to requests generated when manually running a scheduled import is assigned to the child records to prevent failures.

Fix failing manual run of scheduled imports

---

readme.txt
src/Tribe/Aggregator/Cron.php
src/Tribe/Aggregator/Record/Abstract.php

* When scheduling the next cron event, allow for +/- 5 minute adjustments
* When checking if a scheduled import is ready to run, allow for -5 to 0 minutes from the expected scheduled time
See: https://central.tri.be/issues/86628

Add in randomization when scheduling and initiating scheduled imports

---

readme.txt
src/Tribe/Aggregator/Record/Abstract.php

Ticket: https://central.tri.be/issues/87530
This PR adds two simple actions before and after EA post insertion to allow plugins or devs that need to know when that happens (e.g. multilingual ones) to act accordingly.

Add pre and after actions in EA post insertion

---

src/Tribe/REST/V1/Endpoints/Archive_Event.php

The current code is assuming that both arrays are on the same order, resulting in a pagination bug when the parameter array is composed.

Fix bug composing parameters for rest url

---

readme.txt
src/Tribe/REST/V1/Endpoints/Single_Event.php

Adds a filter for modifying the data returned by a REST API call for a single event (e.g. `wp-json/tribe/events/v1/events/[eventId]`).

Adding data filter

---

src/Tribe/Main.php

The `remove_action()` function only accepts 3 parameters. This PR updates the calls to remove the 4th parameter.
*Note: I saw that the contributing guidelines said to open a PR against the `develop` branch, but I did not see a `develop` branch in the repo, so I used the `master` branch instead.*
See: https://central.tri.be/issues/88867

Remove 4th parameter from remove_action calls

---

src/admin-views/aggregator/origins/limit.php

Ticket: https://central.tri.be/issues/87803
Do not show the limit notice when the user chose not to apply a limit.

do not print the notice if no limit set

---

src/functions/template-tags/general.php

Make it easy to translate the plugin.
Old string:
* `Calendar powered by %sThe Events Calendar%s`
New strings:
* `Calendar powered by %s`
* `The Events Calendar`

i18n: Simplify the translation string

---

src/admin-views/tribe-options-general.php

The current translation string:
* `You cannot edit the slug for your events page as you do not have pretty permalinks enabled. The current URL for your events page is <a href="%1$s">%2$s</a>. In order to edit the slug here, <a href="%3$soptions-permalink.php">enable pretty permalinks</a>.`
We can:
1. replace `<a href="%1$s">%2$s</a>` with a simple `%1$s` moving the HTML tags outside the translation string.
2. replacing `<a href="%3$soptions-permalink.php">` with a simple `<a href="%3$">`, moving `options-permalink.php` outside the translation string.
The new translation string:
* `You cannot edit the slug for your events page as you do not have pretty permalinks enabled. The current URL for your events page is %1$s. In order to edit the slug here, <a href="%2$s">enable pretty …

i18n: Avoid using HTML tags in translation strings

---

src/admin-views/tribe-options-display.php

The following translation string:
`The settings below control the display of your calendar. If things don't look right, try switching between the three style sheet options or pick a page template from your theme.</p><p>There are going to be situations where no out-of-the-box template is 100&#37; perfect. Check out our <a href="%s">our themer's guide</a> for instructions on custom modifications.`
has `</p><p>` HTML tags is the string. It should be splited into two strings.

i18n: split translation strings

---

readme.txt
src/Tribe/iCal.php

Ticket: https://central.tri.be/issues/87775
I was not able to find anywhere in the spec where it stated that a multiday allday event should have DTEND set to the day after it ends. However, for single-day all day events it does specify this (although for those the DTEND field is also optional). Given that the spec it specifies this for single-day events it follows that you would need to do this for multiday ones as well. Furthermore, every calendar export I tested with, like Google Calendar, indeed adds a day to the DTEND of their all day multiday exports. They also properly import when we do this with our exports.

Fix for allday multiday events

---

src/Tribe/REST/V1/Endpoints/Single_Event.php

Two different but identical `tribe_rest_single_event_data` hooks somehow co-evolved independently of one another. This spotfix removes the later one.

Remove duplicate filter | M17.19 | Spotfix

---

readme.txt
src/Tribe/Query.php
src/Tribe/REST/V1/Endpoints/Archive_Event.php
src/Tribe/REST/V1/Endpoints/Archive_Organizer.php
src/Tribe/REST/V1/Endpoints/Archive_Venue.php
src/Tribe/Venue.php
src/functions/template-tags/organizer.php
src/functions/template-tags/venue.php
tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php
tests/wpunit/Tribe/Events/QueryTest.php
tests/wpunit/functions/template-tags/organizerTest.php
tests/wpunit/functions/template-tags/venueTest.php

Ticket: https://central.tri.be/issues/89743
This PR:
* add support for the `found_posts` argument to the `tribe_get_events`, `tribe_get_organizers` and `tribe_get_venues` functions
* in so doing the support is added in the `Tribe__Events__Query::getEvents` method too
* adds the tests to cover the new behaviours
* updates TEC REST API code to use the new argument

Add `found_posts` argument support in `tribe_get_` functions

---

readme.txt

* Remove the "requirements" list.
* Required WordPress version is defined in "Requires at least" header field.
* Add the new "Requires PHP" header field.
See more info at: https://generatewp.com/minimum-required-php-version-plugins/

Use the latest "Requires PHP" header field

---

readme.txt
src/functions/template-tags/general.php

Within `tribe_events_the_header_attributes()` we grab the requested event category name and try to load the corresponding term object ... however it's possible the category will not exist and we'll get back null in instead of a term object. This change accommodates that.
:ticket: [#90697](https://central.tri.be/issues/90697)

Avoid notice level error if term does not exist | #90697

---

src/functions/template-tags/general.php

Further enhancement to `tribe_events_the_header_attributes()` — load the term object by _slug_ rather than by name. 
While there was no problem for simple categories (ie where the category was something like 'foo') for more complex names like 'Foo Bar' the slug and the name don't match, as the slug will be hyphenated etc. This fixes that shortcoming.
:ticket: [#90697](https://central.tri.be/issues/90697)

Check for event category by slug, not by name | #90697

---

src/Tribe/JSON_LD/Event.php

Tidies work from a previous PR, changelog entry is already in place. This change:
* Catches possible exceptions when creating DateTime and DateTimeZone objects
* Doesn't attempt timezone conversion/formatting if we lack the info to do so
:ticket: [#42125](https://central.tri.be/issues/42125)

Safety checks and cleanup (JSON LD timezones)

---

readme.txt
src/functions/template-tags/organizer.php

Incorporates @f4w-pwharton's fix (to avoid wrapping a link in another link) and adds a changelog for same. Originally [reviewed here](https://github.com/moderntribe/the-events-calendar/pull/1461).
:ticket: [#91074](https://central.tri.be/issues/91074)

Remove unwanted escaping

---

src/functions/template-tags/organizer.php

`tribe_get_organizer_details()` wraps the result of `tribe_get_organizer_website_link()` in an anchor tag, however `tribe_get_organizer_website_link()` already returns an anchor tag resulting in broken HTML. 
This stops `tribe_get_organizer_details()` adding the second anchor tag.
Bug originally reported here in March: https://theeventscalendar.com/support/forums/topic/single-organizer-website-link-bug/

Fix double anchor tag in tribe_get_organizer_details

---

readme.txt

Some changes in content for the readme file that remove reference to a license being for a year in preparation of subscriptions going live

Subscription Readme update

---

readme.txt
src/views/list/nav.php

By appending `&raquo;` to the plural events label, in some languages such as French this meant we ended up with _Evénements » suivant_ instead of _Evénements suivant »_ ... this change alters the order in which we do things to avoid this.
:ticket: [#72097](https://central.tri.be/issues/72097)

Clear up next events link

---

readme.txt
src/Tribe/JSON_LD/Event.php
src/Tribe/JSON_LD/Organizer.php
src/Tribe/JSON_LD/Venue.php

Builds on the change [made here (in Tribe Common)](https://github.com/moderntribe/tribe-common/pull/561) and ensures the `tribe_json_ld_{$type}_object` filter is available for event, venue and organizer JSON LD data.
:ticket: [#89801](https://central.tri.be/issues/89801)

Restore JSON LD filtering

---

readme.txt
src/Tribe/JSON_LD/Event.php

Ensures our JSON LD output includes correctly set timezone offset. Depends on [Tribe Common PR 562](https://github.com/moderntribe/tribe-common/pull/562)
:ticket: [#78233](https://central.tri.be/issues/78233)

Fix application of UTC offsets in JSON LD output for events | #78233

---

src/Tribe/JSON_LD/Event.php

Explicitly uses the global `$post` object if no other posts are provided. The problem this solves isn't new, but became visible again following the fix made in [#78233](https://central.tri.be/issues/78233).
* No changelog entry, existing entry for 78233 is sufficient
* No props, this was an internal discovery
:ticket: [#92020](https://central.tri.be/issues/92020)

Default to the global post object as needed | #92020

---

src/Tribe/JSON_LD/Event.php

This method (`Tribe__Events__JSON_LD__Event::get_data()`) can accept a post ID, post object or an array of post objects (or of post IDs). 
This flexibility is great, but we ultimately need to make sure it's the post object we're working with or there can be unexpected side effects when subsequent hooks fire (as the callbacks expect post objects).
Changelog added via previous change.
:ticket: [#92020](https://central.tri.be/issues/92020)

Work with the post object wherever possible | #92020

---

package-whitelist.json

Don't strip the attrchange lib (from tribe-common - [added here](https://github.com/moderntribe/tribe-common/pull/559)) during packaging.

Whitelist attrchange lib in common | spotfix | M17.21

---

readme.txt
src/functions/template-tags/general.php

Once we've successfully found and printed our template, we don't need to continue the loop.
:ticket: [#46630](https://central.tri.be/issues/46630)

Avoid unnecessary/unwanted extra iterations within tribe_get_template_part()

---

readme.txt
src/Tribe/Main.php

Improves/tightens conditions under which we redirect from a legacy upcoming/past events URL to the current list view equivalents.
This change is needed because if the single and archive event slugs are the same (something we currently permit) then a single event URL such as `/calendar/pastoral-pleasures/` triggers unwanted redirects to the past events view.
:ticket: [#86942](https://central.tri.be/issues/86942)

Smarten redirect logic, avoid unwanted redirects | #86942

---

readme.txt
src/admin-views/create-venue-fields.php

Tidies up the country and state-province fields (that display inline within the event editor when defining a new venue) so they behave as per other address fields in relation to default venue content.
Background: we previously decided that we _do_ want to use defaults specified in the **Events ‣ Settings ‣ Default Content ‣ Address** fields within the venue editor when defining a brand new venue, but _not_ from within the event editor (whether frontend or backend) when defining new venues inline. This change seems to have mostly rolled out but two fields were left behind.
:ticket: [#44732](https://central.tri.be/issues/44732)

Complete clean up of default venue field handling 

---

src/admin-views/create-venue-fields.php

Don't populate the venue fields if the current post is an auto-draft (ie, it's brand new). Builds on previous work, no additional changelog entry needed.
:ticket: [#44732](https://central.tri.be/issues/44732)

Don't populate venue fields for auto-drafts | #44732

---

readme.txt
src/Tribe/REST/V1/EA_Messages.php
src/admin-views/aggregator/settings.php

After an error msg from 'Other URL' import, the 'Learn more' url was broken.
https://central.tri.be/issues/92890

Fixing the 'Learn more' URL after a failed "Other URL" import preview

---

readme.txt
src/admin-views/events-meta-box.php
src/functions/template-tags/date.php

Adds `tribe_events_timezone_choice()` as a preferred replacement for `wp_timezone_choice()` (key advantage being the output of the former is filterable, which isn't true of the latter).
:ticket: [#92909](https://central.tri.be/issues/92909)

Create a wrapper to make the timezone picker output filterable | #92909

---

src/Tribe/Aggregator/Record/Abstract.php

Ticket: https://central.tri.be/issues/88524
This PR adds a filterable fall-back to look up Venues by title when a match could not be found in any other way.
This helps the code deal with cases like [this feed](https://www.facebook.com/pg/Chayz.Lounge/events/) where the page admin added a different Venue (with different FB ID) for each event.

additionally lookup venues by name to avoid duplicates

---

src/Tribe/REST/V1/Main.php

Ticket:  n/a
From PR: https://github.com/moderntribe/the-events-calendar/pull/1663#issuecomment-343469126
Since the `WP_REST_Terms_Controller` class was introduced in WP 4.7 this PR modified the REST endpoint registration code to avoid registering the taxonomy endpoints if WP is not version `4.7` or above.

Check for WP version before taxonomy endpoint registration

---

src/resources/js/events-admin.js

Further tweaks to get the expected behaviour in both the admin and frontend event editors re linked posts.
:ticket: [♯89015](https://central.tri.be/issues/89015)
:ticket: [♯89995](https://central.tri.be/issues/89995)
:ticket: [♯90107](https://central.tri.be/issues/90107)

Further tweaks to linked post edit link logic | #89015

---

src/admin-views/venue-meta-box.php

Further cleanup of default venue field handling: previous approach resulted in the province field being populated with the default value for _existing_ venues that in fact do not specify a province.
:ticket: [♯44732](https://central.tri.be/issues/44732)

Venue default fields

---

src/Tribe/Aggregator/Record/Abstract.php

Ticket: https://central.tri.be/issues/92947
This PR updates the code in charge of generating the children records to make sure the post author is propagated and applied to the imported events.

ensure post_author is propagated to children records

---

src/Tribe/List_Widget.php

The should_hide_recurrence() / tribeHideRecurrence functionality breaks when this widget is shown on the same page as the Month view for the event calendar.
I have the list widget shown in the sidebar of my site (showing the 3 latest upcoming events in a particular category) with the "Recurring event instances” setting at Events => Settings => General _checked_ so it would hide recurring instances after the first upcoming. This works as intended on all pages except for the main events page that's set to show the monthly calendar view, because it appears that setting is completely ignored on that specific page.
This one change in the code has it trigger the logic for following that setting as expected. Before this fix, it appears the Monthly view was overwriting that setting (so it shows …

Fix bug where the should_hide_recurrence() / tribeHideRecurrence is ignored in some circumstances

---

src/Tribe/Aggregator/Record/Facebook.php

Ticket: n/a
When EA license is not correct or expired the FB-related code would genearate a PHP notice.

do not try to access EA API if not valid

---

readme.txt
src/Tribe/Integrations/WPML/Linked_Posts.php

Ticket: https://central.tri.be/issues/94732
From PR: https://github.com/moderntribe/the-events-calendar/pull/1707 (by @dgwatkins)

Use correct WPML constant to return to current language

---

src/Tribe/Integrations/WPML/Linked_Posts.php

A few lines above this change you are switching to the default language.
Once you have switched language it becomes the current language.
So this line is doing nothing:
`$sitepress->switch_lang( $sitepress->get_current_language() );`
Instead, we can use the ICL_LANGUAGE_CODE constant which is set at the beginning and doesn't change.
One of the problems caused by this was reported here:
https://wpml.org/forums/topic/we-need-to-continue-troubleshooting-a-problem-with-ankit-our-thread-was-closed/#post-1435947
In this case its a combination of ACF with WPML and The Events Calendar, but I'm sure this causes other side effects.

Switch to the previous language correctly

---

readme.txt
src/functions/template-tags/google-map.php

https://central.tri.be/issues/94909
Went the route of modifying `tribe_get_map_link_html()` because it seemed the best way to go (if there's no URL, why output <a> tag?) but also because I found quite a few checks against `tribe_show_google_map_link()` without first checking `&& tribe_address_exists()`, as PRO does in one case.

No Google Maps Link if no address to link to

---

src/Tribe/REST/V1/Endpoints/Single_Event.php
tests/wpunit/Tribe/Events/REST/V1/Endpoints/Single_EventTest.php

https://central.tri.be/issues/96002
This PR is so we can merge the fix into RER branch for our immediate use.

Set edit_date when setting the date on a future event (RER merge)

---

src/Tribe/iCal.php

The calendar description in a generated iCal feed is not translated.
The translation is not used.
Use esc_html__ to enable translation of the description.

Enable translation of iCal calendar description

---

src/Tribe/Template/Month.php

This will allow to have only events that are part of the current term
inside of the the list of events to avoid render extra events that are
not part of the same category.
See https://central.tri.be/issues/80551

Filter events if we are on a category

---

src/Tribe/iCal.php

Due the WP Query was having empty elements it was causing a header other
that a 200 which was creating an issue during the download of the file,
making sure we always have a 200 even if the file is empty allows the
correct download of the file even if is empty.
See: https://central.tri.be/issues/84394

Prevent errors on empty iCal

---

readme.txt
src/views/modules/map.php

Incorporates [@LucaPipolo's change](https://github.com/moderntribe/the-events-calendar/pull/1705), adding a changelog entry and ensuring we output the escaped values.
:ticket: [#96772](https://central.tri.be/issues/96772)

Map ID escaping

---

readme.txt
src/functions/template-tags/general.php

Add `tribe_is_home_events` function similar to `is_home` in WP to test if we are on the homepage of the events.
See Ticket: https://central.tri.be/issues/42195

Add new utility function

---

src/Tribe/Query.php

In order to prevent any 404 error code we need to set `is_home` to `true` if.
we are on the front page, which means the main reading settings are set
to display a page that is displaying an events page, this should turn:
- `is_home`
- `is_front_page`
To `true`.
See: https://central.tri.be/issues/90001

Make sure to set is_home if we are on the front page

---

src/Tribe/Main.php
src/Tribe/Venue.php

This will ensure the options for the map are always present when a venue is saved in order to allow the option to set
them to false if that's the case from the admin panel as they are not present inside of the `$_POST` request if the
checkbox are set to `false`.
It adds a new filter as well `tribe_events_venue_created_map_default` that will allow the community events the option
to fix a bug when `tribe_events_community_apply_map_defaults` is set to `false`.
[Central](https://central.tri.be/issues/91869)

Make sure the Map options are present on save venue

---

readme.txt
src/Tribe/Amalgamator.php
src/admin-views/tribe-options-general.php

Remove option value not required on the conditional in favor of the default `true` that will show the field all the time.
See https://central.tri.be/issues/75208

Merge Duplicates button is always visible

---

src/Tribe/Integrations/WPML/Defaults.php

Avoids creating a path with a double slash (plugin path is passed through `trailingslashit()` in `Tribe__Events__Main::__construct()`).

Plugin path will have trailing slash already

---

readme.txt
src/Tribe/Query.php

For any event that is past on the list view we should consider the end
of the event as the current date instead of the current end of the day
as will wrap events of today in the past.
See: https://central.tri.be/issues/71936

For past events use current date instead of end of day

---

readme.txt
src/Tribe/Customizer/General_Theme.php

If present, this will use the color selected by the user instead of the default color scheme.
See https://central.tri.be/issues/96821

Allow the usage of `featured_color_scheme_custom`

---

readme.txt
src/functions/template-tags/general.php

Allow to filter the title of the events generated by
`tribe_events_template_data()`
See https://central.tri.be/issues/38237

Apply `the_title` filter to each event title

---

readme.txt
src/Tribe/Rewrite.php

🎟  https://central.tri.be/issues/98463
The URL might change due a different slug based on the options page,
make sure this URL is not hardcoded.

Make sure the `/events` page is not hardcoded

---

readme.txt
src/Tribe/Admin_List.php

**Ticket** https://central.tri.be/issues/99266
Make sure columns are generated without error, and prevent the PHP
notice: "Trying to get property of non-object".

Prevent errors during the generation of the columns

---

readme.txt
src/Tribe/Template_Factory.php

**Ticket** https://central.tri.be/issues/99089
Make sure that return type on original functions are honored based on
docblock to create objects specially on JS as `null` is different from
empty string.

Honor the return type on defined filters

---

readme.txt
src/Tribe/Adjacent_Events.php

**Ticket:** [**#101757**](http://central.tri.be/issues/101757)
---
When building the query used to lookup adjacent links, it appears that an empty string is always used for the `_EventStartDate` value and unexpected events are used in the previous/next links
on single event pages.
When `$post_obj->EventStartDate` is called, post meta is checked for a meta key that does not exist. Adjusting this to the correct meta key, `$post_obj->_EventStartDate` provides a correct date and results in properly generated links.
The README mentions a `develop` branch, but I don't see on on this repo. I took a guess that this is the development branch for the upcoming release. Let me know if I should submit the PR against something else.

Fix empty string used as event start date when generating adjacent links

---

readme.txt
src/Tribe/Query.php

Ticket: https://central.tri.be/issues/97667
Make sure the `EventStartDate` column is only accesed when present on
the Query.

Prevent DB error by accessing non defined column

---

readme.txt
src/Tribe/Aggregator/Record/Abstract.php
src/Tribe/Aggregator/Record/List_Table.php
tests/wpunit/Tribe/Events/Aggregator/Record/AbstractTest.php

Ticket: https://central.tri.be/issues/102489
This PR adds a method to the Record class to return the timestamp of the record next retry (modified in PR https://github.com/moderntribe/the-events-calendar/pull/1886) to display it, for failed Scheduled records only, in the Scheduled tab: https://cl.ly/0G0R2M3c2L1g

Display a failed Scheduled record retry time

---

src/Tribe/Aggregator/Record/Queue.php

Ticket: https://central.tri.be/issues/98015
Avoid trying to count something that is not an array.

Avoid notice trying to count un-countables

---

src/Tribe/Aggregator/Record/List_Table.php

Ticket: https://central.tri.be/issues/99106#note-12
Since the `last_import_error` variable might not be defined use `empty` to check it.

Change the check to avoid PHP notices

---

readme.txt
src/Tribe/Rewrite.php

https://central.tri.be/issues/94328
Prevent `url_to_postid` to run if on the main events page to avoid query conflicts.

Prevent `url_to_postid` to run if on the main events page to avoid query conflicts

---

readme.txt
src/Tribe/Aggregator/CLI/Command.php
src/Tribe/Aggregator/CLI/Service_Provider.php
src/Tribe/Aggregator/Record/Abstract.php
src/Tribe/Aggregator/Record/CSV.php
src/Tribe/Aggregator/Records.php
src/Tribe/Main.php

Ticket: #104426
This PR adds the first version of the command to run imports, or scheduled imports, using wp-cli.
```shell
`wp event-aggregator import-from ical http://foo.bar/ical.ics`
```
is the (sudo) syntax to run imports; while scheduled imports can be ran using the import post ID:
```shell
wp event-aggregator run-import 2389
```

Add CLI command to run imports

---

src/Tribe/Aggregator/CLI/Command.php

Ticket: https://central.tri.be/issues/104426
This PR:
* fixes the `location` description
* adds the required `--column_map` parameter for CSV import to be able to run commands like:
```shell
wp event-aggregator import-from csv /Users/luca/Desktop/example-events.csv --content_type=events --column_map=name,description,start_date,start_time,end_date,end_time,excerpt,venue_name,organizer_name,show_map_link,show_map,cost,category,website,currency_symbol,currency_position
```
Same for venues and organizers
* fixes the limit behavioiur to make commands like these work as intended:
```shell
wp event-aggregator import-from url https://wpshindig.com/events/ --start="2018-06-19" --end="2018-07-01"
wp event-aggregator import-from url https://wpshindig.com/events/ --start="2018-06-19" …
```

Fix EA CLI command issues

---

src/admin-views/create-venue-fields.php

Task: https://central.tri.be/issues/106415
When Community Events and TEC are enabled, the Province and State fields break. This PR conditionally checks these vars are in use before attempting to use them. They are traditionally only in use when editing an existing event or after the event has been created and do not exist when an empty "Add event" form is present.

State and Province Data in Create Venue form

---

readme.txt
src/Tribe/Admin/Notice/Timezones.php
src/Tribe/Main.php

https://central.tri.be/issues/105217
Add a notice to admin if the site timezone is set to UTC, when in "TEC Pages" or WordPress General Settings.

Add a warning when the site Timezone is set to UTC

---

src/Tribe/Cost_Utils.php

A very unimportant change but one I noticed while writing tests, so why not?
**Code Review Note:** No changelog entry for this change.
**Ticket:** [**⌗106679**](http://central.tri.be/issues/106679)

⌗106679 Change Hyphen to En Dash in Cost Ranges

---

src/Tribe/Admin/Notice/Marketing.php
src/Tribe/Main.php

Adds a dismissable, time-bound admin notice that will appear on event admin screens up until 2018-06-08. 
:ticket: [#106817](https://central.tri.be/issues/106817)

Add 2018 survey message/link | #106817

---

src/Tribe/Admin/Notice/Marketing.php

Marketing notice should also appear on the (events) tag admin screen. Previously it appeared on all our screens except for this one.
:ticket: [#106817](https://central.tri.be/issues/106817)

Marketing notice should appear on tag screen

---

src/Tribe/Admin/Notice/Marketing.php
src/Tribe/Admin/Notice/Timezones.php
tests/integration/Unticketed_Cost_Formatting_Test.php

Fix version number to `4.6.17` after fix with master.

Fix version number over `@since` docblocks for M18.08

---

readme.txt
src/Tribe/Template/List.php

https://central.tri.be/issues/94613
The problem with the hash had to do with the `search_orderby_title` LIKE delimiters being hashed as well and changing every time it was being requested.

Fix the pagination in list view when a keyword is being searched

---

readme.txt
src/Tribe/Aggregator/Processes/Import_Events.php
tests/wpunit/Tribe/Events/Aggregator/Processes/Import_EventsTest.php

Ticket:  107929
This PR:
* adds two filters in the async queue EA import code to allow overriding the whole import task (`tribe_aggregator_async_import_event_task`) or just the event insertion step (`tribe_aggregator_async_insert_event`)
* wraps the event insertion step in a `try/catch` block to orderly handle the case where the event insertion will generate an error/exception

Handle exceptions thrown during EA imports

---

src/Tribe/Template_Factory.php

🎫 https://central.tri.be/issues/61888
This does not address the issue in the ticket (can't reproduce it) but does fix a php warning when the expected query var isn't available.

Fix a php notice

---

readme.txt
src/Tribe/Aggregator/Page.php

https://central.tri.be/issues/67864
Add this check, so users with expired licenses cannot add new "premium" imports.

Check the Events Aggregator license each time the EA page is accessed

---

readme.txt
src/Tribe/REST/V1/Endpoints/Single_Organizer.php
tests/restv1/OrganizerUpdateCest.php

https://central.tri.be/issues/106026

Allow Organizer insert/update REST API arguments to be empty so that values can be set as empty

---

src/Tribe/Rewrite.php

🎫 https://central.tri.be/issues/69707
Add rewrite rule so we can use the `site.com/events/month/yyyy-mm` permalink

Add  `events/month/yyyy-mm` rewrite rule

---

src/Tribe/Main.php

In 1173c0a16f8db03155a35fe86acf88ff956bc67c, the filter `'tribe_get_meta_default_value_' . $filter` has been modified to `"tribe_get_meta_default_value_{ $filter }"`. This breaks all the 3rd party code using the filter (in my case, this breaks part of the compatibility made with Polylang Pro). I propose to restore the filter name to its initial value.

Restore filter name probably unintentionnally modified

---

src/admin-views/aggregator/banners/eventbrite-upsell.php

https://central.tri.be/issues/107108
As the banner CSS has its own `display`, the conditional display wasn't working because this was being overridden (tribe-dependent sets `display` to `block` or `none` depending if the condition via data attribute is true/false).

Put the banner on its own div so it doesn't mess up with `tribe-dependent`

---

readme.txt
src/Tribe/Template/Month.php

🎫 https://central.tri.be/issues/106991
When there was a search, the "No results" notice was not decoding the complete search, so it was displaying something like:
`There were no results found for "your+awesome+search" this month. Try searching next month.`

Display the exact search term in the "no results" notice on the events page

---

src/Tribe/Template/Month.php

🎫 https://central.tri.be/issues/106991
Came back from QA because the notice results for `I'm a keyword` were `I\'m a keyword` (pre-existent, but worth fixing now)

Add `stripslashes` the the no results notice search term

---

readme.txt
src/Tribe/REST/V1/Endpoints/Single_Event.php
src/Tribe/REST/V1/Validator/Base.php

https://central.tri.be/issues/109482

Allow venue and organizer fields to be intentionally empty on Event Singular REST API calls

---

readme.txt
src/Tribe/Embedded_Maps.php

🎫 https://central.tri.be/issues/95312
Don't enqueue the Google Maps scripts if no API Key present. (prevent errors from being displayed in the console)

Fix Google Map API giving console error when no API key present

---

readme.txt
src/Tribe/Template/Month.php

🎫 https://central.tri.be/issues/109589
Pushing this hotfix. The real problem is related to the calendar nav (baseurl, etc) when using the shortcode.

Fix - Error being displayed when navigating through the month view calendar

---

readme.txt
src/Tribe/REST/V1/Endpoints/Single_Event.php
tests/restv1/EventInsertionCest.php
tests/restv1/EventUpdateCest.php

https://central.tri.be/issues/109627
Adds tests for empty categories/tags

Allow event categories and tags to be provided as empty for saving

---

src/Tribe/Integrations/WPML/Meta.php

🎫 https://central.tri.be/issues/106798
Only return when $_POST is set and there's something in it.

WPML compatibility for Venues and Organizers fix
