- lib/deprecated-classes/TribeEventsUpdate.php
See: https://central.tri.be/issues/35917
> Deprecate the TribeEventsUpdate class

- lib/iCal.php
As @barryhughes commented, the previous solution wasn't fixing all the issues with Google Calendar.
_Ref:_ [#30311](https://central.tri.be/issues/30311)
> Resolves #30311

- src/Tribe/Main.php
This single-line change pull request is a simple fix of a type for the rewrite rule for the main events feed.
> fix feed rewrite rule typo

- src/Tribe/Asset/Abstract_Asset.php
- src/Tribe/Asset/Factory.php
- src/Tribe/Template_Factory.php
Related: https://github.com/moderntribe/events-pro/pull/11
See: https://central.tri.be/issues/36164 and https://central.tri.be/issues/33500
> Further refactor the Template_Factory so that events-pro can override it

- src/Tribe/Importer/Admin_Page.php
- src/Tribe/Importer/Plugin.php
See: https://central.tri.be/issues/36329
> Fix paths for CSV importer views

- .editorconfig
> Adding editorconfig file

- readme.txt
> Gustavo's Changelog for 3.10

- src/views/single-event.php
Stumbled across this and wasn't sure if this was intentional or not? :grin:
> Remove doubled <!--Navigation --> comment

- src/Tribe/Main.php
See: https://central.tri.be/issues/31284
> Escape $ and \ when builing anchor tags via preg_replace

- src/Tribe/Activation_Page.php
See: https://central.tri.be/issues/36717
> Re-enable the activation splash screen

- src/Tribe/Query.php
See: https://central.tri.be/issues/28668
> Don't remove the filter that allows for custom sorting in the event list

- src/Tribe/Tickets/Attendees_Table.php
This is a resubmit of #57 for possible inclusion in `release/119`, per @zbtirrell.
> Allow Attendees_Table::__construct accept arguments [RC]

- src/Tribe/Admin/Helpers.php
- src/Tribe/Credits.php
- src/Tribe/Main.php
- src/Tribe/Query.php
_Resolves:_ [#30696](https://central.tri.be/issues/30696)
> Preventing Notices from Current Screen variables

- src/Tribe/Query.php
See: https://central.tri.be/issues/36770
> Bugfix where EventStartDate was excluded from some queries, busting them

- src/Tribe/Cost_Utils.php
- src/functions/template-tags/general.php
See: https://central.tri.be/issues/36518 and https://central.tri.be/issues/36620
Note: this was already code reviewed in https://github.com/moderntribe/the-events-calendar/pull/82 and this is just pointing those changes at `develop` rather than `release/119`.
> Find min/max prices when price ranges are entered in the "Cost" field

- src/Tribe/API.php
See: https://central.tri.be/issues/36815
> Small interim EventAllDay fix to allow proper imports of CSV files

- src/Tribe/Admin/Event_Meta_Box.php
- src/Tribe/Query.php
- src/Tribe/Templates.php
- src/functions/template-tags/general.php
See: https://central.tri.be/issues/36716
> Refactor is_a() to be instanceof

- src/Tribe/API.php
See: https://central.tri.be/issues/36927
> EventAllDay should be saved using yes/no rather than true/false

- dev/grunt_options/glotpress_download.js
- dev/package.json
See: https://central.tri.be/issues/36860
> grunt task to pull translations from GlotPress

- src/Tribe/API.php
- src/Tribe/Admin/Event_Meta_Box.php
- src/functions/template-tags/general.php
Continuation of: https://central.tri.be/issues/36928
> Stupid typo when I switched from View_Helpers to Date_Utils

- src/admin-views/events-meta-box.php
- src/admin-views/tickets/meta-box.php
- src/functions/template-tags/date.php
On the Pull Request #24 @Loffe did some good changes to our code, so I'm just improving on top of that and applying it to our current Patch.
Props: @Loffe
> Updating the PR#24 - Datetime saparator

- src/Tribe/Main.php
- src/Tribe/Query.php
- src/functions/template-tags/general.php
See: https://central.tri.be/issues/36908
> Codesniffer updates to Tribe__Events__Main

- src/Tribe/Query.php
Brian is a Genius, really quick fix -- Did a fair bit of testing it works like a charm :wink: 
_Ref:_ [#30999 @ N30](https://central.tri.be/issues/30999#note-30)
> Fixing Timezone on #30999

- src/Tribe/Activation_Page.php
_Ref:_ [#33897](https://central.tri.be/issues/33897)
> Prevent Welcome page on WP Actions

- src/Tribe/Main.php
See: https://central.tri.be/issues/37073
> Update version constant to 3.10

- src/admin-views/tribe-options-help.php
Update code to use [wp_star_rating()](https://codex.wordpress.org/Function_Reference/wp_star_rating) function
Updates #35818
> Update code to use wp_star_rating() function

- src/Tribe/Support.php
See: https://central.tri.be/issues/34885
> Make note of any rewrite rule flushing that occurs when on the Help tab

- src/Tribe/Main.php
See: https://central.tri.be/issues/27982
> Allow view selection to function with JS disabled

- src/Tribe/Admin_List.php
This takes the excellent work done by @kittsville and applies it to our `release/119` branch with some tweaks.  Here are the original notes from kittsville from #42:
>
**New:**  
- Added sorting by event category and tags. Code was based off similar work from [my own plugin](https://github.com/kittsville/WP-Librarian/blob/e2bb0e176633dbb38a83912aeccbb2d4cdae03c8/lib/admin-tables.class.php#L453-L493), which was based on code by Mike Schinkel.
>
**Refactored:**  
>
- Removed duplicate is_admin check
- Replaced obfuscated event date sorting logic with single function. Also got rid of unnecessary use of two SQL joins rather than just one.
- Aligned and commented hook registration for an easier to read/understand init(). Now looks more like hook registration in main plugin class
- Replaced 3 …
> Add sortable events table by tax + Refactoring (redux against 119)

- dev/Gruntfile.js
This changeset is aimed to help our plugin release process.
See: https://central.tri.be/issues/35525
> Support the overriding of branch checkouts with command line args

- src/Tribe/Templates.php
- src/views/month/single-day.php
See: https://central.tri.be/issues/27348
> Show "View all" in month view and allow Day tpl to render when disabled

- src/functions/template-tags/general.php
_Ref:_ [#33444](https://central.tri.be/issues/33444)
> Improve tribe_get_events Docblock

- readme.txt
Signed-off-by: Rob La Gatta <rob@tri.be>
> Removing "kick ass" from readme - Updates #37150

- src/functions/template-tags/link.php
- src/views/list/nav.php
See: https://central.tri.be/issues/27981
> Support pagination on listview with JS turned off

- src/Tribe/Date_Utils.php
- src/Tribe/Importer/File_Importer_Events.php
Improves ability to detect existing all day events when importing from CSV (internal ref #35913 for context).
> Prep alternate meta query when matching existing *all day* events (#35913)

- src/Tribe/Query.php
Resubmitting this change against r/119
> get_term_by() returns a false on failure, not a wp_error  (#32613)

- src/Tribe/Cost_Utils.php
- src/functions/template-tags/general.php
Relocated some cost logic into the new `Cost_Utils` class!
See: https://central.tri.be/issues/33715
> Display cost ranges when multiple tickets/costs exist on an event

- src/Tribe/Tickets/Attendees_Table.php
- src/Tribe/Tickets/Tickets_Pro.php
- src/admin-views/tickets/attendees.php
_Ref:_ [#36857](https://central.tri.be/issues/36857)
> Improve Attendees Bulk Action

- src/Tribe/iCal.php
_Ref:_ [#28455](https://central.tri.be/issues/28455)
> iCal Organizer name

- src/views/modules/bar.php
Found this while estimating on an unrelated issue: we were printf()ing when we should have been sprintf()ing.
> We need sprintf not printf when supplying esc_attr() with a string (spotfix, no related issue)

- src/Tribe/Template/Month.php
See: https://central.tri.be/issues/37458
> Only include published and optionally private events in month view

- src/views/modules/meta/organizer.php
See: https://central.tri.be/issues/37508
> removing escaping as this element is pre-escaped and contains HTML

- src/admin-views/tickets/attendees.php
Repointing @aaemnnosttv's [hook PR](https://github.com/moderntribe/the-events-calendar/pull/63) to `release/120`. Thanks again, @aaemnnosttv!
> Add action hooks to event attendees meta box

- src/admin-views/tickets/attendees.php
Re-pointing @aaemnnosttv's [PR](https://github.com/moderntribe/the-events-calendar/pull/53) against our `release/120` branch!  Thanks for the change!
> Make event attendees page title filterable

- src/Tribe/Main.php
See: https://central.tri.be/issues/37509
> Generate the proper event link for next/previous event pagination

- src/Tribe/iCal.php
See: https://central.tri.be/issues/28455
> double quotes are not allowed around the MAILTO

- src/Tribe/API.php
_Ref:_ #154 [C#36646](https://central.tri.be/issues/36646) [C#37856](https://central.tri.be/issues/37856)
> Datepicker bug Fixed

- src/Tribe/Template/Month.php
See: https://central.tri.be/issues/37867
> Ensure that the start/end grid dates include the min/max times as well

- src/Tribe/API.php
- src/Tribe/Date_Utils.php
See: https://central.tri.be/issues/37929
> Only convert dates to YYYY-MM-DD if they aren't already in that format

- src/Tribe/Date_Utils.php
See: https://central.tri.be/issues/37929
> Bah. Need to reference the regex portion

- lang/tribe-events-calendar.pot
See: https://central.tri.be/issues/37644
> updating pot files

- src/Tribe/Template/Month.php
Additionally relocating the HTML cache so the serialized args as a cache key takes into account _ALL_ of the arguments.
See: https://central.tri.be/issues/37604
> Observe the tribe_events_cat taxonomy when fetching month data

- src/admin-views/new-organizer-meta-section.php
Related: https://github.com/moderntribe/events-community/pull/41
See: https://central.tri.be/issues/38058
> Make the email obfuscation notice optional

- src/Tribe/PUE/Checker.php
- src/io/csv/admin-views/general.php
See: https://central.tri.be/issues/38091
> making a couple strings translatable

- src/views/single-event.php
See: https://central.tri.be/issues/38057
> removed the tribe_events_single_event_meta function

- src/Tribe/Template/Day.php
- src/Tribe/Template/Month.php
- src/Tribe/Template_Factory.php
- src/admin-views/tickets/attendees.php
- src/admin-views/tickets/list.php
- src/admin-views/tribe-options-general.php
- src/admin-views/tribe-options-help.php
- src/admin-views/tribe-options-licenses.php
This is a big help for translators to be able to get the grammar correct
when translating.
See: https://central.tri.be/issues/37552
> adding numbered placeholders to translated strings

- readme.txt
- src/views/day/single-event.php
- src/views/list/single-event.php
Swapped the_title() for the_title_attribute() in list and day view <a> links.
> swapped the_title() for the_title_attribute()

- src/admin-views/tribe-options-help.php
See: https://central.tri.be/issues/37721
> Update link to Add-on Documentation

- src/Tribe/Asset/Calendar_Script.php
- src/Tribe/Main.php
- src/Tribe/Rewrite.php
- src/functions/template-tags/link.php
_Ref:_ [Q#16797](https://central.tri.be/issues/16797)
> WPML Compatibility

- src/Tribe/Rewrite.php
_Ref:_ [C#38859](https://central.tri.be/issues/38859)
> Forgotten to add the eventDisplay=all

- src/Tribe/Template/Month.php
See: https://central.tri.be/issues/38864
> Properly fetch the Y-m-d formatted date/times for event start/end

- src/Tribe/Main.php
A `noindex` should now be set for a) month view, always b) other views, when empty, regardless of returned HTTP status. An avenue to modify this behaviour has also been provided through a new hook.
> Rework "noindex" logic so it doesn't depend on a 404 status being set

- src/Tribe/Main.php
When importing posts, WP avoids duplicates by comparing post name, date and type (which are also identical for recurring events). We already had special handling to avoid those recurring events being rejected as dupes, this extends it to cover some other cases (ie, where an event is broken out of the chain).
> Modify workaround for handling WP imports of recurring events (#33497)

- src/Tribe/Rewrite.php
_Ref:_ [C#16797](https://central.tri.be/issues/16797)
> Apply filters to create the Language when _GET['lang'] is set

- src/Tribe/Admin/Helpers.php
- src/Tribe/Admin/Organizer_Chooser_Meta_Box.php
- src/Tribe/Main.php
- src/Tribe/Query.php
_Ref:_ [C#37873](https://central.tri.be/issues/37873)
> Solved the Current Screen Notices

- src/Tribe/Activation_Page.php
- src/Tribe/Field.php
- src/Tribe/Options_Exception.php
- src/Tribe/Post_Exception.php
- src/Tribe/Settings.php
- src/Tribe/Support.php
- src/Tribe/Tickets/Tickets_Pro.php
- src/admin-views/admin-update-message.php
- src/admin-views/admin-welcome-message.php
- src/admin-views/app-shop.php
- src/admin-views/tickets/attendees.php
- src/admin-views/tribe-options-display.php
- src/admin-views/tribe-options-general.php
- src/admin-views/tribe-options-help.php
- src/admin-views/tribe-options-licenses.php
- src/admin-views/tribe-options-network.php
- src/admin-views/tribe-options-timezones.php
- src/io/csv/admin-views/columns.php
- src/io/csv/admin-views/general.php
- src/io/csv/admin-views/header.php
- src/io/csv/admin-views/import.php
- src/io/csv/admin-views/in-progress.php
- src/io/csv/admin-views/result.php
- src/views/single-event.php
_Ref:_ [C#38330](https://central.tri.be/issues/38330)
> Push the Header elements from H2 to H1 and H3 to H2

- src/views/tickets/email.php
_Ref:_ [C#38705](https://central.tri.be/issues/38705)
> Better handling of Multiple organizers on the email

- src/Tribe/Importer/Column_Mapper.php
See: https://central.tri.be/issues/24221#note-52
> Move some of the CSV import fields around so similar ones are neighbors

- src/functions/template-tags/link.php
- src/functions/template-tags/organizer.php
- src/functions/template-tags/venue.php
Addresses https://central.tri.be/issues/38996
> added an underscore

- src/Tribe/Amalgamator.php
_Ref:_ [C#39176](https://central.tri.be/issues/39176)
> clean up esc_url and unnecessary var

- readme.txt
Fix malformed link in readme (spotted by @niconerd).
> Fix broken link markup in readme (spotfix)

- src/views/month/single-day.php
See: https://central.tri.be/issues/38870
and https://github.com/moderntribe/the-events-calendar/pull/131
> Fix translation error

- src/functions/template-tags/meta.php
addresses https://central.tri.be/issues/38899
> refactored and extracted the `tribe_separated_field`

- src/Tribe/Template/Month.php
Ensure the month view query accounts for hidden events.
> Respect status of hidden events in month view (#39562)

- src/Tribe/iCal.php
addresses https://central.tri.be/issues/37562
> updated timezone handling

- src/Tribe/View_Helpers.php
Re [C#39725](https://central.tri.be/issues/39725) this change makes it possible to _maintain_ (but not set) minute-level precision in the event editor where required for specific events - without otherwise breaking out of the default 5 minute increments for all events.
> Optionally support the exact minute of an event/break out of 5min intervals

- src/Tribe/PUE/Checker.php
Sorry for the amount of commits for a simple thing. I messed the `--amend` 
_Ref:_ [C#38372](https://central.tri.be/issues/38372)
> Auto Save Valid PUE keys

- src/Tribe/Cost_Utils.php
_Ref:_ [C#38228](https://central.tri.be/issues/38228)
> International Costs handled

- src/Tribe/Asset/Admin_Menu.php
- src/Tribe/Main.php
- src/resources/css/admin-menu.css
_Ref:_ [C#39840](https://central.tri.be/issues/39840)
On the Admin Menu for Add-ons items the Padding was a little bit off, this CSS file will fix this issue.
> Admin Menu for Addon Items

- src/Tribe/Asset/Bootstrap_Datepicker.php
See: https://central.tri.be/issues/35801
(worth reviewing with `?w=1`)
> add translation for 2 strings

- src/Tribe/iCal.php
- src/functions/template-tags/ical.php
addresses https://central.tri.be/issues/38756
> updated code to generate single event iCal link

- src/Tribe/Admin/Organizer_Chooser_Meta_Box.php
See: https://central.tri.be/issues/39522
> use function to pull singular "organizer" label

- src/Tribe/Admin/Organizer_Chooser_Meta_Box.php
See: https://central.tri.be/issues/40017
> use the function for organizer label

- src/io/csv/admin-views/import.php
See: https://central.tri.be/issues/40069
> providing a new link for iconv

- src/Tribe/Main.php
Thanks @afragen for keeping us honest
https://github.com/moderntribe/the-events-calendar/pull/349#issuecomment-144769450
> fixing escaping properly

- .gitignore
- composer.lock
- tests/_support/Tribe__Events__WP_UnitTestCase.php
- tests/acceptance.suite.dist.yml
- tests/functional.suite.dist.yml
This reduces the number of errors and issues
> updating tests for new WP_Browser version

- src/Tribe/API.php
New pull request for the contribution from @dalethedeveloper https://github.com/moderntribe/the-events-calendar/pull/220 against `release/121`
See: https://central.tri.be/issues/40035
> Type Check fix for saving Event Meta

- src/Tribe/Main.php
- src/admin-views/tribe-options-addons-api.php
_Ref:_ [C#34545](https://central.tri.be/issues/34545)
_Rel:_ moderntribe/events-eventbrite#80 moderntribe/events-facebook#29
> Create the New Add-ons Tab

- src/Tribe/Tickets/Tickets_Pro.php
This adds a filter to allow customizing the attendees csv export contents.
Internal reference: https://central.tri.be/issues/40224
> Filter attendees CSV items

- .gitignore
- codeception.dist.yml
- composer.lock
Also removing junk from .gitignore
> Relocate the active plugin declaration in codeception.dist.yml

- src/Tribe/Main.php
See: https://central.tri.be/issues/38488
> FEED_URL is in common now

- src/admin-views/tribe-options-addons-api.php
See: https://central.tri.be/issues/40318
> cleaned up a fiew more deprecation notices

- tests/functional/Autoloader_Test.php
- tests/functional/Deprecated_Test.php
- tests/functional/Updater_Test.php
Also, created a place to test deprecated methods going forward
> fixing a deprecated method call in this test

- src/functions/template-tags/organizer.php
See: https://central.tri.be/issues/39868
> fix bad array generated by tribe_get_organizer_ids sometimes

- src/Tribe/Google_Data_Markup/Event.php
- src/Tribe/Timezones.php
These were remnants after merge conflict resolution.
> Rename instances of Tribe__Events__Date_Utils to Tribe__Date_Utils

- tests/functional/Tribe_Event_Creation_Test.php
Just fixed two really easy things...
> Updated Tribe_Event_Creation_Test.php

- tests/functional/Deprecated_Test.php
See: https://central.tri.be/issues/40318
> these classes are *not* deprecated

- src/functions/template-tags/general.php
See: https://central.tri.be/issues/40318
> Fixing a deprecated function call

- src/Tribe/iCal.php
- tests/_support/Tribe__Events__WP_UnitTestCase.php
- tests/functional/Tribe_Event_Creation_Test.php
- tests/functional/Tribe__Events__iCal_Test.php
See: https://central.tri.be/issues/38756
> improving code and adding a test

- src/Tribe/Importer/Options.php
- src/io/csv/admin-views/general.php
_Ref:_ [C#38847](https://central.tri.be/issues/38847)
> Deprecated getOption + Importer Type

- src/admin-views/venue-meta-box.php
This is a follow-up to: https://github.com/moderntribe/the-events-calendar/pull/366
> Fix a textdomain issue and reduce the number of capitalized words

- src/Tribe/Activation_Page.php
- src/Tribe/Importer/Admin_Page.php
- src/Tribe/Main.php
_Ref:_ [C#40765](https://central.tri.be/issues/40765)
_Rel:_ moderntribe/events-filterbar#43 moderntribe/events-facebook#40 moderntribe/events-eventbrite#91 moderntribe/events-community#71 moderntribe/tribe-common#12 moderntribe/events-pro#187 moderntribe/the-events-calendar#393
> Page URL/Slug change with Common

- src/Tribe/Importer/Admin_Page.php
_Ref:_ [C#40765](https://central.tri.be/issues/40765)
_Rel:_ moderntribe/events-filterbar#43 moderntribe/events-facebook#40 moderntribe/events-eventbrite#91 moderntribe/events-community#71 moderntribe/tribe-common#12 moderntribe/events-pro#187 moderntribe/the-events-calendar#393 moderntribe/tribe-common#13
> Fatal Error Fixing

- src/Tribe/Capabilities.php
_Ref:_ [C#40953](https://central.tri.be/issues/40953)
_Rel:_ #397
> Venues and Organizer caps back on track

- tests/functional/Capabilities_Test.php
See: https://central.tri.be/issues/40953
> adding tests for editing venues and organizers

- src/Tribe/Main.php
_Ref:_ [C#39832](https://central.tri.be/issues/39832)
_Rel:_ moderntribe/tribe-common#9
> Common Help Page

- src/Tribe/Ajax/Operations.php
a wrapper around exit methods to centralize operations and allow testing
part of the work done for ticket https://central.tri.be/issues/40423
> added Ajax_Operations class

- src/Tribe/Main.php
_Ref:_ [C#41105](https://central.tri.be/issues/41105)
_Rel:_ moderntribe/the-events-calendar#411 moderntribe/tribe-common#19 moderntribe/events-community#77 moderntribe/event-tickets#33
> New Vendor jQuery UI style from Common Lib

- src/admin-views/tickets/meta-box.php
Fix that and clean up some markup.
See: https://central.tri.be/issues/39134
> Cancel was not getting translated

- src/Tribe/Tickets/Orders_Table.php
See: https://central.tri.be/issues/41235
> Fix notice and translation issues

- src/Tribe/Main.php
_Ref:_ [C#39231](https://central.tri.be/issues/39231)
> Modular Text for Help Page

- src/io/csv/admin-views/general.php
_Ref:_ [C#38845](https://central.tri.be/issues/38845)
> Intro text on Importer Page

- .editorconfig
See: https://central.tri.be/issues/41317
> Add jshint and scss-lint to the .editorconfig

- composer.lock
- tests/_support/Tribe__Events__WP_UnitTestCase.php
See: https://tribe.slack.com/archives/products-dev/p1447224044000465
> Update to extend \Codeception\TestCase\WPTestCase

- src/Tribe/Main.php
_Ref:_ [C#39231](https://central.tri.be/issues/39231)
> Improve Help page texting

- src/admin-views/tribe-options-timezones.php
_Ref:_ [C#38330](https://central.tri.be/issues/38330)
> H3 for Timezones

- src/resources/css/tribe-events-full.css
_Ref:_ [C#39080](https://central.tri.be/issues/39080)
> Tooltip overwrite for OL and UL

- src/Tribe/Cost_Utils.php
_Ref:_ [C#38228](https://central.tri.be/issues/38228)
> Cost internationally friendly

- src/Tribe/Main.php
- src/functions/template-tags/query.php
_Ref:_ [C#41738](https://central.tri.be/issues/41738)
> Fix default Display data

- src/Tribe/Cost_Utils.php
After this we Removed support for the weird negative prices.:smile:
_Ref:_ [C#38228](https://central.tri.be/issues/38228)
> Improve how we deal with Range of prices and it's decimals on Cost_utils

- src/Tribe/Main.php
See: https://central.tri.be/issues/41671
> When TEC is active, alter the base settings page parent

- src/functions/template-tags/date.php
_Ref:_ [C#41871](https://central.tri.be/issues/41871)
> Make date methods Replace-able

- src/Tribe/Main.php
_Ref:_ [C#39231](https://central.tri.be/issues/39231)
> Update links on the Help Page

- composer.lock
- src/Tribe/Admin/Bar/Admin_Bar.php
- src/Tribe/Admin/Bar/Configurator_Interface.php
- src/Tribe/Admin/Bar/Default_Configurator.php
- src/Tribe/Constants.php
- src/Tribe/Main.php
- tests/_bootstrap.dist.php
- tests/_support/classes/WP_Screen.php
- tests/functional/Tribe/Events/Admin/Bar/Admin_BarTest.php
- tests/functional/Tribe/Events/Utils/ConstantsTest.php
Ticket https://central.tri.be/issues/41021
I've fixed the issue and refactored (with tests) admin bar related code out of Main.
> fixed issue and refactored admin bar code

- src/admin-views/tribe-options-general.php
See: https://central.tri.be/issues/41980
> Relocating fields from tribe-common back to TEC

- src/admin-views/tribe-options-display.php
See: https://central.tri.be/issues/41980#note-3
> Relocating date format and time separator fields from tribe-common

- readme.txt
- src/functions/template-tags/general.php
Fixed a problem introduced by moderntribe/the-events-calendar#339
_Ref:_ [C#42046](https://central.tri.be/issues/42046)
> Remove wp_trim_excerpt

- src/functions/template-tags/general.php
See: https://central.tri.be/issues/42052
> Enable the list view for fresh installs in addition to month view

- src/Tribe/Main.php
Support inline plugin upgrade notices - [depends on tribe-common PR 53](https://github.com/moderntribe/tribe-common/pull/53).
[C#42047](https://central.tri.be/issues/42047)
> Prominent, inline upgrade notices | 42047

- src/Tribe/Event_Tickets/Main.php
- src/Tribe/Event_Tickets/Ticket_Email.php
Related: https://github.com/moderntribe/event-tickets/pull/83
See: https://central.tri.be/issues/41992
> Hook into event-tickets to inject the event date into the ticket email

- readme.txt
- src/Tribe/Cost_Utils.php
- src/Tribe/Importer/Admin_Page.php
_Ref:_ [C#39041](https://central.tri.be/issues/39041)
_Rel:_ moderntribe/events-filterbar#52
> Handling for Non Numeric Costs

- src/Tribe/Admin_List.php
- src/Tribe/Main.php
_Ref:_ [C#37613](https://central.tri.be/issues/37613)
> Columns now Fired with AJAX too

- readme.txt
- src/Tribe/Main.php
See: https://central.tri.be/issues/42332
> Don't do a destructive escaping of event category URLs

- tests.md
Apart from some whitespace tidies, just adds a note about PhantomJS to steer folks in the right direction (lines 50-55).
> Add note about PhantomJS to test instrucs (spotfix)

- src/functions/template-tags/venue.php
- tests/functional/functions/template-tags/Venue_Template_Tags_Test.php
Ref [C#26901](https://central.tri.be/issues/26901) - adds helper to obtain the venue URL (rather than just a formed HTML link).
> Add helper to get venue URL (raw), plus tests | 26901

- src/Tribe/Template/Month.php
- src/functions/template-tags/loop.php
Ticket https://central.tri.be/issues/41127
Merge after this: https://github.com/moderntribe/tribe-common/pull/57
> use `tribe_get_date_option` for date formats

- src/Tribe/Dates/Known_Range.php
- src/Tribe/Main.php
- src/functions/template-tags/general.php
- tests/functional/Tribe/Events/Dates/Known_RangeTest.php
Ticket: https://central.tri.be/issues/33205
> Fixed known range build and update

- src/functions/template-tags/organizer.php
- src/functions/template-tags/venue.php
_Ref:_ [C#43133](https://central.tri.be/issues/43133)
> Ticket 43133

- src/Tribe/Google_Data_Markup.php
See: https://central.tri.be/issues/43133
> Escape values in the JSON+LD

- src/Tribe/Main.php
- src/resources/js/events-admin.js
_Ref:_ [C#39617](https://central.tri.be/issues/39617)
> Same Slug Archive Dismissible

- readme.txt
- src/Tribe/Google_Data_Markup.php
- src/Tribe/Google_Data_Markup/Event.php
- src/functions/template-tags/general.php
_Ref:_ [C#37989](https://central.tri.be/issues/37989)
> Address Handling for JSON-LD

- readme.txt
- src/Tribe/Advanced_Functions/Register_Meta.php
- src/views/modules/meta/details.php
_Ref:_ [C#38135](https://central.tri.be/issues/38135)
> Add Classes Wrapping around date and time elements

- src/admin-views/tribe-options-general.php
_Ref:_ [C#38134](https://central.tri.be/issues/38134)
> Present the amalgamateDuplicates for everyone

- src/Tribe/Ajax/Select2.php
- src/Tribe/Asset/Dropdowns.php
- src/Tribe/Main.php
- src/resources/js/events-admin.js
- src/resources/js/tribe-dropdowns.js
_Ref:_ [C#41617](https://central.tri.be/issues/41617)
> Wrap the code to make a good usaged of Select2 with AJAX

- src/Tribe/Main.php
- src/Tribe/Shortcode/Event_Details.php
- src/resources/css/tribe-events-theme.css
_Ref:_ [C#37918](https://central.tri.be/issues/37918)
> Create the Shortcode for Event Details

- src/Tribe/Rewrite.php
_Ref:_ [C#42789](https://central.tri.be/issues/42789)
> Esc for Regular Expression on Rewrite Terms

- src/functions/template-tags/general.php
- src/views/list/single-event.php
_Ref:_ [C#42524](https://central.tri.be/issues/42524)
> Allow more HTML on list view and Improve how we trim Excerpt

- src/Tribe/Query.php
_Ref:_ [C#30151](https://central.tri.be/issues/30151)
> ID vs Slug on Listing from Categories

- src/views/modules/meta/organizer.php
_Ref:_ [C#33294](https://central.tri.be/issues/33294)
> Valid HTML with DD and DT

- src/functions/template-tags/general.php
- src/views/month/tooltip.php
_Ref:_ [C#42592](https://central.tri.be/issues/42592)
> Simply make this raw and kses like a post content

- src/views/modules/meta/organizer.php
Ticket:  https://central.tri.be/issues/29941
Related to https://github.com/moderntribe/events-pro/pull/280
> Use different function to get organizer link

- src/Tribe/Main.php
- src/Tribe/Rewrite.php
_Ref:_ [C#42815](https://central.tri.be/issues/42815)
> UTF8 Preparing more Globally Done

- src/resources/css/tribe-events-theme.css
_Ref:_ [C#37918](https://central.tri.be/issues/37918)
> Add a few good lines of css for Shortcodes

- src/views/modules/meta/organizer.php
> Apply the fix that #556 was attempting to apply

- tests/_support/AcceptanceTester.php
- tests/acceptance/CheckUpdatePageCept.php
- tests/acceptance/CheckWelcomePageCept.php
- tests/acceptance/CreateACategoryCept.php
- tests/acceptance/CreateATagCept.php
- tests/acceptance/CreateAVenueCept.php
- tests/acceptance/CreateAnOrganizerCept.php
- tests/acceptance/UpdateAnEventCept.php
New pull request after killing the old one due to new branch.
> Rmacdon465

- src/Tribe/Cost_Utils.php
Ticket: https://central.tri.be/issues/33491
This handles merging costs coming with currency. EB differs in return values...
> added handling of currency prefixed merging costs

- composer.lock
- tests/functional/Tribe/Events/Dates/Known_RangeTest.php
Ticket: https://central.tri.be/issues/42077
Small adjustments to get CORE functional tests back to green
> fixed early call to Date_Utils

- src/Tribe/Importer/Admin_Page.php
- src/Tribe/Importer/File_Uploader.php
Restores commit 46ac11e08bb9b6e77c99f7bff51b2943c752a470 (see [PR 522](https://github.com/moderntribe/the-events-calendar/pull/522)).
[C#37186](https://central.tri.be/issues/37186)
> Restore safety check added in 46ac11e08 | #37186

- src/Tribe/Template/Month.php
Ticket: https://central.tri.be/issues/41383
This restores the work done for the tickets that has been removed during the merge phase.
> list day events in month view by start time

- src/Tribe/Templates.php
_Ref:_ [C#44253](https://central.tri.be/issues/44253)
> Create a DarkMagic to solve the_content madness

- readme.txt
- src/Tribe/Template/Month.php
Add back in month daily event filter that got removed along with readme.txt update for it
_Ref:_ [C#38137](https://central.tri.be/issues/38137)
> Add back month view daily event fitler

- src/resources/js/tribe-events-bar.js
_Ref:_ [C#41662](https://central.tri.be/issues/41662)
> Improve our Core JS to also look for fields on the FilterBar

- src/Tribe/iCal.php
_Ref:_ [C#43345](https://central.tri.be/issues/43345)
> Respect the Category on the Initial page

- src/Tribe/Admin/Event_Meta_Box.php
- src/Tribe/Main.php
_Ref:_ [C#42470](https://central.tri.be/issues/42470)
> Make our Default Methods respect the Default options a little bit better

- src/resources/js/tribe-events.js
_Ref:_ [C#43245](https://central.tri.be/issues/43245)
> Mobile Breakpoint identification Resolved

- src/views/list/nav.php
Quick fix, adds semi colon to &laquo src/view/list/nav.php
> Fix missing semi colon on &laquo in list view nav.php

- src/Tribe/Embedded_Maps.php
_Ref:_ [C#33647](https://central.tri.be/issues/33647)
> Improve embed map title

- src/Tribe/Main.php
_Ref:_ [C#44211](https://central.tri.be/issues/44211)
_Rel:_ moderntribe/tribe-common#69
> the_title needs a second param

- src/Tribe/Shortcode/Event_Details.php
_Ref:_ [C#37918](https://central.tri.be/issues/37918)
> Default shortcode alignment

- src/Tribe/API.php
_Ref:_ [C#42712](https://central.tri.be/issues/42712)
> Yoast Compatibility

- src/Tribe/Main.php
- src/Tribe/Timezones.php
_Ref:_ [C#43097](https://central.tri.be/issues/43097)
> Google Calendar Link is now a bit refactored

- readme.txt
- src/Tribe/Main.php
_Ref:_ [C#43097](https://central.tri.be/issues/43097)
> Remove Z on Gcal

- src/views/list/nav.php
Added missing semicolon to HTML entity (i.e. `&laquo;`).
> Adding missing semicolon

- src/Tribe/Query.php
A [602](https://github.com/moderntribe/the-events-calendar/pull/602) for [122](https://github.com/moderntribe/the-events-calendar/tree/release/122), if you will :wink:
[C#44736](https://central.tri.be/issues/44736)
> Fix handling of DateTime objects re custom event queries | #44736

- src/Tribe/Main.php
- src/admin-views/new-organizer-meta-section.php
See: https://central.tri.be/issues/44832
> Make sure the ajaxurl is accessible to our JS

- src/Tribe/Main.php
- src/Tribe/Template/Day.php
- src/Tribe/Template/Month.php
- src/Tribe/Template/Single_Event.php
- src/Tribe/Template_Factory.php
- src/admin-views/events-meta-box.php
- src/functions/template-tags/general.php
- src/views/widgets/list-widget.php
Related:
* https://github.com/moderntribe/events-pro/pull/304
* https://github.com/moderntribe/events-community/pull/111
See: https://central.tri.be/issues/44259
> Add functions to return lowercase event name (singular & plural)

- src/resources/css/tribe-events-full-mobile.css
- src/resources/css/tribe-events-full.css
- src/resources/css/tribe-events-skeleton.css
- src/resources/css/tribe-events-theme-mobile.css
- src/resources/css/tribe-events-theme.css
https://central.tri.be/issues/39908
> Fixed typo of "stylsheet" to "stylesheet"

- src/Tribe/Admin/Organizer_Chooser_Meta_Box.php
_Ref:_ [C#43693](https://central.tri.be/issues/43693)
> Make sure we are looking for the event in the correct place

- src/Tribe/API.php
Related: https://github.com/moderntribe/events-importer-ical/pull/65
See: https://central.tri.be/issues/43743
> Only set the Timezone Abbr and UTC dates if they aren't already set

- src/Tribe/Template/Single_Event.php
- src/views/default-template.php
_Ref:_ [C#42572](https://central.tri.be/issues/42572)
> Remove the Duplication

- src/Tribe/Admin/Organizer_Chooser_Meta_Box.php
_Ref:_ [C#39026](https://central.tri.be/issues/39026)
> Improve the Organizer Metabox to allow public template on community

- src/Tribe/Admin/Organizer_Chooser_Meta_Box.php
_Ref:_ [C#39026](https://central.tri.be/issues/39026)
> Missused new WP_Post

- readme.txt
- src/Tribe/Main.php
_Ref:_ [C#36246](https://central.tri.be/issues/36246)
> Load l10n using new Helper

- src/Tribe/Main.php
- src/Tribe/Rewrite.php
_Ref:_ [C#44225](https://central.tri.be/issues/44225)
> Conditionally preg_quote stuff on rewrite permalinks slug

- readme.txt
- src/Tribe/Main.php
See: https://central.tri.be/issues/45473
> Only redirect to approved domains

- src/Tribe/Main.php
_Ref:_ [C#45010](https://central.tri.be/issues/45010)
> For some weird reason the dimissal method was removed

- src/Tribe/Rewrite.php
_Ref:_ [C#45516](https://central.tri.be/issues/45516)
> Strip HTML from this param

- src/functions/template-tags/venue.php
- src/views/embed/venue.php
See: https://central.tri.be/issues/43938
> Only link the venue if exclude_from_search is false

- src/resources/css/events-admin.css
- src/resources/css/tribe-events-embed.css
- src/resources/css/tribe-events-full-mobile.css
- src/resources/css/tribe-events-full.css
- src/resources/postcss/events-admin.pcss
- src/resources/postcss/tribe-events-embed.pcss
- src/resources/postcss/tribe-events-full-mobile.pcss
- src/resources/postcss/tribe-events-full.pcss
See: https://central.tri.be/issues/39982
> Add nesting to some PostCSS files

- src/functions/template-tags/general.php
Added ability to override the size and link parameters of the featured image without the need for a whole template override.
> Added featured image size and link filters.

- src/Tribe/Importer/Column_Mapper.php
Ticket: https://central.tri.be/issues/46169
Not the biggest PR in history.
> Timezone is one word

- src/views/embed/footer.php
Follow-up PR to: https://central.tri.be/issues/43938
> Adding comment button for oembed

- src/views/embed/footer.php
Reverts moderntribe/the-events-calendar#675
> Revert "Adding comment button for oembed"

- src/Tribe/Cost_Utils.php
Further improve the uncosted events query (we only want it to look at events, not unrelated post types).
[C#46403](https://central.tri.be/issues/46403)
> Refine uncosted events query | #46403

- readme.txt
- src/Tribe/Main.php
See: https://central.tri.be/issues/46542
> use https for our site URL

- src/views/embed/image.php
See: https://central.tri.be/issues/43938
> Only output the embed image if there is one

- src/Tribe/Rewrite.php
Related: https://github.com/moderntribe/events-pro/pull/323
See: https://central.tri.be/issues/46516
> Add a rewrite endpoint for date-based /embed/ URLs

- src/functions/template-tags/date.php
- src/functions/template-tags/deprecated.php
https://central.tri.be/issues/45076
> Fixed the comments and moved the urls

- src/views/day/nav.php
- src/views/list/nav.php
- src/views/month/nav.php
THe packager caught some view files that needed version numbers added.
> Add version to view files

- readme.txt
- src/functions/template-tags/general.php
Document new hook (also make the post object accessible to callbacks) and add changelog entry.
https://central.tri.be/issues/46477
> Document new hook and add to changelog | #46477

- src/Tribe/Google/Maps_API_Key.php
- src/admin-views/tribe-options-addons-api.php
Ticket: https://central.tri.be/issues/44827#note-19
Wording changes.
> applied wording changes

- package.json
- readme.txt
- src/Tribe/Main.php
- the-events-calendar.php
Bump version numbers (spotfix).
> Version numbers to 4.2.1dev1

- src/Tribe/Linked_Posts.php
- src/Tribe/Linked_Posts/Chooser_Meta_Box.php
- src/Tribe/Organizer.php
- src/Tribe/Venue.php
See: https://central.tri.be/issues/45444
> make lowercase labels translation friendly for linked posts

- src/resources/js/tribe-events-bar.js
- src/resources/js/tribe-events.js
_Ref:_ [C#27425](https://central.tri.be/issues/27425)
> Mobile default View

- src/Tribe/Asset/Admin.php
Fixes a problem introduced by the changes on `tribe-bumpdown`.
> Change the Name of the tribe-inline-bumpdown to tribe-bumpdown

- package.json
- readme.txt
- src/Tribe/Main.php
- the-events-calendar.php
Prep for hotfix.
https://central.tri.be/issues/62562
> Bump version #s, add changelog entry for hotfix/4.2.1.1 release | #62562

- src/Tribe/Aggregator.php
- src/Tribe/Aggregator/API/Abstract.php
- src/Tribe/Aggregator/API/Image.php
- src/Tribe/Aggregator/API/Import.php
- src/Tribe/Aggregator/API/Origins.php
- src/Tribe/Aggregator/Service.php
- src/admin-views/aggregator/tabs/new.php
This Work-in-progress is continued work on: https://central.tri.be/issues/61161
While it isn't complete by any means, it doesn't break things so is arguably mergeable after a few sets of eyes on the progress so far.
And yes. There are debug messages floating around. 💃
> Adding the beginnings of the Origins/Import/Image APIs

- src/Tribe/Ignored_Events.php
_Ref:_ [C#61231](https://central.tri.be/issues/61231)
> Only Apply Ignore to Events

- src/Tribe/Main.php
_Ref:_ [C#62408](https://central.tri.be/issues/62408)
_Rel:_ moderntribe/tribe-common#130
> Expire the Notice when post transitions statuses

- readme.txt
- src/Tribe/Main.php
_Ref:_ [C#63099 ](https://central.tri.be/issues/63099 )
> Enable Front End Edit Venue Link in CE

- src/Tribe/Main.php
When calling remove_action in a function hooked to the same action, all functions hooked to this action with a lower priority are never called, thus breaking 3rd party plugins.
Fortunately, there is an easy way to achieve the same goal using a static variable as proposed in this PR. 
[#63474](https://central.tri.be/issues/63474)
> Don't call remove_action in a function hooked to the same action

- readme.txt
Adds a changelog entry re [PR 751](https://github.com/moderntribe/the-events-calendar/pull/751).
[C#64141](https://central.tri.be/issues/64141)
> Add readme entry | #64141

- src/Tribe/JSON_LD/Event.php
- src/Tribe/List_Widget.php
- src/Tribe/Template/Month.php
- src/functions/template-tags/month.php
_Ref:_ [C#62439](https://central.tri.be/issues/62439)
> JSON-LD Widgets

- src/Tribe/Admin_List.php
- src/views/single-event.php
This will allow different translations and result depending on context:
All (XX) [Event count]
All Events [plural label]
[#64586](https://central.tri.be/issues/64586)
> Add context to string "All %s"

- readme.txt
- src/Tribe/Venue.php
See: https://central.tri.be/issues/64628
> fixed default venue setting

- src/Tribe/Event_Tickets/Attendees_Report.php
Spotfix for earlier work - corrects textdomain.
[C#61992](https://central.tri.be/issues/61992)
> Correct textdomain | #61992

- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Record/CSV.php
- src/Tribe/Aggregator/Record/List_Table.php
- src/Tribe/Aggregator/Tabs/New.php
See: https://central.tri.be/issues/61161
> Update event counts and fix date diff rendering

- src/Tribe/Aggregator/Event.php
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Records.php
- src/Tribe/Asset/Admin.php
- src/Tribe/Ignored_Events.php
- src/resources/js/events-admin.js
_Ref:_ [C#61233](https://central.tri.be/issues/61233)
> Rework Ignored Events

- src/Tribe/Aggregator.php
- src/Tribe/Aggregator/Cron.php
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Service.php
- src/Tribe/Aggregator/Settings.php
_Ref:_ [C#61161](https://central.tri.be/issues/61161)
> Adjust a bit of the docblocks

- src/Tribe/Aggregator/Tabs/New.php
See: https://central.tri.be/issues/65027
> Make sure to pass data to CSV's insert_posts method

- src/admin-views/aggregator/origins/ical.php
- src/admin-views/aggregator/origins/ics.php
- src/admin-views/aggregator/tabs/import-form.php
> replace "Clear Filters" with "Cancel"

- src/admin-views/aggregator/tabs/import-form.php
> conditional helper text for save button on scheduled import

- src/admin-views/aggregator/tabs/import-form.php
> conditional Status/Category helper text for scheduled imports

- src/admin-views/aggregator/origins/csv.php
- src/admin-views/aggregator/origins/facebook.php
- src/admin-views/aggregator/origins/ical.php
- src/admin-views/aggregator/origins/meetup.php
- src/admin-views/aggregator/origins/refine.php
- src/admin-views/aggregator/tabs/import-form.php
See Findings/Feedback Compilation doc
> Remove the clear "x" on select2 boxes

- src/Tribe/Aggregator/Tabs/Abstract.php
See Findings/Feedback Compilation
> Don't make useless roundtrips to Event Aggregator

- src/admin-views/aggregator/origins/refine.php
See Findings/Feedback Compilation
> Show the ics/ical/gcal refine fields at the same time as the source

- src/admin-views/aggregator/meta-box.php
See findings/feedback compilation doc
> Update the text of the "Retain" option for the change authority metabox

- src/admin-views/aggregator/tabs/import-form.php
> Apparently if you set table width to 100%, the datatable resizes

- src/Tribe/Aggregator/Record/List_Table.php
> Add mouseover text for history tab icons

- src/Tribe/Aggregator/API/Image.php
- src/Tribe/Aggregator/Event.php
- src/Tribe/Aggregator/Record/Abstract.php
> Import images from Event Aggregator when they are available

- src/admin-views/aggregator/origins/refine.php
- src/admin-views/aggregator/page.php
- src/resources/js/aggregator-fields.js
> Add datepicker to refine date

- src/Tribe/Aggregator/Tabs/New.php
- src/admin-views/aggregator/tabs/import-form.php
This is only a partial fix. The data in the license info appears to be
stale and not being updated when the API key is changed for some reason.
> check license before showing upsell

- src/Tribe/Aggregator.php
- src/Tribe/Aggregator/API/Image.php
- src/Tribe/Aggregator/API/Import.php
- src/Tribe/Aggregator/Cron.php
- src/Tribe/Aggregator/Errors.php
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Record/CSV.php
- src/Tribe/Aggregator/Records.php
- src/Tribe/Aggregator/Service.php
- src/Tribe/Aggregator/Tabs/Scheduled.php
_Ref:_ [C#61161](https://central.tri.be/issues/61161)
_Note:_ There are a few notes, because I would need to improve our Errors Class to allow overwriting the default message. Which I didn't think was a thing when I initially coded it.
> Improving the way we handle Errors

- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Record/CSV.php
- src/Tribe/Aggregator/Records.php
- src/Tribe/Importer/File_Importer.php
- src/Tribe/Importer/File_Importer_Events.php
See: https://central.tri.be/issues/62663
> Add required info into CSV imports to enable the Import Meta box

- src/Tribe/Aggregator.php
- src/Tribe/Aggregator/Cron.php
- src/Tribe/Aggregator/Errors.php
- src/admin-views/aggregator/settings.php
- src/admin-views/tribe-options-addons-api.php
See: https://central.tri.be/issues/45260
> language updates

- src/Tribe/Aggregator/Tabs.php
See: https://central.tri.be/issues/64994#note-4
> Setup the Edit tab/functionality when doing Ajax

- src/Tribe/Aggregator/Record/CSV.php
- src/admin-views/aggregator/origins/csv.php
Related:
* https://github.com/moderntribe/event-tickets/pull/237
* https://github.com/moderntribe/event-tickets-plus/pull/210
See: https://central.tri.be/issues/61240#note-17
> Add support for ET/ET+ CSV imports and prevent duplicate types

- src/Tribe/Ignored_Events.php
> improve the handling of bulk "Trash" action around ignored events

- src/Tribe/Aggregator/API/Import.php
> Address API todos

- src/Tribe/Ignored_Events.php
> Don't include ignored event count in "All" count

- src/Tribe/Main.php
_Ref:_ [C#62408](https://central.tri.be/issues/62408)
> Improve to make it cover all public possible CPTs

- src/Tribe/Ignored_Events.php
_Ref:_ [C#65029](https://central.tri.be/issues/65029)
> Ignored Events Deleting working again

- src/Tribe/Aggregator/Record/List_Table.php
_Ref:_ [C#61237](https://central.tri.be/issues/61237)
> Make Sure EA dates respect the formating on the settings page

- src/Tribe/Aggregator/Tabs/New.php
Also, added the link for renewal
> fixed the link for "view all" to be post type dependent

- src/Tribe/Aggregator/Records.php
> The edit link uses "id", not "ids"

- src/Tribe/Aggregator/Settings.php
- src/admin-views/aggregator/settings.php
Also some reorganization of the code there to make it more scannable
> import settings need to be available for non-Aggregator

- src/Tribe/Aggregator/Record/List_Table.php
> removing bold around counts

- src/Tribe/Aggregator/Record/List_Table.php
> changed the linking scheme

- src/Tribe/Aggregator/Record/List_Table.php
> only link the "via" for Facebook and Meetup

- src/functions/template-tags/venue.php
- src/views/list/single-event.php
Further tweaks following QA feedback to ensure single events within list view display as previously.
[#39905](https://central.tri.be/issues/39905)
> List view: link to venue, show Gmap link | #39905

- src/Tribe/Aggregator/Cron.php
- src/Tribe/Aggregator/Record/Queue_Processor.php
- src/Tribe/Aggregator/Record/Queue_Realtime.php
- src/Tribe/Aggregator/Tabs/New.php
- src/Tribe/Aggregator/Tabs/Scheduled.php
> Only show Realtime Queue processing UI for imports that were interactive

- src/Tribe/Aggregator/Service.php
- src/Tribe/Aggregator/Tabs/New.php
This is important for slow connections and big file transfers
> crank up the timeout when talking to Event Aggregator

- src/Tribe/Aggregator/Cron.php
Found when debugging schedules
> Process posts when we cron

- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Ignored_Events.php
> When an event is ignored, don't overwrite the post status

- src/Tribe/Aggregator/Record/CSV.php
> Only allow for CSV imports on OUR declared post types

- readme.txt
- src/Tribe/Template/Single_Event.php
- src/functions/template-tags/general.php
_Ref:_ [C#62303](https://central.tri.be/issues/62303) Add tribe_is_past_event() conditional to be used in Event Tickets and Single Event Templates
> tribe_is_past_event conditional and ticket messages

- src/admin-views/aggregator/settings.php
> Remove callout to Google on the iCal/ICS line

- src/Tribe/Aggregator/Record/CSV.php
> Only set CSV to pending when queueing if we are NOT previewing

- src/Tribe/Aggregator.php
> Remove Import Records from posts that ET can attach tickets to

- src/Tribe/API.php
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Record/Queue.php
- src/Tribe/Aggregator/Record/Queue_Realtime.php
- src/Tribe/Aggregator/Tabs/New.php
> improved import results messaging

- src/Tribe/Aggregator/Tabs/New.php
> Check if the service is active with our handy one-liner

- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Record/List_Table.php
> Ensure that schedule counts are updated and that we display correct #

- src/Tribe/Aggregator/API/Image.php
- src/Tribe/Aggregator/Errors.php
- src/Tribe/Aggregator/Record/Abstract.php
> Prevent Notice when wp_upload_bits crashes and burns with image source

- src/Tribe/Aggregator/Settings.php
> Set the default change authority to "overwrite"

- src/Tribe/Aggregator/Event.php
- src/Tribe/Aggregator/Record/Facebook.php
- src/Tribe/Aggregator/Record/Meetup.php
- src/Tribe/Aggregator/Records.php
> Force URLs into Facebook and Meetup events when the EventURL is empty

- src/Tribe/Aggregator/Records.php
- src/Tribe/Aggregator/Tabs/History.php
- src/Tribe/Aggregator/Tabs/Scheduled.php
> Only show Scheduled and History tabs when needed

- src/Tribe/Aggregator/Record/List_Table.php
> Always show "New" total

- src/Tribe/Importer/File_Importer.php
- src/Tribe/Importer/File_Importer_Events.php
See: https://central.tri.be/issues/61238
> Obey Change Authority setting for CSV

- src/admin-views/aggregator/header.php
> Skip invisible tabs

- src/Tribe/Ignored_Events.php
plus some improved syntactical sugar
> improved text

- src/Tribe/Aggregator/Record/CSV.php
See: https://central.tri.be/issues/65945
> Force the first line of CSV to be a header

- src/Tribe/Aggregator/Record/List_Table.php
> More fixes to the counts displayed in the import column

- src/Tribe/Aggregator/Event.php
> Make sure we are importing country, facebook id, and meetup id

- src/Tribe/Importer/Options.php
See: https://central.tri.be/issues/65502
> replace deprecated function call

- src/Tribe/Aggregator/Page.php
- src/Tribe/Ignored_Events.php
> add a link to the text

- src/admin-views/aggregator/settings.php
> removing API link and text around Facebook import settings

- src/Tribe/Importer/File_Importer_Events.php
See: https://central.tri.be/issues/61240#note-27
> Support both numeric and non-numeric categories when importing CSV

- src/admin-views/aggregator/origins/refine.php
> Allow removing Radius Filter on EA

- src/Tribe/Aggregator/Tabs/New.php
Ticket: found while working on https://central.tri.be/issues/40720
Fix some uses of `empty` function on functions
> small 5.2 compat changes on empty

- src/Tribe/Aggregator.php
- src/Tribe/Aggregator/API/Origins.php
- src/Tribe/Aggregator/Service.php
- src/Tribe/Aggregator/Settings.php
- src/admin-views/tribe-options-addons-api.php
> Allow the Service to communicate default settings for oAuth and Limits

- src/Tribe/Aggregator/Records.php
See: https://central.tri.be/issues/66516
> Don't add the Aggregator Record post type to Appearance > Menus

- src/Tribe/Aggregator/Settings.php
- src/admin-views/aggregator/settings.php
See: https://central.tri.be/issues/66518
> Separating ICS from iCal in the Events > Settings > Imports tab

- src/Tribe/Aggregator/API/Origins.php
See: https://central.tri.be/issues/66538
> Don't fetch the oauth data if the service isn't active

- src/Tribe/Aggregator/Meta_Box.php
See: https://central.tri.be/issues/66525
> Fixing the date/tooltip

- src/Tribe/Aggregator/API/Image.php
- src/Tribe/Aggregator/Record/Abstract.php
_Ref:_ [C#66509](https://central.tri.be/issues/66509)
> Make EA image import count correctly created images

- src/Tribe/Aggregator/API/Image.php
_Ref:_ [C#66506](https://central.tri.be/issues/66506)
> Clean EA Image extension for a few cases

- src/Tribe/Aggregator/Record/List_Table.php
> the "all time" number on history is more confusing than useful

- src/admin-views/aggregator/origins/csv.php
- src/admin-views/aggregator/origins/eventbrite.php
- src/admin-views/aggregator/origins/facebook.php
- src/admin-views/aggregator/origins/gcal.php
- src/admin-views/aggregator/origins/ical.php
- src/admin-views/aggregator/origins/ics.php
- src/admin-views/aggregator/origins/meetup.php
- src/admin-views/aggregator/origins/refine.php
- src/admin-views/aggregator/tabs/import-form.php
Related: https://github.com/moderntribe/tribe-common/pull/203
See: https://central.tri.be/issues/66568
> Limit the width of most bumpdowns using the new "all-triggers" rule

- src/admin-views/aggregator/tabs/import-form.php
See: https://central.tri.be/issues/66568
> Add the width rule to the preview bumpdowns too

- src/Tribe/Aggregator/Tabs/New.php
_Ref:_ [C#66664](https://central.tri.be/issues/66664)
> EA: Remove POST info from Service Facebook Token

- src/Tribe/Aggregator/Service.php
Related: https://github.com/moderntribe/tribe-common/pull/206
See: https://central.tri.be/issues/65378
> If EA licenses have notices, then consider the EA service inactive

- src/Tribe/Aggregator/Record/List_Table.php
See: https://central.tri.be/issues/66846
> Adding detailed error messages to tooltips on History tab

- src/Tribe/Aggregator/Page.php
> Shorten preview placeholder text a little | spotfix

- src/admin-views/aggregator/origins/facebook.php
Simplify a bit of the markup and place the input field within a `<td>`
> Setup the proper data-depends when Facebook has been oauth'd

- src/Tribe/Aggregator/Errors.php
- src/Tribe/Aggregator/Record/Abstract.php
See: https://central.tri.be/issues/66891
> Support sprintf-ing messages from the service

- src/Tribe/Aggregator/Service.php
This will allow us to cleanly translate the messages from the EA Service
> Bring over EA Service messages and translate them

- src/Tribe/Aggregator/Record/Abstract.php
Related: https://github.com/moderntribe/events-eventbrite/pull/136
See: https://central.tri.be/issues/67062
> Add some helper methods for record activity

- src/Tribe/Aggregator/Migrate.php
See: https://central.tri.be/issues/61940#note-18
> Write away from the flakey array_filter and check more deliberately

- src/Tribe/Aggregator.php
- src/admin-views/aggregator/settings.php
- src/admin-views/aggregator/status.php
Related: https://github.com/moderntribe/tribe-common/pull/217
See: https://central.tri.be/issues/67093
> Move status section to the bottom of the Help tab

- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Settings.php
- src/Tribe/Importer/File_Importer_Events.php
- src/admin-views/aggregator/settings.php
* Fix issues with default settings in EA
* Actually observe the Show Map setting for events
* Handle Show Map settings as if it were being updated from the origin.  In other words, make the Show Map settings observe the change authority settings
See: https://central.tri.be/issues/67228
> Fix various bugs around setting and updating the Show Map setting in EA

- package-whitelist.json
See: https://central.tri.be/issues/67011
> Include clipboard.js when packaging

- src/Tribe/Rewrite.php
> Whitespace | spotfix

- src/Tribe/Integrations/WPML/Linked_Posts.php
- src/Tribe/Integrations/WPML/Permalinks.php
- src/Tribe/Integrations/WPML/Rewrites.php
- src/Tribe/Integrations/WPML/Utils.php
- src/Tribe/Integrations/WPML/WPML.php
- src/Tribe/Linked_Posts.php
- src/admin-views/admin-welcome-message.php
This includes two WPML fixes and a required update to language on the activation screen.
I'd like to get these rolled into the release.
> develop => release/4.3

- src/Tribe/Aggregator/Page.php
- src/admin-views/aggregator/tabs/import-form.php
Suggestion...use `?w=1`
Related: https://github.com/moderntribe/event-tickets/pull/270
See: https://central.tri.be/issues/67875
> Filter csv column mappings and dynamically output import columns

- src/Tribe/Rewrite.php
Was poking around our rewrite code and saw some funky formatting.
> Fix weird tabulation | spotfix

- src/Tribe/Aggregator/Record/Activity.php
Related: https://github.com/moderntribe/event-tickets/pull/274
See: https://central.tri.be/issues/67883
> Adding hook for additional post types to register their own activities

- src/Tribe/Main.php
- src/admin-views/tribe-options-general.php
_Ref:_ [C#67723](https://central.tri.be/issues/67723)
> Fixing the Settings page links to Welcome and Update pages

- src/admin-views/venue-meta-box.php
See: https://central.tri.be/issues/67820
> When rendering the state drop-down, match by abbreviation OR full name

- src/Tribe/Aggregator/Event.php
- src/Tribe/Aggregator/Record/Abstract.php
_Ref:_ [C#68031](https://central.tri.be/issues/68031)
> Make the Changes to prevent Duplicates from wrong FacebookID

- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Tabs/New.php
See: https://central.tri.be/issues/68290
> Avoid inserting null meta values into postmeta for EA Records

- src/Tribe/Aggregator/Record/Abstract.php
_Ref:_ [C#68284](https://central.tri.be/issues/68284)
> Prevents On Demand Schedule to be triggered on Cron

- src/Tribe/Aggregator/Event.php
- src/Tribe/Aggregator/Meta_Box.php
- src/Tribe/Aggregator/Records.php
- src/admin-views/aggregator/meta-box.php
See: https://central.tri.be/issues/68288
> Allow the EA meta box to failover to meta fields when EA record is mia

- src/Tribe/Aggregator/Cron.php
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Records.php
_Ref:_ [C#68283](https://central.tri.be/issues/68283)
> Prune of Records for Event Aggregator, on 'tribe_aggregator_cron'

- readme.txt
- src/Tribe/Aggregator/Errors.php
- src/Tribe/Aggregator/Record/Abstract.php
_Ref:_ [C#68197](https://central.tri.be/issues/68197)
> Aggregator errors on comments only once daily

- readme.txt
- src/Tribe/Aggregator.php
- src/admin-views/aggregator/status.php
Ticket: https://central.tri.be/issues/68665
Builds on: https://github.com/moderntribe/tribe-common/pull/250
This PR adds a link in the network admin to show the help page.
> Show the help page on network admin

- src/Tribe/Event_Tickets/Attendees_Report.php
_Ref:_ [C#66003](https://central.tri.be/issues/66003) - Minor Change to Core for this ticket.
> #66003 - Setup all fields and start the Ticket Sales Count Displays

- src/Tribe/Main.php
Ticket: https://central.tri.be/issues/68662
Builds on https://github.com/moderntribe/tribe-common/pull/252
> Hide full license on subsites

- src/Tribe/Aggregator.php
- src/Tribe/Aggregator/API/Origins.php
- src/Tribe/Aggregator/Cron.php
- src/Tribe/Aggregator/Meta_Box.php
- src/Tribe/Aggregator/Migrate.php
- src/Tribe/Aggregator/Page.php
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Record/List_Table.php
- src/Tribe/Aggregator/Record/Queue_Realtime.php
- src/Tribe/Aggregator/Service.php
- src/Tribe/Aggregator/Settings.php
- src/Tribe/Aggregator/Tabs.php
- src/Tribe/Aggregator/Tabs/New.php
- src/Tribe/Aggregator/Tabs/Scheduled.php
- src/Tribe/Customizer/General_Theme.php
- src/Tribe/Customizer/Global_Elements.php
- src/Tribe/Customizer/Month_Week_View.php
- src/Tribe/Customizer/Single_Event.php
- src/Tribe/Customizer/Widget.php
- src/Tribe/Ignored_Events.php
- src/Tribe/Main.php
- src/Tribe/Shortcode/Event_Details.php
- src/admin-views/aggregator/page.php
- src/admin-views/aggregator/settings.php
- src/admin-views/aggregator/status.php
- src/admin-views/aggregator/tabs/import-form.php
- src/admin-views/tribe-options-addons-api.php
Ticket: https://central.tri.be/issues/68666
This PR:
- adds a setting to disable EA
- hides some UI when EA is disabled
- prevents EA cron jobs from running when disabled
- refactors some code in Main and around the plugin to use the `tribe` container (see https://github.com/moderntribe/tribe-common/pull/249)
> Allow disabling EA functionalities

- src/Tribe/Admin/Event_Meta_Box.php
- src/admin-views/events-meta-box.php
_Ref:_ [C#66487](https://central.tri.be/issues/66487)
> Timepicker defaults

- src/functions/template-tags/general.php
https://central.tri.be/issues/65937
https://central.tri.be/issues/65919
> Featured img/tooltip changes to support featured events formatting | #65937

- src/Tribe/Template/Month.php
_Ref:_ [C#69123](https://central.tri.be/issues/69123)
_Rel:_ #1098
> Preserve the Event Date Time on Ordering

- src/Tribe/Event_Tickets/Attendees_Report.php
_Ref:_ [C#66484](https://central.tri.be/issues/66484)
Readme changes in Event Tickets Plus as that is where the end user will see the changes.
> #66012 Add in Breakdown of Ticket Sales by Status

- src/admin-views/tribe-options-display.php
- src/admin-views/tribe-options-general.php
_Ref:_ [C#68462](https://central.tri.be/issues/68462)
> Fix the settings page Domain to Core

- src/Tribe/Query.php
_Ref:_ [C#42143](https://central.tri.be/issues/42143)
> Stop `post__not_in` overwrite

- src/Tribe/Customizer/Widget.php
See: https://central.tri.be/issues/65924
> Support the venue widget in the customizer

- src/Tribe/Asset/Tribe_Select2.php
If we enqueue select2 we also need to register the path etc.
> Ensure select2 loads | spotfix

- src/admin-views/event-sidebar-options.php
Update text per Leah.
https://central.tri.be/issues/65897
> Update helper text | #65897

- src/Tribe/Backcompat.php
_Ref:_ [C#67696](https://central.tri.be/issues/67696)
> Avoid errors when Option in Empty

- src/Tribe/Template/Month.php
_Ref:_ [C#69123](https://central.tri.be/issues/69123)
> post__in now working with sticky options

- src/resources/css/tribe-events-full.css
- src/resources/postcss/tribe-events-full.pcss
Our (post-)CSS was referencing a Select2 asset that no longer exists in that location.
> select2x2 path (spotfix)

- src/Tribe/Customizer/Day_List_View.php
See: https://central.tri.be/issues/69243#note-5
> Re-add text that shouldn't have been removed. Whoopsie!

- src/Tribe/Customizer/Day_List_View.php
See: https://central.tri.be/issues/69243
> Change Customizer helper text single paragraph into two on List Settings

- src/Tribe/Aggregator/Record/Abstract.php
Ticket: https://central.tri.be/issues/68684
> Fix small notice on EA

- src/resources/js/tribe-settings.js
- src/resources/js/tribe-settings.min.js
_Ref:_ [C#69353](https://central.tri.be/issues/69353)
> One spot where chosen was forgotten

- src/Tribe/Main.php
- src/Tribe/Query.php
Ticket: https://central.tri.be/issues/69602
This PR will handle the case where permalinks are not activated to allow view setting to still happen as intended.
> Fix display setting with ugly links

- src/Tribe/Asset/Admin.php
_Ref:_ [C#69982](https://central.tri.be/issues/69982)
> Include Dropdowns as a dependency of Admin JS

- src/Tribe/Main.php
_Ref:_ [C#69602](https://central.tri.be/issues/69602)
> Permalinks better handled in general

- src/Tribe/Main.php
_Ref:_ [C#65755](https://central.tri.be/issues/65755)
@borkweb asked me to re-do, without moving the deprecated methods.
> New Common initialization method

- readme.txt
- src/Tribe/Aggregator/Cron.php
- src/Tribe/Aggregator/Errors.php
Ticket: https://central.tri.be/issues/68297
> fixed code to avoid showing import comments in count

- src/Tribe/Main.php
After #1205 was Pull Requested, @borkweb asked me to re-do the reorganization of the deprecated files to avoid having conflicts.
So I've done it, and also added some docblocks about how we load Common Library and our Bind Implementation.
> Re-organizer our Main File

- readme.txt
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Tabs/New.php
Ticket: https://central.tri.be/issues/69960
> Fix notice issue due to missing source for ics files

- src/functions/template-tags/venue.php
_Ref:_ [C#69887](https://central.tri.be/issues/69887) - Only show link to Venue if Pro Active
> #69887 Display Venue Link only if Pro Active

- src/Tribe/Aggregator.php
_Ref:_ [C#70812](https://central.tri.be/issues/70812)
> Prevent Aggregator from Phoning home on every request

- src/Tribe/Main.php
_Ref:_ [C#70894](https://central.tri.be/issues/70894)
_Original:_ #1203
> Allow Venues and Organizers metas to be pre-populated by plugin

- src/Tribe/REST/V1/Headers/Base.php
- tests/integration/Tribe/Events/REST/V1/Headers/BaseTest.php
- tests/restv1/DiscoveryCest.php
Ticket: https://central.tri.be/issues/70382
When a request hits a single event URL the REST URL header will provide the REST URL to fetch that specific event.
> Provide a single event REST url in the header

- readme.txt
- src/Tribe/Main.php
_Ref:_ [C#72149](https://central.tri.be/issues/72149)
> Changes the Search label to prevent duplicate words

- readme.txt
- src/Tribe/iCal.php
_Ref:_ [C#71916](https://central.tri.be/issues/71916)
> Make sure we iCal Echo for single Events

- readme.txt
- src/admin-views/aggregator/status.php
_Ref:_ [C#71872](https://central.tri.be/issues/71872)
> Avoid Escaping Third Party notes on Help Page

- readme.txt
- src/Tribe/Aggregator/API/Image.php
_Ref:_ [C#70576](https://central.tri.be/issues/70576)
> Prevent Fatals on EA Image importing

- src/Tribe/Main.php
- src/Tribe/Query.php
_Ref:_ [C#68496](https://central.tri.be/issues/68496)
> Allow removing the Date filters on our own hooks

- src/Tribe/Aggregator/API/Image.php
- src/Tribe/Aggregator/Record/Queue.php
_Ref:_ [C#70576](https://central.tri.be/issues/70576)
> Image resolution on EA

- src/functions/template-tags/venue.php
`fullAddress()` is in TEC core, not PRO
> Change variable name to avoid confusion with PRO | spotfix

- readme.txt
Adding changelog entry for https://central.tri.be/issues/67759
This was PR'd to tribe-common https://github.com/moderntribe/tribe-common/pull/323
> Add changelog entry

- .gitmodules
- src/Tribe/Main.php
_Ref:_ [C#71908](https://central.tri.be/issues/71908)
> Remove Tickets from Core!

- readme.txt
- src/Tribe/Aggregator/Record/Queue.php
- src/Tribe/Integrations/WPML/Filters.php
- src/Tribe/Integrations/WPML/Linked_Posts.php
_Ref:_ [C#72812](https://central.tri.be/issues/72812)
> Remove all instances of is_a

- src/Tribe/Aggregator/Record/Queue.php
Ticket: https://central.tri.be/issues/72655
Found out while workin on the ticket, this PR avoids the notice
> avoid undefined prop notice

- .travis.yml
- codeception.dist.yml
- tests/muintegration.suite.dist.yml
This isn't specifically related to this release, but let's get it added.
> Add support for travis-ci execution of tests

- src/Tribe/Template/Month.php
See: https://central.tri.be/issues/70497
> Only show the "View More" link in month view if viewable events > 0

- src/Tribe/Inactive_Events.php
Ticket: https://central.tri.be/issues/73764
> Add the Events Category to inactive events

- src/Tribe/Aggregator/Service.php
- src/Tribe/REST/V1/EA_Messages.php
Ticket: https://central.tri.be/issues/73866
This PR updates EA error messages as per doc: https://docs.google.com/document/d/1ultz-_NklnLPC_7yLg_WAKaW9shBITB-44u4vkonyfU/edit
Errors that might be due to a client timeout will also get a link added to refine the import range.
> Refine EA error messages

- src/admin-views/aggregator/settings.php
Leah - please review this changeset :)
> updated language for change authority

- readme.txt
- src/Tribe/Aggregator/Record/Facebook.php
See: https://central.tri.be/issues/74687
> Pass the admin_url to EA Facebook OAuth

- src/Tribe/Aggregator/Event.php
_Ref:_ [C#74670](http://central.tri.be/issues/74670)
> Map the Import Exceprt to the Column

- src/Tribe/Aggregator/Record/List_Table.php
_Ref:_ [C#74658](http://central.tri.be/issues/74658)
> Actually format the Start Date for EA Filters

- src/Tribe/REST/V1/Documentation/Event_Definition_Provider.php
- src/Tribe/REST/V1/Post_Repository.php
_Ref:_ [C#74671](http://central.tri.be/issues/74671)
> Add a field for All Day Event Flaging

- src/Tribe/REST/V1/Endpoints/Archive_Event.php
- src/Tribe/REST/V1/Headers/Base.php
- src/Tribe/REST/V1/Post_Repository.php
_Ref:_ [C#74657](http://central.tri.be/issues/74657)
> Resolve meta_query for Venue and Organizer

- src/Tribe/REST/V1/Endpoints/Archive_Event.php
- src/Tribe/REST/V1/Headers/Base.php
_Ref:_ [C#74985](http://central.tri.be/issues/74985)
> API V1 now supporting Featured Events

- src/Tribe/Aggregator/API/Import.php
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Service.php
_Ref:_ [C#74974](http://central.tri.be/issues/74974)
> Pass the Start and End of the EA search

- src/Tribe/Main.php
https://central.tri.be/issues/72273
> let all http = https

- src/Tribe/Aggregator/Tabs/Abstract.php
_Ref:_ [C#75354](http://central.tri.be/issues/75354)
> Prevent Using URL now uses Source on EA page

- readme.txt
Changelog for https://central.tri.be/issues/74930 is in here since that change actually happens in common.
Also changelog for https://central.tri.be/issues/72273
_see: https://github.com/moderntribe/tribe-common/pull/345_
> add changelog

- src/Tribe/Aggregator/Settings.php
_Ref:_ [C#74974](http://central.tri.be/issues/74974)
> Modify the wording for the Settings on EA ranges for Other URL

- src/Tribe/Aggregator/Record/Queue_Realtime.php
_Ref:_ [C#75377](http://central.tri.be/issues/75377)
---
> Avoid fatals on Queue Processor on EA

- src/Tribe/Linked_Posts/Chooser_Meta_Box.php
- src/admin-views/create-venue-fields.php
https://central.tri.be/issues/73813
see:
moderntribe/events-community#206
moderntribe/the-events-calendar#581
> community refresh button class names and remove google maps links

- src/admin-views/admin-update-message.php
- src/admin-views/admin-welcome-message.php
- src/admin-views/aggregator/settings.php
- src/admin-views/tribe-options-display.php
https://central.tri.be/issues/72273
_see also https://github.com/moderntribe/tribe-common/pull/348_
> links that need to be manually changed

- src/Tribe/Aggregator/Tabs/New.php
Use HTTPS for links, per QA feedback.
https://central.tri.be/issues/72273
> Use HTTPS for links | #72273

- src/admin-views/admin-update-message.php
See: https://central.tri.be/issues/75541
> change facebook link to point at Aggregator

- readme.md
- readme.txt
- src/Tribe/Main.php
- src/admin-views/admin-update-message.php
- src/admin-views/admin-welcome-message.php
related - https://github.com/moderntribe/tribe-common/pull/351
See: https://central.tri.be/issues/72273
I also fixed a few URLs that were redirecting
> change http to https

- src/Tribe/API.php
- src/Tribe/Aggregator/Event.php
- src/Tribe/Main.php
_Ref:_ [C#71152](http://central.tri.be/issues/71152)
---
Depends on: https://github.com/moderntribe/tribe-common/pull/352
> EA Venues and Organizers are now been tracked correctly

- src/admin-views/aggregator/origins/url.php
_Ref:_ [C#68942](http://central.tri.be/issues/68942)
---
> Add the Schedule Field to Other URL edit page

- src/admin-views/aggregator/origins/url.php
> Forgotten Variable on Other URL Page

- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Organizer.php
- src/Tribe/Venue.php
_Ref:_ [C#71152](http://central.tri.be/issues/71152)
---
Depends on: https://github.com/moderntribe/event-aggregator-site/pull/145
> Handle Update EA Venue and Organizer

- src/admin-views/aggregator/origins/refine.php
_Ref:_ [C#68942](http://central.tri.be/issues/68942)
---
> Never should display unix time on Filter Date

- src/admin-views/aggregator/origins/refine.php
_Ref:_ [C#68942](http://central.tri.be/issues/68942)
---
> The description of Filter on EA other URL was UNIX

- src/Tribe/Aggregator/Record/Abstract.php
_Ref:_ [C#75532](http://central.tri.be/issues/75532)
---
> Venue and Organizer now been created and assigned

- src/Tribe/Aggregator/Event.php
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Importer/File_Importer_Events.php
- src/Tribe/Organizer.php
- src/Tribe/Venue.php
_Ref:_ [C#76534](http://central.tri.be/issues/76534)
---
> Re-Assemble Change Authority World

- src/Tribe/Aggregator/Event.php
- src/Tribe/Aggregator/Record/Abstract.php
Ticket: https://central.tri.be/issues/76534
Builds on: https://github.com/moderntribe/tribe-common/pull/358
> Fix change Authority issues

- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Service.php
Ticket: https://central.tri.be/issues/76357
Please see the ticket for notes: https://central.tri.be/issues/76357#note-6
> Fix uncounted manual imports

- src/Tribe/Main.php
Ticket: https://central.tri.be/issues/77302
Good to do this?
> up min common version to `4.5`

- src/Tribe/REST/V1/EA_Messages.php
Ticket: https://central.tri.be/issues/77465
This PR adds the message requested by the ticket; see complementary PR on EA Service here:  https://github.com/moderntribe/event-aggregator-site/pull/148
> add older TEC version message

- src/Tribe/Aggregator/Service.php
Ticket: https://central.tri.be/issues/72634
Add the no-results message
> change message slug to match REST one

- src/Tribe/Main.php
- src/functions/template-tags/venue.php
https://theeventscalendar.com/support/forums/topic/full-address-php-template-file/#post-1275235
> fix comments re: legacy full-address.php | spotfix

- readme.txt
- src/Tribe/REST/V1/Main.php
Fix typo causing validation issues.
:ticket: [#78658](https://central.tri.be/issues/78658)
> Correct API reference URL | #78658

- src/Tribe/Aggregator/Cron.php
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Record/Queue.php
- src/Tribe/Aggregator/Record/Queue_Cleaner.php
- src/Tribe/Aggregator/Record/Queue_Realtime.php
- src/Tribe/Main.php
Ticket: https://central.tri.be/issues/77988
> Support and use the Meta Chunker

- src/admin-views/create-organizer-fields.php
- src/admin-views/create-venue-fields.php
- src/admin-views/organizer-meta-box.php
- src/admin-views/venue-meta-box.php
_Ref:_ [C#79076](http://central.tri.be/issues/79076)
---
> Add more classes to Linked Posts table rows

- package-whitelist.json
_Ref:_ [C#79257](http://central.tri.be/issues/79257)
---
> Whitelist the Files in `common`

- src/Tribe/Main.php
_Ref:_ [C#64088](http://central.tri.be/issues/64088)
> #64088 | Fix Duplication of Organizers and Venues on Event Preview

- readme.txt
_Ref:_ [C#64088](http://central.tri.be/issues/64088)
> #64088 | Readme addition for 64088

- readme.txt
Update link to current forum welcome sticky (but use an m.tri.be link for easier updates going forward).
:ticket: [#44180](https://central.tri.be/issues/44180)
> Readme change

- src/Tribe/Meta/Context.php
- src/Tribe/Meta/Save.php
_Related:_ https://github.com/moderntribe/events-pro/pull/622
> Move Tribe/Recurrence/Series.php to Tribe/Series.php

- src/Tribe/Organizer.php
- src/Tribe/Venue.php
Note: This is being PR'd into `release/F17.4` on purpose - ask @zbtirrell for details.
See: https://central.tri.be/issues/80310
> Improving security for Organizer and Venue meta

- src/Tribe/Asset/Events_Css.php
_Ref:_ [C#80317](http://central.tri.be/issues/80317)
---
> Remove usage of non-needed style

- readme.txt
- src/resources/css/events-admin.css
- src/resources/css/tribe-events-full.css
- src/resources/css/tribe-events-theme-mobile.css
- src/resources/css/tribe-events-theme.css
- src/resources/postcss/tribe-events-full.pcss
_Ref:_ [C#27252](http://central.tri.be/issues/27252)
> 27252 | Make Form Text Consistent

- src/Tribe/Customizer/General_Theme.php
See: https://central.tri.be/issues/71093
> fix customizer language

- src/Tribe/Customizer/General_Theme.php
_Ref:_ [C#80190](http://central.tri.be/issues/80190)
---
> Improve Customizer General Theme Section

- readme.txt
- src/Tribe/Customizer/General_Theme.php
- src/Tribe/Customizer/Month_Week_View.php
- src/Tribe/Ignored_Events.php
- src/admin-views/aggregator/tabs/import-form.php
Set of corrections proposed by Garrett Hyder (community translator).
:ticket: [#77196](https://central.tri.be/issues/77196)
> Correct typos/spelling (props @garrett-eclipse) | #77196

- src/Tribe/Integrations/WPML/WPML.php
Fixes https://github.com/Yoast/wordpress-seo/issues/7117
:ticket: [#81224](https://central.tri.be/issues/81224)
> We are already doing this in WPML__Permalinks::get_post_permalink.

- readme.txt
- src/admin-views/create-venue-fields.php
_Ref:_ [C#76297](http://central.tri.be/issues/76297)
Related PR to Community Events → https://github.com/moderntribe/events-community/pull/255
> #76297 | Fix Ability to Make Organizers or Venues Required for Community Events Submission

- composer.lock
- src/Tribe/Organizer.php
- src/Tribe/REST/V1/Endpoints/Base.php
- src/Tribe/REST/V1/Endpoints/Linked_Post_Base.php
- src/Tribe/REST/V1/Endpoints/Linked_Post_Endpoint_Interface.php
- src/Tribe/REST/V1/Endpoints/Single_Event.php
- src/Tribe/REST/V1/Endpoints/Single_Organizer.php
- src/Tribe/REST/V1/Endpoints/Single_Venue.php
- src/Tribe/REST/V1/Main.php
- src/Tribe/REST/V1/Messages.php
- src/Tribe/Venue.php
- tests/restv1/OrganizerInsertionCest.php
- tests/restv1/OrganizerUpdateCest.php
- tests/restv1/VenueUpdateCest.php
- tests/wpunit/Tribe/Events/REST/V1/Endpoints/Single_OrganizerTest.php
- tests/wpunit/Tribe/Events/REST/V1/Endpoints/Single_VenueTest.php
Tickets:
* https://central.tri.be/issues/79742
* https://central.tri.be/issues/79738
Builds on https://github.com/moderntribe/tribe-common/pull/428
> Add support for Venue and Organizer update

- readme.txt
- src/Tribe/Integrations/WPML/Defaults.php
Also switched a colour and behaviour to their american version, they'll be translated in the english variants
> Spelling & Grammar Fixes

- src/Tribe/Main.php
This will allow us to switch to the Full REST API bucket for testing on our project.
Related:
https://central.tri.be/issues/79399
https://central.tri.be/issues/80267
https://central.tri.be/issues/80268
> Cherry pick register post type / taxonomy filters

- readme.txt
- src/Tribe/Aggregator/Record/Queue_Processor.php
_Ref:_ [C#83382](http://central.tri.be/issues/83382)
---
> Aggregator Insert Events Cron gets re-enqueued if it's not done

- src/Tribe/Query.php
Also added hook doc info :)
This is needed for my work on https://central.tri.be/issues/81167
> Add $query to tribe_query_can_inject_date_field filter

- readme.txt
- src/admin-views/create-organizer-fields.php
_Ref:_ [C#80426](http://central.tri.be/issues/80426)
> #80426 | Adjust "E-mail Address Obfuscation" Label When in Community Events

- readme.txt
- src/Tribe/Integrations/Manager.php
- src/Tribe/Integrations/Twenty_Seventeen.php
- src/Tribe/Main.php
Avoid JS errors and improve layout when Twenty Seventeen is in use.
:ticket: [#70853](https://central.tri.be/issues/70853)
> Improve compatibility with Twenty Seventeen

- src/Tribe/Inactive_Events.php
- src/Tribe/Main.php
- src/resources/js/admin-inactive-events.js
_Ref:_ [C#71570](http://central.tri.be/issues/71570)
---
> Inactive Events Single UI

- src/Tribe/Main.php
- src/Tribe/Organizer.php
- src/Tribe/REST/V1/Endpoints/Single_Organizer.php
- src/Tribe/REST/V1/Endpoints/Single_Venue.php
- src/Tribe/REST/V1/Post_Repository.php
- src/Tribe/Venue.php
Tickets:
* https://central.tri.be/issues/81691
* https://central.tri.be/issues/79740
* https://central.tri.be/issues/76730
* https://central.tri.be/issues/76729
* https://central.tri.be/issues/79737
* https://central.tri.be/issues/79739
More fixes found while using the testing plugin.
> fix more issues found using the test plugin

- src/Tribe/Admin/List.php
_Ref:_ [C#70887](http://central.tri.be/issues/70887)
---
> Prevent Zeroed Status to even Show on In Series Filtering

- src/Tribe/REST/V1/Endpoints/Archive_Event.php
https://central.tri.be/issues/81861
> Add support for TEC Pro geoloc, geoloc_lat, geoloc_lng in REST API /events

- src/Tribe/API.php
Tickets:
* https://central.tri.be/issues/76730
* https://central.tri.be/issues/76729
> make sure date is fetched from the db if not available

- readme.txt
- src/Tribe/Aggregator/Record/Queue.php
Ticket: https://central.tri.be/issues/84259 and https://central.tri.be/issues/84187
Related to EA Service PR: https://github.com/moderntribe/event-aggregator-site/pull/233
> correct the use of the conditional

- src/Tribe/Admin/Inactive_List.php
- src/Tribe/Inactive_Events.php
_Ref:_ [C#83938](http://central.tri.be/issues/83938)
---
> Inactive Events Fix

- readme.txt
Signed-off-by: geoffgraham <geoff@geoffgraham.me>
> Fixes Event Tickets link in Free Plugins list

- src/Tribe/Linked_Posts.php
_Ref:_ [C#84482](http://central.tri.be/issues/84482)
> #84482 | Accommodate Both "An" and "A" in Some Linked Post Strings

- readme.txt
- src/Tribe/Main.php
https://central.tri.be/issues/85206
> pass Post ID to the_title filtering

- readme.txt
- src/views/list/single-event.php
_Ref:_ [C#72289](http://central.tri.be/issues/72289)
> #72289 Fix Stray Comma in List View

- readme.txt
- src/functions/template-tags/general.php
_Ref:_ [C#74291](http://central.tri.be/issues/74291)
> #74291 Fix Mobile.php's Failure to Render Event Featured Images

- src/functions/template-tags/venue.php
_Ref:_ [C#85295](http://central.tri.be/issues/85295)
There is a good deal of filters I did not add docblocks for yet. As that is the most time-consuming part of this (for me), I wanted to submit the changes I've done thus far, see if folks are on board with it, and if so, then do the rest of the filters another time.
> #85295 | Some Cleanup of the Venue Template Tags File

- src/Tribe/Aggregator/Cron.php
- src/Tribe/Aggregator/Record/Queue_Cleaner.php
- src/Tribe/Aggregator/Records.php
Ticket: https://central.tri.be/issues/81639
This PR:
* uses the generic logging methods in https://github.com/moderntribe/tribe-common/pull/493
* modifies the way we fetch children records to limit them to the last 4 hours
See ticket notes for more clarity.
> Attempt fixing neverending failures on cron

- readme.txt
- src/functions/template-tags/venue.php
- src/views/day/single-event.php
_Ref:_ [C#85429](http://central.tri.be/issues/85429)
> #85429 Fix Stray Comma in Day View Venue Details

- src/Tribe/Aggregator/Record/Abstract.php
Ticket: https://central.tri.be/issues/85636
Removes what I guess is a merge aberration.
> remove merge aberration

- readme.txt
Ticket: https://central.tri.be/issues/81639
Added missing changelog entry
> add changelog entry for issue 81639

- src/admin-views/list/column-categories.php
_Ref:_ [C#85739](http://central.tri.be/issues/85739)
---
> Prevent Notice from Non-Existing Variable on Column Categories

- readme.txt
_Ref:_ [C#84202](http://central.tri.be/issues/84202)
> #84202 | Add Changelog Entry

- readme.txt
- src/Tribe/REST/V1/Documentation/Venue_Definition_Provider.php
Also capitalization and grammar
> Fix typo of "organizer" - should be "venue"

- readme.txt
- src/Tribe/Ignored_Events.php
_Ref:_ [C#67890](http://central.tri.be/issues/67890)
---
> Add Hide & Ignore tooltip

- readme.txt
- src/Tribe/Aggregator/Record/Abstract.php
_Ref:_ [C#77819](http://central.tri.be/issues/77819)
---
_Related:_ https://github.com/moderntribe/tribe-common/pull/513
> Convert Start and End if possible on Aggregator Records

- src/Tribe/Aggregator/Admin_Bar.php
_Ref:_ [C#68693](http://central.tri.be/issues/68693)
---
> Add CSV into the menu of Aggregator

- src/Tribe/API.php
- src/Tribe/REST/V1/Endpoints/Single_Event.php
https://central.tri.be/issues/83560
> Add new hook for Tribe__Events__REST__V1__Endpoints__Single_Event::prepare_postarr, improve hooks for event API save

- src/Tribe/Admin/Inactive_List.php
_Ref:_ [C#71570](http://central.tri.be/issues/71570)
---
> Add Post.php to the Base of pages for inactive events

- readme.txt
https://central.tri.be/issues/78023
Exposing common feature in The Events Calendar changelog (re: https://github.com/moderntribe/tribe-common/pull/515)
> Add changelog entry for common fix

- src/Tribe/Aggregator/Record/Queue.php
Ticket: https://central.tri.be/issues/87552
> release the queue lock if fetching

- readme.txt
- src/Tribe/Aggregator/Errors.php
_Ref:_ [C#78890](http://central.tri.be/issues/78890)
---
> Avoid doing anything on the Calls if EA is not active.

- readme.txt
- src/Tribe/Importer/File_Importer_Events.php
_Ref:_ [C#78340](http://central.tri.be/issues/78340)
---
> Make sures we have a way to treat Numeric Named categories

- src/Tribe/REST/V1/Endpoints/Archive_Base.php
- src/Tribe/REST/V1/Endpoints/Single_Event.php
Ticket: n/a
Original  code from:
* @Nslaver in PR https://github.com/moderntribe/the-events-calendar/pull/1578
* @mwender in PR https://github.com/moderntribe/the-events-calendar/pull/1579
I'm simply reporting this code here as we have moved the method to a parent class.
> Add fixes from PRs 1578 and 1579

- src/Tribe/REST/V1/Documentation/Event_Definition_Provider.php
- src/Tribe/REST/V1/Documentation/Organizer_Definition_Provider.php
- src/Tribe/REST/V1/Documentation/Venue_Definition_Provider.php
- src/Tribe/REST/V1/Endpoints/Archive_Category.php
- src/Tribe/REST/V1/Endpoints/Archive_Event.php
- src/Tribe/REST/V1/Endpoints/Archive_Tag.php
- src/Tribe/REST/V1/Endpoints/Base.php
- src/Tribe/REST/V1/Endpoints/Single_Category.php
- src/Tribe/REST/V1/Endpoints/Single_Event.php
- src/Tribe/REST/V1/Endpoints/Single_Organizer.php
- src/Tribe/REST/V1/Endpoints/Single_Tag.php
- src/Tribe/REST/V1/Endpoints/Single_Venue.php
- src/Tribe/REST/V1/Endpoints/Swagger_Documentation.php
Ticket: https://central.tri.be/issues/88661
Based on:  https://github.com/moderntribe/tribe-common/pull/524
> Fix Swagger.io format output to work with editor

- readme.txt
- src/Tribe/REST/V1/Endpoints/Archive_Event.php
Ticket: https://central.tri.be/issues/88748
> Nslaver patch 1

- src/Tribe/REST/V1/Endpoints/Archive_Event.php
https://central.tri.be/issues/81861
> Add geoloc args to tribe_get_events args if set in the request

- src/Tribe/Aggregator/Errors.php
_Ref:_ [C#78890](http://central.tri.be/issues/78890)
---
> Make sure we are check if the Service is active to hide the Errors

- src/Tribe/REST/V1/Documentation/Venue_Definition_Provider.php
- src/Tribe/REST/V1/Post_Repository.php
Needed for https://central.tri.be/issues/81162
> Add geo coordinates to REST API venue responses

- package.json
- readme.txt
- src/Tribe/Main.php
- src/Tribe/Query.php
- src/Tribe/Template/Month.php
- the-events-calendar.php
_Ref:_ [C#88952](http://central.tri.be/issues/88952)
---
> Resolve the WP 4.8.2 problem with $WPDB

- src/Tribe/REST/Interfaces/Post_Repository.php
- src/Tribe/REST/V1/Endpoints/Single_Event.php
- src/Tribe/REST/V1/Endpoints/Single_Organizer.php
- src/Tribe/REST/V1/Endpoints/Single_Venue.php
- src/Tribe/REST/V1/Main.php
- src/Tribe/REST/V1/Post_Repository.php
- src/functions/template-tags/organizer.php
- src/functions/template-tags/venue.php
- tests/restv1/OrganizerSingleCest.php
- tests/restv1/SingleEventCest.php
- tests/restv1/VenueSingleCest.php
- tests/wpunit/Tribe/Events/REST/V1/Endpoints/Single_EventTest.php
- tests/wpunit/Tribe/Events/REST/V1/Post_RepositoryTest.php
https://central.tri.be/issues/88920
> Add JSON-LD data to REST API event/venue/organizer responses (only in single endpoint context)

- src/Tribe/JSON_LD/Venue.php
https://central.tri.be/issues/85223
> Set type on address JSON-LD to PostalAddress

- readme.txt
- src/Tribe/Aggregator/Cron.php
See: https://central.tri.be/issues/88965
> Adjust the EA Cron start time so that it never creates in the past

- readme.txt
- src/Tribe/Main.php
**Ticket:** [**#67482**](http://central.tri.be/issues/67482)
I _think_ I’m doing this right.
> #67482 Rename and Deprecate a Filter

- src/Tribe/Asset/Admin_Ui.php
_Ref:_ [C#80632](http://central.tri.be/issues/80632)
---
> Ticket Editor Validation

- readme.txt
- src/Tribe/Venue.php
**Ticket:** [**#66968**](http://central.tri.be/issues/66968)
> #66968 Prevent Weird Meta Keys

- readme.txt
- src/functions/template-tags/general.php
- src/functions/template-tags/loop.php
**Ticket:** [**#72013**](http://central.tri.be/issues/72013)
---
- Props to @borkweb for helping me out on this one, and helping me identify the JavaScript URL fudgery that was the source of the issue.
- **Note:** I originally submitted #1607 to fix this, but am going to delete that PR.
> #72013 Fix Listview Pagination

- src/Tribe/Asset/Dynamic.php
**Ticket:** [**#72686**](http://central.tri.be/issues/72686)
**Related PR:** https://github.com/moderntribe/tribe-common/pull/543
> #72686 QA Feedback: Ensure Moment.js is Loaded

- src/Tribe/JSON_LD/Event.php
Setting dates to local time instead of UTC for Google
> Update Event.php for Bug #42125

- src/Tribe/Asset/Dynamic.php
- src/resources/js/events-admin.js
_Ref:_ [C#84936](http://central.tri.be/issues/84936)
---
> Move timepicker to common

- readme.txt
- src/Tribe/Customizer/Month_Week_View.php
- src/Tribe/Ignored_Events.php
Adds missing textdomains (props @pedro-mendonca) and provides changelog for same.
:ticket: [#91071](https://central.tri.be/issues/91071)
> Add missing textdomains

- readme.txt
- src/Tribe/Integrations/Manager.php
- src/Tribe/Integrations/WPML/WPML.php
**Ticket:** [**#82286**](http://central.tri.be/issues/82286)
> #82286 Disable Month View Caching [for now] when WPML is Active

- readme.txt
- src/views/list/single-event.php
- src/views/list/single-featured.php
**Ticket:** [**#75547**](http://central.tri.be/issues/75547)
> #75547 Ensure List View Honors the "Show Google Maps Link" Option

- readme.txt
- src/admin-views/tribe-options-general.php
**Ticket:** [**#78621**](http://central.tri.be/issues/78621)
**Related PR:** https://github.com/moderntribe/tribe-common/pull/566
> #78621 Better Accommodate 24-hr Time Format in Options

- src/admin-views/aggregator/meta-box.php
**Ticket:** [**#77957**](http://central.tri.be/issues/77957)
**Code Review Note:**
- This spotfix is a refinement of this earlier PR:
https://github.com/moderntribe/the-events-calendar/pull/1665
- As such, no readme entry needed here since one already exists
> #77957 Refine "Update Authority" Messaging in Edit-Event Screen

- src/Tribe/Aggregator/Record/Abstract.php
Ticket: https://central.tri.be/issues/92947
> implement better fallback logic for event author during imports

- readme.txt
- src/Tribe/Aggregator/Tabs/New.php
_Ref:_ [C#79079](https://central.tri.be/issues/79079)
> #79079 - remove next scheduled import note for on the demand imports

- readme.txt
- src/admin-views/tribe-options-general.php
**Ticket:** [**#92314**](http://central.tri.be/issues/92314)
---
- **Related PR:** https://github.com/moderntribe/tribe-common/pull/571
- **Code Review Note:** No "props" for this ticket.
> #92314 Improve Appearance of Plain-Permalinks Warning in Settings

- src/Tribe/Integrations/Twenty_Seventeen.php
> Update Twenty_Seventeen.php for Bug #89767

- readme.txt
Changelog entry for Central ticket: 89767
> Update readme.txt for Bug #89767

- src/functions/template-tags/organizer.php
> Update organizer.php for Bug #91201

- src/Tribe/REST/V1/Main.php
Ticket: https://central.tri.be/issues/93227
> correctly compare the WP version

- readme.txt
- src/Tribe/Aggregator/API/Import.php
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Tabs/New.php
Ticket: https://central.tri.be/issues/93872
Service Ticket: https://central.tri.be/issues/87326
> support and use message arguments in EA messages

- src/resources/postcss/admin-menu.pcss
Always prefix CSS modifications
> Stop overwriting default styles for other plugin nodes

- readme.txt
- src/Tribe/Aggregator/Record/Abstract.php
Ticket: https://central.tri.be/issues/94323
> Fix EA Client issues where Venues might not be created

- readme.txt
- src/Tribe/Integrations/X_Theme/X_Theme.php
- src/Tribe/Templates.php
**Ticket:** [**#92554**](http://central.tri.be/issues/92554)
**Code Review Note:** There are no "props" for this PR.
> #92554 X Theme Compat

- src/Tribe/Integrations/X_Theme/X_Theme.php
**Ticket:** [**#92554**](http://central.tri.be/issues/92554)
No readme changes needed here!
> #92554 Spotfix: Fix Wrong Method Name

- src/Tribe/REST/V1/Main.php
https://central.tri.be/issues/92825
> Call register_single_event_slug_endpoint so slug endpoints gets added properly

- readme.txt
updated rest-api to link to our article, remove the "read" lingo
Added "other url" info to our EA support
> include rest api

- readme.txt
- src/Tribe/Query.php
- src/Tribe/REST/V1/Endpoints/Archive_Event.php
- src/Tribe/REST/V1/Post_Repository.php
**Ticket:** [**#90005**](http://central.tri.be/issues/90005)
> #90005 Use More Inclusive Start and End Dates in REST GET-events

- readme.txt
- src/Tribe/Embedded_Maps.php
**Ticket:** [**#62910**](http://central.tri.be/issues/62910)
**Related PR:** https://github.com/moderntribe/events-pro/pull/751
> #62910 Use API Key on More Google Maps URLs

- src/Tribe/Aggregator/Record/Abstract.php
Ticket: n/a
Fix a smaller notice found in EA Client code
> fix issue with empty organizers

- src/Tribe/API.php
> make sure timezone abbr is fetched if timezone is valid

- src/Tribe/Organizer.php
- src/Tribe/REST/V1/Endpoints/Single_Organizer.php
- src/Tribe/REST/V1/Endpoints/Single_Venue.php
- src/Tribe/Venue.php
https://central.tri.be/issues/96069
> Add prepare_postarr/save hooks for Organizer and Venue (for RER merge)

- src/Tribe/REST/V1/Post_Repository.php
https://central.tri.be/issues/96090
> Remove duplicate hook, add additional $event parameter instead (for RER merge)

- src/Tribe/REST/V1/Endpoints/Single_Organizer_Slug.php
- src/Tribe/REST/V1/Endpoints/Single_Venue_Slug.php
- src/Tribe/REST/V1/Main.php
- src/Tribe/Validator/Base.php
- tests/restv1/OrganizerSingleSlugCest.php
- tests/restv1/VenueSingleSlugCest.php
- tests/wpunit/Tribe/Events/REST/V1/Endpoints/Single_Organizer_SlugTest.php
- tests/wpunit/Tribe/Events/REST/V1/Endpoints/Single_Venue_SlugTest.php
https://central.tri.be/issues/96088
> Add organizer and venue by-slug endpoints plus tests (for RER)

- readme.txt
- src/Tribe/Aggregator/Event.php
Ticket: https://central.tri.be/issues/96363
> Use lat and long provided by EA Service

- src/Tribe/Organizer.php
Only comments changed other than a filter name, which may warrant a readme or code comment / deprecation
> spotfix | corrections from "venue" to "organizer"

- src/Tribe/REST/V1/Main.php
https://central.tri.be/issues/96088
> Load venue/organizer endpoints

- readme.txt
- src/Tribe/Admin_List.php
_Ref:_ [C#63567](https://central.tri.be/issues/63567)
> #63567 - remove LEFT JOIN for total event count

- readme.txt
- src/Tribe/Rewrite.php
**Ticket:** [**#40976**](http://central.tri.be/issues/40976)
**Code Review Note:** No “props” for this ticket’s readme entry.
> #40976 Make "/page/" Translatable

- readme.txt
- src/views/modules/meta.php
https://central.tri.be/issues/97615
> event single: no stray line if no venue

- readme.txt
**Ticket:** [**#90757**](http://central.tri.be/issues/90757)
> Remove punted readme entry

- src/admin-views/aggregator/settings.php
_Ref:_ [C#61173](https://central.tri.be/issues/61173)
> #61173 - initial coding to move settings to Import Tab

- src/Tribe/Aggregator/Record/Eventbrite.php
_Ref:_ [C#98240](http://central.tri.be/issues/98240)
---
> Allow passing EB License param via EA

- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Record/Eventbrite.php
- src/Tribe/Aggregator/Service.php
_Ref:_ [C#94709](http://central.tri.be/issues/94709)
---
> Prevent Duplicating Events/Venue/Organizer + Prevent 502 EA service

- src/Tribe/Query.php
Ticket: https://central.tri.be/issues/91787
This PR does not include a changelog as is a hotfix to a change already added.
> Don't modify pages as well if is the main_query

- src/Tribe/Aggregator/Record/Eventbrite.php
_Ref:_ [C#98240](http://central.tri.be/issues/98240)
---
> Licenses to the correct param based on Scott's work

- src/Tribe/Aggregator/Record/Eventbrite.php
- src/Tribe/Aggregator/Service.php
_Ref:_ [C#98240](http://central.tri.be/issues/98240)
---
> Modify the filter to be closer to the POST method

- src/Tribe/Aggregator/Event.php
- src/Tribe/Aggregator/Record/Abstract.php
_Ref:_ [C#94375](http://central.tri.be/issues/94375)
---
> Create a EA hook after each event is saved

- package.json
- readme.txt
- src/Tribe/Main.php
- the-events-calendar.php
**Ticket:** [**#99073**](http://central.tri.be/issues/99073)
> Bump Version Numbers to Create M18.04 Release Branch

- readme.txt
- src/Tribe/Admin/Front_Page_View.php
- src/Tribe/Customizer/Front_Page_View.php
- src/Tribe/Main.php
**Ticket:** [**#97978**](http://central.tri.be/issues/97978)
> 97978 Ensure "Main Events Page" Shows up in Customer Homepage Settings

- readme.txt
- src/functions/template-tags/link.php
**Ticket** https://central.tri.be/issues/97772
Make sure the logic around pagination is extendable so we can reuse in
other locations or by other plugins.
> Refactor pagination on list view to be extendable

- src/Tribe/Aggregator/API/Import.php
- src/Tribe/Aggregator/Service.php
_Ref:_ [C#100213](http://central.tri.be/issues/100213)
---
> Allow Aggregator API to be filtered for Licenses

- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Record/Eventbrite.php
- src/Tribe/Aggregator/Service.php
_Ref:_ [C#99056](http://central.tri.be/issues/99056)
---
> Add required Fields to allow Evenbrite License

- src/Tribe/Main.php
- src/Tribe/Query.php
- src/Tribe/Templates.php
- src/functions/template-tags/general.php
**Ticket:** [**#101065**](http://central.tri.be/issues/101065)
> 101065 Spotfix for Template-Loading Error

- src/Tribe/Template/Day.php
- src/Tribe/Template/List.php
**Ticket:** [**#101162**](http://central.tri.be/issues/101162)
**Code Review Note:**
- No readme entry for this change.
- I am not quite sure why these _specific_ changes fix this bug. But I tinkered extensively over this and it worked well with these exact changes.
> Spotfix: 101162 Restore List- and Day-View Pagination

- src/admin-views/aggregator/tabs/import-form.php
- src/admin-views/events-meta-box.php
- src/admin-views/tribe-options-timezones.php
**Ticket:** [**#101346**](http://central.tri.be/issues/101346)
**Code Review Note:** While this is not really a _spotfix_ since it has a ticket, **no readme entry** is required for this change.
> 101346 Change "Timezone" to "Time Zone" in UI Elements

- src/Tribe/Aggregator/Tabs/Edit.php
Ticket: https://central.tri.be/issues/98529
> Allow EA scheduled imports to be edited back to no categories

- src/admin-views/tribe-options-addons-api.php
_Ref:_ [C#81825](https://central.tri.be/issues/81825)
> #81825 - tweak eventbrite to show connection if EA or EB is active

- src/Tribe/Aggregator/Record/List_Table.php
_Related:_ https://github.com/moderntribe/tribe-common/pull/645 https://github.com/moderntribe/events-pro/pull/814
> Resolve some logger Loading methods for Di52

- src/Tribe/API.php
_Ref:_ [C#101480](http://central.tri.be/issues/101480)
---
> Prevent saveEventMeta from API triggering on non-event post requests 

- src/Tribe/Event_Cleaner.php
- src/Tribe/Event_Cleaner_Scheduler.php
- src/Tribe/Main.php
Ref. https://central.tri.be/issues/98826
> Purge expired Events

- readme.txt
- src/Tribe/Event_Tickets/Attendees_Report.php
_Ref:_ [C#93923](https://central.tri.be/issues/93923)
related
https://github.com/moderntribe/event-tickets-plus/pull/537
https://github.com/moderntribe/events-community-tickets/pull/109
> Community Tickets Front End Links

- readme.txt
- src/Tribe/Customizer/Front_Page_View.php
- src/Tribe/Main.php
**Ticket**: https://central.tri.be/issues/100832
> Use a numeric ID to identify the Main Events Page instead

- src/Tribe/REST/V1/Endpoints/Single_Event.php
https://central.tri.be/issues/102705
> Fix EventTimezoneAbbr saving when setting EventTimezone through REST API

- readme.txt
- src/Tribe/Importer/File_Importer_Events.php
Ticket: https://central.tri.be/issues/77956
The new filter added is: `tribe_events_import_event_duplicate_matches`
> Add new filter to determine the duplicates matches of an import

- readme.txt
- src/Tribe/API.php
- src/Tribe/Validator/Base.php
- tests/wpunit/Tribe/Events/Validator/BaseTest.php
https://central.tri.be/issues/102545
> Add tribe_events_event_insert_args and tribe_events_event_update_args hooks

- src/admin-views/aggregator/settings.php
Adjusted the label of the setting to match the one on line 159, as it is the same type of setting.
> Adjusted setting label to match

- src/Tribe/Aggregator/Settings.php
- src/admin-views/aggregator/origins/limit.php
- src/admin-views/aggregator/origins/url.php
Adjusted the wording of an EA message and the time range when importing with time range limit,
based on the discussion with Leah found here:
https://tribe.slack.com/archives/C0258NG6N/p1522670312000236
> Spotfix/adjust EA wording

- src/Tribe/Linked_Posts.php
and sort by DnD when appropriate.
🎫 https://central.tri.be/issues/100733
Linked PR: https://github.com/mt-support/tribe-ext-instructor-linked-post-type/pull/3
> Add filters to allow extensions to hook in easier 

- src/admin-views/organizer-meta-box.php
- src/admin-views/tribe-options-general.php
Changed text string to match the one in "src/admin-views/create-organizer-fields.php".
> Changed text string for consistency

- readme.txt
- src/Tribe/API.php
- tests/wpunit/Tribe/Events/Importer/File_Importer_Events_TimezoneTest.php
_Ref:_ [C#93979](https://central.tri.be/issues/93979)
> #93979 - change timezone isset to empty check

- src/Tribe/Query.php
- tests/wpunit/Tribe/Events/REST/V1/Endpoints/Archive_EventTest.php
Ticket: https://central.tri.be/issues/97667
> Prevent to add the virtual page to the Query

- src/Tribe/Aggregator/Record/Eventbrite.php
- src/Tribe/Aggregator/Records.php
- src/Tribe/Aggregator/Service.php
- src/Tribe/Aggregator/Settings.php
- src/Tribe/Aggregator/Tabs/New.php
- src/admin-views/aggregator/origins/eventbrite.php
- src/admin-views/tribe-options-addons-api.php
_Ref:_ [C#103823](https://central.tri.be/issues/103823)
> #103823 - replace stored eb token with check to EA

- src/Tribe/Aggregator/Record/Eventbrite.php
- src/Tribe/Aggregator/Settings.php
_Ref:_ [C#104641](https://central.tri.be/issues/104641)
> #104641 - add security key to the EB calls and save token on authorize

- src/Tribe/Aggregator/Record/Eventbrite.php
- src/Tribe/Aggregator/Service.php
https://central.tri.be/issues/103823
Fixes import preview issues and problems from changing license keys around after token authorization flow.
> EA Eventbrite API updates

- src/functions/template-tags/month.php
**Ticket:** [**⌗91891**](http://central.tri.be/issues/91891)
**Code Review Note:** No readme entry necessary for these changes.
> ⌗91891 Clarify Nature of Some Template Tags in their Docblocks

- src/Tribe/Linked_Posts.php
From https://github.com/moderntribe/the-events-calendar/pull/1917
> spotfix | fix `@since TBD`

- src/Tribe/Aggregator/API/Image.php
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Service.php
_Ref:_ [C#105396](http://central.tri.be/issues/105396)
---
> Add params for Image Get on Aggregator

- src/Tribe/Aggregator/Record/Abstract.php
https://central.tri.be/issues/105311
> Fix EA image import check logic

- src/Tribe/Aggregator/Service.php
- src/admin-views/aggregator/tabs/import-form.php
_Ref:_ [C#61172](https://central.tri.be/issues/61172)
> #61172 - modify timezone import message for eventbrite

- src/admin-views/create-venue-fields.php
- src/admin-views/venue-meta-box.php
https://central.tri.be/issues/63915 after QA
Fix pre-populate for country and state. Was a pre-existent.
> [pre-existing] Fix pre-populate for country and state

- src/Tribe/Aggregator/CLI/Command.php
Ticket: https://central.tri.be/issues/104426
This PR fixes an issue found by Victor during QA
> avoid passing objects as queue import arguments

- readme.txt
**Ticket:** [**⌗103472**](http://central.tri.be/issues/103472)
> ⌗103472 Readme Updates

- package.json
- readme.txt
- src/Tribe/Main.php
- the-events-calendar.php
**Ticket:** [**⌗103472**](http://central.tri.be/issues/103472)
> Bump Version Numbers for M18.07 Release

- package.json
- readme.txt
- src/Tribe/Main.php
- the-events-calendar.php
_Ref:_ [C#106239](https://central.tri.be/issues/106239)
> #106239 - update version numbers for etr

- src/Tribe/Aggregator/Record/CSV.php
- src/Tribe/Aggregator/Record/Queue_Processor.php
- src/Tribe/Importer/File_Importer.php
Ticket:  https://central.tri.be/issues/105650
This PR fixes the issue related to CSV Imports and the new queueing system by forcing the use of the legacy queue system for CSV Imports to get the work for the release done.
In another MR I will replace the queueing system for CSV imports too (ticket #106663)
> Fix QA Issues 

- src/Tribe/REST/V1/Endpoints/Archive_Category.php
- src/Tribe/REST/V1/Endpoints/Archive_Event.php
- src/Tribe/REST/V1/Endpoints/Archive_Organizer.php
- src/Tribe/REST/V1/Endpoints/Archive_Tag.php
- src/Tribe/REST/V1/Endpoints/Archive_Venue.php
- src/Tribe/REST/V1/Endpoints/Single_Category.php
- src/Tribe/REST/V1/Endpoints/Single_Event.php
- src/Tribe/REST/V1/Endpoints/Single_Organizer.php
- src/Tribe/REST/V1/Endpoints/Single_Tag.php
- src/Tribe/REST/V1/Endpoints/Single_Venue.php
- tests/restv1/CategoryInsertionCest.php
- tests/restv1/CategoryUpdateCest.php
- tests/restv1/EventInsertionCest.php
- tests/restv1/EventUpdateCest.php
- tests/restv1/TagInsertionCest.php
- tests/restv1/TagUpdateCest.php
https://central.tri.be/issues/106026
>  Utilize is_string_not_empty for validation on rest api args that need to not be empty

- src/Tribe/REST/V1/Main.php
https://central.tri.be/issues/106026
> Implement new tribe_register_rest_route method

- tests/integration/Event_Cleaner_Scheduler_Test.php
Ref. https://central.tri.be/issues/102177
> Test - purge expired events

- src/Tribe/REST/V1/Post_Repository.php
- src/Tribe/Timezones.php
Ticket: https://central.tri.be/issues/106558
> Update some REST API methods and utils

- readme.txt
- src/Tribe/Main.php
- src/Tribe/Template/Month.php
https://central.tri.be/issues/72544
> Correct the "View All" link when using the events month view and plain permalinks.

- src/Tribe/Aggregator/Service.php
https://central.tri.be/issues/107604
Only affected imports that sent files like ICS file import option.
> Move tribe_aggregator_service_post_pue_licenses filter to run before $args['file'] is processed and payload setup

- readme.txt
- src/admin-views/aggregator/settings.php
https://central.tri.be/issues/94426
> Modify the default values for the CSV settings if there's no EA license

- readme.txt
- src/views/day/single-event.php
- src/views/list/single-event.php
https://central.tri.be/issues/91610
> Add venue google map in day view + changelog entry

- readme.txt
- src/Tribe/Customizer/Month_Week_View.php
https://central.tri.be/issues/69758
> Fix customizer inconsistencies with month/week views and full styles

- readme.txt
- src/Tribe/iCal.php
https://central.tri.be/issues/104751
>  Ensure that the "Export Events" button is properly displayed.

- readme.txt
- src/Tribe/Linked_Posts.php
https://central.tri.be/issues/71349
> Split linked posts (Organizers and Venues) by ownership, for all users

- readme.txt
> udpate readme for 18.09 tec

- readme.txt
- src/Tribe/Aggregator/Record/Abstract.php
- src/Tribe/Aggregator/Records.php
_Ref:_ [C#106623](https://central.tri.be/issues/106623)
> #106623 - preserve non fields on Eventbrite Imports

- readme.txt
- src/Tribe/Template/Month.php
- src/functions/template-tags/month.php
🎫 https://central.tri.be/issues/67607
Not happy with the results. Been trying many different things, and this one seemed to be to most cost-efficient one. Not sure if you had something else in mind, @barryhughes?
> Add `tribe_events_month_has_events_filtered` function and filter

- readme.txt
- src/Tribe/Aggregator/Service.php
https://central.tri.be/issues/108338
> Fix PHP 5.2 errors.

- package-whitelist.json
🎫 https://central.tri.be/issues/107907
> Add files to whitelist

- src/admin-views/aggregator/banners/eventbrite-upsell.php
https://central.tri.be/issues/107108
> Add `https` to the Eventbrite banner link

- src/views/month/loop-grid.php
Quick & dirty QA repair for the accessibility work.
https://central.tri.be/issues/74447#note-14
> Don't duplicate caption via aria-describedby. QA Repair for #74447

- src/views/day/single-featured.php
https://central.tri.be/issues/91610
Changelog entry already added https://github.com/moderntribe/the-events-calendar/pull/2017
> Port improvements over to featured events template for day view

- src/admin-views/aggregator/settings.php
Ref. https://central.tri.be/issues/106947
- Add the Eventbrite import settings on EA;
- Display the correct import settings when Eventbrite Tickets is enabled;
> Fix the import settings for Eventbrite

- src/admin-views/aggregator/settings.php
Ref. https://central.tri.be/issues/106947
> Add the Global Import Settings if Eventbrite tickets is enabled

- package-whitelist.json
🎫 https://central.tri.be/issues/107907
> Fix filename

- src/resources/postcss/tribe-events-theme.pcss
https://central.tri.be/issues/108754
Changes on the pcss file
> Restore and display header navigation items

- src/admin-views/aggregator/settings.php
https://central.tri.be/issues/94426
> Do not use global phrase if there's no EA license.

- src/views/day.php
- src/views/day/content.php
- src/views/day/loop.php
- src/views/day/nav.php
- src/views/default-template.php
- src/views/list.php
- src/views/list/content.php
- src/views/list/nav.php
- src/views/list/single-event.php
- src/views/list/single-featured.php
- src/views/modules/bar.php
- src/views/modules/map.php
- src/views/month.php
- src/views/month/content.php
- src/views/month/nav.php
- src/views/month/single-day.php
- src/views/month/single-event.php
- src/views/month/tooltip.php
- src/views/single-event.php
Bump and set view version number for those files who haven't had any.
> Bump and set views version number.
